### ISSUE TITLE
Error on IOS Device

### ISSUE THREAD

**Issue by onurc4kir** [florent37/Flutter-AssetsAudioPlayer#1]
Hello, I am trying to run this plugin on IOS device but not work. 

you can see console log.
I think this plugin and sqflite plugin give error. Because i removed AssetsAudioPlayer then I tried, that is work. 
sorry my bad english.

IOS version : 12.1
XCODE version : 10

**********Console Log*******
`Launching lib/GameStartPage.dart on iPhone 8 in debug mode...
Running pod install...
Starting Xcode build...
Xcode build done.                                            5.6s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    === BUILD TARGET sqflite OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/onur/Documents/src/flutter/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-1.0.1/ios/Classes/SwiftAssetsAudioPlayerPlugin.swift:110:49: error: 'setCategory(_:with:)' is unavailable in Swift
                try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayback, with: .mixWithOthers)
                                                    ^~~~~~~~~~~
    AVFoundation.AVAudioSession:26:15: note: 'setCategory(_:with:)' has been explicitly marked unavailable here
        open func setCategory(_ category: AVAudioSession.Category, with options: AVAudioSession.CategoryOptions = []) throws
                  ^
    /Users/onur/Documents/src/flutter/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-1.0.1/ios/Classes/SwiftAssetsAudioPlayerPlugin.swift:110:61: error: 'AVAudioSessionCategoryPlayback' has been renamed to 'AVAudioSession.Category.playback'
                try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayback, with: .mixWithOthers)
                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                AVAudioSession.Category.playback
    AVFoundation.AVAudioSessionCategoryPlayback:3:12: note: 'AVAudioSessionCategoryPlayback' was obsoleted in Swift 3
    public let AVAudioSessionCategoryPlayback: AVAudioSession.Category
               ^

Could not build the application for the simulator.
Error launching application on iPhone 8.
`

**Comment by lubritto** [comment]
try to set the plugin's swift version to 4.0

**Comment by andreahaku** [comment]
I have the following error when trying to build a release version on iOS:
----------------------------------------------------------------------
`- `assets_audio_player` does not specify a Swift version and none of the targets (`Runner`) integrating it have the
    `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the
    targets that integrate this pod.

    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer/xcode/target_validator.rb:115:in
    `verify_swift_pods_swift_version'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer/xcode/target_validator.rb:37:in
    `validate!'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:459:in `validate_targets'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:138:in `install!'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/command/install.rb:48:in `run'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:52:in `run'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/gems/cocoapods-1.6.1/bin/pod:55:in `<top (required)>'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/bin/pod:22:in `load'
    /usr/local/Cellar/cocoapods/1.6.1/libexec/bin/pod:22:in `<main>'

Error output from CocoaPods:
↳

    [!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please
    specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error running pod install`
-----------------------------------------------

Any idea on how to solve this?
Thanks,
Andrea

**Comment by andreahaku** [comment]
So I partially solved the Swift version issue by creating a generic Swift file in the `ios/Runner` folder.

But now I have:
```
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    === BUILD TARGET url_launcher OF PROJECT Pods WITH CONFIGURATION Release ===
    /Users/andreasalvatore/flutter/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-1.0.1/
    ios/Classes/SwiftAssetsAudioPlayerPlugin.swift:110:49: error: 'setCategory(_:with:)' is
    unavailable in Swift
                try
                AVAudioSession.sharedInstance().setCategory(AVAudioSession.Category.playback,
                with: .mixWithOthers)
                                                    ^~~~~~~~~~~
    AVFoundation.AVAudioSession:26:15: note: 'setCategory(_:with:)' has been explicitly marked
    unavailable here
        open func setCategory(_ category: AVAudioSession.Category, with options:
        AVAudioSession.CategoryOptions = []) throws
                  ^
```

thanks for your help.

**Comment by andreahaku** [comment]
I tried using Objective-C to make it work but I wasn't able to do that. Unfortunately I'm not an iOS developer.

But I'll keep on trying because it's working perfectly for my app on Android and it's be great to have it working on iOS as well.

**Comment by lubritto** [comment]
Try to add on podfile 

```

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['SWIFT_VERSION'] = '4.2'
      if target.name == 'assets_audio_player'
        config.build_settings['SWIFT_VERSION'] = '4.0'
      end
    end
  end
end

```

**Comment by andreahaku** [comment]
@lubritto yes now it compiles!

But it seems not able to find the files. I got this error in the console:
```
flutter: log: openOptional({
    file = "k_20_700.mp3";
    folder = "assets/audio";
})
flutter: log: resource not found k_20_700.mp3
flutter: log: playnil
```

I already tried adding this to the `info.plist`:

```
<key>NSAppTransportSecurity</key>
        <dict>
            <key>NSAllowsArbitraryLoads</key>
            <true/>
        </dict>
```

but nothing changed.

The file is there and it's working on Android.

**Comment by andreahaku** [comment]
@lubritto I tried logging in the Swift code and in the Dart code of the library but haven't found why it is not finding the files.

I also tried removing the `subdirectory` and having the Swift code look for the file based on name and extension but no success.

Any idea? Thanks.

**Comment by rookie17** [comment]
> @lubritto I tried logging in the Swift code and in the Dart code of the library but haven't found why it is not finding the files.
> 
> I also tried removing the `subdirectory` and having the Swift code look for the file based on name and extension but no success.
> 
> Any idea? Thanks.


Have you found a way to fix that issue? I have exactly the same problem, 
This is what I see in the console:
flutter: log: openOptional({
    file = "introFadeout.mp3";
    folder = "assets/sounds";
})

The problem is only happening on iOS

**Comment by andreahaku** [comment]
@rookie17 no unfortunately I haven't found any solution. I'm thinking about using another library at this point.

That's a pity as it is working perfectly well on Android and I'm pretty sure that the solution is not that difficult but not being an iOS developer is actually difficult for me to understand where the problem may be.

**Comment by MarkOSullivan94** [comment]
Yeah it looks like it doesn't work for iOS. Could do with some kind of warning on the README.

**Comment by jovanovski** [comment]
Same issue here, works on Android, does not work on iOS

```
flutter: log: openOptional({
    file = "mascot_clean.mp3";
    folder = "assets/sounds";
})
flutter: log: resource not found mascot_clean.mp3
flutter: log: playnil
```

**Comment by RicardoRB** [comment]
Same issue as @jovanovski Any idea why this could happen?

**Comment by gridfriday** [comment]
Modify the following file: SwiftAssetsAudioPlayerPlugin.swift

You will find it in the package directory (ios/Classes/)

In function open(), 

replace:
guard let url = Bundle.main.url(forResource: asset, withExtension: "", subdirectory: "flutter_assets/"+folder) else {
...
} 

with: 
guard let url = Bundle.main.url(forResource: asset, withExtension: "", subdirectory: "Frameworks/App.framework/flutter_assets/" + folder + "/") else {
...
}

**Comment by RicardoRB** [comment]
@gridfriday could you create a pull request?

**Comment by florent37** [comment]
ccan you try with 1.0.2 ?
