### ISSUE TITLE
Example code pubspec.yaml gives error code 66

### ISSUE THREAD

**Issue by Nucl3arSn3k** [florent37/Flutter-AssetsAudioPlayer#10]
Good morning. When I run the example code included on the github,and I attempt to run the pubspec.yaml file,this occurs.

`Could not find a file named "pubspec.yaml" in "C:\Users\Skelly\Documents\offline code".
pub get failed (66)
exit code 66`

How can I fix this?

**Comment by florent37** [comment]
can you try with the current code ?
