### ISSUE TITLE
Playlist issue 

### ISSUE THREAD

**Issue by Abdaallaa** [florent37/Flutter-AssetsAudioPlayer#104]
The playlist don't loop over all its audios 
I have a list of words (1s for each audio)
And want to play it 
Code
assetsAudioPlayer.open(
  Playlist(
    Audio ("assets/audios/colors.mp3"),
    Audio ("assets/audios/blue.mp3"),
    Audio ("assets/audios/colors.mp3"),
    Audio ("assets/audios/blue.mp3")
  )
);

**Comment by florent37** [comment]
Did you set loop to true ?

**Comment by florent37** [comment]
assetsAudioPlayer.loop = true

**Comment by Abdaallaa** [comment]
I don't want it to loop 
I mean I put in the list 6 audios as an example 
It will play the first one then the third then the fifth then the last one 

So if I want to play it I have to add empty MP3 file after each audio

**Comment by florent37** [comment]
Oh ok it send multiple time ''finished'' maybe, I'll look for this !

**Comment by florent37** [comment]
I reproduced it and fixed it, you can find it in `1.6.0+1`

**Comment by florent37** [comment]
https://github.com/florent37/Flutter-AssetsAudioPlayer/commit/b245c030ae7d54cd6981ae1b47ab5bf612a52105

**Comment by Abdaallaa** [comment]
it worked well thanks
