### ISSUE TITLE
App crashes entirely on Real IOS Device, version 1.6.0.

### ISSUE THREAD

**Issue by Azandowski** [florent37/Flutter-AssetsAudioPlayer#106]
App crashes when I try to play music Audio or Playlist. Does not matter

**Comment by florent37** [comment]
Again 😅

**Comment by florent37** [comment]
I'll try this when I will be home

**Comment by florent37** [comment]
can you follow the teemplate & send me a code to try please ?

**Comment by florent37** [comment]
I tried the sample main.dart on a real iphone & no crash, can you send me a compilable code that crash please ?

**Comment by florent37** [comment]
without futher informations I close it, please send testable code to reproduce
