### ISSUE TITLE
Is there any limitation using App Background

### ISSUE THREAD

**Issue by kalismeras61** [florent37/Flutter-AssetsAudioPlayer#107]
We will create a music app it will run background  and also foreground s want know Is there any limitation running backgroundor foreground ? Can i run music 2-3 hours without killing app by OS?

**Comment by florent37** [comment]
I'm currently using a foreground service to display notification on Android, but half of the player is handled on Flutter / dart side. I think if I start a background service it will be in another service which will not have access to the flutter runtime, so it will only can play the current audio (the flutter -> android) only perform actions on 1 audio per player, so it will be complicated to have all features on real background

**Comment by manojvsp12** [comment]
As a user, I haven't noticed any limitations in usage in foreground or background. Some custom mobile OS have battery optimizations enabled, which may kill the app and that needs to be disabled the user.

**Comment by florent37** [comment]
maybe, as you have a notification the process is still in foreground, I don't think the os will kill it

**Comment by florent37** [comment]
Background services are limited on android, the solution is often to use foreground & attach to notification, without this (notification + foreground) the app might be killed after 10s
