### ISSUE TITLE
Audio.file issue 

### ISSUE THREAD

**Issue by Abdaallaa** [florent37/Flutter-AssetsAudioPlayer#108]
Assets audio and network works well but when I try to run a file audio i have the following issue 
![15902893888655479911865246292203](https://user-images.githubusercontent.com/44484978/82744685-1e6a2600-9d7c-11ea-9808-9bf4121e80bb.jpg)

I pass the path to it

**Comment by florent37** [comment]
it seems to be an exo player issue, maybe it's related to m4a format

**Comment by florent37** [comment]
i'm using progressive container to play audios, and it's compatible with m4a 


https://exoplayer.dev/supported-formats.html#progressive-container-formats

**Comment by florent37** [comment]
I don't know what I should change to fix this, the exoplayer is an external library provided by google, and we do not define what extractor it uses, just provide a container & an audio

**Comment by florent37** [comment]
for you case, the setup used of exoplayer is : 

```dart
 val path = if (assetAudioPackage.isNullOrBlank()) {
                    flutterAssets.getAssetFilePathByName(assetAudioPath!!)
                } else {
                    flutterAssets.getAssetFilePathByName(assetAudioPath!!, assetAudioPackage)
                }
                val assetDataSource = AssetDataSource(context)
                assetDataSource.open(DataSpec(Uri.parse(path)))

                val factory = DataSource.Factory { assetDataSource }
                mediaSource = ProgressiveMediaSource
                        .Factory(factory, DefaultExtractorsFactory())
                        .createMediaSource(assetDataSource.uri)
```

**Comment by Abdaallaa** [comment]
from the assets file(Audio("assets path")) I can play m4a normally 
But within the same assetsAudioPlayer object can't play m4a from Audio.file("path")

**Comment by florent37** [comment]
Ok maybe I have a different setup for file & asset

**Comment by Abdaallaa** [comment]
The problem as the error says comes from the data you passed to the  ProgressiveMediaPeriod class 

the following code which throw the exception (header is from the class WaveHeader) 
`int bytesPerFrame = header.numChannels * header.bitsPerSample / 8;
      // Validate the header. Blocks are expected to correspond to single frames.
      if (header.blockSize != bytesPerFrame) {
        throw new ParserException(
            "Expected block size: " + bytesPerFrame + "; got: " + header.blockSize);
      }`
the header has to contain 2 bytes of data but we pass one 

don't know world it be helpful or not 😅

**Comment by florent37** [comment]
Yes and no :) it's not a code I wrote, it's inside the Google library I use (exoplayer) the only thing I do it create an exo player and give him the audio file

**Comment by florent37** [comment]
Can you send me a m4a you're using please ? Here or by mail if you want to keep it private

**Comment by florent37** [comment]
I tried to migrate to FileDataSource (exoplayer) instead of defaultDataSource

can you try the `^1.6.2+4` ?

**Comment by florent37** [comment]
I set it as closed until you try it
but if this does not work, feel free to reopen it :)

**Comment by Abdaallaa** [comment]
https://drive.google.com/open?id=1A3sfUq_3R1tNo192eqiOAt916fSPNR19
