### ISSUE TITLE
Found double instead of Duration in PlayerBuilder.currentPosition() builder function

### ISSUE THREAD

**Issue by intkhabahmed** [florent37/Flutter-AssetsAudioPlayer#109]
**Flutter Version**

My version : 1.17.1

**Lib Version**

My version : 1.6.0

**Platform (Android / iOS / web) + version**

Platform : Android/iOS

**Describe the bug**

I was trying to use the `PlayerBuilder.currentPosition()` to get the current position of the player, but the builder function was `Function(BuildContext, double)` instead of `Function(BuildContext, Duration)` due to which it was throwing TypeError. Is it the correct function body or not?

**Comment by florent37** [comment]
I think it's a big in the library I'll fix it

**Comment by florent37** [comment]
thanks to have found this, I fixed it

**Comment by florent37** [comment]
I pushed it in `^1.6.0+3` can you try ?

**Comment by intkhabahmed** [comment]
I have verified it, it's working now. Thanks.

**Comment by florent37** [comment]
you're welcome :)
