### ISSUE TITLE
Lock screen controls

### ISSUE THREAD

**Issue by Sun3** [florent37/Flutter-AssetsAudioPlayer#11]
Will the player support lock screen controls? For example, as the music plays on the background and the phone goes to sleep from the lock screen the user needs to be able to pause the audio or skip or stop.

Thanks

**Comment by shinriyo** [comment]
@Sun3 
https://github.com/luanpotter/audioplayers
it is better

**Comment by Sun3** [comment]
@shinriyo Thanks for the suggestion unfortunately audioplayers also does not support player controls on the lock screen.

**Comment by Sun3** [comment]
I wanted to check if there was an updated status on adding support for lock screen controls.

Thanks

**Comment by TheAlexandru** [comment]
I use
https://pub.dev/packages/flutter_media_notification

It is not perfect but it does the job

**Comment by florent37** [comment]
you can use for now https://pub.dev/packages/flutter_media_notification
