### ISSUE TITLE
Add a song to on play playlist

### ISSUE THREAD

**Issue by sahharYoucef** [florent37/Flutter-AssetsAudioPlayer#110]
Is there any way to add a song to playlist , like updating current list when it's on play .and please add extra field to Metas to add a map of value , i already forked your project and did that but i think it's a good feature to add.

**Comment by florent37** [comment]
If you forked to add this could you provide a pull Request ? 😎

For adding into a playing playlist I'll looking for this, it should not be difficult to add ✌️

**Comment by florent37** [comment]
thanks for the pull request i merged it and published it in 1.6.0+4

**Comment by florent37** [comment]
for the mutable playlist I'll do this tomorrow ;)

**Comment by florent37** [comment]
I added those two methods on playlist 

```dart
Playlist add(Audio audio);

Playlist addAll(List<Audio> audios);
```

**Comment by florent37** [comment]
and removed the immutable code around this

**Comment by florent37** [comment]
I also added a getter `assetAudioPlayer.playlist` to retrieve the current playing playlist (beware, can be null)

**Comment by florent37** [comment]
I pushed it in 1.4.1, you can try :)
