### ISSUE TITLE
Music player paused accidentally when the app is launching

### ISSUE THREAD

**Issue by AlexVincent525** [florent37/Flutter-AssetsAudioPlayer#112]
**Flutter Version**

My version : 1.17.1

**Lib Version**

My version : 1.6.0+4

**Platform (Android / iOS / web) + version**

Platform : Android (iOS not tested)
Device Model: OnePlus 8 Pro (IN2020) / OnePlus 6T (A6010)

**Describe the bug**

When a flutter app implemented this package (e.g. just import it), start the app will pause the current playing audio (Music that was playing).

**Step to reproduce**

1. Add `assets_audio_player: ^1.6.0+4` into `pubspec.yaml`.
2. Play a song with some music player.
3. Run the app.
4. When the app start, the song was paused.

**Comment by florent37** [comment]
when you tell `current playing audio`, it's for example "youtube music player" ?

**Comment by AlexVincent525** [comment]
Yes, just like the one in the screenshot.
![Screenshot_20200526-003123__01](https://user-images.githubusercontent.com/15884415/82830425-4b3b4c00-9ee8-11ea-8532-e16ae319fc51.jpg)

**Comment by florent37** [comment]
Ok thanks that's my next bug to fix !

**Comment by florent37** [comment]
found, it's because of the `requestAudioFocus`, used to pause the media player on phone call

**Comment by florent37** [comment]
maybe I can make this optional, like "requestAudioFocus: true" on open method (by default), which enable to listen audio focus & stop on phone call


setting it to false will solve your issue, but recieving a phone call will not pause the audio !

**Comment by florent37** [comment]
or maybe migrate to https://stackoverflow.com/questions/5948961/how-to-know-whether-i-am-in-a-call-on-android, to only pause on phone call :) I'll look for this

**Comment by florent37** [comment]
this solution requires runtime permission :/ it's not a good solution for the user

**Comment by AlexVincent525** [comment]
> found, it's because of the `requestAudioFocus`, used to pause the media player on phone call

This sounds good. How if we can `requestAudioFocus` only when we start the first play?

**Comment by florent37** [comment]
If we do this, it will stop the other media player at the start, like your qq music player

I think you'll need to make a choice, 

1. make this media player require focus (pause others players, intercept phone call state)

2. Don't mind if audio focus : don't pause other players, but don't know if the phone is receiving a call

**Comment by AlexVincent525** [comment]
> 1. make this media player require focus (pause others players, intercept phone call state)

Am I missing something? I mean pause other players when the app which calling this package to play an audio. This behaviour is fine because it calls by user's request.

e.g. I'm playing some music with QQMusic, then I start my flutter app, choose an audio and try to play it, at that time it should stop my music and play the audio I requested.

**Comment by florent37** [comment]
Oh ok I see, I just have to move the request audio, sorry ^^ I'll do that today

**Comment by florent37** [comment]
I fixed this, can you try the  `^1.6.2+5` ?

**Comment by florent37** [comment]
I close it but if this does not work, reopen it please :)

**Comment by AlexVincent525** [comment]
Thanks for your rapid response! And it's been resolved through I tested with my devices.

**Comment by vinh-savvycom** [comment]
Hi @AlexV525 , current I'm using version assets_audio_player: ^2.0.13+8. But when I play a AssetsAudioPlayerGroup. Sound play normally but when I go to background and open app again. Sound auto stopped. Please help me check it. Thanks

**Comment by kalismeras61** [comment]
@vinh-savvycom can you paste your open method here ?

**Comment by vinh-savvycom** [comment]
@kalismeras61 here is code init AssetsAudioPlayerGroup
```
AudioPlayer() {
    playerGroup = AssetsAudioPlayerGroup(
      updateNotification: (player, audios) async {
        return PlayerGroupMetas(
          title: currentSong.title,
          subTitle: currentSong.categoryName,
          image: MetasImage.network(
              getUrlFromServer(currentSong.thumb.path, currentSong.thumb.uuid)),
        );
      },
      respectSilentMode: true,
      showNotification: true,
      notificationStopEnabled: false,
      onNotificationPause: (player, audios) {
        togglePlay();
      },
      onNotificationPlay: (player, audios) {
        togglePlay();
      },
    );
  }
```

and here sample code add audio and play

```
Audio audio = Audio.network(
            getMediaURLFromServer(soundData.path, soundData.uuid),
            metas: Metas(
              title: song.title,
              album: song.categoryName,
              image: MetasImage.network(
                getUrlFromServer(song.thumb.path, song.thumb.uuid),
              ),
            ),
          );
          playerGroup.add(
            audio,
            volume: soundData.fileVolume / 100.0,
            loopMode: LoopMode.single,
          );
```
