### ISSUE TITLE
Optional change icon on background player

### ISSUE THREAD

**Issue by vladimirlapikov** [florent37/Flutter-AssetsAudioPlayer#115]
Hi , it will be helpful to add control over an icon of background player to change the default icon to my app icon for example
thnx again :)

**Comment by florent37** [comment]
It will be dificult because you have to give on Android a resource icon (like the launcher icon)

I think the simplest way to provide it is to add a manifest extra field which will refer to the notification icon (like how firebase does)

**Comment by vladimirlapikov** [comment]
Thanks,I"ll check it

**Comment by florent37** [comment]
For now it's not implemented but I'll try to add this field. It will not be configurable from flutter but from the Android manifest

**Comment by florent37** [comment]
just added

in your android/app/src/main/AndroidManifest.xml

add

```
<meta-data
            android:name="assets.audio.player.notification.icon"
            android:resource="@drawable/ic_music_custom"/>
```

here ic_music_custom is a drawable I added into android resources, like the launcher icon

**Comment by florent37** [comment]
I pushed it in `1.6.2`

**Comment by florent37** [comment]
(meta data goes inside <application> 

```xml
     ...

     <meta-data
            android:name="assets.audio.player.notification.icon"
            android:resource="@drawable/ic_music_custom"/>
  
    </application>
</manifest>
```

**Comment by vladimirlapikov** [comment]
thank you very very much :)))))

**Comment by florent37** [comment]
You're welcome thanks for using this lib and pushing issues :)
