### ISSUE TITLE
bluetooth headset  doens't work

### ISSUE THREAD

**Issue by kalismeras61** [florent37/Flutter-AssetsAudioPlayer#117]
**Flutter Version**

My version : 1.17.1 stable

**Lib Version**

My version : 1.6.0+4 

**Platform (Android / iOS / web) + version**

Platform : Andorid 

I have bluetooth headset which has only pause/play icon it is working with spotify, anghami app but when i use with your plugin it is not working. ( Notification center is already enabled. )

**Comment by florent37** [comment]
What's your Android version please ?

**Comment by kalismeras61** [comment]
Android version is 9

**Comment by florent37** [comment]
Did you enabled notification on this asset audio player ?

On the open methode

**Comment by kalismeras61** [comment]
Yes, of course. I can see notification center musics only headset dosent work

**Comment by kalismeras61** [comment]
Is there anything ? for testing?

**Comment by florent37** [comment]
I did not changed anything about this since the last commits, I'll work on it soon

**Comment by florent37** [comment]
but it's related to https://github.com/florent37/Flutter-AssetsAudioPlayer/issues/97
fixing this will surely fix the #97

**Comment by florent37** [comment]
I pushed some code around bluetooth can you try the `1.6.3+1` ?

**Comment by kalismeras61** [comment]
Ok, will test and let you know.
