### ISSUE TITLE
When app is killed from task switcher the background player not dissapears

### ISSUE THREAD

**Issue by vladimirlapikov** [florent37/Flutter-AssetsAudioPlayer#118]
Hi, when I play a song and closing the app from task switcher (with background player on), the background player stays on, when the song is not played or paused it works as expected - quits the app and quits the background player too

**Comment by florent37** [comment]
thanks to have found this, I fix it

**Comment by florent37** [comment]
fixed in `^1.6.2+2` can you try ?

**Comment by vladimirlapikov** [comment]
It's working !!!!!!! definitely buying you a coffee's !!!!  thank you for your effort

**Comment by florent37** [comment]
You have a Kofi link in the sponsor button ✌️😎

**Comment by vladimirlapikov** [comment]
Is this an option too to support directly from ko-fi site? --> https://ko-fi.com/A160LCC
