### ISSUE TITLE
error while flutter create example

### ISSUE THREAD

**Issue by BahodurSaidov** [florent37/Flutter-AssetsAudioPlayer#119]
**Flutter Version**

My version : 1.17.0 channel beta

**Lib Version**

My version : 1.6.2

**Platform (Android / iOS / web) + version**

Platform : Android

**Describe the bug**

After git cloning, run in example, flutter create .
flutter build apk --release 

Error:
Recreating project ....
  android\app\build.gradle (created)
  android\app\src\main\kotlin\com\github\florent37\example\MainActivity.kt (created)
  android\build.gradle (created)
  android\example_android.iml (created)
  android\.gitignore (created)
  android\app\src\debug\AndroidManifest.xml (created)
  android\app\src\main\AndroidManifest.xml (created)
  android\app\src\main\res\drawable\launch_background.xml (created)
  android\app\src\main\res\mipmap-hdpi\ic_launcher.png (created)
  android\app\src\main\res\mipmap-mdpi\ic_launcher.png (created)
  android\app\src\main\res\mipmap-xhdpi\ic_launcher.png (created)
  android\app\src\main\res\mipmap-xxhdpi\ic_launcher.png (created)
  android\app\src\main\res\mipmap-xxxhdpi\ic_launcher.png (created)
  android\app\src\main\res\values\styles.xml (created)
  android\app\src\profile\AndroidManifest.xml (created)
  android\gradle\wrapper\gradle-wrapper.properties (created)
  android\gradle.properties (created)
  android\settings.gradle (created)
The plugin `assets_audio_player` doesn't have a main class defined in D:\...\...\flutter_audio_newer\android\src\main\java\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.java or D:\...\...\flutter_audio_newer\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt. This is likely to due to an incorrect `androidPackage: com.github.florent37.assets_audio_player` or `mainClass` entry in the plugin's pubspec.yaml.
If you are the author of this plugin, fix the `androidPackage` entry or move the main class to any of locations used above. Otherwise, please contact the author of this plugin and consider using a different plugin in the meanwhile.

**Comment by florent37** [comment]
thanks I fix it

**Comment by florent37** [comment]
can you `git pull` then try again please ?

**Comment by florent37** [comment]
I think I should move to beta for this case, in master it only use package & pluginClass

**Comment by florent37** [comment]
if it not work it's maybe a flutter cache error 

can you try this ?

https://github.com/flutter/flutter/issues/52739#issuecomment-600566849

**Comment by BahodurSaidov** [comment]
> if it not work it's maybe a flutter cache error 
> 
> can you try this ?
> 
> https://github.com/flutter/flutter/issues/52739#issuecomment-600566849

Hi, it seems this issue is not related to that. I tried (before creating this issue) by recloning 2 times and also tried flutter doctor (with no problems), flutter clean... 
No idea what to say... 

Actually i thing my previous clone is still working fine with building...

**Comment by BahodurSaidov** [comment]
I will try with new clone soon lil busy now...

**Comment by BahodurSaidov** [comment]
Also just to mention that after trying this plugin i had cloned the official flutter Gallery app and successfully built with latest updates...no issues

**Comment by BahodurSaidov** [comment]
> can you `git pull` then try again please ? 

I think your this commit did the trick! I updated my file accordingly and clean build worked!

But another issue in the example is the scroll issue in the app... I can't scroll down to access other functional buttons...

**Comment by florent37** [comment]
my sample is not responsive, I should try to make it scrollable yes, i'm using large device for now
