### ISSUE TITLE
Notification player doesn't hold play/pause state when there is incoming call

### ISSUE THREAD

**Issue by manojvsp12** [florent37/Flutter-AssetsAudioPlayer#122]
**Flutter Version**

My version : 1.19.0

**Lib Version**

My version : 1.6.0+2

**Platform (Android / iOS / web) + version**

Platform : Android

**Describe the bug**

Current Notification player is in paused state and app is running backgroud. There is an incoming call. After call ends, player starts playing automatically where it should be in paused state.

**Comment by florent37** [comment]
thanks for the issue, did you pause manually the audio before the call ?

**Comment by florent37** [comment]
you want the audio to keep the pause state after the phone call stop ?

**Comment by manojvsp12** [comment]
yes..before call, manually paused. and after call ends, expecting the player to be in paused state itself. if its in playing state before call, expecting to continue playing after call ends.

**Comment by florent37** [comment]
Yes I added some code to pause the audio automatically on phone call then restore the state after the phone call.

I need to try with a manually pause just before, maybe I have a bug

**Comment by florent37** [comment]
I do not reproduce, please look https://youtu.be/DHdkFaRE8ZE

**Comment by florent37** [comment]
can you record your screen too ?

**Comment by florent37** [comment]
& send me your "open" code please

**Comment by manojvsp12** [comment]
I upgraded to latest AssetsAudioPlayer and i didnt find this issue.  If I find again, will repoen this issue.

**Comment by florent37** [comment]
thanks :)
