### ISSUE TITLE
Notification buttons

### ISSUE THREAD

**Issue by azamat7g** [florent37/Flutter-AssetsAudioPlayer#124]
**Flutter Version**

My version : 1.17.0

**Lib Version**

My version : 1.6.2

**Platform (Android / iOS / web) + version**

Platform : Android

**Describe the bug**

Thanks for this awesome package. I try to use this package for radio app. So i enable notification and disable all buttons except play/pause. Notification not appear. I try to find a problem and i found it. The problem in this file NotificationService.kt:140. If all buttons are disabled the function setShowActionsInCompactView(0, 1, 2) gives error. Please fix this issue, thanks

code:
```
AssetsAudioPlayer radioPlayer = AssetsAudioPlayer();

radioPlayer.open(
  Audio.liveStream(
    STREAM_URL,
    metas: Metas(
      title: "Title",
      artist: "Artist",
      image: MetasImage.network(...)
    ),
  ),
  showNotification: true,
  notificationSettings: NotificationSettings(
    stopEnabled: false,
    prevEnabled: false,
    nextEnabled: false,
    playPauseEnabled: true
  )
);
```

**Comment by florent37** [comment]
I fixed it, will push it in `1.6.2+3`
