### ISSUE TITLE
Loop audio makes interval of half second 

### ISSUE THREAD

**Issue by vladimirlapikov** [florent37/Flutter-AssetsAudioPlayer#125]
Hi, when  I make audio player in a loop there is an interval between, 
example:
my audio file is 1 minute length, when I looping it the file ends and then there is a silence for half second,maybe less, but it breaks the "illusion" of endless audio'
thnx again for effort , 
P.S. bought you coffees through "buy me a coffee" button link :)))

**Comment by florent37** [comment]
Thanks a lot for the cofee :)

Yes it's an issue I know, it's the gape-less

For multiple audios it seems to be difficult, but for 1 audio which loop I think I can do something

**Comment by florent37** [comment]
implemented on android, it works, just wait until I add this on ios(&mac) & web

**Comment by vladimirlapikov** [comment]
Thank U very very much :)))))

**Comment by florent37** [comment]
I have to set the minVersion ios to 10.0 for that feature :/ is it ok for you @vladimirlapikov ?

**Comment by florent37** [comment]
I have to use this class https://developer.apple.com/documentation/avfoundation/avplayerlooper

before there will be a gap between sounds

**Comment by florent37** [comment]
nice, I do not set the min sdk, but keep in mind before ios10 you'll get a gap

**Comment by vladimirlapikov** [comment]
OK, I will remember that :)

**Comment by florent37** [comment]
but I add this functionality too on ios8/9, but with a ***ing gap

just missing the web and it'll be ok for you to try

**Comment by florent37** [comment]
can you try with `2.0.0+5` ?

**Comment by Alphabets007** [comment]
There is gap when playing single audio in loop. Second time audio starts after very small silent gap.
I am using version 2.0.9+2

**Comment by vladimirlapikov** [comment]
Take a look at this issue:
https://sound.stackexchange.com/questions/25846/is-it-possible-to-loop-mp3-without-gaps

**Comment by Alphabets007** [comment]
> > There is gap when playing single audio in loop. Second time audio starts after very small silent gap.
> > I am using version 2.0.9+2
> > Hi the solution I found is simply to use non mp3 files
> > `

I am using OGG file, but its not working.

**Comment by vladimirlapikov** [comment]
Ogg maybe in the list too,anyway
When you playing a loop what audio redactor do u use?

**Comment by Alphabets007** [comment]
> Ogg maybe in the list too,anyway
> When you playing a loop what audio redactor do u use?

I don't know what is "Audio Redactor".

**Comment by vladimirlapikov** [comment]
> > Ogg maybe in the list too,anyway
> > When you playing a loop what audio redactor do u use?
> 
> I don't know what is "Audio Redactor".

Ok,i used Cubase to prepare my audio files for the app,do u use simething like that?
Because maybe the Audio you use has a gap instantly

**Comment by Alphabets007** [comment]
> > > Ogg maybe in the list too,anyway
> > > When you playing a loop what audio redactor do u use?
> > 
> > 
> > I don't know what is "Audio Redactor".
> 
> Ok,i used Cubase to prepare my audio files for the app,do u use simething like that?
> Because maybe the Audio you use has a gap instantly

No i don't use anything like that, but i downloaded audio from free websites

**Comment by vladimirlapikov** [comment]
So maybe try audacity, it can help

**Comment by wellbranding** [comment]
Any updates on IOS? I have checked and indeed the gap exists :(
