### ISSUE TITLE
Bluetooth controls on release

### ISSUE THREAD

**Issue by florent37** [florent37/Flutter-AssetsAudioPlayer#129]
**Platform (Android / iOS / web) + version**

Platform : Android

**Describe the bug**

When I am running my app in debug mode (flutter run), I am able to control app using media buttons 

but when I build as apk for release (flutter build apk --release), install apk manually and tried to control, I am unable to control.

**Comment by florent37** [comment]
I pushed some code around bluetooth can you try the `1.6.3+1` ?

**Comment by manojvsp12** [comment]
Checked on 1.6.4 and it works on release version. Tested with oneplus bullets wireless and Volkswagen car media player. Thanks a lot. 🥳

**Comment by florent37** [comment]
Awesome 😎
