### ISSUE TITLE
Urls with %2F do not work

### ISSUE THREAD

**Issue by SHRJamal** [florent37/Flutter-AssetsAudioPlayer#134]
Flutter version: 1.17 Stable

Lib version: 1.6.3

Platform:  Android

Bug:

Audio links that have %2F inside are not working, I guess the plugin replace with '/'.
For example, I have this link I get from firebase storage:
[url-example](https://firebasestorage.googleapis.com/v0/b/heylol-b41f2.appspot.com/o/Chats%2Fsound_file%2F1590428125470.aac?alt=media&token=88cbc7b2-cf24-4e86-9c07-a2072dcd43d6)
This doesn't work when I try to play it in the plugin, but if u copy it in the browser is working fine.

Thanks

**Comment by florent37** [comment]
It's on Android ok Maybe I have a configuration around uri to add, will check, thanks for the uri, this will help a lot

**Comment by SHRJamal** [comment]
Thanks!
Just note that may help too:
This plugin [https://github.com/luanpotter/audioplayers](audioplayers) is playing them right.

**Comment by florent37** [comment]
Yes I'll check but maybe they do not use exoplayer

**Comment by florent37** [comment]
Yes they're using the old mediaplayer, but no worry I'll find ! If I can reproduce I can fix it

**Comment by SHRJamal** [comment]
Thanks for all effort you do for the community, This plugin is really awesome.

**Comment by florent37** [comment]
Thanks 🥰

**Comment by florent37** [comment]
Yes it's the Uri that replace it by %2F, and the exo player I use take only uri as input, I'm trying to find how to prevent formatting the %2F but I think it's not possible

**Comment by florent37** [comment]
Exoplayer give me some issues too on some audio format. I think I'll add the two implementation in my lib, by default : exoplayer & if I have an issue opening the audio, switch to mediaplayer, but some functionnalities may not work (ex, playspeed)

**Comment by florent37** [comment]
I started to implement this, this will fix your case & also other issues

**Comment by SHRJamal** [comment]
Thanks!
I guess this is a good idea, both solution Exoplayer and MediaPlayer have problems, merging them will solve many issues.
Isn't there any native Android plugin wrapping those players that solve these issues?

**Comment by florent37** [comment]
I don't know :/

**Comment by florent37** [comment]
I'm currently working on it don't worry

**Comment by florent37** [comment]
it works ! I create a merge request & will publish a beta to let you try

**Comment by florent37** [comment]
It's not really sexy but it combine exoplayer & media player to use the one who works

**Comment by florent37** [comment]
hummm I have to fix some thigs before publis this :) but I'm on a good way, I publish it in a branch & merge request for you if you want to try (on a sample)

**Comment by florent37** [comment]
Look at this branch if you want, I'll adjust some code before pushing it into pub.dev,
But you can clone the repo & try your code inside main.dart

**Comment by SHRJamal** [comment]
Thank you, I will try it.

**Comment by SHRJamal** [comment]
It works, that what I get, it logged the previews error, and then plays.
That cool.
<img width="842" alt="Screen Shot 2020-05-28 at 20 01 51" src="https://user-images.githubusercontent.com/31532251/83187910-cdb14f00-a126-11ea-93ff-845344ba5895.png">

I will try to use that branch on my app to see how it goes.

**Comment by florent37** [comment]
yes it's because I try with exoplayer, then try with mediaplayer

you can tyr with `1.6.3+2`, I publish it

**Comment by florent37** [comment]
published
