### ISSUE TITLE
Example doesn't build

### ISSUE THREAD

**Issue by mtoka** [florent37/Flutter-AssetsAudioPlayer#136]
**Flutter Version**

My version : 1.17.1

**Lib Version**

My version : 

**Platform (Android / iOS / web) + version**

Platform : Android Nexus 6 API 28

**Describe the bug**

When trying to Run main.dart after cloning. I get error:

```
FAILURE: Build failed with an exception.

* Where:
Settings file '/Users/<username>/Projects/AndroidStudioProjects/flutter_projects/Flutter-AssetsAudioPlayer/example/android/settings.gradle' line: 15

* What went wrong:
A problem occurred evaluating settings 'android'.
> Could not read script '/Users/<username>/Development/flutter/packages/flutter_tools/gradle/app_plugin_loader.gradle' as it does not exist.
```

**Comment by florent37** [comment]
it's related to https://github.com/flutter/flutter/issues/55619

**Comment by florent37** [comment]
what's your flutter branch ?

**Comment by florent37** [comment]
can you try to put this in `example/android/settings.gradle`

```
include ':app'

def flutterProjectRoot = rootProject.projectDir.parentFile.toPath()

def plugins = new Properties()
def pluginsFile = new File(flutterProjectRoot.toFile(), '.flutter-plugins')
if (pluginsFile.exists()) {
pluginsFile.withReader('UTF-8') { reader -> plugins.load(reader) }
}

plugins.each { name, path ->
def pluginDirectory = flutterProjectRoot.resolve(path).resolve('android').toFile()
include ":$name"
project(":$name").projectDir = pluginDirectory
}
```

it this work, I'll include this directly into the sample

**Comment by florent37** [comment]
I pushed it in the last commit, can you try to `git pull` then try again ?

**Comment by mtoka** [comment]
> what's your flutter branch ?

stable

**Comment by florent37** [comment]
I'm on master, but did the change described in the other issue, can you try with the new version of example/ (git pull)

**Comment by mtoka** [comment]
Yes, i tried `git pull`
works on iPhone Simulator 13.5 iPhone 11 Pro with console output:
```
Launching lib/main.dart on iPhone 11 Pro in debug mode...
Running Xcode build...
Xcode build done.                                           20.5s
Debug service listening on ws://127.0.0.1:55170/jhuBq2rS3w8=/ws
Syncing files to device iPhone 11 Pro...
flutter: finished : false
```
for your reference look on last line in above code.
works on Android Emulator
```
Launching lib/main.dart on AOSP on IA Emulator in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build/app/outputs/apk/debug/app-debug.apk.
Debug service listening on ws://127.0.0.1:58363/raEA_nByTU4=/ws
Syncing files to device AOSP on IA Emulator...
D/EGL_emulation(13114): eglMakeCurrent: 0xe4a24500: ver 3 0 (tinfo 0xe4a6d7d0)
D/eglCodecCommon(13114): setVertexArrayObject: set vao to 0 (0) 1 0
I/flutter (13114): finished : false
```
again, despite last line app is running on emulator

Seems all functionality is working correctly.

**Comment by florent37** [comment]
So the issue is still opened ? 

You cannot run it where ?

**Comment by mtoka** [comment]
I would say it is resolved, thanks.
Not sure what are implications of last line from console
`flutter: finished : false`

**Comment by florent37** [comment]
flutter: finished : false it's just because the "stream" finished is initialized with the "false" value

it's an Rx BehaviorSubject

**Comment by florent37** [comment]
```
  final BehaviorSubject<bool> _playlistFinished =
      BehaviorSubject<bool>.seeded(false);
```
