### ISSUE TITLE
Notification disappears after sometime when audio is paused 

### ISSUE THREAD

**Issue by vipulasri** [florent37/Flutter-AssetsAudioPlayer#139]
**Flutter Version**

My version : stable latest

**Lib Version**

My version : 1.6.3+2

**Platform (Android / iOS / web) + version**

Platform : Android

**Describe the bug**

Notification disappears after sometime when audio is paused, approx within a minute. 

**Steps to reproduce**
1. Play a sound with notification
2. Pause the sound 
3. Wait for around a minute, notification will disappear 

**Expected Behaviour**
Notification shouldn't disappear as there can be a case where user paused it for some reason in between and when he wants to resume, notification is not there.

**Comment by florent37** [comment]
I think I know why, 
I think it's because of this code on android 

NotificationService.kt line 173
```
 if (!action.isPlaying) {
            stopForeground(false)
        }
```

**Comment by florent37** [comment]
I'll try to remove this and see if It does not add bugs

**Comment by vipulasri** [comment]
Yeah, I saw that code that's why raised the issue. As I wanted to know your perspective on this implementation.

**Comment by florent37** [comment]
fixed and published in `1.6.4`

**Comment by florent37** [comment]
can you try ?

**Comment by vipulasri** [comment]
It's working now. It's fixed. 🎉

**Comment by florent37** [comment]
✌️
