### ISSUE TITLE
Error on IOS

### ISSUE THREAD

**Issue by drmcoder** [florent37/Flutter-AssetsAudioPlayer#141]
Xcode's output:
↳
    /Users/santoshrijal/development/flutter/.pub-cache/hosted/pub.dartlang.org/webview_media-0.1.2/ios/Classes/FlutterWebView.m:407:20: warning: 'loadData:MIMEType:characterEncodingName:baseURL:' is only available on iOS 9.0 or newer [-Wunguarded-availability]
      return [_webView loadData:nsData MIMEType:mimeType characterEncodingName:encoding baseURL:nsUrl];
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'WebKit' imported from /Users/santoshrijal/development/flutter/.pub-cache/hosted/pub.dartlang.org/webview_media-0.1.2/ios/Classes/FlutterWebView.h:6:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/WebKit.framework/Headers/WKWebView.h:116:1: note: 'loadData:MIMEType:characterEncodingName:baseURL:' has been marked as being introduced in iOS 9.0 here, but the deployment target is iOS 8.0.0
    - (nullable WKNavigation *)loadData:(NSData *)data MIMEType:(NSString *)MIMEType characterEncodingName:(NSString *)characterEncodingName baseURL:(NSURL *)baseURL API_AVAILABLE(macos(10.11), ios(9.0));
    ^
    /Users/santoshrijal/development/flutter/.pub-cache/hosted/pub.dartlang.org/webview_media-0.1.2/ios/Classes/FlutterWebView.m:407:20: note: enclose 'loadData:MIMEType:characterEncodingName:baseURL:' in an @available check to silence this warning
      return [_webView loadData:nsData MIMEType:mimeType characterEncodingName:encoding baseURL:nsUrl];
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 warning generated.
    /Users/santoshrijal/development/flutter/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-1.6.4/ios/Classes/Music.swift:136:44: error: type 'AVAudioSession.Category' (aka 'NSString') has no member 'playback'
                return AVAudioSession.Category.playback
                       ~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~
    /Users/santoshrijal/development/flutter/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-1.6.4/ios/Classes/Music.swift:138:44: error: type 'AVAudioSession.Category' (aka 'NSString') has no member 'soloAmbient'
                return AVAudioSession.Category.soloAmbient
                       ~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~
    /Users/santoshrijal/development/flutter/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-1.6.4/ios/Classes/Music.swift:140:44: error: type 'AVAudioSession.Category' (aka 'NSString') has no member 'playback'
                return AVAudioSession.Category.playback
                       ~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~
    /Users/santoshrijal/development/flutter/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-1.6.4/ios/Classes/Music.swift:187:66: error: type 'String' has no member 'playback'
                    try AVAudioSession.sharedInstance().setCategory(.playback, mode: .default, options: [])
                                                                    ~^~~~~~~~
    /Users/santoshrijal/development/flutter/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-1.6.4/ios/Classes/Music.swift:187:83: error: type 'String' has no member 'default'
                    try AVAudioSession.sharedInstance().setCategory(.playback, mode: .default, options: [])
                                                                                     ~^~~~~~~
    /Users/santoshrijal/development/flutter/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-1.6.4/ios/Classes/Music.swift:190:66: error: type 'String' has no member 'playback'
                    try AVAudioSession.sharedInstance().setCategory(.playback, options: [])
                                                                    ~^~~~~~~~
    /Users/santoshrijal/development/flutter/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-1.6.4/ios/Classes/Music.swift:364:44: error: type 'AVAudioSession.Mode' (aka 'NSString') has no member 'default'
                let mode = AVAudioSession.Mode.default
                           ~~~~~~~~~~~~~~~~~~~ ^~~~~~~
    /Users/santoshrijal/development/flutter/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-1.6.4/ios/Classes/Music.swift:367:42: error: value of type 'AVAudioSession.Category' (aka 'NSString') has no member 'rawValue'
                print("category " + category.rawValue);
                                    ~~~~~~~~ ^~~~~~~~
    /Users/santoshrijal/development/flutter/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-1.6.4/ios/Classes/Music.swift:379:65: error: 'AVAudioSession.Category' (aka 'NSString') is not implicitly convertible to 'String'; did you mean to use 'as' to explicitly convert?
                    try AVAudioSession.sharedInstance().setCategory(category, options: .mixWithOthers)
                                                                    ^
                                                                             as String
    /Users/santoshrijal/development/flutter/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-1.6.4/ios/Classes/Music.swift:481:47: error: extraneous argument label 'preferredTimescale:' in call
            let targetTime = CMTimeMakeWithSeconds(Double(to) / 1000.0, preferredTimescale: 1)
                                                  ^                     ~~~~~~~~~~~~~~~~~~~~

    /Users/santoshrijal/development/flutter/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-1.6.4/ios/Classes/Music.swift:527:38: error: 'zero' has been renamed to 'kCMTimeZero'
            self.player?.seek(to: CMTime.zero)
                                         ^~~~
                                         kCMTimeZero
    CoreMedia.CMTime:16:23: note: 'zero' was introduced in Swift 4.2
        public static let zero: CMTime
                          ^
    /Users/santoshrijal/development/flutter/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-1.6.4/ios/Classes/Music.swift:465:11: warning: 'catch' block is unreachable because no errors are thrown in 'do' block
            } catch let error {
              ^
    note: Using new build system
    note: Planning build
    note: Constructing build description

**Comment by florent37** [comment]
it seems to be the same issue (fixed) as https://github.com/florent37/Flutter-AssetsAudioPlayer/issues/126

**Comment by florent37** [comment]
just update the swift version like https://github.com/florent37/Flutter-AssetsAudioPlayer/issues/126#issuecomment-634120409

https://github.com/florent37/Flutter-AssetsAudioPlayer/issues/126#issuecomment-634126652

**Comment by florent37** [comment]
I'll see if I have to do some change in the repo directly

**Comment by florent37** [comment]
I just set the siwft version to 4.2 on the podspec as defined here https://guides.cocoapods.org/syntax/podspec.html

can you try the `1.6.4+2` ?
