### ISSUE TITLE
get audio object from player

### ISSUE THREAD

**Issue by vipulasri** [florent37/Flutter-AssetsAudioPlayer#142]
**Describe the feature you'd like**
Right now, in order to change the notification, we need to update the meta in audio. After the audio has been played, we don't have the access to audio object. 
It will be great to have player object return audio object and then we can modify its meta. 
something like: `player.getAudio()`

**Comment by florent37** [comment]
you can access the audio using the playlist (asset audio player wrap your single audio into a full playlist)

```
final audio = player.readingPlaylist.current;
```

then to modify the metas you have an existing method

as said in the readme

```
After your audio creation, just call 

```dart
audio.updateMetas(
       player: _assetsAudioPlayer, //add the player if the audio is actually played
       title: "My new title",
       artist: "My new artist",
       //if I not provide a new album, it keep the old one
       image: MetasImage.network(
         //my new image url
       ),
);
```
