### ISSUE TITLE
custom action for notification stop

### ISSUE THREAD

**Issue by vipulasri** [florent37/Flutter-AssetsAudioPlayer#143]
**Describe the feature you'd like**
It will be good to have an option to add custom action for "stop" in the notification just like `customPlayPauseAction`, `customNextAction` and `customPrevAction`.

**Usecase:**
In my app, I am playing multiple sounds together and I have configured the `customPlayPauseAction` to play/pause all sounds together. But when I click on "stop", only the latest one stops.

**Comment by florent37** [comment]
Ok I add this, but keep in mind it will be only for android, the stop button is not present on ios

**Comment by florent37** [comment]
I added this for you on `1.6.4+1`

**Comment by vipulasri** [comment]
I am facing the following issues: 
1. I am using `1.6.4+1` but the package manager is downloading `1.6.4+2`. 
2. The control is not going into `customStopAction`.

**Comment by florent37** [comment]
Just saw why it's not working, I fix it and push `1.6.4+3`

**Comment by florent37** [comment]
pushed, can you try ?

**Comment by vipulasri** [comment]
It's working now, but when I click stop current notification is dismissed but a new notification gets displayed after it. which I think is an issue.

**Comment by florent37** [comment]
mmm yes, I'll look for it, for now please use it "as it", I keep this issue opened, and will fix the notification dismiss

**Comment by vipulasri** [comment]
@florent37 I really appreciate your efforts in maintaining this library and resolving the issue in an instant. Thanks!

**Comment by florent37** [comment]
:)

**Comment by florent37** [comment]
I'm working on it

**Comment by florent37** [comment]
fixed I publish a version with this & your seekbar fix (thanks again)

**Comment by florent37** [comment]
please try the `1.6.4+5`
I'll work on the #148 next :)

**Comment by vipulasri** [comment]
Thanks for resolving issues so quick :)

**Comment by vipulasri** [comment]
I will check the updated library as soon as possible and will update you.

**Comment by florent37** [comment]
:)

**Comment by vipulasri** [comment]
Facing issue while running the app with the updated library version: `1.6.4+5`

**Comment by vipulasri** [comment]
Facing issue while building the app with the updated library version: `1.6.4+5`

P.S: Tried deleting cache as well

Error logs:
`e: /Users/vipulasri/flutter/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-1.6.4+5/android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/NotificationActionReceiver.kt: (14, 14): Unresolved reference: NotificationAction
e: /Users/vipulasri/flutter/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-1.6.4+5/android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/NotificationActionReceiver.kt: (15, 14): Unresolved reference: NotificationAction
e: /Users/vipulasri/flutter/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-1.6.4+5/android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/NotificationActionReceiver.kt: (19, 14): Unresolved reference: NotificationAction
e: /Users/vipulasri/flutter/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-1.6.4+5/android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/NotificationActionReceiver.kt: (20, 14): Unresolved reference: NotificationAction
e: /Users/vipulasri/flutter/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-1.6.4+5/android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/NotificationActionReceiver.kt: (27, 13): Unresolved reference: NotificationAction
e: /Users/vipulasri/flutter/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-1.6.4+5/android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/NotificationManager.kt: (16, 73): Unresolved reference: NotificationAction
e: /Users/vipulasri/flutter/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-1.6.4+5/android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/NotificationManager.kt: (22, 73): Unresolved reference: NotificationAction
e: /Users/vipulasri/flutter/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-1.6.4+5/android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/NotificationService.kt: (43, 16): Unresolved reference: NotificationAction
e: /Users/vipulasri/flutter/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-1.6.4+5/android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/NotificationService.kt: (46, 16): Unresolved reference: NotificationAction
e: /Users/vipulasri/flutter/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-1.6.4+5/android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/NotificationService.kt: (59, 45): Unresolved reference: NotificationAction
e: /Users/vipulasri/flutter/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-1.6.4+5/android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/NotificationService.kt: (85, 45): Unresolved reference: NotificationAction
e: /Users/vipulasri/flutter/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-1.6.4+5/android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/NotificationService.kt: (99, 59): Unresolved reference: NotificationAction
e: /Users/vipulasri/flutter/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-1.6.4+5/android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/NotificationService.kt: (113, 103): Unresolved reference: NotificationAction
e: /Users/vipulasri/flutter/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-1.6.4+5/android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/NotificationService.kt: (131, 64): Unresolved reference: NotificationAction
e: /Users/vipulasri/flutter/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-1.6.4+5/android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/NotificationService.kt: (139, 64): Unresolved reference: NotificationAction
e: /Users/vipulasri/flutter/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-1.6.4+5/android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/NotificationService.kt: (163, 56): Unresolved reference: NotificationAction`

**Comment by florent37** [comment]
Can you try to ''flutter clean'' ?

**Comment by vipulasri** [comment]
My bad. Yeah, it worked. Thanks!
Notification stop custom action as well as seekbar enabled functionality working fine.

**Comment by florent37** [comment]
I almost finished seekbar on notif

**Comment by florent37** [comment]
It should be on master but did not published it. Last thing I had to add : the manual seek by user on notif. But actually it display the current position

**Comment by vipulasri** [comment]
Ohh great!

**Comment by florent37** [comment]
:)
