### ISSUE TITLE
[Android] notification seekbar doesn't get updated

### ISSUE THREAD

**Issue by vipulasri** [florent37/Flutter-AssetsAudioPlayer#145]
**Flutter Version**

My version : latest stable

**Lib Version**

My version : 1.6.4+3

**Platform (Android / iOS / web) + version**

Platform : Android

**Describe the bug**
Seekbar in the notification isn't updated as per the song/audio being played.

**Comment by florent37** [comment]
Yes, can you try to add it ? It should be in android code in Notification Service or in the player directly. I saw it was using PlaybackState & MediaSession

**Comment by florent37** [comment]
https://developer.android.com/about/versions/10/features#media-notifications

**Comment by florent37** [comment]
I'm working on it, I almost finished :)

**Comment by florent37** [comment]
done, I pushed it in master & will publish a new version

**Comment by florent37** [comment]
will be in `1.7.0`

**Comment by vipulasri** [comment]
That's really amazing!

**Comment by florent37** [comment]
just pushed :) thanks for you pull request too ;)

**Comment by vipulasri** [comment]
I wanted to contribute :)

**Comment by florent37** [comment]
I love this library and want to make it an must have :)

**Comment by vipulasri** [comment]
I would like it too. I would love to keep contributing.
