### ISSUE TITLE
ability to hide seekbar in notification

### ISSUE THREAD

**Issue by vipulasri** [florent37/Flutter-AssetsAudioPlayer#146]
**Describe the feature you'd like**
There should be an option to hide the seekbar in the notification. 

**Usecase**
While playing audio from the network, seekbar doesn't make sense in that case.

**Comment by florent37** [comment]
I don't know if it's possible in android, 

I think if I remove the bar it will change the complete look of the notification, like if it was completely yellow (if the artwork was Yello), removing this part will make the notif become gray and only have the yellow part/image I the right. Is that you want ?

**Comment by florent37** [comment]
I'll add this but I think you will prefer the old design

**Comment by vipulasri** [comment]
Nope, the current notification design is great. Let's not change it. Let me look for alternatives as well.

**Comment by vipulasri** [comment]
Added this functionality to iOS as well in #151
