### ISSUE TITLE
support for desktop apps

### ISSUE THREAD

**Issue by vipulasri** [florent37/Flutter-AssetsAudioPlayer#153]
**Describe the feature you'd like**
I think we are already using `AVPlayer` on iOS, we can check if it works fine for macOS. 
Also, as of now flutter only supports macOS.

**Comment by florent37** [comment]
I started few weeks to implement macos, I worked except for "assets" because I missed one flutter method on macos. I'll reimplement it soon :)

**Comment by vipulasri** [comment]
Ohh I see now, We already have macOS related code here. Yeah, we can also update the readme after that.

**Comment by florent37** [comment]
yes but I have to rework it, it's dusplicated code. I'm on it :) maybe today i'll work

**Comment by florent37** [comment]
I have to create a single file that run on ios & mac (with some exlusions) then create symbol link

**Comment by vipulasri** [comment]
Great man! I will keep tabs on it, in order to get the most out of it.

**Comment by florent37** [comment]
:D you're lucky I'm on my computer now, my newborn is sleeping I can geek :)

**Comment by florent37** [comment]
it's partially compatble, take a look at https://github.com/florent37/Flutter-AssetsAudioPlayer/blob/master/darwin/Classes/Music.swift

you can run the sample on macos but you will have an ui error

**Comment by florent37** [comment]
I'll continue tomorrow

**Comment by florent37** [comment]
For assets (which was not available) I found a cheat : I copy from asset to a top file on the flutter side, then create an audio.file from it, for finally play it

**Comment by vipulasri** [comment]
Actually, I am a newbie in iOS development that's why I can't figure out most of the things.

**Comment by florent37** [comment]
I finished it :) and published a major `2.0.0` with this new support :)

**Comment by vipulasri** [comment]
That's amazing. You are awesome :)
