### ISSUE TITLE
Third party audio libraries support

### ISSUE THREAD

**Issue by smakarov** [florent37/Flutter-AssetsAudioPlayer#154]
Thanks for this unique project!
I'am going to implement some music application using BASS audio library(android and ios). How do you think does it possible without a lot of pain replace current audio engine with BASS?

**Comment by florent37** [comment]
Can you send me a link of your library ?

**Comment by florent37** [comment]
On Android I have a system of ''wrapper'' that can be useful for your usecase (but you will have to fork the lib)

On ios I'll need to implement the system of wrapper, but I think it'll be easy to add

**Comment by smakarov** [comment]
> Can you send me a link of your library ?

http://www.un4seen.com/

**Comment by florent37** [comment]
yes, on android look at 
https://github.com/florent37/Flutter-AssetsAudioPlayer/blob/master/android/src/main/kotlin/com/github/florent37/assets_audio_player/playerimplem/PlayerImplem.kt

and 

https://github.com/florent37/Flutter-AssetsAudioPlayer/blob/master/android/src/main/kotlin/com/github/florent37/assets_audio_player/playerimplem/PlayerImplemMediaPlayer.kt

I think the bass implementation can be inside a PlayerImplem ?

**Comment by smakarov** [comment]
Thanks a lot for pointing on this. BASS in java, but I think it worth to try. I'll let you know if it will be successful =)

**Comment by florent37** [comment]
:)

**Comment by florent37** [comment]
I'll make some change in swift for you
