### ISSUE TITLE
Awesome Flutter

### ISSUE THREAD

**Issue by Solido** [florent37/Flutter-AssetsAudioPlayer#157]
Ce serait super d'avoir ton entrée dans 
https://github.com/Solido/awesome-flutter !

**Comment by florent37** [comment]
Carrément ! Comment l'ajouter ? Il faut que je te fasse une merge request ?

**Comment by Solido** [comment]
Yep une PR !

**Comment by florent37** [comment]
créé https://github.com/Solido/awesome-flutter/pull/694 :)
