### ISSUE TITLE
Play in background without notification.

### ISSUE THREAD

**Issue by chenparty** [florent37/Flutter-AssetsAudioPlayer#159]
Hi, I use the plugin for audio alarm, and need enable background mode, but audio's duration is about 3~5 seconds,  so i do not want to show any Notification or MPNowPlayingInfoCenter always, then i add : showNotification: false, but it doesn't work.  What can i do? Im looking forward to your reply.

**Comment by florent37** [comment]
you're on ios no ? 

`but audio's duration is about 3~5 seconds` -> your audio is splitted ?

can you send me sample code to reproduce ?

**Comment by chenparty** [comment]
> you're on ios no ?
> 
> `but audio's duration is about 3~5 seconds` -> your audio is paused during playing by the system ?
> 
> can you send me sample code to reproduce ?
1. Yes, ios.
2. Sorry, I mean my audio file is 3~5 seconds long.  Audio isn't paused during playing.
3. My audio file lasts for a short time, so I don’t want to show any notification when its playing, then I add: showNotification: false, but it doesn't work. MPNowPlayingInfoCenter still works. 
4. Here is my code: 
`_player.open(`
`      Audio(audioName),`
 `     showNotification: false,`
 `     playInBackground: PlayInBackground.enabled,`
 `     respectSilentMode: true`
 `   );`

**Comment by florent37** [comment]
have you enabled the "background mode" in xcode ? (I try to find why it's not working)

**Comment by florent37** [comment]
https://developer.apple.com/documentation/avfoundation/media_assets_playback_and_editing/creating_a_basic_video_player_ios_and_tvos/enabling_background_audio

**Comment by florent37** [comment]
I tried your code & it seems to work, please try the `main_test.dart`

**Comment by florent37** [comment]
but make sure in your `info.plist` in ios/Runner you have

```
<key>UIBackgroundModes</key>
<array>
		<string>audio</string>
		<string>fetch</string>
</array>
```

**Comment by chenparty** [comment]
@florent37  thanks a lot，i try the main_test.dart ，it seems good. I will check my code again.
