### ISSUE TITLE
Single notification bar for multiple player & navigation to specific player page when user clicks in notification.

### ISSUE THREAD

**Issue by Timus23** [florent37/Flutter-AssetsAudioPlayer#162]
**Describe the feature you'd like**

Now all the music instance have separate notification bar but if user want to control all the instance from one place, there is no option for that. There should be an single notification bar for playing multiple music at once so that user can stop, pause and play all the instance of player at once.

and most of the music player notification bar give option to navigate to the player page when the click on it would be nice to see this feature in this package. 
something like this.
https://play.google.com/store/apps/details?id=ipnossoft.rma.free

**Comment by florent37** [comment]
I thinked about that but, there's one thing : ios

I have to have a different way to handle notification on android & ios...

on ios it's not really a notification but a MRCommandCenter, which have a single instance

on android we can have / attach mutliple notifications

**Comment by florent37** [comment]
I did it with only one notification to make the ux similar on Android & iOS

**Comment by florent37** [comment]
`There should be an single notification bar for playing multiple music at once so that user can stop, pause and play all the instance of player at once.`

yes that's a good idea :) , but what do you display as tite/image/album ?

for now it displays current audio's metas

**Comment by florent37** [comment]
(I try the app)

**Comment by florent37** [comment]
Oh ok I see, like a notification group with only play/pause & stop, which affect an group

<img width="410" alt="Capture d’écran 2020-06-05 à 08 13 43" src="https://user-images.githubusercontent.com/5754972/83843071-8ae20f00-a704-11ea-8115-e2d2f8cd4d9e.png">

yes that's a good feature to add :)

**Comment by florent37** [comment]
Maybe it can be a new way of "playlist", like "ParallelPlaylist" (help me to find a name :D) 

`open(ParallelPlaylist(audios, 
        titleBuilder: (player, number) => "En cours de lecture",
        subTitleBuilder: (player, number) => "$number sons séléctionés"
)), showNotification: true)`

and the songs plays in parallel, 

what do you thinkg about this code ?

**Comment by Timus23** [comment]
for multiple music with single notification. we can ask for what they what to show in that like common metas for multiple  or we can simple show how many track it is playing and hav control like play pause and stop.

**Comment by Timus23** [comment]
yas we can also ask for metas in this function so that user can add their own title, description and image as they do in single player.

**Comment by florent37** [comment]
yes like this I don't have to add localisation inside the app :D instead I have to add EN, FR, DE, etc....

**Comment by Timus23** [comment]
we can add autoStart as a param and also pause and play single music of that parallel playlist from ui but not from notification.. we can show status like how many tracks are playing and all in it and update notification as user play or pause like that above example app  if no metas are given. if metas are given nth to do.

**Comment by Timus23** [comment]
as most of the music player app navigate us to the players page when they click on it. It would be awesome if it is added in this library. 
like this packages does. 
https://pub.dev/packages/flutter_local_notifications
This notification library gives option to do specific task when user click on the notification. we can add feature something like that in it.

**Comment by florent37** [comment]
```This notification library gives option to do specific task when user click on the notification. we can add feature something like that in it.``` can you send me where ?

**Comment by florent37** [comment]
how do you handle multiple audios ? it always loop ? or if you add an audio, it like update the title (+1 audio) then remove this audio when finished ?

**Comment by florent37** [comment]
this mutable style look better, the add method took the audio specific play style 

```
final playlist =  ParallelPlaylist(
        titleBuilder: (player, number) => "En cours de lecture",
        subTitleBuilder: (player, number) => "$number sons séléctionnés",
        imageBuilder: (player, number) => MetaImage.asset("images/relax.png")
    );
open(
   playlist
), showNotification: true);
```

```
playlist.add(audio, loop: true); play this audio infinitely
playlist.add(audio2); //add, play, then "stop" this audio when finished
```

**Comment by florent37** [comment]
or maybe it can be a different objet than `assetAudioPlayer, because what does the method `shuffle`, `next`, `previous`, `loop`

**Comment by florent37** [comment]
like `AssetAudioPlayerGroup`, looks better I think

**Comment by Timus23** [comment]
https://github.com/MaikuB/flutter_local_notifications/blob/master/flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java
in this file plugin has used  PluginRegistry.NewIntentListener and  ActivityAware. which help to know when we get new intent.
when android get new intent option it trigger the newIntent function.
from there it hav called 
private Boolean sendNotificationPayloadMessage(Intent intent) {
        if (SELECT_NOTIFICATION.equals(intent.getAction())) {
            String payload = intent.getStringExtra(PAYLOAD);
            channel.invokeMethod("selectNotification", payload);
            return true;
        }
        return false;
    } 
which eventually call the method in dart side which handle what to do. it as also passes payload. we can pass Map of track id , name etc.

**Comment by Timus23** [comment]
https://github.com/MaikuB/flutter_local_notifications/blob/69def7967cda5377ec799b5e9658855a2e7129ff/flutter_local_notifications/android/src/main/java/com/dexterous/flutterlocalnotifications/FlutterLocalNotificationsPlugin.java#L129 
in this function it has added action and intent param to be passed in dart side.
in dart side it. it has used behavioursubject stream to from payload it.
in ios i don't hav much idea how it has implemented.

**Comment by Timus23** [comment]
> this mutable style look better, the add method took the audio specific play style
> 
> ```dart
> final playlist =  ParallelPlaylist(
>         titleBuilder: (player, number) => "En cours de lecture",
>         subTitleBuilder: (player, number) => "$number sons séléctionnés",
>         imageBuilder: (player, number) => MetaImage.asset("images/relax.png")
>     );
> open(
>    playlist
> ), showNotification: true);
> ```
> 
> ```dart
> playlist.add(audio1, loop: true); //play this audio infinitely
> playlist.add(audio2); //add, play, then "stop" this audio when finished
> ```

this Approach seems good.

**Comment by florent37** [comment]
Yes for the open action I have an idea :)
It's like you described (activity aware + intent + subject)

For the format, I think it'll be another player style, wrapping multiple players

**Comment by florent37** [comment]
Initialisation : 

```
final AssetAudioPlayerGroup group = AssetAudioPlayerGroup(
      displayNotification: true, //default
      titleBuilder: (player, number) => "En cours de lecture",
      subTitleBuilder: (player, number) => "$number sons séléctionnés",
      imageBuilder: (player, number) => MetaImage.asset("images/relax.png")
);
```

Add audios (case 1)

```
group.add(audio1, loop: true); //play this audio infinitely
group.add(audio2); //add, play, then "stop" this audio when finished
```

Add audios (case 1)

```
AssetAudioPlayer player1 = AssetAudioPlayer();
player1.open(audio1, loop: true); //play this audio infinitely

group.add(player1); //<-----

AssetAudioPlayer player2 = AssetAudioPlayer();
player2.open(audio2); //add, play, then "stop" this audio when finished

group.add(player2); //<-----
```

**Comment by florent37** [comment]
I think I'll provide the 2 in the lib, add just audio (which will create the player), or add an existing player

**Comment by florent37** [comment]
I prefer this : 
```
final AssetAudioPlayerGroup group = AssetAudioPlayerGroup(
      displayNotification: true, //default
      updateNotification: (playerGroup, List<PlayingAudio>playingAudios) => AudioGroupMetas(
             title: "En cours de lecture",
             subTitle: "$number sons séléctionés",
             image: MetaImage.asset("images/relax.png"),
      ),

      //added
      onNotificationOpened: (player, playingAudios) {
            
      },
      //custom action, do not set to have default behavior
      onNotificationPlay: (player, playingAudios) {
            
      },
      //custom action, do not set to have default behavior
      onNotificationPaused: (player, playingAudios) {
            
      },
      //custom action, do not set to have default behavior
      onNotificationStop: (player, playingAudios) {
            
      }
);
```

**Comment by florent37** [comment]
(did not have time to implement this, but I will start it soon)

**Comment by Timus23** [comment]
> I prefer this :
> 
> ```
> final AssetAudioPlayerGroup group = AssetAudioPlayerGroup(
>       displayNotification: true, //default
>       updateNotification: (playerGroup, List<PlayingAudio>playingAudios) => AudioGroupMetas(
>              title: "En cours de lecture",
>              subTitle: "$number sons séléctionés",
>              image: MetaImage.asset("images/relax.png"),
>       ),
> 
>       //added
>       onNotificationOpened: (player, playingAudios) {
>             
>       },
>       //custom action, do not set to have default behavior
>       onNotificationPlay: (player, playingAudios) {
>             
>       },
>       //custom action, do not set to have default behavior
>       onNotificationPaused: (player, playingAudios) {
>             
>       },
>       //custom action, do not set to have default behavior
>       onNotificationStop: (player, playingAudios) {
>             
>       }
> );
> ```

seems great. Thank you for this awesome library. hoping that this feature will be included in this library soon.

**Comment by vipulasri** [comment]
I had the same requirement, I did all the heavy lifting of this implementation on my side as library provides most of the things.

**Comment by florent37** [comment]
I published it in 2.0.1+1 (as beta)

it does not figure in README.md (I think it will need some evolve/features to become public)

you can help me for that, I need you to try it and tell me what's missing for you

I send you the code I tried : https://github.com/florent37/Flutter-AssetsAudioPlayer/blob/master/example/lib/main_group.dart

And the class `AssetsAudioPlayerGroup`, for you to know what are the available methods

https://github.com/florent37/Flutter-AssetsAudioPlayer/blob/master/lib/src/player_group.dart

Can you please try and tell me what others methods you need please ?

**Comment by Timus23** [comment]
okey i will look into it. what about the navigation feature? @florent37

**Comment by florent37** [comment]
Navigation ?

**Comment by florent37** [comment]
Oh no the opening intent I did not have time to work on it

**Comment by florent37** [comment]
I have some others issues to fix before continue working on new features

**Comment by Timus23** [comment]
okey. thank a lot for this awesome library.

**Comment by florent37** [comment]
why did you closed it ? it's not finished :)

**Comment by florent37** [comment]
created : https://github.com/florent37/Flutter-AssetsAudioPlayer/issues/174
