### ISSUE TITLE
Extra listeners or expansion of the current ones

### ISSUE THREAD

**Issue by TheOnlyNurse** [florent37/Flutter-AssetsAudioPlayer#164]
**Describe the feature you'd like**
When the notification playback is stopped (through the button provided there), neither streams playlistAudioFinished nor playlistFinished fire to indicate completion. There should be some way to know that the audio service has shut down so that the UI can react accordingly.

My 2 cents on a possible solution is either change isPlaying into an enum with 3 states (playing, pause, stopped) or just create a new stream altogether that shows the notification state.

**Comment by Timus23** [comment]
For that i have used custom stop function in notificationSetting than in that function u can stop player manually and do that what ever u want in that function. But having enum with 3 state playing, pause and stop gonna b great.

**Comment by florent37** [comment]
Yes it should be called, I'll add that

**Comment by florent37** [comment]
And yes the stopped state is much difficult to see, you have to look at ''current'' that should be null

**Comment by florent37** [comment]
I added 
```
 if (call.arguments == null) {
            _playlistAudioFinished.add(Playing(
              audio: this._current.value.audio,
              index: this._current.value.index,
              hasNext: false,
              playlist: this._current.value.playlist,
            ));
            _playlistFinished.value = true;
            _current.value = null;
            _playerState.value = PlayerState.stop;
```

on "stop" so the finish listener are called

& I added a PlayerState enum in the player, with the listeners & builders

```
final BehaviorSubject<PlayerState> _playerState = BehaviorSubject<PlayerState>.seeded(PlayerState.stop);
ValueStream<PlayerState> get playerState => _playerState.stream;
```

**Comment by florent37** [comment]
please try the `2.0.1`

**Comment by florent37** [comment]
`PlayerState state = _player.playerState.value;` //because its a stream
