### ISSUE TITLE
Audio stops when screen locks on ios

### ISSUE THREAD

**Issue by pro100svitlo** [florent37/Flutter-AssetsAudioPlayer#168]
**Flutter Version**

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.14.6 18G3020, locale en)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Android Studio (version 3.6)
[✓] Connected device (2 available)
```

**Lib Version**

`assets_audio_player: 2.0.0+6`

**Platform (Android / iOS / web) + version**

Platform : `ios`

**Describe the bug**

I turn on audio and then I would like to lock screen.
When I am doing it - audio stops... 
Same happen with iPad - I just close screen cover and it stops.
How to prevent it?

Thanks 🍻

**Comment by florent37** [comment]
Did you enabled ''background mode'' in xcode capabilities ?

**Comment by pro100svitlo** [comment]
Oh, I missed it for some reason...
Now it works, thanks 👍

**Comment by pro100svitlo** [comment]
I missed it probably cos here in this topic there were talk about `http calls`, but no word about background audio...

----
To enable http calls on macOs, you have to add input/output calls capabilities into info.plist

<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
</dict>
<key>UIBackgroundModes</key>
<array>
    <string>audio</string>
    <string>fetch</string>
</array>
<key>com.apple.security.network.client</key>
<true/>

----

**Comment by pro100svitlo** [comment]
Cos of [this](https://github.com/florent37/Flutter-AssetsAudioPlayer/issues/168#issuecomment-640163045) it might be a good idea to  update a bit the docs 😉 

Thank you one more time for this library 🍻

**Comment by florent37** [comment]
Yes I should update the readme :) can you try to do it ? adding what saved you ? :)

**Comment by pro100svitlo** [comment]
Sure:

----
To enable background play on iOs (and preventing audio stops when screen locked) please add next lines to Info.plist:
```
<key>UIBackgroundModes</key>
<array>
    <string>audio</string>
</array>
```
Also, you can add `capasibilities` for background audio from xCode pannel.
