### ISSUE TITLE
IOS Notification Center Controls Removed Datas on Background

### ISSUE THREAD

**Issue by kalismeras61** [florent37/Flutter-AssetsAudioPlayer#169]
**Flutter Version**

My version : 1.17.3 Stable

**Lib Version**

My version : 2.0.0 

**Platform (Android / iOS / web) + version**

Platform :  IOS version 13.4.1 

**Describe the bug**

 I can run audios on background but when app is background notification center controls doesn't work. When i click next or prev button music stops immediately and removed the song details. It continues when I app is foreground.

**Small code to reproduce**

**Comment by kalismeras61** [comment]
After update plugin it is fixed.

**Comment by florent37** [comment]
Ok :)
