### ISSUE TITLE
[New Feature] Increase buffer size when using Audio.network mode

### ISSUE THREAD

**Issue by manojvsp12** [florent37/Flutter-AssetsAudioPlayer#170]
**Describe the feature you'd like**
In scenario like network speed is low or while travelling, frequent buffering is happening. If buffer size is increased, playback will be from buffer, thus reducing frequent buffering.

**Comment by florent37** [comment]
Can you find a code on ExoPlayer (android) and AvPlayer (ios) to increase the buffer size ? 

If yes I'll implement it :)

**Comment by manojvsp12** [comment]
can you refer below links
https://stackoverflow.com/questions/54073206/android-exoplayer-start-playing-as-soon-as-possible-without-too-much-buffering
https://blogs.akamai.com/2019/10/enhancing-video-streaming-quality-for-exoplayer---part-2-exoplayers-buffering-strategy-how-to-lower-.html#:~:text=ExoPlayer%20will%20buffer%20until%20it,worth%20maxBufferMs%20of%20media%20data.

**Comment by florent37** [comment]
Ok thanks, Can you try to add it in a merge request ?

**Comment by florent37** [comment]
done in `2.0.3`, I done what's in your link https://blogs.akamai.com/2019/10/enhancing-video-streaming-quality-for-exoplayer---part-2-exoplayers-buffering-strategy-how-to-lower-.html#:~:text=ExoPlayer%20will%20buffer%20until%20it,worth%20maxBufferMs%20of%20media%20data
