### ISSUE TITLE
Build failed after updating the package

### ISSUE THREAD

**Issue by wal33d006** [florent37/Flutter-AssetsAudioPlayer#176]
**Flutter Version**

My version : latest stable

**Lib Version**

My version : 

**Platform (Android / iOS / web) + version**

Platform : Android

**Describe the bug**
`The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin assets_audio_player...
Running Gradle task 'assembleAarRelease'...

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':compileReleaseAidl'.
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '/Users/waleedarshad/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-2.0.1+2/android/local.properties'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

Exception: The plugin assets_audio_player could not be built due to the issue above.`

**Comment by florent37** [comment]
can you try to "flutter clean" ?

**Comment by wal33d006** [comment]
Got it actually. I had some issues in my Manifest file. My bad. Thanks 🙌

**Comment by florent37** [comment]
:)

**Comment by MobileMon** [comment]
@wal33d006 same thing is happening to me, can you describe how you fixed it?

**Comment by wal33d006** [comment]
It wasn't actually the issue with the plugin at all. My manifest file was having some syntax errors
