### ISSUE TITLE
No implementation found for method loopSingleAudio on channel assets_audio_player

### ISSUE THREAD

**Issue by kalismeras61** [florent37/Flutter-AssetsAudioPlayer#177]
**Flutter Version**

My version : 1.17.3

**Lib Version**

My version : 2.0.1

**Platform (Android / iOS / web) + version**

Platform : IOS

**Describe the bug**

After Upgrade Latest version i get this issue for IOS. 

```dart
2020-06-08 10:17:22.787841+0300 Runner[17999:7845407] [VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method loopSingleAudio on channel assets_audio_player)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
<asynchronous suspension>
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
#2      AssetsAudioPlayer._loopSingleAudio (package:assets_audio_player/src/assets_audio_player.dart:866:10)
#3      AssetsAudioPlayer.setLoop (package:assets_audio_player/src/assets_audio_player.dart:300:7)
#4      AssetsAudioPlayer._open (package:assets_audio_player/src/assets_audio_player.dart:719:15)
```

**Comment by florent37** [comment]
can you try to "flutter clean" 

I looked and the method is present in swift

**Comment by florent37** [comment]
https://github.com/florent37/Flutter-AssetsAudioPlayer/blob/fe77f5d1b059e7902560411785ce74ea3e5850f1/darwin/Classes/Music.swift#L1002

**Comment by florent37** [comment]
or try with `2.0.1+3`

**Comment by kalismeras61** [comment]
I updated plugin and did few times flutter clean same problem
Exception has occurred.
MissingPluginException (MissingPluginException(No implementation found for method loopSingleAudio on channel assets_audio_player))

**Comment by florent37** [comment]
It's wired, I'll look at it

**Comment by kalismeras61** [comment]
Ok, every new playing song i get this issue.

**Comment by florent37** [comment]
Ok I'll look for it it's wired. Can you try to see in your xcode project if you open the ''music.swift'' (with cmd + shift + O) if the word is present in this file please ?

**Comment by kalismeras61** [comment]
No it is not in 
https://dpaste.org/jzQo

**Comment by kalismeras61** [comment]
This is the missing part my IOS version is 13.4.1 


    private var looper: Any?

    func loopSingleAudio(loop: Bool) {
        _loopSingleAudio = loop
        
        if(loop){
            #if os(iOS)
            if #available(iOS 10.0, *) {
                self.looper = AVPlayerLooper(player: self.player!, templateItem: self.player!.items()[0])
            }
            #elseif os(OSX)
            if #available(OSX 10.12, *) {
                self.looper = AVPlayerLooper(player: self.player!, templateItem: self.player!.items()[0])
            }
            #endif
        } else {
            #if os(iOS)
            if #available(iOS 10.0, *) {
                (self.looper as? AVPlayerLooper)?.disableLooping()
                self.looper = nil
            }
            #elseif os(OSX)
            if #available(OSX 10.12, *) {
                (self.looper as? AVPlayerLooper)?.disableLooping()
                self.looper = nil
            }
            #endif
        }
    }

**Comment by florent37** [comment]
It's wired, can you try to go to ios/ delete the pubspec.lock then run 

pod install

**Comment by florent37** [comment]
The swift code should be published with all the project, I don't understand

**Comment by kalismeras61** [comment]
I tried them delete pods folder, podfile.lock file and also pubspec.lock

**Comment by kalismeras61** [comment]
By the way , am using this repo maybe it helps to finding error
https://github.com/sahharYoucef/Flutter-AssetsAudioPlayer/blob/master/darwin/Classes/Music.swift

**Comment by florent37** [comment]
I'll try to publish a new version deleting the build folder, pods, etc. But I don't know if it will fix this, maybe I have to edit a pod file

**Comment by kalismeras61** [comment]
Ok, i looked also example app you provided. There is no loopSingleAudio method in music.swift file

**Comment by florent37** [comment]
in this file ? https://github.com/florent37/Flutter-AssetsAudioPlayer/blob/master/darwin/Classes/Music.swift

**Comment by florent37** [comment]
I'm trying to create an external project and include the library, to see what files come from servers

**Comment by florent37** [comment]
the downloaded folder is 

(assuming you have $FLUTTER_SDK configured)

```
$FLUTTER_SDK/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-2.0.1+3/
```

if you're on mac, can you try to open the 

```
open $FLUTTER_SDK/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-2.0.1+3/ios/Classes/Music.swift
``` 

? 

and maybe try to delete 

```
rm -rf $FLUTTER_SDK/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-*
```

**Comment by kalismeras61** [comment]
For some reason it is not downloaded correct Music.swift file when i using below package. Can you check this also ? 

 assets_audio_player:
    git:
      url: https://github.com/sahharYoucef/Flutter-AssetsAudioPlayer.git
      ref: master

**Comment by kalismeras61** [comment]
Ok, there was a problem with pull so we fixed it. Thanks for your help!!

**Comment by florent37** [comment]
Wow why the other project ?
