### ISSUE TITLE
Metadata from Livestream

### ISSUE THREAD

**Issue by Hypercruse** [florent37/Flutter-AssetsAudioPlayer#180]
I dont know if you have implemented this already, but i couldnt find anything for that. I'd like to know if its possible to access the metadata like artists etc from the livestream and update the metadata in the app accordingly.

Thx for this great flutter plugin and your hard work! 

Cheers
Chris

**Comment by florent37** [comment]
Thank you :)
What do you mean by ''access the metadata from livesteam'' ? 

From the url fetching the data ?

**Comment by florent37** [comment]
I don't think it's sent in the url, no ?

**Comment by Hypercruse** [comment]
Sorry if it wasnt clear what i meant. 
So im trying to make an app and part of it is that you can visit different streams on which music is being played. I got the stream adresses and the ports of those streams, and the hosts told me that the data their stream publishes contains information like artist name, song name etc of the current song. I wonder if its possible to get this information with your tool

Thanks for the quick reply & have a good evening

**Comment by LouisForaux** [comment]
The metadata for livestream was sent in the header of the live stream (If my memories are good). Instead of getting them by that way, for what you can't read the JSON of the service @Hypercruse ? Icecast/Shoutcast have a JSON url, compatible with Dart....

Have a good day,

**Comment by florent37** [comment]
Yes I think you have to listen it directly from dart, because the player only send this url to the media player and does not open a new http client connection to retrieve headers

**Comment by Hypercruse** [comment]
Alright thank you so much for your help! I will do that

**Comment by Pavithran4015** [comment]
@Hypercruse Did you find a way to achieve this? please let me know if have any answers.
