### ISSUE TITLE
library does not find files with korean characters in the path

### ISSUE THREAD

**Issue by ToluwaniO** [florent37/Flutter-AssetsAudioPlayer#186]
**Flutter Version**

My version :  Flutter 1.19.0-6.0.pre.27 • channel master 

**Lib Version**

My version : ^2.0.1

**Platform (Android / iOS / web) + version**

Platform :  Android 10 and iOS 13

**Describe the bug**

The library doesn't find resources that contain Korean characters. The bug is not reproducible with English characters.
`flutter: received call log with arguments resource not found assets/audio/ㄷ.mp3
flutter: log: resource not found assets/audio/ㄷ.mp3
`

**Small code to reproduce**

```dart
import 'package:assets_audio_player/assets_audio_player.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State {
  
  final AssetsAudioPlayer _assetsAudioPlayer = AssetsAudioPlayer();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: RaisedButton(
            child: Text("open"),
            onPressed: () {
              //open code here
              AssetsAudioPlayer.newPlayer().open(
                  Audio("assets/audio/ㄷ.mp3"),
                  showNotification: true,
              );
            }
          ),
        ),
      ),
    );
  }
}
```

**Comment by florent37** [comment]
are those charactere part of UTF-8 ?

maybe I think it encode it into urf8 while sendinf it from flutter to android ?

**Comment by florent37** [comment]
I close it for now, please reopen it when you have informations :)
