### ISSUE TITLE
[New feature] Update current playlist.

### ISSUE THREAD

**Issue by pro100svitlo** [florent37/Flutter-AssetsAudioPlayer#191]
It would be nice to have the possibility to update the current playlist (which was set via `player.open(playlist)`).

Why?

In my case when I create a playlist I am checking if audio was cached by me previously, then  I add it as a local file. If no - then add network audio and when the user plays it - I am caching it. 
When caching is done - I would like to update playlist (replace network audio with local), so in case user would like to hear that song one more time, he/she will not need internet connection anymore.

```
- add(audio)
- addAt(audio, index)
- addAll(List audios)

- remove(audio)
- removeAt(audio, index)
- removeAll(List audios)

- contains(audio)
```

**Comment by florent37** [comment]
I added this operators on `2.0.2+4``

but did not "stop" the player if the current index is the removed index (or inserted index)

I will do this later :)

**Comment by florent37** [comment]
done :) in `2.0.2+5`

**Comment by pro100svitlo** [comment]
Have a question/proposition here.
I noticed next thing: when I updating the current audio it started playing from start.
So my question/proposition would be pass the current position and start playing from same place :)

```dart
  void onAudioAddedAt(int index) {
    if (assetsAudioPlayer._playlist.playlistIndex == index) {
      assetsAudioPlayer._openPlaylistCurrent(seek: _currentPosition.value);
    }
  }
```
Then user experience should be more smooth 😄

**Comment by florent37** [comment]
Oh yes good idea

**Comment by florent37** [comment]
But only if case of the path is the same ? 
What do you update in this audio else ? Metas ?

**Comment by pro100svitlo** [comment]
Hm, it's interesting point (about path).

So in my case I am playing audio from network if it was not cached before. And when caching done - I am updating the list item.

So in my case comparation of the audio path will not work.
And there are no any silver bullet.

But I have two ideas:
1) add some kind of tag oaram to metas, and if it's same, then the audio technically the same, but some data changed
2) add comparation function as parameter, when updating playlist. That function should return book, and developer should handle comparation of old audio and new: if Dev think audio same - then return true (play from same seek) or false if play from start.

Wdyt?

**Comment by florent37** [comment]
yes I have an id params into meta, it can be used here ?

**Comment by pro100svitlo** [comment]
yes, I guess using `id` is  a good idea.

**Comment by florent37** [comment]
@pro100svitlo what if instead of replacing it into playlist, you could update and audio ?

like 

PlayList p = PlayList(audios: [ Audio.network(url), Audio.network(url2) ];

 // fetch audio locally

`p.audios[0].mute( (audio) -> audio.copyWith(type: File, url: filepath)`

I don't know if its simplest :/

**Comment by florent37** [comment]
I think your solution with id is the easier :)

**Comment by florent37** [comment]
and what if instead of `insert` and `remove` I add a `replace` method ?

```
p.replace(index, replacer : (oldAudio) {
    return Audio.file(newPath, metas: oldAudio.metas)
);
```

**Comment by florent37** [comment]
I like this one, because if you use insert it's IMO for a "new item"

**Comment by florent37** [comment]
look at #218 

```
class _MyHomePageState extends State<MyHomePage> {
  String downloadingProgress;
  final AssetsAudioPlayer _player = AssetsAudioPlayer.newPlayer();


  final Playlist playlist = Playlist(audios: [
    Audio.network(mp3Url, metas: Metas(title: 'hello world')),
  ]);

  @override
  void initState() {
    super.initState();
    _player.currentPosition.listen((event) {
      print("_player.currentPosition: $event");
    });
    _player.open(
      playlist,
      autoStart: true,
      showNotification: true,
    );
    _downloadInParallel();
  }

  void _downloadInParallel() async {
    final tempDir = await getTemporaryDirectory();
    final downloadPath = tempDir.path + "/downloaded.mp3";
    print('full path $downloadPath');

    await Future.delayed(Duration(seconds: 3));

    await downloadFileTo(
        dio: dio,
        url: mp3Url,
        savePath: downloadPath,
        progressFunction: (received, total) {
          if (total != -1) {
            setState(() {
              downloadingProgress = (received / total * 100).toStringAsFixed(0) + "%";
            });
          }
        });
    setState(() {
      print("downloaded, switching to file type $downloadPath");
      playlist.replace(
        0,
            (oldAudio) {
          return oldAudio.copyWith(audioType: AudioType.file, path: downloadPath);
        },
        keepPlayingPositionIfCurrent: true,
      );
      this.downloadingProgress = null;
    });
  }
```

**Comment by florent37** [comment]
```
playlist.replace(
        0,
        (oldAudio) {
          return oldAudio.copyWith(
                 audioType: AudioType.file, 
                 path: downloadPath
           );
        },
        keepPlayingPositionIfCurrent: true,
);
```

**Comment by florent37** [comment]
and I think i'll "move" this code directly in the library, to enable download, cache network files #217

**Comment by florent37** [comment]
can you try with `2.0.4+2` and the code I sent ? 

https://github.com/florent37/Flutter-AssetsAudioPlayer/blob/master/example/lib/main_update_playlist.dart

**Comment by florent37** [comment]
note that on ios, durations are in Second, so you can have a mini gap/jump while switching from one audio to other :'(

**Comment by pro100svitlo** [comment]
Hi!

Wow, you wrote really a lot :)
I really like the idea with  `replace`, it looks more logical.
Will try all this tomorrow in  the morning 👍

**Comment by florent37** [comment]
:)

**Comment by gorusarswa** [comment]
Hi,
Just tried to add one audio into existing play list. It works good and add the song into existing playlist but it does not update the hasNext parameter into the playlist. 
I started player like this:-
```
assetsAudioPlayer.open(
  Playlist(
    audios: [
      Audio("assets/audios/song1.mp3"),
      Audio("assets/audios/song2.mp3")
    ]
  ),
  loopMode: LoopMode.playlist //loop the full playlist
);
```
Then added one more song
```
assetsAudioPlayer.playlist.add(Audio("assets/audios/song3.mp3"));
```
Now on second song it show the playlist like this
```
Playing {
	audio: PlayingAudio {
		audio: Audio {
			path: assets/audios/song2.mp3,
			package: null,
			audioType: AudioType.file,
			_metas: Instance of 'Metas',
			_networkHeaders: null
		},
		duration: 0: 04: 20.840000
	},
	index: 1,
	hasNext: false,
	playlist: ReadingPlaylist {
			audios: [Audio { path: assets/audios/song1.mp3},
                                     Audio { path: assets/audios/song2.mp3},
                                     Audio { path: assets/audios/song3.mp3}]
```
I am at index 1, playing song2. The playlist still have song3 to play but it show hasNext as false. 
Also if I call assetsAudioPlayer.next(); it play song1 agian. But never go to song3.

**Comment by meyubaraj** [comment]
I opened Player with the playlist:

```dart
_audioPlayer.open(
        Playlist(
          audios: songs
              .map(
                (song) => Audio(
                  song.url,
                  metas: Metas(
                    id: song.id,
                    title: song.title,
                    artist: song.artist.name,
                    album: song.album,
                    image: MetasImage.network(song.cover),
                  ),
                ),
              )
              .toList(),
        ),
        showNotification: true,
        autoStart: false,
      );
```


Everything is working fine but when I add another audio in the playlist:

```dart
_audioPlayer.playlist.add(Audio(
        song.url,
        metas: Metas(
          id: song.id,
          title: song.title,
          artist: song.artist.name,
          album: song.album,
          image: MetasImage.network(song.cover),
        ),
      ));
```

The playlist updates but when I click next then the player stops. The new song doesn't play at all :'(
