### ISSUE TITLE
Multiple seeks don't work

### ISSUE THREAD

**Issue by TheOnlyNurse** [florent37/Flutter-AssetsAudioPlayer#193]
**Flutter Version**

My version :  1.17.3

**Lib Version**

My version : 2.0.1

**Platform (Android / iOS / web) + version**

Platform : Android

**Describe the bug**

Seeking multiple times does not work. Specifically, seeking once to 0 (which works) and then trying to seek once again to 0 (which doesn't work).

**Small code to reproduce**
Open file normally:
```dart
await AssetsAudioPlayer.open(Audio.file( // Audio file here))
```

Seek to 0. Works the first time but not any subsequent number of times.
```
AssetsAudioPlayer.seek(Duration(seconds: 0));
```

**Comment by florent37** [comment]
I added an optional parameter on seek, it's because I protected the seek method to not having multiple pings with the same value

can you try with `seek(Duration(seconds: 0), force: true)` ? 

on version `2.0.2`
