### ISSUE TITLE
[BUG] Seek Does not work on the Web

### ISSUE THREAD

**Issue by preetjdp** [florent37/Flutter-AssetsAudioPlayer#194]
**Flutter Version**

My version : 1.19.0-6.0.pre.57

**Lib Version**

My version : 2.0.1+9

**Platform (Android / iOS / web) + version**

Platform :  Web

**Describe the bug**

**A clear and concise description of what the bug is.**

`player.seekBy(Duration())` does not work on the web.

**Reason**
On further debugging it seems that the value to seek to is passed as `milliseconds` and the number system that `AudioElement` uses is seconds.
What this leads to is when one does `player.seek(Duration(second:1))`  it moves the ` _audioElement?.currentTime` to `1000 seconds` thus ending the audio clip.

https://github.com/florent37/Flutter-AssetsAudioPlayer/blob/d1a4a0002bfc7bc2d283776a5579c7e09557dd1a/assets_audio_player_web/lib/web/web_player_html.dart#L169-L176

I'll submit a fix in a few hours.

But do you think this is affecting anything else?

**Comment by florent37** [comment]
oh yes, will you send a pull request ?

**Comment by preetjdp** [comment]
Doing it now :)
