### ISSUE TITLE
Shuffle

### ISSUE THREAD

**Issue by xrgouda** [florent37/Flutter-AssetsAudioPlayer#2]
How can i shuffle more than audio and make it play automatic when one finished another one starts? and thank you..

**Comment by shinriyo** [comment]
@xrgouda 
you can just use `shuffle` method.

https://api.dartlang.org/stable/2.5.0/dart-collection/ListMixin/shuffle.html

**Comment by florent37** [comment]
you can use the shuffle method on a list simply

assetsAudioPlayer only handle playing 1 song by 1 song, just create a list, shuffle it, then use open on each. I will try to add a "playlist" feature to open a list of items !
