### ISSUE TITLE
Buffer Audio

### ISSUE THREAD

**Issue by isaac5003** [florent37/Flutter-AssetsAudioPlayer#200]
Buenas tardes, tengo el siguiente problema: Estoy creando una aplicación de radio y los usuarios tienen conexión a Internet lento. Se podrá almacenar en el buffer una porción del Streaming para no tener cortes en el audio?

**Comment by florent37** [comment]
can you please write in english :)

**Comment by isaac5003** [comment]
Good afternoon, I have the following problem: 
I am creating a radio application for users who have 
internet connection slow. Can a portion of the Streaming be 
stored in the buffer to avoid having cuts in the audio?  (Lag)

**Comment by florent37** [comment]
I increased the buffer size on Android, can you try with the last version ?

**Comment by isaac5003** [comment]
I have the version 2.0.1, i will try the new version.
Can I manually change the buffer?

**Comment by florent37** [comment]
no it just set to max capacity on exoplayer (android) on https://github.com/florent37/Flutter-AssetsAudioPlayer/issues/170

following this link : https://blogs.akamai.com/2019/10/enhancing-video-streaming-quality-for-exoplayer---part-2-exoplayers-buffering-strategy-how-to-lower-.html#:~:text=ExoPlayer%20will%20buffer%20until%20it,worth%20maxBufferMs%20of%20media%20data

**Comment by florent37** [comment]
the max buffer value is an exoplayer constant 

`final long loadControlBufferMs = DefaultLoadControl.MAX_BUFFER_MS;` 

This is `50000` milliseconds in ExoPlayer (50 seconds)

**Comment by isaac5003** [comment]
I will have my application in test mode. Thanks for your help  :)

**Comment by florent37** [comment]
:)

**Comment by isaac5003** [comment]
I did tests and it fails. Music stops  after 15 minutes of playing :( I don't know it happens

**Comment by florent37** [comment]
you want 15min of buffer ?

**Comment by florent37** [comment]
the max is 50seconds regarding the documentation :/

**Comment by isaac5003** [comment]
I don't want 15 minutes of buffer. After 15 minutes it starts to fail :(

**Comment by florent37** [comment]
Oh ok

**Comment by florent37** [comment]
can you try with `2.0.5`, it has a custom error handling

and for example you can reopen the network if it fails due a network error

```
_player.onErrorDo = (handler){
  handler.player.open(YOUR_AUDIO);
};
```

Try to open again on same position

```
_player.onErrorDo = (handler){
  handler.player.open(
      handler.playlist.copyWith(
        startIndex: handler.playlistIndex
      ),
      seek: handler.currentPosition
  );
};
```
