### ISSUE TITLE
PlayerState fires pause instead of stop

### ISSUE THREAD

**Issue by TheOnlyNurse** [florent37/Flutter-AssetsAudioPlayer#201]
**Flutter Version**

My version : 1.17.3

**Lib Version**

My version : 2.0.2

**Platform (Android / iOS / web) + version**

Platform : Android

**Describe the bug**

PlayerState.pause is called instead of PlayerState.stop when a stop event is fired by the notification controls.

**Comment by florent37** [comment]
thanks to have noticied that, it's a regression, I fixed it in `2.0.2+7`
