### ISSUE TITLE
 Music Player doesnot stop when track finish when loopMode in none.

### ISSUE THREAD

**Issue by Timus23** [florent37/Flutter-AssetsAudioPlayer#202]
**Flutter Version**
1.17.2
**Lib Version**
2.0.2+6
**Platform (Android / iOS / web) + version**

Platform : Android 

**Describe the bug**

When track finish the isPlaying value still remains true. and after that pressing pause and play won't play the track again.

**Comment by florent37** [comment]
Ok thanks for this issue, I may misses something :)

**Comment by florent37** [comment]
fixed, please try with `2.0.2+8`
