### ISSUE TITLE
LoopMode limitations

### ISSUE THREAD

**Issue by pro100svitlo** [florent37/Flutter-AssetsAudioPlayer#203]
There are some moments that are not clean and not obvious about the new `LoopMode`.

When `LoopMode.single` is on - audio is repeating.  That's fine. 

But then I am not able to play next (cos of the `single`),  but at the same moment, 

**I am able to play previous audio.** That's weird. 

Looks like it should be enabled for both: next and prev. 
`LoopMode` should touch only when audio is finished and does not make any impact on other user actions.

**Comment by florent37** [comment]
Ok I try :)

**Comment by florent37** [comment]
Ok I will follow spotify : 

next (requested by user) should also move to next music : I change that, ant set the loopmode to LoopMode.playlist (if was .single)

prev should back to start of audio (like current) and if we request again, go to prev audio & change loopmode to .playlist (if was .single)

**Comment by florent37** [comment]
fixed in 2.0.2+9, can you try ?

**Comment by pro100svitlo** [comment]
Hm, I don't think that `prev` or `next` should touch the `loopMode`

**Comment by pro100svitlo** [comment]
Its two different things.
what if I enable a single loop but I would like to apply it for the next track?
Why should I reEnable it for every song?

**Comment by florent37** [comment]
I think for this case with what I added you should re enable it yes

**Comment by florent37** [comment]
but in  the other case, what if you want to make the loopmode to playlist, you should have to update this in the code, I have to make a choice between the two options :)

maybe add an optional params to next & prev to handle this ?

**Comment by pro100svitlo** [comment]
smth like this?
```dart
void next({bool overrideLoopMode. = false}){}
```

so if `overrideLoopMode` == false, then loopMode will stay the same it was?

If yes, then it might work 😉

**Comment by florent37** [comment]
yes :) I do that

**Comment by florent37** [comment]
I was thinking to 

```
void next({bool keepLoopMode = true}){}
```

**Comment by pro100svitlo** [comment]
yes,  your variant sounds better 👍

**Comment by florent37** [comment]
I added this, just a little try & I push

**Comment by florent37** [comment]
done, it works perfectly, I'm publishing `2.0.3+1`

**Comment by pro100svitlo** [comment]
> done, it works perfectly, I'm publishing `2.0.3+1`

Thank you!
Will check it today in the evening

**Comment by pro100svitlo** [comment]
this one looks fine 👍
