### ISSUE TITLE
Notification disappears when paused

### ISSUE THREAD

**Issue by Alusio** [florent37/Flutter-AssetsAudioPlayer#204]
**Flutter Version**

My version : 1.17.3

**Lib Version**

My version : 2.0.3+2

**Platform (Android / iOS / web) + version**

Platform : Android 10.0

**Describe the bug**

When I press pause in the notification, it disappears.
it's normal ?

**Comment by florent37** [comment]
you're using a livestream ?

because on livestream, the pause is in fact a stop :) that could be why :) 

I should have to not remove the notif in this case

**Comment by Alusio** [comment]
Yes it's livestream ^^

**Comment by florent37** [comment]
Ok :) I'll make some change to not remove the notification on this case, sorry for this

**Comment by florent37** [comment]
fixed :) please try `2.0.3+3`
