### ISSUE TITLE
This example is problematic

### ISSUE THREAD

**Issue by 309791679** [florent37/Flutter-AssetsAudioPlayer#206]
assetsAudioPlayer.open(
  Playlist(
    assetAudioPaths: [
      "assets/audios/song1.mp3",
      "assets/audios/song2.mp3"
    ]
  )
);

This example is problematic
assetAudioPaths :Did not explain Types error,
What it should be, there is no description in the source code

asset_audio_player 2.0.3 + 3

**Comment by 309791679** [comment]
I want to make a loop playlist audio, not very familiar with this
The only example is it, but it reports an error

**Comment by florent37** [comment]
yes this Playlist builder do not exist anymore sorry, I fix it

**Comment by florent37** [comment]
I just fixed it

```
assetsAudioPlayer.open(
  Playlist(
    audios: [
      Audio("assets/audios/song1.mp3"),
      Audio("assets/audios/song2.mp3")
    ]
  ),
  loopMode: LoopMode.playlist() //loop the full playlist
);

assetsAudioPlayer.next();
assetsAudioPlayer.prev();
assetsAudioPlayer.playAtIndex(1);
```

**Comment by florent37** [comment]
and added the loopmode also your your usecase :)

to loop a single audio, you can use LoopMode.single

**Comment by 309791679** [comment]
> 并添加了loopmode也是您的用例:)
> 
> 循环播放单个音频，您可以使用 `LoopMode.single`

Hello, my list will be dynamic, what should I do?

List<Audio> sl=[Audio.file("/storage/emulated/0/fluttera/audio/cPHnk.mp3"), Audio.file("/storage/emulated/0/fluttera/audio/123456.mp3")];



add doesn't work, as if not mentioned in the documentation
