### ISSUE TITLE
Run some code when Audio finishes.

### ISSUE THREAD

**Issue by rdcoder33** [florent37/Flutter-AssetsAudioPlayer#207]
Say, I playing a audio and when it finishes, I want to navigate the user to a new screen.
I used listener with logic to run code when `currentposition == duration` but that doesn't.

Is it possible to run some code when a track finishes? If not please try to add this feature. May be onTrackFinish method should be added to the audio builders.

**Comment by Timus23** [comment]
There is a stream called playlistAudioFinished which is called at each audio finished.
and playlistFinished stream when whole playlist is finished.

**Comment by Timus23** [comment]
https://pub.dev/packages/assets_audio_player#-finished

**Comment by florent37** [comment]
yes for 1 single audio listen to `playlistAudioFinished`

for a complete playlist use `playlistFinished`

**Comment by florent37** [comment]
player.playlistAudioFinished.listen((finished) {
    if(finished) { your code } 
});

**Comment by florent37** [comment]
note that if you open just one audio, at its end it will ping both of `playlistAudioFinished` & `playlistFinished`
