### ISSUE TITLE
Song plays past max duration

### ISSUE THREAD

**Issue by TheOnlyNurse** [florent37/Flutter-AssetsAudioPlayer#209]
**Flutter Version**

My version : 1.17.3

**Lib Version**

My version : 2.0.2

**Platform (Android / iOS / web) + version**

Platform : Android

**Describe the bug**
When playing audio from file, the player ticks past the maximum duration.

![Screenshot_1592116340](https://user-images.githubusercontent.com/42935405/84586680-eaef5880-ae5c-11ea-8442-9dfa7a13436b.png)

**Comment by florent37** [comment]
Ok i'll fix it

**Comment by Timus23** [comment]
> Ok i'll fix it

not only in file but it happens while playing with url also with me where current position exceed the duration of the music.

**Comment by florent37** [comment]
I fixed it, just adding some other code on others issues before publish it

**Comment by florent37** [comment]
fixed in 2.0.4
