### ISSUE TITLE
Pause doesn't work

### ISSUE THREAD

**Issue by TheOnlyNurse** [florent37/Flutter-AssetsAudioPlayer#210]
**Flutter Version**

My version : 1.17.3

**Lib Version**

My version : 2.0.2

**Platform (Android / iOS / web) + version**

Platform : Android

**Describe the bug**
AssetsAudioPlayer.pause does not work. Local files played can be stopped but not paused. Can't test whether play works because I'm unable to pause first.

**Comment by florent37** [comment]
Hi, can you send me your open method and the type of audio file you're using please ?

**Comment by TheOnlyNurse** [comment]
Sorry for wasting your time, seems to have been some kind of error on my end. I cannot seem to reproduce the issue anymore.
