### ISSUE TITLE
assetsAudioPlayer.setVolume(0.5);  Failure

### ISSUE THREAD

**Issue by 309791679** [florent37/Flutter-AssetsAudioPlayer#211]
Hello, this api should be invalid, my Android version 10

assetsAudioPlayer.setVolume(0.5); 
Test multiple times, confirm invalid

**Comment by florent37** [comment]
Can you send me how you opened the song ?

And when do you use setvolume ? Directly next to open ?

**Comment by florent37** [comment]
To set a song directly while opening an audio, set it inside the open method

**Comment by 309791679** [comment]
playLocal() {
    player.setVolume（0.5）;
    player.open(Playlist(audios: List_audio),
        loopMode: LoopMode.playlist,
    );


  }

**Comment by 309791679** [comment]
> 要在打开音频时直接设置歌曲，请在open方法中进行设置
Isn't that the case?

**Comment by florent37** [comment]
It will not work it you set volume before open

Try 

Open(yourAudio, volume: 0.5)

**Comment by 309791679** [comment]
What if the volume needs to be changed dynamically?
I also tried to put it behind the opening, but it didn't work

**Comment by 309791679** [comment]
> 如果您在打开之前设置音量，它将无法正常工作
> 
> 尝试
> 
> 打开（yourAudio，音量：0.5）

I am a list player, and may need to dynamically modify the volume during playback, I don't know if it can meet

**Comment by florent37** [comment]
You can use setvolume but after the open method

**Comment by florent37** [comment]
I think I'll throw an exception if some methods are called before open so with that nobody can do that :)

**Comment by bringbackthedog** [comment]
> I think I'll throw an exception if some methods are called before open so with that nobody can do that :)

Pleaseeee ! 👍🏾 :)
This isn't obvious
