### ISSUE TITLE
Handle `noNetwork` conditions

### ISSUE THREAD

**Issue by pro100svitlo** [florent37/Flutter-AssetsAudioPlayer#214]
Right now if I turn on example app without internet (flight mode) and click `Online` track - it freezes the app, which is not nice.
Also when it happens, the player throws `PlatformException`, and it's not usable after it...

So, here I have a few  propositions:
- there should be some enum with  errorTypes : `noNetwork`/`internalError`/`unknownError`, etc
- there should be optional listener (or mb stream) for errors, with error type, msg, stackTrace
- would be nice  if networkError appear after not more then  2sec after `.open` called,  otherwise it's hard to show user why click didn't make any impact
- errors should be caught internally and should  not affect the player itself

**Comment by florent37** [comment]
Can you try to implement that ? I do not have much time for now to implement this

**Comment by pro100svitlo** [comment]
I can try to take a look, but I  have 0 experience with library development :)

**Comment by Timus23** [comment]
#222

**Comment by florent37** [comment]
I started on #224

**Comment by florent37** [comment]
for now I have 
```
enum AssetsAudioPlayerErrorType {
  Network,
  Player
}
```

**Comment by florent37** [comment]
Player is like `unknownError`

**Comment by florent37** [comment]
It's not finished yet

**Comment by florent37** [comment]
it's available, you can try the 2.0.5

look at readme : 

```
_player.onErrorDo = (handler){
  handler.player.stop();
};
```


and in the handler you have an `error` that has an attribut `type` that can be `Network` :)

**Comment by Timus23** [comment]
i hav tried the new update. its awesome. i tried to use this update for my issue #187 . it solve the problem mostly. but choosing action to pause when internet connection goes off and when net comes online choosing play action still doesn't play the music from that point. as new handler give all the necessary thing to reopen the play from exact same point but reopening it in that reason will reset everything and process bar shown in ui will goes to 0 and than suddenly moves to that point. idk if it can be fixed or not.

**Comment by pro100svitlo** [comment]
It works as expected when you `open` audio, it plays for some time, and then network gone 👍 

But if I will try open network audio when there is no connection, it still froze the app 😢

**Comment by Timus23** [comment]
@pro100svitlo for that we can check in flutter only. There are many package which help to check network connection. If network is not available we can stop the user from calling that method and show approriate message from flutter only.

**Comment by pro100svitlo** [comment]
@Timus23  Yes, you are right.
But there still might be cases, when `package` will return you that network fine, but in fact, there are no transmission. In those cases that package will be useless.

**Comment by Timus23** [comment]
yea there some cases. when i tried to open network songs without internet. it simply freezes the app and when i enable the network. it start playing music automatically and unfreezes the app. In that case the error handling didn't work.

**Comment by pro100svitlo** [comment]
I still think that this handling should be done internally, cos there pretty much cases:
- when audio should be opened
- when audio switched  to  next/prev by the user from widget
- when audio switched  to  next/prev by the user from notification
- when audio switched  to  next by loop mechanism

I  all those cases if the audio is not cached and needs a network - the app will be frozen
