### ISSUE TITLE
[Android] [HLS] Add hls support (Got error message when playing live stream format "m3u8")

### ISSUE THREAD

**Issue by erickcchoi** [florent37/Flutter-AssetsAudioPlayer#215]
**Flutter Version**

My version : 1.17.3

**Lib Version**

My version : 2.0.3+6

**Platform (Android / iOS / web) + version**

Platform : Android 29

**Describe the bug**

The example code can play the stream, but get error message when playing live stream format "m3u8".

**error message below :**

I/ExoPlayerImpl( 9534): Init 7c4b802 [ExoPlayerLib/2.11.4] [generic_x86_64, Android SDK built for x86_64, Google, 29]
E/ExoPlayerImplInternal( 9534): Source error
E/ExoPlayerImplInternal( 9534):   com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor, Ac4Extractor, FlacExtractor) could read the stream.
E/ExoPlayerImplInternal( 9534):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractorHolder.selectExtractor(ProgressiveMediaPeriod.java:1090)
E/ExoPlayerImplInternal( 9534):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:969)
E/ExoPlayerImplInternal( 9534):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
E/ExoPlayerImplInternal( 9534):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal( 9534):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal( 9534):       at java.lang.Thread.run(Thread.java:919)
I/ExoPlayerImpl( 9534): Release 7c4b802 [ExoPlayerLib/2.11.4] [generic_x86_64, Android SDK built for x86_64, Google, 29] [goog.exo.core]
V/MediaPlayer( 9534): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 9534): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaHTTPService( 9534): MediaHTTPService(android.media.MediaHTTPService@a8cff6f): Cookies: null
V/MediaHTTPService( 9534): makeHTTPConnection: CookieHandler (java.net.CookieManager@40ab8a5) exists.
V/MediaHTTPService( 9534): makeHTTPConnection(android.media.MediaHTTPService@a8cff6f): cookieHandler: java.net.CookieManager@40ab8a5 Cookies: null
W/MediaPlayerNative( 9534): info/warning (801, 0)
V/MediaPlayer( 9534): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 9534): cleanDrmObj: mDrmObj=null mDrmSessionId=null
W/MediaPlayer( 9534): mediaplayer went away with unhandled events
W/MediaPlayer( 9534): mediaplayer went away with unhandled events

**Small code to reproduce**
Just modify the 2.0.3+6 's example code "main_livestream.dart" with the URL below :

"https://18843.live.streamtheworld.com/WBBRAMAAC48/HLS/playlist.m3u8",

**Comment by florent37** [comment]
Do you know if it's an hls ?

**Comment by erickcchoi** [comment]
Yes, it is hls. it can play with the example code, but get Error message. Please advice how to solve the problem. Thank you.

**Comment by florent37** [comment]
Let me check, I thinks for android I just have to add one or 2 lines of code to make exoplayer compatible with hls (it's an extension to add)

**Comment by florent37** [comment]
fixed in 2.0.4

**Comment by erickcchoi** [comment]
Thank you so much for your quick respond.

**Comment by florent37** [comment]
:)

**Comment by florent37** [comment]
I made a lot of refacto to make it work :D

**Comment by florent37** [comment]
look at this : https://github.com/florent37/Flutter-AssetsAudioPlayer/pull/216/files

**Comment by erickcchoi** [comment]
Please advice, any new configuration require for the HLS support need?

**Comment by florent37** [comment]
nope :) it's done by the library

**Comment by erickcchoi** [comment]
updated to 2.0.4, but with the same result as before:

E/ExoPlayerImplInternal( 4183): Source error
E/ExoPlayerImplInternal( 4183):   com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor, AmrExtractor, Ac4Extractor, FlacExtractor) could read the stream.
E/ExoPlayerImplInternal( 4183):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractorHolder.selectExtractor(ProgressiveMediaPeriod.java:1090)
E/ExoPlayerImplInternal( 4183):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:969)
E/ExoPlayerImplInternal( 4183):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
E/ExoPlayerImplInternal( 4183):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal( 4183):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal( 4183):       at java.lang.Thread.run(Thread.java:923)
D/PlayerImplem( 4183): failed to open with exoplayer(Default)
I/ExoPlayerImpl( 4183): Release f9bbb62 [ExoPlayerLib/2.11.4] [generic_x86_64_arm64, sdk_gphone_x86_64_arm64, Google, 29] [goog.exo.core]
D/PlayerImplem( 4183): trying to open with exoplayer(HLS)
I/ExoPlayerImpl( 4183): Init 315c8d3 [ExoPlayerLib/2.11.4] [generic_x86_64_arm64, sdk_gphone_x86_64_arm64, Google, 29]
I/VideoCapabilities( 4183): Unsupported profile 4 for video/mp4v-es

**Comment by erickcchoi** [comment]
In 2.0.3+6 it shows error message, but still can play the audio.
In 2.0.4 it shows error message, but can't play the audio.

**Comment by florent37** [comment]
I tried with your link, and it worked, but yes It will show the error into logs

because : I try multiple formats on exoplayer, and play the first which do not throw exception

**Comment by florent37** [comment]
```
private val playerImpls = listOf<PlayerImplemTester>(
            PlayerImplemTesterExoPlayer(PlayerImplemTesterExoPlayer.Type.Default),
            PlayerImplemTesterExoPlayer(PlayerImplemTesterExoPlayer.Type.HLS),
            PlayerImplemTesterExoPlayer(PlayerImplemTesterExoPlayer.Type.DASH),
            PlayerImplemTesterExoPlayer(PlayerImplemTesterExoPlayer.Type.SmoothStreaming),
            PlayerImplemTesterMediaPlayer()
    )
```

**Comment by florent37** [comment]
the error message is in your case for `HLS`

**Comment by florent37** [comment]
look at main_liveStream.dart

https://github.com/florent37/Flutter-AssetsAudioPlayer/blob/master/example/lib/main_livestream.dart

it's your link

**Comment by erickcchoi** [comment]
Is it possible to open the HLS support base on the URL extension "m3u8" so it can reduce the few second delay.

**Comment by florent37** [comment]
what if the url does not contain m3u8 ?

**Comment by florent37** [comment]
there's a lot of hls formats, I can add it for m3u8, but if I do that I have to handle others. I start to add it for `m3u8` then will add on demands :)

**Comment by erickcchoi** [comment]
If extension is not m3u8, please set as default. Because the few second are really effect the user's exprence.

**Comment by florent37** [comment]
what i'll do : if . m3u8 -> move HLS at first position of array
else -> change nothing

**Comment by erickcchoi** [comment]
if it end with ".m3u8" please switch to HLS, other then ".m3u8" please change nothing.

**Comment by erickcchoi** [comment]
Actually the 2.0.3+6 can play the HLS ".m3u8" audio without problem, in 2.0.3+6 the only problem is the HLS format will cause it show the error message.

**Comment by florent37** [comment]
please try with 2.0.4+1

**Comment by erickcchoi** [comment]
Tested with 10 differents source, It work's fine, Thank you for your great help.

**Comment by florent37** [comment]
:)

**Comment by florent37** [comment]
thanks to have noticied this

**Comment by florent37** [comment]
I also added this to speed up hls

```
Enabling faster start-up times
You can improve HLS start up times noticeably by enabling chunkless preparation. When you enable chunkless preparation and #EXT-X-STREAM-INF tags contain the CODECS attribute, ExoPlayer will avoid downloading media segments as part of preparation. The following snippet shows how to enable chunkless preparation:

HlsMediaSource hlsMediaSource =
    new HlsMediaSource.Factory(dataSourceFactory)
        .setAllowChunklessPreparation(true)
        .createMediaSource(hlsUri);
```

**Comment by erickcchoi** [comment]
That's cool, thank you.

**Comment by erickcchoi** [comment]
Tested 2.0.4+2, it is working great, Thank you.

**Comment by erickcchoi** [comment]
Please advice, Will the HLS also support in IOS.

**Comment by florent37** [comment]
I tested and yes :)

**Comment by florent37** [comment]
it already work (with the link)

**Comment by erickcchoi** [comment]
Thank you.
