### ISSUE TITLE
Offline Play

### ISSUE THREAD

**Issue by ncr9108** [florent37/Flutter-AssetsAudioPlayer#217]
Can we add a feature like play song in offline too..
after one time play from network..after that..it will availabla as offline too.

**Comment by florent37** [comment]
like a cache feature ?

**Comment by florent37** [comment]
I think it'll be possible BUT I'll have 2 options : 

1. Download from flutter, cache it, then play it

PROS : cost less on brandwith (only the media size)

CONS : download en full song before playing it

2. Play from native mediaplayer, download it in parallel, then next time, play from the parallel downloaded

PROS : play directly the song

CONS : cost 2x the brandwitch (the song from native, the song from frutter)

**Comment by ncr9108** [comment]
Yes From Cache. 
1 Download from flutter, cache it, then play it, next time, just play from cache

this option is better

**Comment by florent37** [comment]
but you'll have to wait until the download finished before play it :)  but yes it cost less

**Comment by ncr9108** [comment]
Yes...we can

**Comment by ncr9108** [comment]
How Much Time it take for this update?

**Comment by florent37** [comment]
I'dont know, it depend how much free time I'll have

If it's hurry, you can try to do it into a fork then send it in a merge request

**Comment by ncr9108** [comment]
Ok..No Prob.. i will wait for it..no hurry..

**Comment by florent37** [comment]
what I'll add

1. `cached` attribute on **only** Audio.network

```
Audio.network(url, cached: true);
```

2. Add a `AssetsAudioPlayerCache`, *optional*

```
//by default if not set
val _defaultCache = AssetsAudioPlayerCache(cachePathProvider : (audio) async {
       String fileName = path. //do something
       return '${(await getTemporaryDirectory()).path}/$fileName';
});

//if I want a custom cache
val customCache = AssetsAudioPlayerCache(cachePathProvider : (audio) async {
       return /* what you want */;
});
```

3. add the `AssetsAudioPlayerCache` as argument of `AssetsAudioPlayer` init

`AssetsAudioPlayer(cacheManager: customCache);`

and by default `AssetsAudioPlayer()` will use `_defaultCache`

4. on _open method, if audio type is `network` and `cache == true`, I will call a download method

5. on finished, the audio become a file type, with the new path

6. add a download percent stream

**Comment by florent37** [comment]
I'll do this tomorrow ;)

**Comment by florent37** [comment]
I started a merge request, but it's not finished

**Comment by ncr9108** [comment]
Perfect... 👌😃

**Comment by florent37** [comment]
I think I can send you a beta version of the feature :)

**Comment by florent37** [comment]
I will not update the readme before you try but : 

use version : `2.0.5`

use `Audio.network(url, cached: true)`

if you want the download progress : `_player.cacheDownloadInfos.listen`

complete sample : 

```
class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  String downloadingProgress;

  final AssetsAudioPlayer _player = AssetsAudioPlayer.newPlayer();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            playerWidget(context)
          ],
        ),
      ),
    );
  }

  @override
  void initState() {
    super.initState();
    _player.cacheDownloadInfos.listen((infos) {
      print(infos.percent);
    });
    _player.open(
        Audio.network(mp3Url, cached: true),
        autoStart: true,
    );
  }

  @override
  Widget playerWidget(BuildContext context) {
    return PlayerBuilder.current(
      player: _player,
      builder: (context, current) {
        if(current == null){
          return SizedBox();
        }
        return PlayerBuilder.isPlaying(
          player: _player,
          builder: (context, isPlaying) {
            return FloatingActionButton(
              child: isPlaying ? Icon(Icons.pause) : Icon(Icons.play_arrow),
              onPressed: () {
                _player.playOrPause();
              },
            );
          },
        );
      },
    );
  }
}
```

**Comment by florent37** [comment]
and if you want to know when it's downloaded, just listen to 

```
_player.cacheDownloadInfos.listen((infos) {
      if(infos.percent == 1) { 
          //downloaded
      }
});
```

**Comment by florent37** [comment]
tell me if it work and I'll publish a new version with an updated README :)

**Comment by leidig54** [comment]
> tell me if it work and I'll publish a new version with an updated README :)

are you able to update the README with instructions on how to use this feature? Would be extremely helpful! Thank you.
