### ISSUE TITLE
For iOS i am getting this error

### ISSUE THREAD

**Issue by MuthuSubramaniam** [florent37/Flutter-AssetsAudioPlayer#22]
`assets_audio_player` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

![image](https://user-images.githubusercontent.com/39517706/69924204-17590e00-14e5-11ea-97ed-74bc82ce3b45.png)

**Comment by florent37** [comment]
can you try with the 1.2.2 I updated the swift compiler

**Comment by scullabyte** [comment]
Getting this error with both 1.2.2 and 1.2.3
