### ISSUE TITLE
Play or pause does not work

### ISSUE THREAD

**Issue by willyamdev** [florent37/Flutter-AssetsAudioPlayer#220]
**Flutter Version**

My version :  1.17.3

**Lib Version**

My version : ^2.0.4+1

**Platform (Android / iOS / web) + version**

Platform : Android + 8.1.0 and 10

**Describe the bug**

When finishing a playlist in loopmode = LoopMode.none the audio stops, as expected!

But if I change the playlist right after finishing a playlist with the audio stopped, the audio starts playing in the new playlist normally but I can't pause the music, it's just as if the button isn't being pressed!

It is as if the function "assetsAudioPlayer.playOrPause ();" don't run!

When I put loopmode = LoopMode.playlist this possible bug does not happen, because the playlist keeps playing on some song.

**Small code to reproduce**

```dart

//home.dart
PlayerBuilder.isPlaying(
    player: _musicPlayerController.assetsAudioPlayer,
    builder: (context, isPlaying) {
    return GestureDetector(
           onTap: () => _musicPlayerController.playOrPauseMusic(),
           child: NeumorphicContainer(
               containerShape: BoxShape.circle,
               width: maxHeightGrid * 70,
               height: maxHeightGrid * 70,
                child: Icon( isPlaying ? Icons.pause : Icons.play_arrow, color: ColorHelper.primaryColor),
       ),
   );
})

//music_player_controller.dart
playOrPauseMusic() {
    assetsAudioPlayer.playOrPause();
}
```
The strangest thing is that there are no errors on the console! It's like everything is right ...

I don't know if it's really a bug but I will warn you if i discover something in my code that may be helping to cause it, for now, that's all I know.

**Comment by florent37** [comment]
Can you send me your ''open'' method and also the type of audio you're using ? (Local, network, etc.)

It will help me to figure why :)

**Comment by willyamdev** [comment]
Sorry but I didn't quite understand what would be "open method" but I think this can be useful.

```dart

//music_player_controller.dart

//This method is called when user select a music in ListView
initPlaylistSounds(SongInfo song, List<SongInfo> songsList, bool autoPlay) {

    musicsList = songsList;
    int index = musicsList.indexOf(song);
    currentMusicIndex = index;

    assetsAudioPlayer.open(
        Playlist(audios: convertListToPlaylist(songsList), startIndex: index),
        autoStart: autoPlay,
        showNotification: true,
        notificationSettings: NotificationSettings(stopEnabled: false),
        loopMode: LoopMode.playlist);

}

List<Audio> convertListToPlaylist(List<SongInfo> songsList) {
    List<Audio> playlist = List();
    for (int i = 0; i < songsList.length; i++) {
      playlist.add(
        Audio.file(
          songsList[i].filePath,
          metas: Metas(
            title: songsList[i].title,
            artist: songsList[i].artist,
            album: songsList[i].album,
            image: songsList[i].albumArtwork == null
                ? MetasImage.asset("assets/images/default/music_background.png")
                : MetasImage.file(
                    songsList[i].albumArtwork),
          ),
        ),
      );
    }
    return playlist;
  }


```

The type of audio i using is Local, is audios that are on the user's cell phone.

**Comment by Timus23** [comment]
one of the case i hav encounter this problem is when invalid track is played and after that i try to play valid track. it play the music but pause doesn't work in that condition.

**Comment by Timus23** [comment]
i think unhandled error in the player also bring this problem.

**Comment by florent37** [comment]
yes the code seems good, maybe you're right @Timus23 , I must success to reproduce it to fix it

**Comment by Timus23** [comment]
i have tried a bit to solve and handle no network issue in #222 . it solve the play and pause problem when it we try to play network audio in offline mode. but there are many more error to be catch. I am confused how to do that and how to send that to dart. through player status or what ? now player status is generated from dart side only.

**Comment by leidig54** [comment]
Im having the same issue after I sop the player and restart. Play or Pause works fine on the first play through but not any after stopping.

**Comment by florent37** [comment]
I added the error handling in `2.0.5+1`

can you try ? 

by default on error while playing it will stop the player

BUT as said in readme you can do other things

https://github.com/florent37/Flutter-AssetsAudioPlayer#error-handling

**Comment by willyamdev** [comment]
Great! I finished testing now and for my, the problem was solved. 

Thank you!

**Comment by florent37** [comment]
;)
