### ISSUE TITLE
Question.

### ISSUE THREAD

**Issue by isaac5003** [florent37/Flutter-AssetsAudioPlayer#221]
version 2.0.4 + 2 is video compatible? What is HLS, Dash, SmoothStream?

**Comment by florent37** [comment]
It's an audio player, it does not intent to play video, you have other packages for this

And hls, dash, smooth stream are media formats / transport. When you use an url to play an audio, it can be directly a mp3, or use one of this format to compress it

**Comment by isaac5003** [comment]
thanks :D
