### ISSUE TITLE
Can't build 2.0.5

### ISSUE THREAD

**Issue by Alusio** [florent37/Flutter-AssetsAudioPlayer#226]
**Flutter Version**

My version : 1.20.0-1.0.pre.57

**Lib Version**

My version : 2.0.5

**Platform (Android / iOS / web) + version**

Platform : Android 10.0

**Describe the bug**

Impossible to build the 2.0.5

**Small code to reproduce**

e: C:\Users\Alexandre\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\assets_audio_player-2.0.5\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (60, 13): Unresolved reference: NotificationAction
e: C:\Users\Alexandre\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\assets_audio_player-2.0.5\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (109, 39): Unresolved reference: NotificationManager
e: C:\Users\Alexandre\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\assets_audio_player-2.0.5\android\src\main\kotlin\com\github\florent37\assets_audio_player\Player.kt: (9, 62): Unresolved reference: NotificationManager
e: C:\Users\Alexandre\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\assets_audio_player-2.0.5\android\src\main\kotlin\com\github\florent37\assets_audio_player\Player.kt: (28, 42): Unresolved reference: NotificationManager
e: C:\Users\Alexandre\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\assets_audio_player-2.0.5\android\src\main\kotlin\com\github\florent37\assets_audio_player\notification\NotificationService.kt: (120, 16): Unresolved reference: NotificationAction
e: C:\Users\Alexandre\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\assets_audio_player-2.0.5\android\src\main\kotlin\com\github\florent37\assets_audio_player\notification\NotificationService.kt: (123, 16): Unresolved reference: NotificationAction
e: C:\Users\Alexandre\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\assets_audio_player-2.0.5\android\src\main\kotlin\com\github\florent37\assets_audio_player\notification\NotificationService.kt: (131, 29): Unresolved reference: NotificationActionReceiver
e: C:\Users\Alexandre\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\assets_audio_player-2.0.5\android\src\main\kotlin\com\github\florent37\assets_audio_player\notification\NotificationService.kt: (137, 45): Unresolved reference: NotificationAction
e: C:\Users\Alexandre\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\assets_audio_player-2.0.5\android\src\main\kotlin\com\github\florent37\assets_audio_player\notification\NotificationService.kt: (212, 45): Unresolved reference: NotificationAction
e: C:\Users\Alexandre\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\assets_audio_player-2.0.5\android\src\main\kotlin\com\github\florent37\assets_audio_player\notification\NotificationService.kt: (227, 59): Unresolved reference: NotificationAction
e: C:\Users\Alexandre\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\assets_audio_player-2.0.5\android\src\main\kotlin\com\github\florent37\assets_audio_player\notification\NotificationService.kt: (241, 103): Unresolved reference: NotificationAction
e: C:\Users\Alexandre\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\assets_audio_player-2.0.5\android\src\main\kotlin\com\github\florent37\assets_audio_player\notification\NotificationService.kt: (259, 64): Unresolved reference: NotificationAction
e: C:\Users\Alexandre\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\assets_audio_player-2.0.5\android\src\main\kotlin\com\github\florent37\assets_audio_player\notification\NotificationService.kt: (267, 64): Unresolved reference: NotificationAction
e: C:\Users\Alexandre\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\assets_audio_player-2.0.5\android\src\main\kotlin\com\github\florent37\assets_audio_player\notification\NotificationService.kt: (295, 56): Unresolved reference: NotificationAction

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':assets_audio_player:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 28s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by florent37** [comment]
can you try to do `flutter clean` ?

**Comment by Alusio** [comment]
Oh I had a wrong configuration ^^ nevermind ;) thx

**Comment by harshmittal2810** [comment]
@Alusio Can you please write down solution, I am also facing the same problem in Android devices but IOS working fine.

**Comment by Alusio** [comment]
I just did `flutter clean` command ;)

**Comment by harshmittal2810** [comment]
I tried that and pub cache fix too but still facing the same issue. 😢

**Comment by Alusio** [comment]
Upgrade your flutter and check again all of your package version

**Comment by Alusio** [comment]
Can you put here your pubspec.yaml ?

**Comment by harshmittal2810** [comment]
Yes sure.
`
environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  modal_progress_hud: ^0.1.3
  sticky_headers: ^0.1.8+1
  flutter_statusbarcolor: ^0.2.3

  font_awesome_flutter: ^8.10.0
  assets_audio_player: ^2.0.13+1
  carousel_slider: ^2.3.1
  auto_size_text: ^2.1.0
  flutter_time_picker_spinner: ^1.0.6+1
  chips_choice: ^2.0.1
  in_app_purchase: ^0.3.4+16
  flutter_local_notifications: ^3.0.1+2

  ###firebase
  firebase_core: ^0.5.2
  firebase_crashlytics: ^0.2.3
  firebase_analytics: ^6.2.0
  firebase_messaging: ^7.0.3
  firebase_auth: ^0.18.3
  flutter_facebook_auth: ^0.3.3
  sign_in_with_apple: ^2.5.4
  google_sign_in: ^4.5.6
  dio: ^3.0.10

  webview_flutter: ^1.0.6
  flutter_gifimage: ^1.0.1

  url_launcher: ^5.7.10
#  rflutter_alert: ^1.1.0
  purchases_flutter: ^1.4.3

  package_info: ^0.4.3+2
  smooth_page_indicator: ^0.2.0
#  meta: ^1.2.3
  flutter_svg: ^0.19.1
  http: ^0.12.2
  http_interceptor: ^0.3.3
  shared_preferences: ^0.5.12+4
  cached_network_image: ^2.3.3
  sealed_unions: ^3.0.2+2
  flutter_stream_friends: ^0.8.0

  intl: ^0.16.1
  intl_translation: ^0.17.10+1

  sentry: ^3.0.1
  provider: ^4.3.2+2

#  sqflite: ^1.3.2+1
#  path_provider: ^1.6.24

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  image_path: "icon/icon.jpg"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/video/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 200
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 900

    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Regular.ttf
        - asset: assets/fonts/Oswald-Light.ttf
          weight: 200
        - asset: assets/fonts/Oswald-Medium.ttf
          weight: 500
        - asset: assets/fonts/Oswald-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Oswald-Bold.ttf
          weight: 700`

**Comment by Alusio** [comment]
sounds good to me ... very strange. Didi you try to remove manually the .pub-cache/hosted /pub.dartlang.org in the flutter folder ?

**Comment by harshmittal2810** [comment]
Tried and still facing the same issue.
