### ISSUE TITLE
`dispose` should be Future

### ISSUE THREAD

**Issue by pro100svitlo** [florent37/Flutter-AssetsAudioPlayer#229]
If i `open` and then immediately call `dispose` i catch `Bad state: Cannot add new events after calling close` error.

This happened when audio is network.
I expect, that  if might gone if `dispose` might be Future. Also `stop`  iside `dispose` shouldbe called with  `await` keyword.

**Comment by florent37** [comment]
thanks. I did it in `2.0.5+2` :)

**Comment by roshansrashtasoft** [comment]
I/flutter ( 5556): Bad state: Cannot add new events after calling close
I/flutter ( 5556): #0      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:243:24)
I/flutter ( 5556): #1      Subject._add (package:rxdart/src/subjects/subject.dart:151:17)
I/flutter ( 5556): #2      Subject.add (package:rxdart/src/subjects/subject.dart:141:5)
I/flutter ( 5556): #3      AssetsAudioPlayer._replaceRealtimeSubscription.<anonymous closure> (package:assets_audio_player/src/assets_audio_player.dart:733:29)
I/flutter ( 5556): #4      _rootRunUnary (dart:async/zone.dart:1407:47)
I/flutter ( 5556): #5      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
I/flutter ( 5556): #6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
I/flutter ( 5556): #7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
I/flutter ( 5556): #8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
I/flutter ( 5556): #9      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
I/flutter ( 5556): #10     _MapStream._handleData (dart:async/stream_pipe.dart:218:10)
I/flutter ( 5556): #11     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
I/flutter ( 5556): #12     _rootRunUnary (dart:async/zone.dart:1407:47)
I/flutter ( 5556): #13     _CustomZone.
I/flutter ( 5556): ----------------------------------------------------

How To Resolved This Error

assets_audio_player: 3.1.1
