### ISSUE TITLE
Kotlin Version Error

### ISSUE THREAD

**Issue by mutlu-tekin** [florent37/Flutter-AssetsAudioPlayer#23]
* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.10 and higher.
The following dependencies do not satisfy the required version:
project ':assets_audio_player' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BU�LD FAILED in 4s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by yossefEl** [comment]
I faced the same problem 
just go to **_{flutter folder root}_/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-1.0.1/**
and then **android/** folder
open the file **build.gradle** 
set     **ext.kotlin_version = '1.3.10'** 
```
buildscript {
    ext.kotlin_version = '1.3.10'
    repositories {
        google()
        jcenter()
    }
....
}
```

**Comment by florent37** [comment]
fixed
