### ISSUE TITLE
Update current notification

### ISSUE THREAD

**Issue by pro100svitlo** [florent37/Flutter-AssetsAudioPlayer#231]
Actually this is not a feature request, but request to add some info to `readme` doc.

I found that if a `open` a playlist with `showNotification=false`, then notification didn't update, when audio changed.

To fix that I added next line:
```dart
_player.showNotification = true;
```
inside `_player.current` stream listener.
As a result, every time audio changed (manually by user or automatically by the loop mode) the notification is also changed 🎉

**Comment by florent37** [comment]
It does not work when you're playing a playlist, and when it switch (without user interraction) from song 1 to 2 ?

if yes, it's not a feature request, it's a bug :)

it's on android or ios ?

**Comment by pro100svitlo** [comment]
Just double-checked, it didn't switched at all :)

(without `_player.showNotification = true;`)

**Comment by pro100svitlo** [comment]
notification is always from the first audio

**Comment by florent37** [comment]
Ok I'll fix it

**Comment by florent37** [comment]
I came again on this issue, if you open with `showNotification=false` it's normal that the "old notification" do not recieve the new playlist metadatas :) no ?

the first time I did not saw the `=false`

**Comment by florent37** [comment]
can you explain me what do you want in the readme ?
