### ISSUE TITLE
[BUG] Setter 'loop=' called on null

### ISSUE THREAD

**Issue by AlexVincent525** [florent37/Flutter-AssetsAudioPlayer#232]
Hi, it's me again 😃 

**Flutter Version**: 1.17.4

**Lib Version**: 2.0.1

**Platform (Android / iOS / web) + version**: Android (iOS not tested)

**Describe the bug**

Called on null exception when I was tried to load a audio.

**Small code to reproduce**

Check out [Audio page builder](https://github.com/fluttercandies/flutter_wechat_assets_picker/blob/master/lib/src/widget/builder/audio_page_builder.dart) which provided the full usage in my case.

** Error logs**
```
E/flutter (15169): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The setter 'loop=' was called on null.
E/flutter (15169): Receiver: null
E/flutter (15169): Tried calling: loop=false
E/flutter (15169): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
E/flutter (15169): #1      AssetsAudioPlayer.setLoop (package:assets_audio_player/src/assets_audio_player.dart:292:15)
E/flutter (15169): #2      AssetsAudioPlayer.loop= (package:assets_audio_player/src/assets_audio_player.dart:288:5)
E/flutter (15169): #3      _AudioWidgetState._open (package:assets_audio_player/src/widget/audio_widget.dart:122:13)
E/flutter (15169): #4      _AudioWidgetState.initState (package:assets_audio_player/src/widget/audio_widget.dart:118:5)
```

**Comment by florent37** [comment]
have you called loop before the open method ? 

can you try with the lastest version, I fully reworked the loop behavior, now it's an enum :)

`2.0.5+2`

**Comment by AlexVincent525** [comment]
> have you called loop before the open method ?

I didn't actually, it seems like called inside.

> can you try with the lastest version, I fully reworked the loop behavior, now it's an enum :)

Currently I don't have test environment, I'll give you feedback after few hours :P

**Comment by florent37** [comment]
it happen when you call the open method so ?

**Comment by florent37** [comment]
oh yes it's in the stack `_AudioWidgetState._open`

**Comment by AlexVincent525** [comment]
Resolved confirmed, thanks!

**Comment by florent37** [comment]
:)
