### ISSUE TITLE
When i play ios that record android, It is problem

### ISSUE THREAD

**Issue by alexonepath** [florent37/Flutter-AssetsAudioPlayer#236]
**Flutter Version**

My version : 1.17.3

**Lib Version**

My version : 2.0.5+2

**Platform (Android / iOS / web) + version**

Platform : 13.5.1

**Describe the bug**

1. What I recorded on ios is played on Android.
2. What I recorded on ios is played on ios.
3. What I recorded on Android does not play on ios.

You can download test file
- https://static-oppaya.autocoupon.kr/dev/4/voice/2020-06-21_24294677366355.m4a

Error Message:
flutter: PlatformException(PLAY_ERROR, Cannot play https://static-oppaya.autocoupon.kr/dev/4/voice/2020-06-21_24294677366355.m4a, Cannot Open)

**Small code to reproduce**

```dart
  Future<void> play() async {
    audioPlayer.open(widget.isLocal ? Audio.file(widget.path) : Audio.network(widget.path));
    if (mounted) {
      setState(() {
        playing = true;
      });
    }
  }
```

**Comment by florent37** [comment]
I have a 403 access denied for your file

https://static-oppaya.autocoupon.kr/dev/4/voice/2020-06-21_24294677366355.m4a

**Comment by florent37** [comment]
I close if for now, and will reopen it when I'll have the file :) and succeed to reproduce
