### ISSUE TITLE
Add a Live Tag to the MPNowPlayingInfoCenter on iOS when playing a LiveStream

### ISSUE THREAD

**Issue by chevalierv** [florent37/Flutter-AssetsAudioPlayer#240]
Hi!

Could you add this tag when you start playing a live stream on iOS ? This will switch the control center to Live Mode with a specific UI on Car Play and Watch OS. I don't know if there is an android equivalent but this would be great!

https://developer.apple.com/documentation/mediaplayer/mpnowplayinginfopropertyislivestream

Thanks for your work.

Valentin

**Comment by florent37** [comment]
it's not necessary to have this on android :)

but what should I add

`props[MPNowPlayingInfoPropertyIsLiveStream] = 1.0`

if it's a livestream ? 

If yes It'll add today ;)

**Comment by chevalierv** [comment]
Yeah that's it. I'll test it tonight if it's available.

**Comment by florent37** [comment]
done :) `^2.0.6+3`

**Comment by florent37** [comment]
<img width="356" alt="Capture d’écran 2020-06-23 à 15 25 51" src="https://user-images.githubusercontent.com/5754972/85409548-3ba23800-b566-11ea-82d5-8b681570d6a9.png">
<img width="341" alt="Capture d’écran 2020-06-23 à 15 25 55" src="https://user-images.githubusercontent.com/5754972/85409552-3d6bfb80-b566-11ea-8704-06e5138e378b.png">
