### ISSUE TITLE
PLay asset audio one by one with different playback speeds

### ISSUE THREAD

**Issue by pateldhruv0248** [florent37/Flutter-AssetsAudioPlayer#245]
Hello,
I loved this package, and it is very helpful to play asset audio, as this have playback speed for 'asset audio'.

But I want to play different audio files with different playback speeds, one after another just like playlist (But playlist played with different playback speeds) (For assets audio). 
Example:-
My asset folder have 3 audio files :- **audio1.wav,  audio2.wav,  audio3.wav**
So i want play :-
audio1.wav with 1.25x playback speed,   _(then after audio1.wav is completed)_
audio2.wav with 1.40x playback speed,   _(then after audio2.wav is completed)_
audio3.wav with 7.86x playback speed

_Also, it would be helpful if the duration of every audio file is obtained after adding different playback speed._

I also don't know if it is already possible to do with present version. I am using `assets_audio_player: ^1.6.2` version.
I tried the issue on stack-overflow, but didn't got success. Hope this will help me.
(Sorry if my English was not perfect)
Thanks.

**Comment by florent37** [comment]
Maybe if I add an array in the playlist with the seems of each index, it'll help you ?

Like

Playlist(audios: [audio1, audio2], speeds : [0.5, 2]) ?

**Comment by florent37** [comment]
It's not already available but I can add it

**Comment by florent37** [comment]
The other way is to add a speed inside the audio

Maybe it's better ?

**Comment by pateldhruv0248** [comment]
yes, the 2nd option is better i guess, as i want to give random speeds between certain range

**Comment by florent37** [comment]
It will be only a ''start speed''

If you want to have a different speed during the playing, you'll have to listen for ''currentPosition'' and update the play speed during the play

**Comment by pateldhruv0248** [comment]
The main issue was to play audio one after other, The audio was playing simultaneously. And BTW, thanks for quick reply.

**Comment by pateldhruv0248** [comment]
> It will be only a ''start speed''
> 
> If you want to have a different speed during the playing, you'll have to listen for ''currentPosition'' and update the play speed during the play

I have different audio files, so i just want to give speed only once the audio starts, i.e. every audio will have a constant speed from start to end.
But different audio with different speeds,
I hope I am able to explain clearly.

**Comment by florent37** [comment]
Ok I see :) yes adding a startspeed directly into the audio will fix it ;)

**Comment by florent37** [comment]
added :) 

```
Audio(
      "assets/audios/rock.mp3",
      playSpeed: 2.0,
    ),
```

**Comment by florent37** [comment]
try the `^2.0.6+4`

**Comment by pateldhruv0248** [comment]
Thanks a lot for solving the issue quickly. It is now working exactly I wanted.
Also, I have one more issue, If you can help with that, It would be great.

I want to run a task after the playlist is completely played i.e. When the audio (playlist) is finished.

The code i tried is...
```
Future<void> nextTask() async{
    print('perform next task');
  }

  void musicBox() async{
    final assetsAudioPlayer = AssetsAudioPlayer();
    await assetsAudioPlayer.open(
        Playlist(
            audios: [
              Audio('assets/14678', playSpeed: 3),
              Audio('assets/14675', playSpeed: 7),
              Audio('assets/14676', playSpeed: 6),
            ]
        ),
    );
    await nextTask();    //Call function after above playlist is finished playing
  }
```

Here, nextTask is called in middle when the audio is playing, But I want to wait till the audio is completely played.

I am not sure if i have placed Future and await properly or not.
Would be great if you can help me. Thanks

**Comment by florent37** [comment]
this future does not exist yet, for now you only can listen to playlistFinished

it's not sexy but you can try 

```
await assetsAudioPlayer.playlistFinished.where((finished) => finished == true).first()
```

**Comment by florent37** [comment]
open just wait until the first audio has been opened
