### ISSUE TITLE
ANR: Context.startForegroundService() did not then call Service.startForeground()

### ISSUE THREAD

**Issue by mohamnag** [florent37/Flutter-AssetsAudioPlayer#247]
**Flutter Version**

My version : 1.17.4

**Lib Version**

My version : 2.0.1+7

**Platform (Android / iOS / web) + version**

Platform : Android

**Describe the bug**

library is used simply for playing short sounds by calling the open method with default params (`showNotification = false`) but play console is reporting lots of ANRs with following data:

```
Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{165abae u0 com.example.product/com.github.florent37.assets_audio_player.notification.NotificationService}
```

I could not reproduce it in debug mode therefore not sure if also applies to the more recent versions of this plugin but somebody more familiar with the code might have the insight.

**Small code to reproduce**

```dart
import 'package:assets_audio_player/assets_audio_player.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State {
  
  final AssetsAudioPlayer _assetsAudioPlayer = AssetsAudioPlayer();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: RaisedButton(
            child: Text("open"),
            onPressed: () {
              _assetsAudioPlayer.open(Audio("audio/somefile.mp3"))
            }
          ),
        ),
      ),
    );
  }
}
```

**Comment by florent37** [comment]
I don't reproduce, what's your manufacturer ?

**Comment by florent37** [comment]
I checked with breakpoints, all "service" related method are called only when the showNotification is true, I don't undestand

do you have the stackstrace ? (ex: using firebase crash report)

**Comment by florent37** [comment]
it seems to happen on some device :'( https://issuetracker.google.com/issues/76112072#comment56

**Comment by mohamnag** [comment]
Thanks for digging it out. Yes in my case is also mainly Samsung phones. I can't find a specific connection to phone boot time but it might be basically same problem (too busy phone / too few resources). I will try to move the initialization of the instance to a possible later time and see if that fixes the issue.

**Comment by mohamnag** [comment]
so some days after I deployed and distributed a version with delayed assets audio player initialization and letting lots of users update to this version. unfortunately all those ANRs still happening. I assume its a combination of things probably due to crowded startup of app. so really no idea how to solve this...

**Comment by markst** [comment]
For us the occurrences are currently only on Samsung Galaxy S10e & Samsung Galaxy S8.

**Comment by kalismeras61** [comment]
Can you try latest version of this plugin ?
