### ISSUE TITLE
Catch InvalidResponseCodeException

### ISSUE THREAD

**Issue by Alusio** [florent37/Flutter-AssetsAudioPlayer#249]
Hello,

Dans certains cas mon URL est inaccessible. J'ai donc l'exception suivante qui est levée.

E/ExoPlayerImplInternal( 6634): Source error
E/ExoPlayerImplInternal( 6634):   com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
E/ExoPlayerImplInternal( 6634):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:300)
E/ExoPlayerImplInternal( 6634):       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
E/ExoPlayerImplInternal( 6634):       at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
E/ExoPlayerImplInternal( 6634):       at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:65)
E/ExoPlayerImplInternal( 6634):       at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:170)
E/ExoPlayerImplInternal( 6634):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
E/ExoPlayerImplInternal( 6634):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal( 6634):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal( 6634):       at java.lang.Thread.run(Thread.java:919)

cependant, avec un 
try{
}catch (e){
}

Impossible de la catcher?

Es-ce normal ?

**Comment by Alusio** [comment]
Après vérification, elle est bien catch, mais après un freeze total de l'application.

**Comment by florent37** [comment]
Bonjour, peux tu m'envoyer l'url que je puisse tester ? 
J'ai peut être mal fait un try catch quelque part

Si l'URL est sensible / privée, tu peux me l'envoyer par mail : champigny.florent@gmail.com

**Comment by florent37** [comment]
je pense avoir trouvé un fix, j'ai fait plusieurs choses

1. si il y a une erreur > 400 sur le premier player natif (ça en teste plusieurs), ça lève une exception qui arrête la recherche des players

2. le mediaplayer est maintenant initialisé en background thread, ce qui evite le freeze

3. l'erreur http remonte à flutter

fait bien attention par contre a fair des `await` devant les méthodes open, play, pause si tu veux catcher les exceptions

et tu as `onErrorDo` pour réagir aux erreurs de lecture

je t'envoir sur la suite un exemple complet

**Comment by florent37** [comment]
```dart
import 'package:assets_audio_player/assets_audio_player.dart';
import 'package:flutter/material.dart';

final streamUrl = "https://18843.live.streamtheworld.com/WBBRAMAAC48/HLS/playlist.m3u8";

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'From File path',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  String downloadedFilePath;
  String downloadingProgress;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Player(streamUrl),
          ],
        ),
      ),
    );
  }
}

class Player extends StatefulWidget {
  final String streamPath;

  Player(this.streamPath);

  @override
  _PlayerState createState() => _PlayerState();
}

class _PlayerState extends State<Player> {
  final AssetsAudioPlayer _player = AssetsAudioPlayer.newPlayer();

  @override
  void initState() {
    super.initState();
    _init();
  }

  void _init() async {
    try {
      _player.onErrorDo = (error) {
        error.player.stop();
      };
      await _player.open(
        Audio.liveStream(this.widget.streamPath, metas: Metas(
            title: "title",
            album: "album",
            artist: "artist",
            image: MetasImage.network("https://i.pinimg.com/564x/e3/77/94/e377940a4c2417221d04c47e5a52d2d4.jpg")
        )),
        autoStart: false,
        showNotification: true,
        notificationSettings: NotificationSettings(
            nextEnabled: false,
            prevEnabled: false,
            stopEnabled: false
        ),
      );
    } catch(t) {
      print(t);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        PlayerBuilder.isBuffering(
          player: _player,
          builder: (context, isBuffering) {
            if (isBuffering) {
              return Column(
                children: [
                  CircularProgressIndicator(),
                  SizedBox(height: 8,),
                  Text("Buffering"),
                ],
              );
            } else {
              return SizedBox(); //empty
            }
          },
        ),
        PlayerBuilder.isPlaying(
          player: _player,
          builder: (context, isPlaying) {
            return FloatingActionButton(
              child: isPlaying ? Icon(Icons.pause) : Icon(Icons.play_arrow),
              onPressed: () async {
                try {
                  await _player.playOrPause();
                } catch (t) {
                  print(t);
                }
              },
            );
          },
        ),
      ],
    );
  }
}

```

**Comment by florent37** [comment]
tu peux tester `2.0.6+5` et me dire si c'est mieux ?

**Comment by Alusio** [comment]
Je viens de tester. Cela marche très bien !
Merci beaucoup pour ton travail !

**Comment by florent37** [comment]
:) merci
