### ISSUE TITLE
[ iOS ] [ help wanted ] Notification buttons does not work on IOS when app background.

### ISSUE THREAD

**Issue by kalismeras61** [florent37/Flutter-AssetsAudioPlayer#252]
**Flutter Version**

My version : 1.17.4 stable

**Lib Version**

My version : latest

**Platform (Android / iOS / web) + version**

Platform : IOS / 13.4.1 

Music playing background when i click next button it is removing songs details and stop playing music.

**Comment by kalismeras61** [comment]
I have still same issue notification buttons doesnt work on when app is on background. 

see the video : https://youtu.be/jDyJzIg-w-A

**Comment by kalismeras61** [comment]
@florent37  any update ?

**Comment by kalismeras61** [comment]
@florent37  i found another issue when app is background the next music is not playing. That's why it's a problem.

**Comment by kalismeras61** [comment]
no update ? :(

**Comment by florent37** [comment]
no sorry, I don't know how to fix it :/ notifications are extremely difficult to try & fix on ios :/

**Comment by florent37** [comment]
I mark it as "help wanted"
