### ISSUE TITLE
Music does not continue after the phone call on IOS

### ISSUE THREAD

**Issue by kalismeras61** [florent37/Flutter-AssetsAudioPlayer#253]
**Flutter Version**

My version : 1.17.4

**Lib Version**

My version : latest

**Platform (Android / iOS / web) + version**

Platform : IOS / 13.14.1

**Describe the bug**

When i use recorder or when i have incoming call music does't continue after call.

**Comment by kalismeras61** [comment]
@florent37 any suggestion for that ?

**Comment by florent37** [comment]
I need to try, currently I'm working on a similar usecase : pause When unplug the headset. Just after that, I'll fix your usecase

**Comment by kalismeras61** [comment]
Thanks!

**Comment by florent37** [comment]
I added this on android & it works, but on ios I don't have any device and the trigger https://blog.erikvdwal.nl/resuming-avplayer-after-being-interrupted/ don't seems to be called :/

**Comment by kalismeras61** [comment]
If it is merged. I can test it on our app

**Comment by florent37** [comment]
yes, I pushed it, in a `2.0.7+3`

if it does not work, you'll have to try to fix it using your device & opeining the xcode project adding breakpoints

hope it work :) 

I added on the open method a new argument : 
```
open(
     ...
    phoneCallStrategy : PhoneCallStrategy.pauseOnPhoneCallResumeAfter
```

**Comment by kalismeras61** [comment]
Yeah it is working when i receive call. But when i use TTS, it is not working. Let me explain it briefly; 

While playing music in my app, I keep TTS active by holding down anywhere in the app at the same time. When I hold it down for a long time, it goes into listening mode. (like siri or google assistant) And it senses my voice, but the music stops for 2 seconds then continues. I don't want music to play while it is in listening mode.
