### ISSUE TITLE
support visualizers ?

### ISSUE THREAD

**Issue by liuchuancong** [florent37/Flutter-AssetsAudioPlayer#259]
```
https://github.com/iamSahdeep/FlutterVisualizers
```

```
player.getAudioSessionId()
```
How can i get this?

**Comment by liuchuancong** [comment]
```
https://github.com/GautamChibde/android-audio-visualizer
```
And this

**Comment by florent37** [comment]
I can add this 

docs for the implementation : 
android mediaplayer : `player.getAudioSessionId()`
android exoplayer : 
```
Player.AudioComponent audioComponent = exoPlayer.getAudioComponent();
int audioSessionid=audioComponent.getAudioSessionId();
```

**Comment by florent37** [comment]
but it seems to work only on android ?

**Comment by liuchuancong** [comment]
Thanks a lot!  you are very nice!

**Comment by liuchuancong** [comment]
yes,i just want work on android

**Comment by florent37** [comment]
you can use the `2.0.6+7`

to retrieve the audioSessionId, as it's async, you can

1. observe the stream

```
int sessionId;

@override
  void initState() {
   _assetsAudioPlayer.audioSessionId.listen((sessionId) {
       setState((){
           this.sessionId = sessionId;
       })
    ));
}

build(context) {
     if(sessionId == null) {
        //display without visualizer
     } else  {
        //display with visualizer
}
```

or await for the value

```
```
int sessionId;

void _openMySong() async {
    _assetsAudioPlayer.open(....);
    this.sessionId = await _assetsAudioPlayer.audioSessionId.first;
    setState((){
           this.sessionId = sessionId;
       });
}

build(context) {
     if(sessionId == null) {
        //display without visualizer
     } else  {
        //display with visualizer
    }
}
```

**Comment by florent37** [comment]
reopen this ticket if this does not work :)

**Comment by liuchuancong** [comment]
I can got 'sessionId' when reload.

I can't get 'sessionId'

```
runApp, pause, play, assetsAudioPlayer.open(_playlist), next(),prev().etc.
```
I  cant't recevied

**Comment by florent37** [comment]
can you explain with more detail please :)

**Comment by florent37** [comment]
sessionId is providen after each native (android) `open`, so after any interraction (next, prev) the stream should be updated

can you send me your code ?

**Comment by florent37** [comment]
I think I found a fix, some times the audio session id comes later from the exo player, I added a listener, which should fix your issue :)

can you try the `2.0.7+2` ?

**Comment by liuchuancong** [comment]
```
  Future<void> _playSong() async {
    print('start');
    await AudioInstance().requestRecordAudioPermission();
    final sessionId = await AudioInstance().assetsAudioPlayer.audioSessionId.first;
    print(sessionId);
    print('end');
    await AudioInstance().playNetWorkSong();
  }
```
```
Restarted application in 1,454ms.
Reloaded 4 of 872 libraries in 613ms.
I/flutter (10198): start
```
cann't go on with the next work

**Comment by liuchuancong** [comment]
```
  void audioSessionListener() {
    _sessionIdsubscription =
        AudioInstance().assetsAudioPlayer.audioSessionId.listen((sessionId) {
          print('sessionId$sessionId');
      if (sessionId != null) {
        setState(() {
          _sessionId = sessionId;
        });
      }
    });
  }
```
same as here!

**Comment by liuchuancong** [comment]
after   flutter clean  It's works! thanks

**Comment by florent37** [comment]
:)
