### ISSUE TITLE
Pause music when headset unplugged

### ISSUE THREAD

**Issue by alecchan** [florent37/Flutter-AssetsAudioPlayer#261]
It should be possible to pause audio automatically when the headset is disconnected/unplugged.

**Comment by florent37** [comment]
have you testes on android and/or ios ?

**Comment by alecchan** [comment]
Andriod. Sorry, I don't have an Apple device to test.

**Comment by florent37** [comment]
I just added this

while opening a song, add 

```
assetsAudioPlayer.open(
   ...
  headPhoneStrategy: HeadPhoneStrategy.pauseOnUnplug,
)
```

values : 

```
enum HeadPhoneStrategy {
  none,
  pauseOnUnplug,
  pauseOnUnplugPlayOnPlug
}
```

If you want to make it work on bluetooth too, you'll have to add the BLUETOOTH permission inside your AndroidManifest.xml

```xml  
<uses-permission android:name="android.permission.BLUETOOTH" />
```

I publish it in `2.0.7` can you try ?

**Comment by alecchan** [comment]
Thank you very much. I will update my code and let you know how I get on.

**Comment by alecchan** [comment]
I am getting the following compilation error.

C:\Users\chan_\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\assets_audio_player-2.0.6+4\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (19, 14): Conflicting declarations: internal val METHOD_POSITION: String, internal val METHOD_POSITION: String
e: C:\Users\chan_\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\assets_audio_player-2.0.6+4\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (20, 14): Conflicting declarations: internal val METHOD_VOLUME: String, internal val METHOD_VOLUME: String

**Comment by florent37** [comment]
just perform a `flutter clean` :) it often happen while upgrading a library

**Comment by alecchan** [comment]
Both Bluetooth and wired headphones seem to be working as advertised. Thanks again.

**Comment by florent37** [comment]
=)
