### ISSUE TITLE
error in logs after upgrading to assets_audio_player 2.0.7+2 from 2.0.6+7

### ISSUE THREAD

**Issue by kw2019ltd** [florent37/Flutter-AssetsAudioPlayer#265]
E/System  (29470): java.lang.SecurityException: Need BLUETOOTH permission: Neither user 10741 nor current process has android.permission.BLUETOOTH.
E/System  (29470): 	at android.os.Parcel.createException(Parcel.java:2071)
E/System  (29470): 	at android.os.Parcel.readException(Parcel.java:2039)
E/System  (29470): 	at android.os.Parcel.readException(Parcel.java:1987)
E/System  (29470): 	at android.bluetooth.IBluetoothManager$Stub$Proxy.unregisterStateChangeCallback(IBluetoothManager.java:582)
E/System  (29470): 	at android.bluetooth.BluetoothHeadset.close(BluetoothHeadset.java:452)
E/System  (29470): 	at android.bluetooth.BluetoothHeadset.finalize(BluetoothHeadset.java:462)
E/System  (29470): 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:294)
E/System  (29470): 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:281)
E/System  (29470): 	at java.lang.Daemons$Daemon.run(Daemons.java:142)
E/System  (29470): 	at java.lang.Thread.run(Thread.java:919)
E/System  (29470): Caused by: android.os.RemoteException: Remote stack trace:
E/System  (29470): 	at android.app.ContextImpl.enforce(ContextImpl.java:1930)
E/System  (29470): 	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:1958)
E/System  (29470): 	at com.android.server.BluetoothManagerService.unregisterStateChangeCallback(BluetoothManagerService.java:640)
E/System  (29470): 	at android.bluetooth.IBluetoothManager$Stub.onTransact(IBluetoothManager.java:303)
E/System  (29470): 	at android.os.Binder.execTransactInternal(Binder.java:1032)

**Comment by florent37** [comment]
yes it's just a waning because of a new feature I added (https://github.com/florent37/Flutter-AssetsAudioPlayer#headphone-strategy) but it should not crash, I'll remove the warning in a next release

**Comment by florent37** [comment]
fixed

**Comment by kw2019ltd** [comment]
still i see the error with assets_audio_player: ^2.0.7+8


Launching lib\main.dart on HD1903 in debug mode...
Running Gradle task 'assembleDebug'...
Note: C:\Tools\flutter\.pub-cache\git\plugins-8bc1c72165683889e27d7dab99b8f5c64e333ba7\packages\camera\android\src\main\java\io\flutter\plugins\camera\CameraPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_admob-0.9.3+2\android\src\main\java\io\flutter\plugins\firebaseadmob\AdRequestBuilderFactory.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_remote_config-0.3.1\android\src\main\java\io\flutter\plugins\firebase\firebaseremoteconfig\MethodCallHandlerImpl.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_flexible_toast-0.1.4\android\src\main\kotlin\sanketvekariya\flutter_flexible_toast\GifImageView.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\multi_image_picker-4.6.7\android\src\main\java\com\vitanov\multiimagepicker\FileDirectory.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.4.11\android\src\main\java\io\flutter\plugins\urllauncher\WebViewActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
√ Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
Debug service listening on ws://127.0.0.1:59894/WIVrG3x96rI=/ws
Syncing files to device HD1903...
D/OpScreenModeManager(26587): setRefreshRate token android.os.BinderProxy@4d17144 rate 1 mCurrentRate 0
D/OpScreenModeManager(26587): updateScenario fullScreen 1
W/Gralloc3(26587): mapper 3.x is not supported
D/        (26587): Successfully load libgui-plugin.so, this=0x71440f1050
I/Choreographer(26587): Skipped 40 frames!  The application may be doing too much work on its main thread.
W/Ads     (26587): Update ad debug logging enablement as false
I/OpenGLRenderer(26587): Davey! duration=710ms; Flags=1, IntendedVsync=142428021834989, Vsync=142428688501629, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=142428697051395, AnimationStart=142428697134781, PerformTraversalsStart=142428698576031, DrawStart=142428717777176, SyncQueued=142428726977697, SyncStart=142428727324208, IssueDrawCommandsStart=142428728341083, SwapBuffers=142428731850406, FrameCompleted=142428732843895, DequeueBufferDuration=2015000, QueueBufferDuration=582000, 
D/OnePlusJankManager(26587):  Chor uploadMDM JANK_TYPE_ONCE mViewTitle = kw.ltd.barcodeisraelapp/kw.ltd.barcodeisraelapp.MainActivity--- jank level = 3
I/DpmTcmClient(26587): RegisterTcmMonitor from: $Proxy0
E/System  (26587): Uncaught exception thrown by finalizer
E/System  (26587): java.lang.SecurityException: Need BLUETOOTH permission: Neither user 10746 nor current process has android.permission.BLUETOOTH.
E/System  (26587): 	at android.os.Parcel.createException(Parcel.java:2071)
E/System  (26587): 	at android.os.Parcel.readException(Parcel.java:2039)
E/System  (26587): 	at android.os.Parcel.readException(Parcel.java:1987)
E/System  (26587): 	at android.bluetooth.IBluetoothManager$Stub$Proxy.unregisterStateChangeCallback(IBluetoothManager.java:582)
E/System  (26587): 	at android.bluetooth.BluetoothHeadset.close(BluetoothHeadset.java:452)
E/System  (26587): 	at android.bluetooth.BluetoothHeadset.finalize(BluetoothHeadset.java:462)
E/System  (26587): 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:294)
E/System  (26587): 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:281)
E/System  (26587): 	at java.lang.Daemons$Daemon.run(Daemons.java:142)
E/System  (26587): 	at java.lang.Thread.run(Thread.java:919)
E/System  (26587): Caused by: android.os.RemoteException: Remote stack trace:
E/System  (26587): 	at android.app.ContextImpl.enforce(ContextImpl.java:1930)
E/System  (26587): 	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:1958)
E/System  (26587): 	at com.android.server.BluetoothManagerService.unregisterStateChangeCallback(BluetoothManagerService.java:640)
E/System  (26587): 	at android.bluetooth.IBluetoothManager$Stub.onTransact(IBluetoothManager.java:303)
E/System  (26587): 	at android.os.Binder.execTransactInternal(Binder.java:1032)
E/System  (26587): 
D/skia    (26587): --- Failed to create image decoder with message 'unimplemented'
D/PhoneWindow(26587): setNavigationBarColor: ff000000
E/FlutterFcmService(26587): Fatal: failed to find callback
W/System  (26587): Ignoring header If-None-Match because its value was null.
