### ISSUE TITLE
Playlist Error

### ISSUE THREAD

**Issue by madsters** [florent37/Flutter-AssetsAudioPlayer#271]
**Flutter Version**

My version : 1.17.5

**Lib Version**

My version : 2.0.7+8

**Platform (Android / iOS / web) + version**

Platform : iOS 13

**Describe the bug**

I'm trying to play a radio livestream, but every time I get an error: 
```
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <D7ADF486-2086-4FFE-BCA6-2EF89DE54358>.<1>, NSUnderlyingError=0x6000036e1d70 {Error Domain=kCFErrorDomainCFNetwork Code=-1022 "(null)"}}
flutter: PlatformException(PLAY_ERROR, Cannot play http://stream.lohro.de:8000/lohro.mp3.m3u, The operation could not be completed)
```

**Small code to reproduce**

```dart
import 'package:assets_audio_player/assets_audio_player.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State {
  
  final AssetsAudioPlayer _assetsAudioPlayer = AssetsAudioPlayer();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: RaisedButton(
            child: Text("open"),
            onPressed: () {
              _assetsAudioPlayer.open(Audio.liveStream(
                  "http://stream.lohro.de:8000/lohro.mp3.m3u"));
            }
          ),
        ),
      ),
    );
  }
}
```

**Comment by florent37** [comment]
did you add the transport security infos into your info.plist ?

```
<key>NSAppTransportSecurity</key>
<dict>
<key>NSAllowsArbitraryLoads</key>
<true/>
</dict>
```

**Comment by madsters** [comment]
Yes, but then I get an error, that my can‘t get compiled. Where exactly do I have to put those security infos?

**Comment by florent37** [comment]
In your ios/Runner/info.plist

**Comment by madsters** [comment]
yes, I know this. But when copying and pasting into this file I am getting an error. Where exactly in the file do I have to put those lines? My current info.plist (without any changes) can be found [here](https://pastebin.com/7WWY6EpN).
Sorry, I'm new to Flutter and Dart. I knew it since this morning.

**Comment by madsters** [comment]
Ok, problem solved. Thanks
