### ISSUE TITLE
BUG - Player interact with other audio app

### ISSUE THREAD

**Issue by Alusio** [florent37/Flutter-AssetsAudioPlayer#272]
Bonjour,

Je viens de remarquer que lorsqu'une autre application audio est déjà lancée (Exemple Spotify).
Quand l'application avec le plugin se lace. Les deux audio sont superposés.
Lorsque je mets en pause l'audio. Cela va mettre en pause l'audio de l'app et de Spotify.

Y - t-il un solution ?

Merci d'avance ;)

**Comment by florent37** [comment]
bonjour, es-tu sur ios ? 

(j'imagine que oui, c'est le système de audioSession qui est un peu chiant à gérer)

**Comment by Alusio** [comment]
Nan je suis sur Android :/

**Comment by florent37** [comment]
Ah sur Android c'est pas normal ça, je vais voir !

**Comment by florent37** [comment]
alors ça va te faire rire mais c'est la fonctionnalité "stop when call" qui en fait fait appel au focus

il faut que tu utilise `phoneCallStrategy: PhoneCallStrategy.none,` dans ton open pour la désactiver, tu peux essayer ?

**Comment by florent37** [comment]
teste avec la `2.0.8+2` 

bon par contre comme c'est un soucis de focus, va falloir trancher entre le fait de ne pas arr$eter le son pendant les appels ou jouer en parallele de spotify :)

**Comment by Alusio** [comment]
J'ai testé (avec un peu de retard). Merci ;)
