### ISSUE TITLE
Please Add Pause And Resume To Play Local Asset

### ISSUE THREAD

**Issue by akmalviya03** [florent37/Flutter-AssetsAudioPlayer#274]
I have been using this package from last 4 months. This helped me to build some beautiful applications using flutter. The package is lacking of some features like a resume, It has pause feature but when I try to play the same audio from where It was paused. Audio starts to play from 0.0 secs. Thank you for building this package.

**Comment by florent37** [comment]
can you send me the code you are using ?

it hase a play/pause feature, but maybe you just call two time the `open` method ?

**Comment by florent37** [comment]
oh Maybe I found it, are you using a loop mode  ?

**Comment by florent37** [comment]
the resume is present in the player, can you send me the code you're using please ?

**Comment by akmalviya03** [comment]
I'm was testing this plugin and I got this code from documentation. I changed 1.mp3 with the song available in my assets/audio folder. But I was only able to found play(),playorpause(),stop() method. I was getting confused, which method to call to pause or resume music. Because documentation has only three methods. Sorry, for the late response.

final assetsAudioPlayer = AssetsAudioPlayer();

assetsAudioPlayer.open(
    Audio("assets/audios/song1.mp3"),
);


assetsAudioPlayer.playorpause(); //This method starts song from duration 0 seconds instead of where I left.

**Comment by florent37** [comment]
for your usecase you have to save the currentPosition of your audio

you can use 
assetsAudioPlayer.currentPosition.listen((position) {
      //save
})

and the next step open it with the saved position

assetsAudioPlayer.open(
      Audio("assets/audios/song1.mp3"),
      seek: //your position
);
