### ISSUE TITLE
Support for stream 301 redirect

### ISSUE THREAD

**Issue by markturnip** [florent37/Flutter-AssetsAudioPlayer#275]
This works great with m3u8 & aacp.

However I can't seem to get it to stream my m4a format:
http://media.emit.com/pbs/tomorrow-land/202005081300/aac_mid.m4a

**Comment by markturnip** [comment]
Ah seems it's due to this url being a 301 redirect.

**Comment by florent37** [comment]
are you on android or ios ? (or other plattform)

**Comment by markturnip** [comment]
Android. I have a feeling it will work since `AVPlayer` works with redirect URLs.

**Comment by florent37** [comment]
On Android I added the `allowCrossProtocolRedirect` on exoplayer as mentioned in the official documentation 

(the allowCrossProtocol)

```
val allowCrossProtocol = true
                    val dataSource = DefaultHttpDataSource(userAgent, DefaultHttpDataSource.DEFAULT_CONNECT_TIMEOUT_MILLIS, DefaultHttpDataSource.DEFAULT_READ_TIMEOUT_MILLIS, allowCrossProtocol, null)              
```

https://exoplayer.dev/troubleshooting.html

**Comment by florent37** [comment]
what's the format of your `m4a` ? Dash, Hls, smoothstream or default ?

**Comment by florent37** [comment]
what's your version ? of the library ?

**Comment by florent37** [comment]
I succeed to play your url inside my sample `main_livestream.dart` on Android in the last version, can you check ?
