### ISSUE TITLE
Stop / restart playing the file with AudioWidget

### ISSUE THREAD

**Issue by lucasjbyoung** [florent37/Flutter-AssetsAudioPlayer#276]
It would be great to be able to stop / restart playing the audio from within the AudioWidget

**Comment by liuchuancong** [comment]
You can use 

```
 assetsAudioPlayer.seek(Duration(minutes: 0, seconds: 0, hours: 0))    
```

**Comment by florent37** [comment]
the behavior for a audio widget is different

to stop : remove it from the widget tree

to restart, re-add it into the widget tree (or with a different key)
