### ISSUE TITLE
Duration for each song in playlist

### ISSUE THREAD

**Issue by merfire** [florent37/Flutter-AssetsAudioPlayer#279]
Is there any way to get duration of each song in playlist ? 
For example I have list of songs and I want to show the duration on the right side of each list item.
I only found duration of current song, I apologize if this is already implemented I really cound't find it.

**Comment by florent37** [comment]
the duration is fetched only when the audio is opened :/ 


maybe with creating a player for each item and using "autoStart" false you can fetch them, but they will not be in the same playlist unfortunately

**Comment by merfire** [comment]
Thanks for the answer. I will probably use Meta extra field and add duration manually, because I have only 10 songs and this won't be a problem. I was just curious if this feature already existed.
