### ISSUE TITLE
IOS: published application. 

### ISSUE THREAD

**Issue by Zhogolev** [florent37/Flutter-AssetsAudioPlayer#280]
**Flutter Version**

My version : 1.17.5

**Lib Version**

My version : ^2.0.6+4

**Platform (Android / iOS / web) + version**

Platform :  Ios

**Xcode Version**

My version: 11.5

**Describe the bug**

On distribution version of application.
If to start playing audio, then pause, then go to launch(home) screen, then got to the application. Audio start playing

On version launched from xcode after application resumed, audio kept pause.

**Comment by florent37** [comment]
can you try with 2.0.8 ?

**Comment by kalismeras61** [comment]
No issue right now. Closing.
