### ISSUE TITLE
Player Plays audios simultaneously isntead of stopping the first

### ISSUE THREAD

**Issue by ashishfeels** [florent37/Flutter-AssetsAudioPlayer#282]
Hello @florent37 I implemented this awesome package but when i try to play something it plays and when i play another audio instead of stopping it and playing the recent audio it starts playing parallely. Is this a bug or is there anything im missing.
im using to play a livestream.

do i need to call dispose before playing new stream ?
Also how can i set meta when im playing a live stream ?

**Comment by ashishfeels** [comment]
probably related to #277 observing same behaviour . creates news instance when played next song quickly.

**Comment by liuchuancong** [comment]
Can you named with id?

**Comment by ashishfeels** [comment]
yes i tried initializing the player with a named id

**Comment by florent37** [comment]
can you try with `2.0.8` I fixed #277 maybe it will fix yours too

**Comment by ashishfeels** [comment]
yes will try and report back Thanks
