### ISSUE TITLE
[ Bug ] [ Android ] Album Art returns null on Android 10

### ISSUE THREAD

**Issue by mahadydev** [florent37/Flutter-AssetsAudioPlayer#283]
Platform :  Android

Hi ,

In android 10 , The meta Image path is not working . Works fine in android 9 or less. And its seems like the flutter_audio_query package from pub.dev is also broken. I can't get any image from album art in api29. Is it because album_art deprecated starting from api 29 ?
Is there anyway to call `contentResolver. loadThumbnail and get the bitmap in dart file from platform channel? I am not a native expert. Help me out brother.

Regard

**Comment by florent37** [comment]
thanks for the issue

are you talking about ab album art from local file, network or asset ?

**Comment by mahadydev** [comment]
Hi thanks for response.  
I am talking about metas inside the Audio file. Usually we have meta datas in a audio file right? 

let me reproduce my code :
  //Play a song
 ``` playSingleSong(SongInfo songInfo) {
    assetsAudioPlayer.open(
      Audio.file(
        songInfo.filePath,
        metas: Metas(
          title: songInfo.title,
          artist: songInfo.artist,
          album: songInfo.album,
          image: MetasImage.file(songInfo.albumArtwork),
        ),
      ),
      playInBackground: PlayInBackground.enabled,
      showNotification: true,
      notificationSettings: NotificationSettings(),
    );

    notifyListeners();
  }```

So the "image: MetasImage.file(songInfo.albumArtwork)" option return the album art file path . It works every device under android 10 but in android 10 it returns null

**Comment by mahadydev** [comment]
I am using flutter_audio_query  package to get all the information about song title , artist , album , image etc. maybe thats their package limitation which is not supporting android 10.  I'll check on them too.

**Comment by florent37** [comment]
Ok I see, maybe android 10 needs a content provider to fetch images from file (sdcard) ? 

I'll see if I find something about it, can you try to help me finding some source about it ?

**Comment by florent37** [comment]
I added some code to parse the content uri on android, can you try the `2.0.8+3` please ? and send me the result if it not work, I did not succeed to reproduce with the library & my device, maybe it has been fixed ?
