### ISSUE TITLE
assetsAudioPlayer.next(keepLoopMode: true)  not Work

### ISSUE THREAD

**Issue by liuchuancong** [florent37/Flutter-AssetsAudioPlayer#285]
```
etc.
```

**Comment by florent37** [comment]
what behavior do you have ?

can you send me you code ? (including the open method)

**Comment by liuchuancong** [comment]
if(currentPosition > 0)
The first time currentPosition  = 0
The second  time execute  assetsAudioPlayer.next()
assetsAudioPlayer.next()  Need to execute twice

**Comment by liuchuancong** [comment]
jsut run 
```
Future<void> next() async {
    await assetsAudioPlayer.next(keepLoopMode: true);
  }
```

**Comment by liuchuancong** [comment]
![乐秀视频第22部_20200713183615618](https://user-images.githubusercontent.com/36957912/87295488-d83d7180-c537-11ea-8217-c7394326cc95.gif)

**Comment by florent37** [comment]
I'm on it !

**Comment by liuchuancong** [comment]
Yes i can see you :)

**Comment by liuchuancong** [comment]
I taped toggleButton and  taped next button not work,
i jsut  run 
```
Future<void> next() async {
    await assetsAudioPlayer.next(keepLoopMode: true);
  }
```

**Comment by liuchuancong** [comment]
if  currentPosition > 0   like:  0:43   
if you  taped  prevButton    currentPosition  first time  currentPosition  will  be 0:00 .  
and taped again, it will run `assetsAudioPlayer.prev(keepLoopMode: true);`


if currentPosition  equles 0:00,and then drag  seekbar  currentPosition > 0,  it will repeat

**Comment by florent37** [comment]
before 3sec I assume that pressing prev will reset the song

**Comment by florent37** [comment]
like all media players (eg: spotify)

**Comment by florent37** [comment]
for next I try to reproduce but it seems to work, and keep the signle loop mode while pressing next

**Comment by liuchuancong** [comment]
why not jump to previous song？

**Comment by liuchuancong** [comment]
In my opinoin, I think  when keep the signle loop model, click nextButton  or  pervButton,will restat current song,maybe it's my mistake,thank you

**Comment by liuchuancong** [comment]
can you add  LoopModel.Random model？
