### ISSUE TITLE
Background Play

### ISSUE THREAD

**Issue by jrmarkham** [florent37/Flutter-AssetsAudioPlayer#286]
First: Great plugin-- works very well. 

So on Android music will play in the background and iOS it doesn't. In the app, I am building a game I'd want it not to play in the background.

It would be useful to turn on/off but more importantly to turn off by default in Android.

**Comment by florent37** [comment]
You have on the open method a ''backgroundEnabled'' have you tried this ?

**Comment by florent37** [comment]
```enum PlayInBackground { enabled, disabledPause, disabledRestoreOnForeground } ```

**Comment by Srini-B** [comment]
I have this block but it stops completely when locked or minimised or switch to other apps. iOS v 13.5, flutter v1.17.5, plugin v ^2.0.7+9

![Annotation 2020-07-18 163133](https://user-images.githubusercontent.com/22414119/87851256-9ab05e00-c914-11ea-8739-a51a9f504d95.jpg)
