### ISSUE TITLE
PlatformException PLAY_ERROR on macOS

### ISSUE THREAD

**Issue by tsinis** [florent37/Flutter-AssetsAudioPlayer#287]
Hey @florent37! First I want to thank you for solving the Issue [#273](https://github.com/florent37/Flutter-AssetsAudioPlayer/issues/273), but now macOS have different problem:

**Flutter Version**

My version :  1.19-1.20

**Lib Version**

My version : 2.0.8

**Platform (Android / iOS / web) + version**

Platform : macOS (both 10.14.6 and 10.15.4)

**Describe the bug**

Unable to run any audio from the assets or network, but it works on other platforms. Here is the error from this repo's example:
<details>
  <summary>Exception has occurred.</summary>
PlatformException (PlatformException(PLAY_ERROR, Cannot play https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Music_for_Video/springtide/Sounds_strange_weird_but_unmistakably_romantic_Vol1/springtide_-_03_-_We_Are_Heading_to_the_East.mp3, The operation could not be completed))
</details>

**Small code to reproduce**

```
flutter channel master
flutter upgrade
flutter config --enable-macos-desktop
git clone https://github.com/florent37/Flutter-AssetsAudioPlayer.git
cd Flutter-AssetsAudioPlayer
cd example
rm -rf macos
flutter create .
flutter pub get
flutter run -d macos -v
```
App will run, but then try to play any song - Exception wil be thrown (stated above).

Thanks!

**Comment by florent37** [comment]
You have on the open method a ''backgroundEnabled'' have you tried this ?

**Comment by florent37** [comment]
I get it it was because I addeed nerwork headers :/ I push a new release for you

**Comment by florent37** [comment]
`2.0.8+1`
