### ISSUE TITLE
The plugin `assets_audio_player` requires your app to be migrated to the Android embedding v2

### ISSUE THREAD

**Issue by sahharYoucef** [florent37/Flutter-AssetsAudioPlayer#289]
The plugin `assets_audio_player` requires your app to be migrated to the Android embedding v2. Follow the steps on https://flutter.dev/go/android-project-migration and re-run this command.

is there any way to bypass this error , I'm not getting any problem when running , but I'm not able to run tests in my app .

**Comment by florent37** [comment]
I don't think so, I had to migrate to the v2, and it's not back compatible, sorry

**Comment by JeasonLaung** [comment]
add this meta in AndroidManifest.xml and this problem is resovled
`<meta-data
            android:name="flutterEmbedding"
            android:value="2" />`
