### ISSUE TITLE
Could not find assets_audio_player-Swift.h

### ISSUE THREAD

**Issue by kruseborn** [florent37/Flutter-AssetsAudioPlayer#29]
I am using version **^1.2.3**, it works on Windows using android, but I am getting this error when trying to build it on a mac.

```
=== BUILD TARGET assets_audio_player OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/tobbe/development/flutter/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-1.2.3/ios/Classes/AssetsAudioPlayerPlugin.m:2:9: fatal error:
    'assets_audio_player/assets_audio_player-Swift.h' file not found
    #import <assets_audio_player/assets_audio_player-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
```

**Comment by manojchandrashekar** [comment]
I am facing this issue as well.

**Comment by florent37** [comment]
can you try with the 1.2.4 ?

it it's not fixed, I will need some help, I don't know how to fix an xcode error like that :/

**Comment by manojchandrashekar** [comment]
I managed to solve this by -

1. Delete the ios folder and recreate it with -swift option.

`rm -rf ios && flutter create -i swift .`

2. Modify the Podfile to change swift version for this plugin as mentioned here - https://github.com/florent37/Flutter-AssetsAudioPlayer/issues/1#issuecomment-471976498

**Comment by comlaterra** [comment]
Actually, you just need to make sure you are using swift 4.2 in your `pbxproj`.
( remove and re-create the iOS project can be a mess if you'd changed anything manually )
