### ISSUE TITLE
Next & Prev on Notifications recreates the Player Instance

### ISSUE THREAD

**Issue by ashishfeels** [florent37/Flutter-AssetsAudioPlayer#290]
Click on Notification (next & previous) creates new instance of player resulting parallelly playing two audios.
 mentioning #277

**Comment by ashishfeels** [comment]
clicked close by mistake

**Comment by johnny-stevie** [comment]
Happens with me too.

**Comment by ashishfeels** [comment]
Found another scenario where tapping play button multiple times while its stream is buffering also creates new instance.  @johnny-stevie can you also verify this. This will help in solving this issue once in for all.

**Comment by johnny-stevie** [comment]
I can confirm that spamming next or prev on notification bar is another way to invoke the bug from my side

**Comment by ashishfeels** [comment]
@johnny-stevie can you check this fork if this fixes the issue for you ? also check with playlist, assets if it works please tell me i will create a PR to this repo

https://github.com/ashishfeels/Flutter-AssetsAudioPlayer

**Comment by johnny-stevie** [comment]
This is fantastic!!! Completely solves the problem for next() and prev() on network songs. I haven't extensively tested assets audio but from what I've encountered, this bug only occurred with network songs and none that are local like in storage or assets. Thank you very much!!! Can somebody else confirm this to corroborate my testing?

**Comment by ashishfeels** [comment]
@johnny-stevie thanks will wait for some more time to see if someone else can confirm and then i will create the PR

**Comment by johnny-stevie** [comment]
I've tested playlists with local, network and assets Audios. play(),next(),prev() work like a charm!

**Comment by ashishfeels** [comment]
@johnny-stevie thanks for the confirmation livestream also works fine i will create a PR then, Thanks mate.

**Comment by florent37** [comment]
it's published in `2.0.8+4` ca you try ?

**Comment by florent37** [comment]
thanks to @ashishfeels 👍

**Comment by ashishfeels** [comment]
Welcome @florent37

**Comment by andynvt** [comment]
I still meet this bug on `^2.0.15` how can I fix it?

**Comment by andynvt** [comment]
> I still meet this bug with network playlist on `^2.0.15` how can I fix it?

Thank you this issue https://github.com/florent37/Flutter-AssetsAudioPlayer/issues/514
I solved it

```
bool enabled = true;
void onNext() async {
    if (enabled) {
      enabled = false;
      await _player.pause();
      await _player.next();
      enabled = true;
    }
  }
```

**Comment by andynvt** [comment]
> > I still meet this bug with network playlist on `^2.0.15` how can I fix it?
> 
> Thank you this issue #514
> I solved it in the dart code. But notification click still error
> 
> ```
> final _player = AssetsAudioPlayer();
> bool enabled = true;
> void onNext() async {
>     if (enabled) {
>       enabled = false;
>       await _player.pause();
>       await _player.next();
>       enabled = true;
>     }
>   }
> ```

Oh, actually I found it

```
await _player.open(
      Playlist(
        startIndex: index,
        audios: audios,
      ),
      loopMode: LoopMode.playlist,
      showNotification: true,
      notificationSettings: NotificationSettings(
        customNextAction: (_) => onNext(),
        customPrevAction: (_) => onPrev(),
      ),
    );
```
