### ISSUE TITLE
[Bug] [Android] dispatching onAudioFocusChange(-2)

### ISSUE THREAD

**Issue by Umarkamboh** [florent37/Flutter-AssetsAudioPlayer#293]
**Describe the bug**

audio is playing well but when i am going to next screen, (in next screen i am aslo using flutter sound plugin for recording purpose.), it stop playing audio and below errors pop up.

thanks, 

**Small code to reproduce**

```dart
dispatching onAudioFocusChange(-2) to android.media.AudioManager@2798f2acom.github.florent37.assets_audio_player.stopwhencall. StopWhenCallAudioFocus$sam$i$android_media_AudioManager_OnAudioFocusChangeListener$0@a635560
```

**Comment by florent37** [comment]
I don't know how to fix it, I don't have any clue to know what's wrong :/

**Comment by kalismeras61** [comment]
Please use latest version.
