### ISSUE TITLE
Different Volume silders/panel for Different Songs played Simultaneously or in Parallel? [help wanted]

### ISSUE THREAD

**Issue by singlesoup** [florent37/Flutter-AssetsAudioPlayer#294]
Hey, this is an amazing plugin. I use it extensively.

So I don't know if this feature already exists or not and also its not a bug so posting here.
It would be amazing if we could **change or control the volume of each different songs played simultaneously**. If we can already do it , would you point me to where I could implement this?

I would be waiting for your response. Thanks !

**Comment by johnny-stevie** [comment]
You can monitor playlist indexes and change the corresponding audio player to the volume you want
`int songIndexToChangeVolume = 5;
  double volumeLevel = 0.5;
  _assetsAudioPlayer.current.listen(playing){
  if(playing.playlist.index==songIndexToChangeVolume)
   _assetsAudioPlayer.setVolume(volumeLevel);
}`

**Comment by singlesoup** [comment]
This is great, but does it also work with` AssetsAudioPlayer.newPlayer().open();` ? 

![volume](https://user-images.githubusercontent.com/54581715/88366915-10e71180-cda8-11ea-8e28-4fd5751cdf5e.jpg)

Slider is something that we can implement on our end to change the volume dynamically. But what I am looking for is to access the volume of the tracks which are playing simultaneously to be able to change them like the image above. Can we do it?

**Comment by florent37** [comment]
yes each player have a volume method


and on the `open` method you also have a volume parameter ;) 

the system volume is different, and it's not impacted by the audio player

can you try the `setVolume` method and `open(audio, volume: 0.5)` ?
