### ISSUE TITLE
[Android] Is there a way to resume audio (like Spotify) after my player is done?

### ISSUE THREAD

**Issue by savioPimenta** [florent37/Flutter-AssetsAudioPlayer#295]
I have an app that has to stop the current music in a interval of 15 minutes, play an audio and (when the player is done) resume the native player after finishing playback.
My app is working except for this feature.

**Comment by johnny-stevie** [comment]
@savioPimenta Do you mean like respectAudioFocus? Stop the audio when another app has audio running and start again when it's finished. Is that what you mean?

**Comment by savioPimenta** [comment]
Exactly! Do you know how i can do this?

**Comment by johnny-stevie** [comment]
No clue, sorry. I have been wanting this new feature to be added too but I'm not very savvy with native code. If you are on Android there is this audio player package that's not as good as FlutterAssetsAudioPlayer but it nicely implements this feature. If you are good with native code you can copy some parts that are related to the respectAudioFocus feature as its called in the package. This is the package. The native code is written in java.
[https://github.com/danielR2001/flutter_exoplayer](url)

**Comment by ashishfeels** [comment]
This can be implemented i saw the code and found that it's already there probably not if other player is playing some music, but if you are on call for 15 minutes or so it will resume. playing after call is disconnected. @johnny-stevie @savioPimenta. I have to look more btw.

**Comment by surpriso1997** [comment]
> 
> 
> I have an app that has to stop the current music in a interval of 15 minutes, play an audio and (when the player is done) resume the native player after finishing playback.
> My app is working except for this feature.
I think you are talking about desktop spotify playing some ads after playing music for certain amount of time , and resuming music after ads completes. If then it might work for you.

I think you can do like this.
1. When you start playing your first audio , fire a timer for 15 minutes, OR if your tracks durations are longer than 15 minutes you can simply observe the duration of track with AssetsAudioPlayer's realTimePlayingInfos stream. 
2. At 15 minutes mark, pause the currently playing audio.    Create another AsssetAudiPlayer's instance and play the second audio. 
3. When the second audio completes, pause/stop , the audio player instance you created for playing this second audio. 
4. Resume your older audio player.

**Comment by ashishfeels** [comment]
this has to be done in native code, have to check the player hasAudioFocus if true then play the current track/song

**Comment by florent37** [comment]
when the asset native player open a song, to be exact, when he fire a "play, it request an audio focus (to be interrupted on phone call)

but I don't know how to tell to the audio player to resume, someone help ?

**Comment by ashishfeels** [comment]
@florent37 i will try to look into and if i found something will update here. i was going through the native code, but kotlin limits me :D

**Comment by ashishfeels** [comment]
@florent37 This may help https://stackoverflow.com/questions/54326310/how-to-pause-video-when-other-app-play-music-and-resume-once-the-music-stops

Also we can have listener when the interruption happens to control the playback this will be a nice additon.

**Comment by savioPimenta** [comment]
I managed to make it work in native code. After the asset_audio_player is done, i call a native function to resume the main player. The code used: `val intent = Intent("com.android.music.musicservicecommand");
                        intent.putExtra("command", "play");
                        sendBroadcast(intent);` I just virtually pressed play.

**Comment by ashishfeels** [comment]
you can create a repo so that we can test. and if all goes well you can create a PR

**Comment by florent37** [comment]
yes it seems to be great

https://stackoverflow.com/questions/14910360/how-to-play-or-resume-music-of-another-music-player-from-my-code

but I have to make it optional, maybe some users don't want to reesume other players, AND we cannot know if others players are playing

maybe using 

```
Intent i = new Intent("com.android.music.musicservicecommand.togglepause");
i.putExtra("command", "togglepause");
sendBroadcast(i);
```

**Comment by florent37** [comment]
but where I add it ? inside a new method ?

like `player.resumeOthersPlayers()` ?

**Comment by florent37** [comment]
```
_subscriptions.add(_assetsAudioPlayer.playlistAudioFinished.listen((data) {
      _assetsAudioPlayer.resumeOthersPlayers();
}));
```

**Comment by ashishfeels** [comment]
this is for assetAudio player to start playing after some interuption right ? @florent37

**Comment by florent37** [comment]
This is to tell to others players like "spotify" to play

**Comment by florent37** [comment]
but I don't know if this will not "resume" the current player :/

**Comment by ashishfeels** [comment]
oh. cool got it thanks i was confused sorry.

**Comment by florent37** [comment]
I think I will rename the stopWhenCall to "audioFocus" and add a usecase to tell "I take the audio focus, then resume others"

**Comment by ashishfeels** [comment]
also i  found one issue should i create an issue?
whenever network goes for asset player it gets notifies about the network
and player stops and if the network is back then it does not work i have to start the app again

**Comment by ashishfeels** [comment]
> I think I will rename the stopWhenCall to "audioFocus" and add a usecase to tell "I take the audio focus, then resume others"

can you also expose a variable that would notify whether the audiofocus has changed this will allow custom config for players.

**Comment by florent37** [comment]
on iOS I cannot be notified :/

**Comment by ashishfeels** [comment]
> on iOS I cannot be notified :/

yes unfortunately some features are for android

**Comment by ashishfeels** [comment]
> also i found one issue should i create an issue?
> whenever network goes for asset player it gets notifies about the network
> and player stops and if the network is back then it does not work i have to start the app again

i can send you my app which im trying out with assetaudio playeryou can check

**Comment by florent37** [comment]
for now I have ```enum PhoneCallStrategy { none, pauseOnPhoneCall, pauseOnPhoneCallResumeAfter }```

I'm thinking of 
```dart
AudioFocusStrategy.none, //don't do anything
AudioFocusStrategy.take(), //pause others players
AudioFocusStrategy.take(resumeAfterInterruption: true), //pause others native players, if phone call, pause, then resume the asset player
AudioFocusStrategy.take(resumeAfterInterruption: true, resumeOthersPlayersAfterDone: true),  //pause others native players, if phone call, pause, then resume the asset player, when the audio finished, resume others native players
```

**Comment by ashishfeels** [comment]
> for now I have `enum PhoneCallStrategy { none, pauseOnPhoneCall, pauseOnPhoneCallResumeAfter }`
> 
> I'm thinking of
> 
> ```dart
> AudioFocusStrategy.none, //don't do anything
> AudioFocusStrategy.take(), //pause others native players
> AudioFocusStrategy.take(resumeAfterInterruption: true), //pause others native players, if phone call, pause, then resume the asset player
> AudioFocusStrategy.take(resumeAfterInterruption: true, resumeOthersPlayersAfterDone: true),  //pause others native players, if phone call, pause, then resume the asset player, when the audio finished, resume others native players
> ```

this seems good

**Comment by florent37** [comment]
I addd this in a merge request but did not try for now, just finished to develop it

**Comment by ashishfeels** [comment]
cool @florent37  also will there be any modification on network error issue ? i have to restart the app again to play audio.

**Comment by florent37** [comment]
create another merge request for this @ashishfeels

**Comment by florent37** [comment]
fixed in `2.0.9`

**Comment by florent37** [comment]
```
await _assetsAudioPlayer.open(
                            myAudio,
                            audioFocusStrategy: AudioFocusStrategy.request(
                              resumeAfterInterruption: true,
                              resumeOthersPlayersAfterDone: true
                            ),

```

**Comment by ashishfeels** [comment]
Thanks @florent37 you are awesome man.

**Comment by ro1pixel** [comment]
> await _assetsAudioPlayer.open(
>                             myAudio,
>                             audioFocusStrategy: AudioFocusStrategy.request(
>                               resumeAfterInterruption: true,
>                               resumeOthersPlayersAfterDone: true
>                             ),

This does not work for me
iOS 15.0

anyone got this to work?

**Comment by nietsmmar** [comment]
This is not working for me on iOS 14.7.1. Am I the only one?

**Comment by daveshirman** [comment]
Was trying to get this to work today too, but it doesn't resume the other app's playback.

@florent37 Hi, please could you respond with how we can get this working?

Your work is MUCH appreciated + a donation coming your way I promise!
