### ISSUE TITLE
App shows only one notification

### ISSUE THREAD

**Issue by surpriso1997** [florent37/Flutter-AssetsAudioPlayer#298]
**Flutter Version**

My version : .1.17.5

**Lib Version**

My version : 2.0.6+3

**Platform (Android / iOS / web) + version**

Platform : android

**Describe the bug**

I have implemented both standard AssetsAudioPlayer  and AssetsAudioPlayerGroup in my app for separate features. I have enabled notifications for both them. When I play audio with either of them, notifications appear as expected but when audios are played with both of those audios, only one notiification appears (player which is played later). 
Is this the intended behaviour of the package?

Not entirely related but, I have a feature to download files in the app, if I start downloading a file, AssetsAudioPlayer's notification is replaced with the downloder's.

**Small code to reproduce**

Asset audio player group:
```
 AssetsAudioPlayerGroup group;

   group = AssetsAudioPlayerGroup(
      showNotification: true,
      notificationStopEnabled: true,
      playInBackground: PlayInBackground.enabled,
      onNotificationOpened: (g, a) {
        print("notification opened");
      },
      onNotificationPause: (g, a) {
        group.pause();
      },
      onNotificationPlay: (g, a) {
        group.play();
      },
      onNotificationStop: (g, a) {
        playingIds.value.clear();
        playingItemsListStream.add([]);

        group.stop();
      },
      updateNotification: (g, a) async {
        return PlayerGroupMetas(
          title: "Group 1",
          subTitle: "this is group plauing",
          image: MetasImage.asset(placeholder_image),
        );
      },
    );

```
AssetsAudioPlayer  stanadard:
```

   try {
        await assetsAudioPlayer
            .open(
          playlist.value,
          showNotification: true,
          autoStart: true,
          loopMode: isFromPlaylist ? LoopMode.none : LoopMode.single,
          playInBackground: PlayInBackground.enabled,
          notificationSettings: NotificationSettings(
            customStopAction: (_) {
              playingAudio.value = null;
              assetsAudioPlayer?.stop();
            },
            customPrevAction: seekRewindSinglePlayer,
            customNextAction: seekForwardSinglePlayer,
          ),
        )
            .catchError((error) {
          stopPlayer();

          //  print("error on player is::: $error");
        });
      } on PlatformException catch (e) {
        stopPlayer();
        //  print("error on player is::: $e");
      }
```

**Comment by florent37** [comment]
Oh I see, mmm maybe It's because they have the same notification ID, 
but I think i'ts more complicated than just this, I'll try to investigate and make them work in paralleel

**Comment by kalismeras61** [comment]
Closed due to no update from user.
