### ISSUE TITLE
Custom action when pressing on notification

### ISSUE THREAD

**Issue by sahharYoucef** [florent37/Flutter-AssetsAudioPlayer#299]
Hi
can you a custom action when pressing on notification like opening special route or run a function;

**Comment by ashishfeels** [comment]
its already there @sahharYoucef i guess please check the documentation.

**Comment by sahharYoucef** [comment]
> its already there @sahharYoucef i guess please check the documentation.

Not notification icons, I'm talking about the notification panel, when you press on it open the app, i want to open custom route

**Comment by ashishfeels** [comment]
will have to check.

**Comment by surpriso1997** [comment]
> 
> 
> > its already there @sahharYoucef i guess please check the documentation.
> 
> Not notification icons, I'm talking about the notification panel, when you press on it open the app, i want to open custom route

```
AssetsAudioPlayer.setupNotificationsOpenAction( (notitifcaiton{}); 

```
Works on android not sure on ios.

**Comment by ashishfeels** [comment]
> > > its already there @sahharYoucef i guess please check the documentation.
> > 
> > 
> > Not notification icons, I'm talking about the notification panel, when you press on it open the app, i want to open custom route
> 
> ```
> AssetsAudioPlayer.setupNotificationsOpenAction( (notitifcaiton{}); 
> ```
> 
> Works on android not sure on ios.

this is probably not written in docs. please correct me if i'm wrong

**Comment by surpriso1997** [comment]
@ashishfeels This was sent  as a PR by @Timus23 and florent modified naming and stuff.
I think it is present in one of the example files.

**Comment by florent37** [comment]
yes sorry it's not on the readme

but @Timus23 send me a PR to handle this, 

you have a callback for this, you can see the `main.dart`

it's using 

`AssetsAudioPlayer.setupNotificationsOpenAction(CALLBACK);`

**Comment by florent37** [comment]
only on android :'(

**Comment by ashishfeels** [comment]
@florent37 i will update the docs.

**Comment by florent37** [comment]
I added this in README

## Handle notification click (android)

Add in main 
```dart
AssetsAudioPlayer.setupNotificationsOpenAction((notification) {
    //custom action
    return true; //true : handled, does not notify others listeners
                 //false : enable others listeners to handle it
});
```

Then if you want a custom action on widget

```dart
AssetsAudioPlayer.addNotificationOpenAction((notification) {
   //custom action
   return false; //true : handled, does not notify others listeners
                 //false : enable others listeners to handle it
});
```
