### ISSUE TITLE
Support duration on HLS/DASH live stream with m3u8

### ISSUE THREAD

**Issue by dfdgsdfg** [florent37/Flutter-AssetsAudioPlayer#300]
Some live stream can have duration like just static mp3 file on network.

Here is some example for duration with m3u8.

https://github.com/globocom/m3u8/issues/136

**Comment by ashishfeels** [comment]
Already Supported Check the Docs. @dfdgsdfg

**Comment by dfdgsdfg** [comment]
Oh. I think to find some mistake form document.  Maybe only live stream works like below?

Anyway just thank you so much for your perfect works. It is just wonderful. 

Thank you. 💯 💯 💯 💯 💯  


#### 🎵 Current song
```dart
//The current playing audio, filled with the total song duration
assetsAudioPlayer.current //ValueObservable<PlayingAudio>

//Retrieve directly the current played asset
final PlayingAudio playing = assetsAudioPlayer.current.value;

//Listen to the current playing song
assetsAudioPlayer.current.listen((playingAudio){    
    final asset = playingAudio.assetAudio; 
    final songDuration = playingAudio.duration;      // ------> seems to change playingAudio.audio.duration 
})
```

#### ⌛ Current song duration
```dart
//Listen to the current playing song
final duration = assetsAudioPlayer.current.value.duration;    // ------> seems to change playingAudio.current.audio.duration
```

**Comment by ashishfeels** [comment]
`final assetsAudioPlayer = AssetsAudioPlayer();

try {
    await assetsAudioPlayer.open(
        Audio.liveStream(MY_LIVESTREAM_URL),
    );
} catch (t) {
    //stream unreachable
}`

Like This

**Comment by danybuoy** [comment]
Hi there, really enjoying this plugin - it's quite handy. I'm also running into the problem where when streaming an HLS file it seems like the player is unable to determine the total duration of the stream (which can be derived from multiplying the number of segments with the duration of the current segment)

**Comment by dfdgsdfg** [comment]
Seems android exoplayer does not support m3u8.

https://github.com/google/ExoPlayer/issues/4066
