### ISSUE TITLE
Error handler in AssetsAudioPlayerGroup

### ISSUE THREAD

**Issue by surpriso1997** [florent37/Flutter-AssetsAudioPlayer#303]
**Describe the feature you'd like**
Error handler (onErrorDo) was added in standard AssetsAudioPlayer but , it doesn't exist in AssetsAudioPlayerGroup's add function.
Right now there is no way to catch Platform Exceptions in AssetAudioPlayerGroup().add().

**Comment by florent37** [comment]
published in 2.0.8+5 =)
