### ISSUE TITLE
Disable output to debug console

### ISSUE THREAD

**Issue by johnareid54** [florent37/Flutter-AssetsAudioPlayer#306]
Would it be possible to disable the output being sent to the debug console?
The player seems to be working fine, but it is really difficult to read any console outputs as it produces a lot of information:

> D/PlayerImplem( 7160): trying to open with exoplayer(Default)
> I/ExoPlayerImpl( 7160): Init c12a648 [ExoPlayerLib/2.11.4] [generic_x86, Android SDK built for x86, Google, 29]
> I/OMXClient( 7160): IOmx service obtained
> I/ACodec  ( 7160): codec does not support config priority (err -2147483648)
> D/AudioTrack( 7160): stop(524): called with 26496 frames delivered
> I/ExoPlayerImpl( 7160): Release c12a648 [ExoPlayerLib/2.11.4] [generic_x86, Android SDK built for x86, Google, 29] [goog.exo.core]

This may not seem like much, but my code is in a loop, playing the audio and then waits for two seconds before starting the loop again.

**Comment by johnareid54** [comment]
Thanks, Florent, your quick response is highly appreciated!

**Comment by phimath** [comment]
How do you disable the output?  I looked at the commit and the docs but don't see the API to disable console output.

**Comment by johnareid54** [comment]
@phimath How do you disable the output?
I used the code this morning, there was no output in the console window, which was the case before.
