### ISSUE TITLE
Audio laggy when app runs in background on Android

### ISSUE THREAD

**Issue by daniellampl** [florent37/Flutter-AssetsAudioPlayer#311]
**Flutter Version**

My version : v1.17.5

**Lib Version**

My version : 2.0.9

**Platform (Android / iOS / web) + version**

Platform : Android 10 (OnePlus 5)

**Describe the bug**

When I open a single audio from storage and start playing the file, everything seems to work as expected. But when I put the application in the background, the playing is very laggy and many dropouts. After reopening the application, the audio plays normally again.

**Comment by wershest** [comment]
Same problem on my OnePlus 5T, Android 10. 
I just upgraded the OS of my phone a few days ago. It seems like the issue only occurs on Android 10.
I wonder if this problem just appears when older phones upgrade to android 10.

**Comment by mob1solwin** [comment]
Same problem on Redmi 9. I played audio with max speed but when app goes to background it's play with normal speed and after move to foreground mode audio will again play with max speed.

**Comment by kalismeras61** [comment]
Can you try with latest commit. 

assets_audio_player:
git:
url: https://github.com/florent37/Flutter-AssetsAudioPlayer.git
ref: b49a4360f6a7f182d4a6e23ebcdbf43ad570913b

**Comment by mob1solwin** [comment]
It's working after upgrade to assets_audio_player: ^2.0.13
Thank you very much kalismeras61.

**Comment by kalismeras61** [comment]
Closing duee https://github.com/florent37/Flutter-AssetsAudioPlayer/issues/311#issuecomment-771411276
