### ISSUE TITLE
iOS Notification

### ISSUE THREAD

**Issue by AtixD** [florent37/Flutter-AssetsAudioPlayer#314]
**Flutter Version**

My version : 1.17.5

**Lib Version**

My version : 2.0.9+2

**Platform (Android / iOS / web) + version**

Platform : iOS

**Describe the bug**

Hi, when I start the playlist, and I have hided the  application -> in notification press next -> playlist has stopped. 
If i start the playlist, and I have hided the application -> in notification press pause -> in notification press play -> playlist has worked. 
Maybe, you know how fix it. Thanks.

Reproduce: https://yadi.sk/i/dOwZN07opcG9bg

**Small code to reproduce**

```dart
    await _audioPlayer.open(
      playlist,
      autoStart: true,
      headPhoneStrategy: HeadPhoneStrategy.pauseOnUnplugPlayOnPlug,
      playInBackground: PlayInBackground.enabled,
      showNotification: true,
      seek: seek,
      volume: 1,
    );
```

**Comment by kalismeras61** [comment]
I have also same issue. Even I tested with plugin example project it is working with emulator but doesnt work real device. Notification next, prev button doesn't work

**Comment by AtixD** [comment]
@florent37 After update 2.0.9+2 seek bar in ios doesn't work.

**Comment by kalismeras61** [comment]
@florent37  one more thing when app in background and playing playlist ( from url ) it is not going next song .

**Comment by kalismeras61** [comment]
#252

**Comment by florent37** [comment]
@AtixD I think I know why, it's because I use milliseconds now (maybe), I can fix it, but not sure it will fix all the issue :/ notifications on ios are buggy

**Comment by kalismeras61** [comment]
@florent37  any update ? @AtixD  did you find anything for playing songs on background ?

**Comment by AtixD** [comment]
@kalismeras61 Hi, no.
I haven't researched this yet

**Comment by AtixD** [comment]
@florent37 Hi, Do you have idea, how can I solve the problem?

**Comment by ThalapathySiva** [comment]
Hi @florent37  @AtixD  experiencing same issue any update?

**Comment by lawkeen** [comment]
Hello, @florent37 @AtixD @ThalapathySiva @kalismeras61 do you have any info about the seek bar fix is ios?

**Comment by kalismeras61** [comment]
it is fixed latest build. Please use it.
