### ISSUE TITLE
Is there difference Whats the difference between assets_audio_player and assets_audio_player_web

### ISSUE THREAD

**Issue by akshayru** [florent37/Flutter-AssetsAudioPlayer#318]
I found 2 packages and both looks similar assets_audio_player vs assets_audio_player_web. Is there any difference? I noticed assets_audio_player also play audio on web

**Comment by DomingoMG** [comment]
It's the same, I guess to indicate the platform

**Comment by florent37** [comment]
For now I had to separate the web code. Just import the assets audio player and if you're on web it will recursively import the _web
