### ISSUE TITLE
No support for Web？

### ISSUE THREAD

**Issue by AngusPei** [florent37/Flutter-AssetsAudioPlayer#32]
No support for Web

**Comment by florent37** [comment]
I really don't know how to make it usable for web,
I may need some help to do that

If someone know how to play a song using dart on web I will appreciate some help
or directly a merge request 😄

**Comment by florent37** [comment]
I set it as "help wanted"

**Comment by AngusPei** [comment]
ok...

**Comment by Tonne-TM** [comment]
I can't help implementing web, but it would be nice if the "web" badge on  [pub.dev](https://pub.dev/packages/assets_audio_player) could be removed. Because I implemented the library thinking it supports web.

**Comment by florent37** [comment]
it's currently in progress :)
