### ISSUE TITLE
playlistAudioFinished not being called on IOS simulator

### ISSUE THREAD

**Issue by johnareid54** [florent37/Flutter-AssetsAudioPlayer#329]
**Flutter Version**

My version : 1.20.1

**Lib Version**

My version : assets_audio_player: ^2.0.9

**Platform (Android / iOS / web) + version**

Platform : Mac OS X 10.15.6 19G73

**Describe the bug**

I copied the code (without any changes) from my windows pc to my MacBook. **AssetsAudioPlayer.PlaylistAudioFinished** works on the pc (Android simulator) but when used on the IOS simulator it is not being called. 
If I replace the call with **assetsAudioPlayer.playlistFinished** then it is called, but obviously it is before the audio is finished.
This is really puzzling, why would a change of operating systems make any difference to the APi? I am beginning to think that it could be my MacBook is the problem.

Note: Audio file being called is very small, less than 10k just one spoken word.
Edit: Tried the code this morning with a large 7 minutes audio file and it still did not call the PlaylistAudioFinished.

**Small code to reproduce**

 @override
  void initState() {
    playword() {
      _assetsAudioPlayer.open(Audio("assets/words/44.mp3"));
    }

    _assetsAudioPlayer.playlistAudioFinished.listen((data) async {
      await Future.delayed(const Duration(seconds: 2));
      _counter++;
      if (stop) return;
      print('counter: $_counter');
      playword();
    });

    playword();

    super.initState();
  }

**Comment by johnareid54** [comment]
I changed my code to a playlist including a 2 seconds blank file and used the loop command, which means I don't need to use the playListAudioFinished. This is working fine so no need to worry about this bug.

**Comment by luisra** [comment]
This issue is not limited to the simulator. On finished is not being called on iOS devices when using AudioWidget.

**Comment by yeeemayy** [comment]
> I changed my code to a playlist including a 2 seconds blank file and used the loop command, which means I don't need to use the playListAudioFinished. This is working fine so no need to worry about this bug. I also suspect that this bug may be hardware specific and therefore difficult to reproduce.

can you share about how do you use the loop command to replace playListAudioFinished? I am facing the same issue on both real device and simulator.

**Comment by johnareid54** [comment]
Sorry @yeeemayy 
I have had to stop using Assets Audio Player as the plugin  stopped working!
It is not @florent37 fault, the flutter team keep changing the goal posts!

If it is any help I am using soundpool (https://pub.dev/packages/soundpool) which is designed for playing short audio files - had no problems with it so far.

**Comment by yeeemayy** [comment]
I see, but I need the app to work on both Android and IOS, so soundpool is not a suitable option for me. Thanks anyway! :)

**Comment by johnareid54** [comment]
You asked for the code sample:

void playword(String file) {
  _assetsAudioPlayer.open(Playlist(audios: [Audio("assets/$file.mp3"), Audio("assets/audio/blank.mp3")]),
      loopMode: LoopMode.playlist);
}
