### ISSUE TITLE
playlistFinished and iOS Simulator bugs

### ISSUE THREAD

**Issue by lawkeen** [florent37/Flutter-AssetsAudioPlayer#340]
Flutter version:  Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.6 19G2021)

Lib version : assets_audio_player: ^2.0.9+2

Platform : iOS + 13.6

Hi, first is thank you for the package. I got three bugs, the first is notification doesn't show at iOS Simulator (maybe it'll work at device normally, but I can't test is, cause no have no iPhone). The second is, that playlistFinished is triggered with true then screen is disposed. I have a method, which opens the new screen then the audio has been finished, so then I going back 
playlistFinished is triggering and new screen trying to open and getting an error. And the third one is that playlistFinished triggers two times, I mean it opens two screens at once.

```
          _subscriptions.add(_player.playlistFinished.listen((data) {
            if (data) {
                openHomeWork(widget.lessonContent, context);
          }));
```

I will appreciate any advice. Thank you!

**Comment by kalismeras61** [comment]
Hello @lawkeen 
1- Apple remove RemoteCommandCenter simulation since iOS 11,
so i suggest you to use iOS 10.x simulator to debug RemoteCommandCenter. Otherwise you can use real device.
2- Use playlistAudioFinished stream for routing new page.
