### ISSUE TITLE
After playing several sound, audio stops working.

### ISSUE THREAD

**Issue by brice-fromentin** [florent37/Flutter-AssetsAudioPlayer#342]
**Flutter Version**

Flutter version : 1.20.2
Lib version : 2.0.9+2
Platform : Android

**Describe the bug**

After playing several sounds, the audio throws exception and stop working. Sometimes I need to restart the emulator.

I/OMXClient( 4733): IOmx service obtained
I/ACodec  ( 4733): codec does not support config priority (err -2147483648)
E/IAudioFlinger( 4733): createTrack returned error -12
E/AudioTrack( 4733): createTrack_l(0): AudioFlinger could not create track, status: -12 output 0
E/AudioTrack-JNI( 4733): Error -12 initializing AudioTrack
D/AudioTrack( 4733): gather(): no metrics gathered, track status=-12
E/android.media.AudioTrack( 4733): Error code -20 when initializing AudioTrack.
E/ExoPlayerImplInternal( 4733): Renderer error: index=1, type=audio, format=Format(null, null, null, audio/mpeg, null, -1, null, [-1, -1, -1.0], [2, 44100]), rendererSupport=YES
E/ExoPlayerImplInternal( 4733):   com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed: 0, Config(44100, 12, 44100)
E/ExoPlayerImplInternal( 4733):       at com.google.android.exoplayer2.BaseRenderer.createRendererException(BaseRenderer.java:359)
E/ExoPlayerImplInternal( 4733):       at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:831)
E/ExoPlayerImplInternal( 4733):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1590)
E/ExoPlayerImplInternal( 4733):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:721)
E/ExoPlayerImplInternal( 4733):       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599)
E/ExoPlayerImplInternal( 4733):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329)
E/ExoPlayerImplInternal( 4733):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal( 4733):       at android.os.Looper.loop(Looper.java:223)
E/ExoPlayerImplInternal( 4733):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal( 4733):   Caused by: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed: 0, Config(44100, 12, 44100)
E/ExoPlayerImplInternal( 4733):       at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.buildAudioTrack(DefaultAudioSink.java:1417)
E/ExoPlayerImplInternal( 4733):       at com.google.android.exoplayer2.audio.DefaultAudioSink.initialize(DefaultAudioSink.java:516)
E/ExoPlayerImplInternal( 4733):       at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:597)
E/ExoPlayerImplInternal( 4733):       at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:824)
E/ExoPlayerImplInternal( 4733):       ... 7 more

**Small code to reproduce**

[...]
  /// Stop & Dispose the current sound player
  _cleanup() {
    this._player.stop();
    this._player.dispose();

    this._player = AssetsAudioPlayer.newPlayer();
  }

  /// Play the file once in assets folder
  play(String fileName, double volume, bool isLooping) {
    // Stop current sound player
    this._cleanup();

    // Set Loop Mode
    var loopMode = LoopMode.none;
    if (isLooping) {
      loopMode = LoopMode.single;
    }

    // Play FileName
    this._player.open(Audio.file(fileName),
        autoStart: true,
        forceOpen: true,
        loopMode: loopMode,
        respectSilentMode: true,
        volume: volume);
    this.volume = volume;
    this.isPaused = false;
  }
[...]

**Comment by nohli** [comment]
Just out of curiosity (had the same issue until changed the code to creating a new player every time a sound is played):

Does it also happen when you just play one sound with LoopMode.single?
