### ISSUE TITLE
Music Stops when app is background after one song played [IOS]

### ISSUE THREAD

**Issue by kalismeras61** [florent37/Flutter-AssetsAudioPlayer#344]
**Flutter Version**

My version :  latest stable

**Lib Version**

My version : Latest

**Platform (Android / iOS / web) + version**

Platform :  IOS 13.7

**Describe the bug**

Music doesn't continue when app is background. It is only playing one song and then stopping playing.

**Comment by ThalapathySiva** [comment]
I am also facing same issue any solution ? @kalismeras61  @florent37

**Comment by kalismeras61** [comment]
@kalismeras61  i fixed the issue. 


Use, below func.

    func deinitMediaPlayerNotifEvent() {     
            commandCenter.playCommand.isEnabled = false   
            commandCenter.playCommand.removeTarget(self)
            commandCenter.pauseCommand.isEnabled = false   
            commandCenter.pauseCommand.removeTarget(self)
            commandCenter.previousTrackCommand.isEnabled = false   
            commandCenter.previousTrackCommand.removeTarget(self)
            commandCenter.nextTrackCommand.isEnabled = false   
            commandCenter.nextTrackCommand.removeTarget(self)     
    }

**Comment by ThalapathySiva** [comment]
could you tell me where to use this function? @kalismeras61

**Comment by kalismeras61** [comment]
> could you tell me where to use this function? @kalismeras61

You have to change this here;

https://github.com/florent37/Flutter-AssetsAudioPlayer/blob/master/darwin/Classes/Music.swift

**Comment by ThalapathySiva** [comment]
isn't this added in latest version ? should we change it manually.. thanks for your reply...

**Comment by kalismeras61** [comment]
It is added, but it is wrong.  You should fork this repository and change it.

**Comment by bacr** [comment]
Why this issue is closed?
