### ISSUE TITLE
I want to create mix player with one audio and video file play together at same time

### ISSUE THREAD

**Issue by bhallaramdhatarwal** [florent37/Flutter-AssetsAudioPlayer#353]
I am trying to play video and audio at same time in flutter by using

assets_audio_player: ^2.0.9+2 ==> For assets audio file playing
video_player: 0.10.12+2 ==> for URL Video file playing

but when play audio and video in same time at same screen that time video was stack and video volume is stopped. 
and if I used URL for audio & video. And audio player library for audio play that time smoothly play both audio and video

Thanks

**Comment by kalismeras61** [comment]
This is not a bug, you can fork with both repository an change category to mixOthers.
