### ISSUE TITLE
ios background control does not have the duration time and position time

### ISSUE THREAD

**Issue by xibici** [florent37/Flutter-AssetsAudioPlayer#355]
**Describe the feature you'd like**

**Comment by xibici** [comment]
![image](https://user-images.githubusercontent.com/46315437/93706614-75c9a880-fb5a-11ea-9e22-fc1f320e85c4.jpeg)like that

**Comment by bacr** [comment]
Same issue here

**Comment by tmdevlet** [comment]
And for me. This plugin has so many bugs for final ios 14 (((((((

**Comment by kalismeras61** [comment]
it is fixed.
