### ISSUE TITLE
IOS compile failed

### ISSUE THREAD

**Issue by xylim666** [florent37/Flutter-AssetsAudioPlayer#36]
Getting below error when compiling for IOS 

 /Users/runner/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-1.2.3/ios/Classes/SwiftAssetsAudioPlayerPlugin.swift:114:103: error: 'AVAudioSessionModeDefault' has been renamed to 'AVAudioSession.Mode.default'
                    try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayback, mode: AVAudioSessionModeDefault, options: [])
                                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                                          AVAudioSession.Mode.default
    AVFoundation.AVAudioSessionModeDefault:3:12: note: 'AVAudioSessionModeDefault' was obsoleted in Swift 3
    public let AVAudioSessionModeDefault: AVAudioSession.Mode
               ^
    /Users/runner/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-1.2.3/ios/Classes/SwiftAssetsAudioPlayerPlugin.swift:116:36: error: ambiguous reference to member 'setCategory'
                    try AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayback, with: .mixWithOthers)
                        ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~

**Comment by florent37** [comment]
you need to migrate the swift version

please follow those instructions : https://github.com/florent37/Flutter-AssetsAudioPlayer/issues/29#issuecomment-590537548

**Comment by xylim666** [comment]
<img width="955" alt="Screenshot 2020-04-07 at 4 11 31 PM" src="https://user-images.githubusercontent.com/22316067/78647881-c1aacd00-78ed-11ea-8093-f8966b01c875.png">

even with the added code in podfile i'm still getting that error
