### ISSUE TITLE
notification is not showing on iOS

### ISSUE THREAD

**Issue by DomingoMG** [florent37/Flutter-AssetsAudioPlayer#360]
**Flutter Version**

My version : 1.20.4

**Lib Version**

My version : ^2.0.10

**Platform (Android / iOS / web) + version**

Platform : iOS - version software 13.3

**Describe the bug**
I am trying to show notifications on iOS when I press the play button.
On Android it shows up correctly, but on iOS it doesn't show at all.

This is the method that is executed, in android it works in iOS it is not shown and it should be equivalent.

**Small code to reproduce**
```

void initAudioStreaming( bool autoStart ){
    audioPlayer.open(
      currentAudioMetadata.toAudioLiveStreaming(),
      showNotification: true,
      volume: 1.0,
      autoStart: autoStart,
      respectSilentMode: true,
      playInBackground: PlayInBackground.enabled, 
      notificationSettings: NotificationSettings(
        nextEnabled: true,
        prevEnabled: true,
        seekBarEnabled: false
      ),
    );
    updateNotification( currentAudioMetadata );
  }

```

**Info.split**
```
<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>
<key>UIBackgroundModes</key>
	<array>
		<string>remote-notification</string>
		<string>audio</string>
		<string>fetch</string>
	</array>
```

**Comment by kalismeras61** [comment]
@DomingoMG  are you using simulator ? CAn you try it with real device ?

**Comment by DomingoMG** [comment]
@kalismeras61 If I'm using a simulator, I don't have a real device.

**Comment by kalismeras61** [comment]
Do you have this issue with latest versions?

**Comment by DomingoMG** [comment]
@kalismeras61 
I have updated to version:
**assets_audio_player: ^2.0.13+1**

But the notification still doesn't appear on iOS

Attached a demo:
<a href="https://www.youtube.com/embed/YnN5_zxpIpw
" target="_blank"><img src="https://i.ytimg.com/vi/iXrotaDby5I/maxresdefault.jpg" 
alt="IMAGE ALT TEXT HERE" width="240" height="180" border="10" /></a>

**Comment by kalismeras61** [comment]
@DomingoMG ok got it. 

Apple remove RemoteCommandCenter simulation since iOS 11,

so i suggest you to use iOS 10.x simulator to debug RemoteCommandCenter.
