### ISSUE TITLE
Cannot play simultaneous sounds.

### ISSUE THREAD

**Issue by brice-fromentin** [florent37/Flutter-AssetsAudioPlayer#368]
**Flutter Version**

My version : 1.22

**Lib Version**

My version : 2.0.10

**Platform (Android / iOS / web) + version**

Platform : iPad OS 14

**Describe the bug**

I launch a playlist on one player, I create a second player and open a file. The second file plays but the first one is stopped.

It works on Android but not on iPad OS 14 Simulator

**Small code to reproduce**

```dart
    var player1 = AssetsAudioPlayer.newPlayer();
    player1.open(Playlist(audios: playlist), loopMode: LoopMode.playlist);

    [...]

    var player2 = AssetsAudioPlayer.newPlayer();
    player2.open(Audio.file(fileName));

```

**Comment by surpriso1997** [comment]
Have you tried using AssetsAudioPlayer.group(), it allows you to play multiple audios simultaneously.

**Comment by brice-fromentin** [comment]
Thanks fot the trick, I check this and give you a feedback.

________________________________
De : Manish Chaulagain <notifications@github.com>
Envoyé : Thursday, October 8, 2020 5:29:58 PM
À : florent37/Flutter-AssetsAudioPlayer <Flutter-AssetsAudioPlayer@noreply.github.com>
Cc : brice-fromentin <brice.fromentin@outlook.com>; Author <author@noreply.github.com>
Objet : Re: [florent37/Flutter-AssetsAudioPlayer] Cannot play simultaneous sounds. (#368)


Have you tried using AssetsAudioPlayer.group(), it allows you to play multiple audios simultaneously.

**Comment by brice-fromentin** [comment]
I try this :

    // Play FileName
    var soundGroup = AssetsAudioPlayerGroup(updateNotification: null);
    var audio = Audio.file(fileName);
    soundGroup.add(audio, loopMode: LoopMode.none, volume: 1.0);
    this._player = soundGroup.audiosWithPlayers[this._audio];
    this._player.play();

But no sound on both iOS and Android.

De : Brice FROMENTIN<mailto:brice.fromentin@outlook.com>
Envoyé le :jeudi 8 octobre 2020 19:11
À : florent37/Flutter-AssetsAudioPlayer<mailto:reply@reply.github.com>; florent37/Flutter-AssetsAudioPlayer<mailto:Flutter-AssetsAudioPlayer@noreply.github.com>
Cc : Author<mailto:author@noreply.github.com>
Objet :Re: [florent37/Flutter-AssetsAudioPlayer] Cannot play simultaneous sounds. (#368)

Thanks fot the trick, I check this and give you a feedback.


De : Manish Chaulagain <notifications@github.com>
Envoyé : Thursday, October 8, 2020 5:29:58 PM
À : florent37/Flutter-AssetsAudioPlayer <Flutter-AssetsAudioPlayer@noreply.github.com>
Cc : brice-fromentin <brice.fromentin@outlook.com>; Author <author@noreply.github.com>
Objet : Re: [florent37/Flutter-AssetsAudioPlayer] Cannot play simultaneous sounds. (#368)


Have you tried using AssetsAudioPlayer.group(), it allows you to play multiple audios simultaneously.

**Comment by surpriso1997** [comment]
@brice-fromentin When you tried playing it , didn't it give any logs. If the audio did not play it should have given Platform Exeption and error messages with what happened wrong. We are using AssetsAudioPlayerGroup to play multiple sounds and it is working fine.
 Did you try this example in the repository?
 https://github.com/florent37/Flutter-AssetsAudioPlayer/blob/master/example/lib/main_group.dart

**Comment by brice-fromentin** [comment]
Here is the log :

I/ExoPlayerImpl( 4625): Init e77d73e [ExoPlayerLib/2.11.4] [generic_x86_arm, sdk_gphone_x86_arm, Google, 30]
I/OMXClient( 4625): IOmx service obtained
I/ACodec  ( 4625): codec does not support config priority (err -2147483648)

De : Manish Chaulagain<mailto:notifications@github.com>
Envoyé le :vendredi 9 octobre 2020 16:13
À : florent37/Flutter-AssetsAudioPlayer<mailto:Flutter-AssetsAudioPlayer@noreply.github.com>
Cc : brice-fromentin<mailto:brice.fromentin@outlook.com>; Mention<mailto:mention@noreply.github.com>
Objet :Re: [florent37/Flutter-AssetsAudioPlayer] Cannot play simultaneous sounds. (#368)


@brice-fromentin<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbrice-fromentin&data=02%7C01%7C%7C431c8573dc0f40832dec08d86c5d75a3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637378495937920147&sdata=s7OblLSuTShlu6%2BHaKlRVenU9FhpbovjxR9tGKwGRJ0%3D&reserved=0> When you tried playing it , didn't it give any logs. If the audio did not play it should have given Platform Exeption and error messages with what happened wrong. We are using AssetsAudioPlayerGroup to play multiple sounds and it is working fine.
Did you try this example in the repository?
https://github.com/florent37/Flutter-AssetsAudioPlayer/blob/master/example/lib/main_group.dart<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fflorent37%2FFlutter-AssetsAudioPlayer%2Fblob%2Fmaster%2Fexample%2Flib%2Fmain_group.dart&data=02%7C01%7C%7C431c8573dc0f40832dec08d86c5d75a3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637378495937920147&sdata=VAu4%2BoygyfSEkNdKrwHQLqR6%2BodJ1srpgw06BJiGC5s%3D&reserved=0>

**Comment by brice-fromentin** [comment]
I create a non working sample application : https://github.com/brice-fromentin/player_group

He does not generate logs.

De : Brice FROMENTIN<mailto:brice.fromentin@outlook.com>
Envoyé le :samedi 10 octobre 2020 15:08
À : florent37/Flutter-AssetsAudioPlayer<mailto:reply@reply.github.com>; florent37/Flutter-AssetsAudioPlayer<mailto:Flutter-AssetsAudioPlayer@noreply.github.com>
Cc : Mention<mailto:mention@noreply.github.com>
Objet :RE : [florent37/Flutter-AssetsAudioPlayer] Cannot play simultaneous sounds. (#368)

Here is the log :

I/ExoPlayerImpl( 4625): Init e77d73e [ExoPlayerLib/2.11.4] [generic_x86_arm, sdk_gphone_x86_arm, Google, 30]
I/OMXClient( 4625): IOmx service obtained
I/ACodec  ( 4625): codec does not support config priority (err -2147483648)

De : Manish Chaulagain<mailto:notifications@github.com>
Envoyé le :vendredi 9 octobre 2020 16:13
À : florent37/Flutter-AssetsAudioPlayer<mailto:Flutter-AssetsAudioPlayer@noreply.github.com>
Cc : brice-fromentin<mailto:brice.fromentin@outlook.com>; Mention<mailto:mention@noreply.github.com>
Objet :Re: [florent37/Flutter-AssetsAudioPlayer] Cannot play simultaneous sounds. (#368)


@brice-fromentin<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbrice-fromentin&data=02%7C01%7C%7C431c8573dc0f40832dec08d86c5d75a3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637378495937920147&sdata=s7OblLSuTShlu6%2BHaKlRVenU9FhpbovjxR9tGKwGRJ0%3D&reserved=0> When you tried playing it , didn't it give any logs. If the audio did not play it should have given Platform Exeption and error messages with what happened wrong. We are using AssetsAudioPlayerGroup to play multiple sounds and it is working fine.
Did you try this example in the repository?
https://github.com/florent37/Flutter-AssetsAudioPlayer/blob/master/example/lib/main_group.dart<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fflorent37%2FFlutter-AssetsAudioPlayer%2Fblob%2Fmaster%2Fexample%2Flib%2Fmain_group.dart&data=02%7C01%7C%7C431c8573dc0f40832dec08d86c5d75a3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637378495937920147&sdata=VAu4%2BoygyfSEkNdKrwHQLqR6%2BodJ1srpgw06BJiGC5s%3D&reserved=0>
