### ISSUE TITLE
Notification SeekBar not working on iOS

### ISSUE THREAD

**Issue by esentis** [florent37/Flutter-AssetsAudioPlayer#375]
Is there any issue with notification seekbar not working on iOS? I haven't seen any open issues.

While on Android, it works as intended. But on iOS the seekbar is not interactive even though it works inside the app. Are there any different settings I should pass that im not aware?

**Comment by lawkeen** [comment]
Hi, @esentis same issue to me did you fix it?

**Comment by esentis** [comment]
> Hi, @esentis same issue to me did you fix it?

Unfortunately not. Still a bug in my app.

**Comment by tmdevlet** [comment]
Are you going to fix it soon? Your packet is good but I can't use it in production with this bug. And I very want to do it.

**Comment by florent37** [comment]
I don't know how to fix it, the sdk for notification on ios is buggy and don't work fine, if someone find something I will appreciate his help

**Comment by kalismeras61** [comment]
@florent37 i added seekbar control 

https://github.com/florent37/Flutter-AssetsAudioPlayer/pull/394

**Comment by kalismeras61** [comment]
It is fixed with this PR https://github.com/florent37/Flutter-AssetsAudioPlayer/pull/394 . Closed.
