### ISSUE TITLE
Because assets_audio_player >=2.0.11 depends on assets_audio_player_web ^2.0.11 which doesn't match any versions, assets_audio_player >=2.0.11 is forbidden.

### ISSUE THREAD

**Issue by JAICHANGPARK** [florent37/Flutter-AssetsAudioPlayer#378]
**Flutter Version**

My version : 2.23.0.18.1

**Lib Version**

My version : 2.0.11

**Platform (Android / iOS / web) + version**

Platform : Android

**Describe the bug**

```
Because assets_audio_player >=2.0.11 depends on assets_audio_player_web ^2.0.11 which doesn't match any versions, assets_audio_player >=2.0.11 is forbidden.
So, because flutter_angel_legs_5_1 depends on assets_audio_player ^2.0.11, version solving failed.
pub get failed (1; So, because flutter_angel_legs_5_1 depends on assets_audio_player ^2.0.11, version solving failed.)
```

**Comment by nohli** [comment]
Got the same error.
The new version of assets_audio_player_web also needs to be published to pub.dev.

**Comment by JEuler** [comment]
Same

**Comment by stanrisever** [comment]
Same problem

**Comment by jpetro416** [comment]
assets_audio_player >=2.0.11 depends on assets_audio_player_web ^2.0.11 which doesn't match any

**Comment by henoktadesse** [comment]
The same happened for 2.0.11, for now I downgraded one version back and `assets_audio_player: 2.0.9+2` worked.

**Comment by florent37** [comment]
should be fixed, please use the 2.0.12

**Comment by nohli** [comment]
> Got the same error.
> The new version of assets_audio_player_web also needs to be published to pub.dev.

@florent37 
Now it depends on assets_audio_player_web ^2.0.12, but the published version is 2.0.9+2:
https://pub.dev/packages/assets_audio_player_web

**Comment by florent37** [comment]
I re-published the 2.0.12 just now, can you retry ?

**Comment by florent37** [comment]
https://pub.dev/packages/assets_audio_player_web/versions/2.0.12

**Comment by johnareid54** [comment]
@JAICHANGPARK and @nohli and @jpetro416 and @JEuler 

Did you get the audio to work on the web, and if so could you post a sample of the steps taken?
