### ISSUE TITLE
is there a plan to add a gape-less loop function?

### ISSUE THREAD

**Issue by hiwa-jalal** [florent37/Flutter-AssetsAudioPlayer#38]

**Comment by florent37** [comment]
what is a gape-less loop function ? :)

**Comment by hiwa-jalal** [comment]
[like this package](https://pub.dev/packages/gapless_audio_loop), and also as a side note why the audio start as soon as we load it i.e using the open method.

**Comment by florent37** [comment]
maybe in the open method we can add an "autoStart" argument for your case

```dart
assetsAudioPlayer.open(
    Audio("assets/audios/song1.mp3"),
    autoStart: false
);
```

**Comment by florent37** [comment]
I just added the `autoStart: false` attribute to `open` methods in the 1.2.6 if it can help you :)

**Comment by hiwa-jalal** [comment]
yes it will help a lot thanks, but how about gape-less loop?

**Comment by florent37** [comment]
I don't really understand what I need to add on the package, can you use what's described in the other package and provide a Pull Request with the gape-less feature in this repository ?

**Comment by hiwa-jalal** [comment]
i mean now you have a loop function in your package and it works pretty well except there is a  gap between every loop, the other package i mentioned has a gape-less loop which make it loop continuously without having a gap, so i asked if you could add that functionality to your package to make it even better!

**Comment by vipulasri** [comment]
@hiwa-jalal gap will be there when using `mp3` format as its dependent on its encoding. 
https://sound.stackexchange.com/a/8917

**Comment by florent37** [comment]
I don't think I will change the code for it, I moved to exoplayer which hande easiely this, but I'm not sure I can do more work

If I recieve a pull request I will merge it but for now I don't know if it's possible

**Comment by florent37** [comment]
because the loop is handled on flutter side, the solutions have a "next-file" pre-cached with 2 players, on native side

**Comment by florent37** [comment]
for now I close it
