### ISSUE TITLE
App working in debug mode fine but when trying to build a release apk Build Fails

### ISSUE THREAD

**Issue by saurabhunify** [florent37/Flutter-AssetsAudioPlayer#398]
Flutter Version 
Flutter 1.22.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8874f21e79 (11 days ago) • 2020-10-29 14:14:35 -0700
Engine • revision a1440ca392
Tools • Dart 2.10.3

My version : 2.0.13

My version : 

Android 10

Platform : 

Windows

I'm working with assets_audio_player's various versions from last few months now earlier it was working fine in one of my projects and I build both android and ios versions of my app and It was working.
Recently I used same functionality in a new app used almost identical code. 
The thing that annoys me that is that the same code in working fine in debug mode in emulators and physical device but Build fails when generating a release build with error
Launching lib\main.dart on RMX2061 in release mode...
Running Gradle task 'assembleRelease'...
Plugin project :firebase_core_web not found. Please update settings.gradle.
Plugin project :location_web not found. Please update settings.gradle.
Plugin project :firebase_auth_web not found. Please update settings.gradle.
WARNING: [Processor] Library 'C:\Users\saurabh1\.gradle\caches\modules-2\files-2.1\io.flutter\flutter_embedding_release\1.0.0-a1440ca392ca23e874a105c5f3248b495bd0e247\82bfee9d8ba0b5d7f0fe66dc67f75e53bb636aeb\flutter_embedding_release-1.0.0-a1440ca392ca23e874a105c5f3248b495bd0e247.jar' contains references to both AndroidX and old support library. This seems like the library is partially migrated. Jetifier will try to rewrite the library anyway.
 Example of androidX reference: 'androidx/annotation/NonNull'
 Example of support library reference: 'android/support/annotation/NonNull'
Not resetting hidden file - E:\flutterProjects\dishuum_app\build\app\intermediates\flutter\release\flutter_assets\assets\icons\Thumbs.db
WARNING: [Processor] Library 'C:\Users\saurabh1\.gradle\caches\modules-2\files-2.1\io.flutter\flutter_embedding_profile\1.0.0-a1440ca392ca23e874a105c5f3248b495bd0e247\4e1da5a8a0342c506fda9bd711264ec3af30c4dd\flutter_embedding_profile-1.0.0-a1440ca392ca23e874a105c5f3248b495bd0e247.jar' contains references to both AndroidX and old support library. This seems like the library is partially migrated. Jetifier will try to rewrite the library anyway.
 Example of androidX reference: 'androidx/annotation/NonNull'
 Example of support library reference: 'android/support/annotation/NonNull'

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:profileRuntimeClasspath'.
   > Failed to transform libs.jar to match attributes {artifactType=processed-jar, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: E:\flutterProjects\dishuum_app\build\app\intermediates\flutter\profile\libs.jar.
         > Transform's input file does not exist: E:\flutterProjects\dishuum_app\build\app\intermediates\flutter\profile\libs.jar. (See https://issuetracker.google.com/issues/158753935)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 34s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin assets_audio_player...
Running Gradle task 'assembleAarRelease'...
√ Built build\app\outputs\repo.
Building plugin assets_audio_player_web...
Running Gradle task 'assembleAarRelease'...

FAILURE: Build failed with an exception.

* What went wrong:
Task 'assembleAarRelease' not found in root project 'assets_audio_player_web'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 29s

Exception: The plugin assets_audio_player_web could not be built due to the issue above.

Here's an output of flutter doctor command :
 Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.3, on Microsoft Windows [Version 10.0.19041.572], locale en-IN)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Android Studio (version 4.0)
[!] VS Code (version 1.50.1)
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[√] Connected device (1 available)

! Doctor found issues in 1 category.

**Comment by hzlgnn** [comment]
same issue

**Flutter Version** 1.22.5

**Platform (Android / iOS / web) + version**

Platform : Android

assets_audio_player version : 2.0.13+3

**Describe the bug**

I can run the project without any errors in debug mode. Now I'm trying to create apk but got an error like this: 
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':compileReleaseAidl'.
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '/Users/mac/development/flutter/.pub-cache/git/Flutter-AssetsAudioPlayer-a8e5083f10b2aa8482f586d00af1349ca19c183a/android/local.properties'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUİLD FAILED in 2s


The plugin assets_audio_player could not be built due to the issue above.




flutter doctor result
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H2 darwin-x64, locale tr-TR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
[✓] Android Studio (version 4.0)
[✓] Connected device (2 available)

• No issues found!

**Comment by imiskolee** [comment]
same issue now 3.0.x

**Comment by huxaiphaer** [comment]
@saurabhunify , @imiskolee , @hzlgnn , do you have any solution for this apparently ?

**Comment by ZantsuRocks** [comment]
Same issue here, why this issue was closed without a solution?

**Comment by imiskolee** [comment]
> @saurabhunify , @imiskolee , @hzlgnn , do you have any solution for this apparently ?

I am no longer using this now.
