### ISSUE TITLE
Is there any way to keep playing audio even after the app is closed? 

### ISSUE THREAD

**Issue by stha-ums** [florent37/Flutter-AssetsAudioPlayer#405]
I want the audio to keep playing even after the app is closed. 
Now audio can be played in the background but I want to audio to keep playing even app is terminated or cleared from recent apps. 

is this feature already available and if not what can I do to achieve this?

**Comment by kalismeras61** [comment]
If i understand correctly you want to play files even app is terminated ? all music providers can't play music.

**Comment by stha-ums** [comment]
yes, I want to play even after the app is terminated. 

I have been provided an android app(developed with native java) that can keep playing audio even after the app is terminated.

>  all music providers can't play music when app is terminated
is this a flutter limitation?

**Comment by afkcodes** [comment]
@stha-ums this package can do it because it does not creates a foreground service, you can look for other similar packages or push the app in background when the back button is pressed instead of exiting.

**Comment by tarush-r** [comment]
> @stha-ums this package can do it because it does not creates a foreground service, you can look for other similar packages or push the app in background when the back button is pressed instead of exiting.

how do I push the app in background instead of exiting? and also is this the problem with all audio players or just this one? please help thank you

**Comment by afkcodes** [comment]
@tarush-r this is not an issue with the package it's just the implementation how it is. You can search on google on how to push app into background

**Comment by tarush-r** [comment]
> @tarush-r this is not an issue with the package it's just the implementation how it is. You can search on google on how to push app into background

I tried multiple plugins to keep the app running in background(none of them worked), I even enabled the playInBackground enum of the plugin still the audio stops playing when I press the back button, when I press the home button the audio continues to play

**Comment by afkcodes** [comment]
You can use this 
https://pub.dev/packages/move_to_background

**Comment by tarush-r** [comment]
> You can use this
> https://pub.dev/packages/move_to_background

yes I tried that plugin as well, it did not work

**Comment by afkcodes** [comment]
Your implementation seems wrong for me it's not happening.

**Comment by stha-ums** [comment]
> You can use this
> https://pub.dev/packages/move_to_background

this works, but when I clear the app from a recent app I want the app to keep playing audio.

**Comment by MohamedSaad8** [comment]
please any one help me, I try to open the audio with assetsAduioPlayer.open(Aduio.file()) and the file path get it from package  
FlutterAduioQuery this return all songs filePath but when i pass the file path to open it throw exception open(null , null ,null) 
i am read the documentation of assetsAudioPlayer in this case and find about open file information that say "for file uri, please look at https://pub.dev/packages/path_provider"  
Can any one help me ??
