### ISSUE TITLE
Re play current song

### ISSUE THREAD

**Issue by pablomagana** [florent37/Flutter-AssetsAudioPlayer#407]
Hi, 
i'm trying to implement to repeat the current song, like reset player, but i'm not found any method to do that.
How i can to reset the song when it finished or when i press a button?

Thanks

**Comment by kalismeras61** [comment]
You can use LoopMode.single for looping song.

**Comment by pablomagana** [comment]
But i want to reset song only one time

**Comment by kalismeras61** [comment]
I didn't understand what you mean with Reset ? if you want to repeat current song you can use LoopMode enum. Can you elaborate what you want ?

**Comment by pablomagana** [comment]
That's just what I need.
I have a song that loads at the beginning and is waiting to play with the play button, but when the song is finished, I need the song to return to the initial state ready to play again when the play button is pressed again.

At the moment, I apply a LoopMode.single and I'm listening to the status of the song. When it finishes, I call the pause method, but I don't think it's the best solution

**Comment by ManojDvs** [comment]
hey can anyone help me , if i call next and previous methods , multiple audios starts playing for me.

**Comment by kalismeras61** [comment]
@ManojDvs  already fixed. Please use plugin as a git repo and last commit.
