### ISSUE TITLE
After clicking on pause in the notification panel, the ability to click on play disappears

### ISSUE THREAD

**Issue by VladislavYU** [florent37/Flutter-AssetsAudioPlayer#408]
**Flutter Version**

My version : 1.22.4

**Lib Version**

My version : 2.0.13+1

**Platform (Android / iOS / web) + version**

Platform : iOS 14.2

**Describe the bug**

I start the radio stream and after clicking on pause in the notification panel, the ability to click on play disappears. On Android this work without problems. Maybe have simple solution this problem about I'm not know?
This [video](https://yadi.sk/i/SeB0fkEUF_UD3A) shows this problem.

**Comment by kalismeras61** [comment]
Please try below, it should work. Closing for now.

assets_audio_player:
git:
url: https://github.com/florent37/Flutter-AssetsAudioPlayer.git
ref: master
