### ISSUE TITLE
bug in newer version!

### ISSUE THREAD

**Issue by hiwa-jalal** [florent37/Flutter-AssetsAudioPlayer#41]
the package was running fine but after upgrading to 1.26 and newer verisons my application can't run and it shows this 
```e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.5\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (13, 14): Conflicting declarations: internal val METHOD_POSITION: String, internal val METHOD_POSITION: String
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.5\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (14, 14): Conflicting declarations: internal val METHOD_FINISHED: String, internal val METHOD_FINISHED: String
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.5\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (15, 14): Conflicting declarations: internal val METHOD_IS_PLAYING: String, internal val METHOD_IS_PLAYING: String
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.5\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (16, 14): Conflicting declarations: internal val METHOD_CURRENT: String, internal val METHOD_CURRENT: String
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.5\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (17, 14): Conflicting declarations: internal val METHOD_NEXT: String, internal val METHOD_NEXT: String
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.5\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (18, 14): Conflicting declarations: internal val METHOD_PREV: String, internal val METHOD_PREV: String
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.5\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (20, 7): Redeclaration: AssetsAudioPlayerPlugin
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.5\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (47, 42): Overload resolution ambiguity: 
internal val METHOD_POSITION: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
internal val METHOD_POSITION: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.5\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (103, 34): Overload resolution ambiguity: 
internal val METHOD_POSITION: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
internal val METHOD_POSITION: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.5\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (107, 34): Overload resolution ambiguity: 
internal val METHOD_IS_PLAYING: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
internal val METHOD_IS_PLAYING: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.5\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (137, 34): Overload resolution ambiguity: 
internal val METHOD_POSITION: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
internal val METHOD_POSITION: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.5\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (149, 34): Overload resolution ambiguity: 
internal val METHOD_POSITION: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
internal val METHOD_POSITION: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.5\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (159, 34): Overload resolution ambiguity: 
internal val METHOD_FINISHED: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
internal val METHOD_FINISHED: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.5\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (160, 34): Overload resolution ambiguity: 
internal val METHOD_IS_PLAYING: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
internal val METHOD_IS_PLAYING: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.5\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (163, 30): Overload resolution ambiguity: 
internal val METHOD_CURRENT: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
internal val METHOD_CURRENT: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.5\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (182, 34): Overload resolution ambiguity: 
internal val METHOD_IS_PLAYING: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
internal val METHOD_IS_PLAYING: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.5\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (190, 34): Overload resolution ambiguity: 
internal val METHOD_IS_PLAYING: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
internal val METHOD_IS_PLAYING: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.5\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (197, 34): Overload resolution ambiguity: 
internal val METHOD_POSITION: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
internal val METHOD_POSITION: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.8\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (14, 14): Conflicting declarations: internal val METHOD_POSITION: String, internal val METHOD_POSITION: String
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.8\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (16, 14): Conflicting declarations: internal val METHOD_FINISHED: String, internal val METHOD_FINISHED: String
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.8\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (17, 14): Conflicting declarations: internal val METHOD_IS_PLAYING: String, internal val METHOD_IS_PLAYING: String
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.8\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (18, 14): Conflicting declarations: internal val METHOD_CURRENT: String, internal val METHOD_CURRENT: String
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.8\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (19, 14): Conflicting declarations: internal val METHOD_NEXT: String, internal val METHOD_NEXT: String
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.8\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (20, 14): Conflicting declarations: internal val METHOD_PREV: String, internal val METHOD_PREV: String
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.8\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (40, 42): Overload resolution ambiguity: 
internal val METHOD_POSITION: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
internal val METHOD_POSITION: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.8\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (76, 34): Overload resolution ambiguity: 
internal val METHOD_POSITION: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
internal val METHOD_POSITION: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.8\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (90, 34): Overload resolution ambiguity: 
internal val METHOD_POSITION: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
internal val METHOD_POSITION: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.8\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (100, 34): Overload resolution ambiguity: 
internal val METHOD_FINISHED: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
internal val METHOD_FINISHED: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.8\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (104, 30): Overload resolution ambiguity: 
internal val METHOD_CURRENT: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
internal val METHOD_CURRENT: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.8\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (118, 34): Overload resolution ambiguity: 
internal val METHOD_POSITION: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
internal val METHOD_POSITION: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.8\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (123, 34): Overload resolution ambiguity: 
internal val METHOD_IS_PLAYING: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
internal val METHOD_IS_PLAYING: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.8\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (142, 34): Overload resolution ambiguity: 
internal val METHOD_IS_PLAYING: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
internal val METHOD_IS_PLAYING: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.8\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (150, 34): Overload resolution ambiguity: 
internal val METHOD_IS_PLAYING: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
internal val METHOD_IS_PLAYING: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.8\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (157, 34): Overload resolution ambiguity: 
internal val METHOD_POSITION: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
internal val METHOD_POSITION: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.8\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (169, 7): Redeclaration: AssetsAudioPlayerPlugin
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.8\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (175, 87): Type mismatch: inferred type is BinaryMessenger! but MethodChannel was expected
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.8\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (175, 110): Too many arguments for public constructor AssetsAudioPlayerPlugin(context: Context, channel: MethodChannel) defined in com.github.florent37.assetsaudioplayer.AssetsAudioPlayerPlugin

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':assets_audio_player:compileDebugKotlin'.
```

**Comment by kw2019ltd** [comment]
Launching lib\main.dart on HD1903 in debug mode...
Running Gradle task 'assembleDebug'...
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.3\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (13, 14): Conflicting declarations: internal val METHOD_POSITION: String, internal val METHOD_POSITION: String
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.3\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (14, 14): Conflicting declarations: internal val METHOD_FINISHED: String, internal val METHOD_FINISHED: String
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.3\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (15, 14): Conflicting declarations: internal val METHOD_IS_PLAYING: String, internal val METHOD_IS_PLAYING: String
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.3\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (16, 14): Conflicting declarations: internal val METHOD_CURRENT: String, internal val METHOD_CURRENT: String
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.3\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (17, 14): Conflicting declarations: internal val METHOD_NEXT: String, internal val METHOD_NEXT: String
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.3\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (18, 14): Conflicting declarations: internal val METHOD_PREV: String, internal val METHOD_PREV: String
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.3\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (20, 7): Redeclaration: AssetsAudioPlayerPlugin
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.3\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (47, 42): Overload resolution ambiguity: 
internal val METHOD_POSITION: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
internal val METHOD_POSITION: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.3\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (103, 34): Overload resolution ambiguity: 
internal val METHOD_POSITION: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
internal val METHOD_POSITION: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.3\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (107, 34): Overload resolution ambiguity: 
internal val METHOD_IS_PLAYING: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
internal val METHOD_IS_PLAYING: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.3\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (137, 34): Overload resolution ambiguity: 
internal val METHOD_POSITION: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
internal val METHOD_POSITION: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.3\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (149, 34): Overload resolution ambiguity: 
internal val METHOD_POSITION: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
internal val METHOD_POSITION: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.3\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (159, 34): Overload resolution ambiguity: 
internal val METHOD_FINISHED: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
internal val METHOD_FINISHED: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.3\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (160, 34): Overload resolution ambiguity: 
internal val METHOD_IS_PLAYING: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
internal val METHOD_IS_PLAYING: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.3\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (163, 30): Overload resolution ambiguity: 
internal val METHOD_CURRENT: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
internal val METHOD_CURRENT: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.3\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (182, 34): Overload resolution ambiguity: 
internal val METHOD_IS_PLAYING: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
internal val METHOD_IS_PLAYING: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.3\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (190, 34): Overload resolution ambiguity: 
internal val METHOD_IS_PLAYING: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
internal val METHOD_IS_PLAYING: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.3\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (197, 34): Overload resolution ambiguity: 
internal val METHOD_POSITION: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
internal val METHOD_POSITION: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.8\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (14, 14): Conflicting declarations: internal val METHOD_POSITION: String, internal val METHOD_POSITION: String
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.8\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (16, 14): Conflicting declarations: internal val METHOD_FINISHED: String, internal val METHOD_FINISHED: String
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.8\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (17, 14): Conflicting declarations: internal val METHOD_IS_PLAYING: String, internal val METHOD_IS_PLAYING: String
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.8\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (18, 14): Conflicting declarations: internal val METHOD_CURRENT: String, internal val METHOD_CURRENT: String
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.8\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (19, 14): Conflicting declarations: internal val METHOD_NEXT: String, internal val METHOD_NEXT: String
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.8\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (20, 14): Conflicting declarations: internal val METHOD_PREV: String, internal val METHOD_PREV: String
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.8\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (40, 42): Overload resolution ambiguity: 
internal val METHOD_POSITION: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
internal val METHOD_POSITION: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.8\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (76, 34): Overload resolution ambiguity: 
internal val METHOD_POSITION: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
internal val METHOD_POSITION: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.8\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (90, 34): Overload resolution ambiguity: 
internal val METHOD_POSITION: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
internal val METHOD_POSITION: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.8\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (100, 34): Overload resolution ambiguity: 
internal val METHOD_FINISHED: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
internal val METHOD_FINISHED: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.8\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (104, 30): Overload resolution ambiguity: 
internal val METHOD_CURRENT: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
internal val METHOD_CURRENT: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.8\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (118, 34): Overload resolution ambiguity: 
internal val METHOD_POSITION: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
internal val METHOD_POSITION: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.8\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (123, 34): Overload resolution ambiguity: 
internal val METHOD_IS_PLAYING: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
internal val METHOD_IS_PLAYING: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.8\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (142, 34): Overload resolution ambiguity: 
internal val METHOD_IS_PLAYING: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
internal val METHOD_IS_PLAYING: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.8\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (150, 34): Overload resolution ambiguity: 
internal val METHOD_IS_PLAYING: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
internal val METHOD_IS_PLAYING: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.8\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (157, 34): Overload resolution ambiguity: 
internal val METHOD_POSITION: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
internal val METHOD_POSITION: String defined in com.github.florent37.assetsaudioplayer in file AssetsAudioPlayerPlugin.kt
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.8\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (169, 7): Redeclaration: AssetsAudioPlayerPlugin
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.8\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (175, 87): Type mismatch: inferred type is BinaryMessenger! but MethodChannel was expected
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.2.8\android\src\main\kotlin\com\github\florent37\assetsaudioplayer\AssetsAudioPlayerPlugin.kt: (175, 110): Too many arguments for public constructor AssetsAudioPlayerPlugin(context: Context, channel: MethodChannel) defined in com.github.florent37.assetsaudioplayer.AssetsAudioPlayerPlugin

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':assets_audio_player:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by florent37** [comment]
just saw this comment https://github.com/OpenFlutter/flutter_image_compress/issues/69

can you try a `flutter clean`

seems to be a dart cache error

**Comment by florent37** [comment]
tell me if it works

**Comment by hiwa-jalal** [comment]
thanks, `flutter clean` fixed it.

**Comment by florent37** [comment]
:)
