### ISSUE TITLE
Playback error com.google.android.exoplayer2.ExoPlaybackException: Source error

### ISSUE THREAD

**Issue by BartusZak** [florent37/Flutter-AssetsAudioPlayer#410]
**Flutter Version**

My version : 
Flutter 1.22.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 1aafb3a8b9 (2 weeks ago) • 2020-11-13 09:59:28 -0800
Engine • revision 2c956a31c0
Tools • Dart 2.10.4

**Lib Version**

My version : 
assets_audio_player: ^2.0.13+1

**Platform (Android / iOS / web) + version**

Platform : 
![image](https://user-images.githubusercontent.com/16143176/100614610-ad04c480-3316-11eb-95ae-4f9c22e8e9e4.png)

**Describe the bug**

I/ExoPlayerImpl( 9053): Init 73b39ae [ExoPlayerLib/2.12.1] [generic_x86_arm, sdk_gphone_x86_arm, Google, 30]
E/ExoPlayerImplInternal( 9053): Playback error
E/ExoPlayerImplInternal( 9053):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal( 9053):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554)
E/ExoPlayerImplInternal( 9053):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal( 9053):       at android.os.Looper.loop(Looper.java:223)
E/ExoPlayerImplInternal( 9053):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal( 9053):   Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor) could read the stream. 
E/ExoPlayerImplInternal( 9053):       at com.google.android.exoplayer2.source.BundledExtractorsAdapter.init(BundledExtractorsAdapter.java:92)
E/ExoPlayerImplInternal( 9053):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1024)
E/ExoPlayerImplInternal( 9053):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
E/ExoPlayerImplInternal( 9053):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal( 9053):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal( 9053):       at java.lang.Thread.run(Thread.java:923)
I/ExoPlayerImpl( 9053): Release 73b39ae [ExoPlayerLib/2.12.1] [generic_x86_arm, sdk_gphone_x86_arm, Google, 30] [goog.exo.core]
V/MediaPlayer( 9053): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 9053): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaHTTPService( 9053): MediaHTTPService(android.media.MediaHTTPService@a62d54b): Cookies: null
V/MediaHTTPService( 9053): makeHTTPConnection: CookieManager created: java.net.CookieManager@c13db28
V/MediaHTTPService( 9053): makeHTTPConnection(android.media.MediaHTTPService@a62d54b): cookieHandler: java.net.CookieManager@c13db28 Cookies: null
W/Glide   ( 9053): Failed to find GeneratedAppGlideModule. You should include an annotationProcessor compile dependency on com.github.bumptech.glide:compiler in your application and a @GlideModule annotated AppGlideModule implementation or LibraryGlideModules will be silently ignored

**Small code to reproduce**

```dart
  await _assetsAudioPlayer.open(
        Audio.network(
          url))
```

**Comment by kalismeras61** [comment]
Player updated . Can you use latest commit ? It should work. Closing for now, it there is any issue please re-open.

assets_audio_player:
git:
url: https://github.com/florent37/Flutter-AssetsAudioPlayer.git
ref: b49a4360f6a7f182d4a6e23ebcdbf43ad570913b
