### ISSUE TITLE
Resource not found when trying to play sound

### ISSUE THREAD

**Issue by Jayvd** [florent37/Flutter-AssetsAudioPlayer#413]
```

                            AssetsAudioPlayer.newPlayer().open(
                              Audio("assets/sounds/alarm.mp3"),
                              autoStart: true,
                              showNotification: true,
                            );
```
`flutter: log: resource not found assets/sounds/alarm.mp3`

[](url)
![Screen Shot 2020-12-02 at 9 38 31 PM](https://user-images.githubusercontent.com/10528643/100886804-d2482d00-34e6-11eb-9976-93012d2d55ff.png)

Platform: iOS
Note: I tried using wav and mp3 files, both doesn't work.  

Any idea hwo to fix this please?

**Comment by rezabayesteh** [comment]
Try to add alarm.mp3 to your assets in pubspec.yaml file: 
```
assets:
    - assets/sounds/alarm.mp3
```
