### ISSUE TITLE
How to Customize the notification UI? 

### ISSUE THREAD

**Issue by stha-ums** [florent37/Flutter-AssetsAudioPlayer#414]
I want the notification to look like this, 
![image](https://user-images.githubusercontent.com/34161121/101243843-0875ee80-372b-11eb-9075-cdef72b1bb59.png)

Is there any way that I can customize the UI?

**Comment by mayouf** [comment]
Hi,
DId you find how to do it ?

**Comment by stha-ums** [comment]
not really. If you want custom notification UI than i guess for now you have to implement in native code.
