### ISSUE TITLE
noy building

### ISSUE THREAD

**Issue by NVS-Creations** [florent37/Flutter-AssetsAudioPlayer#417]
asset_audio_player is not building for android

**Comment by neilweber** [comment]
The plugin and example app are building and running fine for me.  Please provide more details.

[√] Flutter (Channel beta, 1.24.0-10.2.pre, on Microsoft Windows [Version 10.0.19042.630], locale en-US)
    • Flutter version 1.24.0-10.2.pre at C:\Users\Neil\Projects\flutter
    • Framework revision 022b333a08 (4 weeks ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

**Comment by NVS-Creations** [comment]
Hi sir 
I have a doubt 
Iam playing song by getting link from firebase as string list .How to play like a  playlist by getting link from firebase

**Comment by JAICHANGPARK** [comment]
@florent37 

I had some problem 

```
github\florent37\assets_audio_player\notification\NotificationActionReceiver.kt: (30, 39): Type mismatch: inferred type is Intent? but Intent was expected


* What went wrong:
Execution failed for task ':assets_audio_player:compileDebugKotlin'.
> Compilation error. See log for more details

```


## Doctor

```
Flutter is already up to date on channel beta
Flutter 1.25.0-8.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 8f89f6505b (2 days ago) • 2020-12-15 15:07:52 -0800
Engine • revision 92ae191c17
Tools • Dart 2.12.0 (build 2.12.0-133.2.beta)
```
