### ISSUE TITLE
Audio play cause Music stop in iOS

### ISSUE THREAD

**Issue by JmyW** [florent37/Flutter-AssetsAudioPlayer#423]
I use the latest version - 2.0.13+1 

In my iPhone, I have a background music playback. Every time when I use your lib to play an asset audio (1 sec mp3). The background music is stop and even the music player name of command center is gone.

I tried to set Respect System Silent Mode as true or false, both same stop the background music. 

Could you check it?

**Comment by kalismeras61** [comment]
Did you added below things on your IOS settings ?

https://github.com/florent37/Flutter-AssetsAudioPlayer#network-policies-androidiosmacos

**Comment by BlackStriker99** [comment]
@kalismeras61  facing same issue with the **android** and **ios** please reopen this issue.and i have also followed all the things which are mentioned in the document.

**Comment by mohsin2596** [comment]
Did anyone manage to solve this? Spotify completely stops if a small beep sound is played through my app

**Comment by jasminder** [comment]
Any updates on this? Issue still exists. No work on this since this long? Basic need I think.
