### ISSUE TITLE
ExoPlayer upgrade

### ISSUE THREAD

**Issue by stanislavdavid** [florent37/Flutter-AssetsAudioPlayer#433]
Hi, I am flutter beginner. I saw, that your plugin uses old exoplayer version. I tried to upgrade to 2.11.8 and it works without problems in my project. 
When I upgrade to latest version 2.12.2 it was not working with exception
 
```
AppData\Local\Pub\Cache\hosted\pub.dartlang.org\assets_audio_player-2.0.13+1\android\src\main\kotlin\com\github\florent37\assets_audio_player\playerimplem\PlayerImplemExoPlayer.kt: (172, 44): Type mismatch: inferred type is Uri? but Uri was expected

FAILURE: Build failed with an exception.
```

I saw that new versions has many fixes in changelog, may be it can help on android devices :-)

**Comment by kalismeras61** [comment]
all updates have been made.
