### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by applingtalen** [florent37/Flutter-AssetsAudioPlayer#435]
Hi,
I'm new at programming, so it could be that I'm asking the obvious. 
I have copied the example and added the dependency. However I still get a lot of errors:
import 'dart:async';

import 'package:assets_audio_player/assets_audio_player.dart';
import 'package:assets_audio_player_example/player/PlaySpeedSelector.dart';
import 'package:flutter/material.dart';
import 'package:flutter_neumorphic/flutter_neumorphic.dart';
import 'package:rxdart/subjects.dart';

import 'player/ForwardRewindSelector.dart';
import 'player/PlayingControls.dart';
import 'player/PositionSeekWidget.dart';
import 'player/SongsSelector.dart';
import 'player/VolumeSelector.dart';

Only the 'flutter material' and 'assets_audio_player' are not underlined in red, the rest is (except' dart:async').
Do I need to add more dependencies, if so which ones?
Thanks.
Willem

**Comment by kalismeras61** [comment]
You have to flutter pub get.

**Comment by ronlinet** [comment]
If flutter pub get doesn't work,  as in in my case, you can copy manually the files to your lib directory from here https://github.com/florent37/Flutter-AssetsAudioPlayer/tree/master/example/lib/player
