### ISSUE TITLE
Audio.network works fine on android emulator but does not work on real device. 

### ISSUE THREAD

**Issue by am2074** [florent37/Flutter-AssetsAudioPlayer#441]
As the title says, there is a critical error where Audio.network does not work on actual devices. However, it runs just fine on emulated ones. Both the real and the emulated device are Pixel 3a's with Android 11.

When running it on the actual device, the flutter log says the following: 

`I/flutter (13640): PlatformException(OPEN, null, null, null)
E/flutter (13640): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(OPEN, null, null, null)
`

**Comment by BringTheChill** [comment]
@am2074 how do you fix this?
