### ISSUE TITLE
There is a BUG in the cache demo that generates one cache at a time, but points to the wrong path because the.mp3 is missing

### ISSUE THREAD

**Issue by ZhangZhiH** [florent37/Flutter-AssetsAudioPlayer#445]
![image](https://user-images.githubusercontent.com/14193471/105629749-caba5a00-5e7f-11eb-9256-44c0aeea468a.png)
The figure must be added. MP3 to be accessed

**Comment by Shahmirzali-Huseynov** [comment]
Hello, what did you do for solving ?  @ZhangZhiH

**Comment by ZhangZhiH** [comment]
I didn't use it because it was unstable

**Comment by ZhangZhiH** [comment]
> Hello, what did you do for solving ? @ZhangZhiH

I didn't use it because it was unstable
