### ISSUE TITLE
How to keep the state of the last music because when a finished music instance is automatically emptied This only happens in the Android environment

### ISSUE THREAD

**Issue by ZhangZhiH** [florent37/Flutter-AssetsAudioPlayer#446]
How to keep the state of the last music because when a finished music instance is automatically emptied This only happens in the Android environment

**Comment by comlaterra** [comment]
With "Finished" you meant stopped?

If so, you should use Pause:
```
assetsAudioPlayer.pause();
```

**Comment by ManojDvs** [comment]
hey can anyone help me on this, when i tap next or previous multiple audios starts playing for me.

**Comment by ZhangZhiH** [comment]
> “完成”是指您停止了吗？
> 
> 如果是这样，则应使用“暂停”：
> 
> ```
> assetsAudioPlayer.pause();
> ```



> “完成”是指您停止了吗？
> 
> 如果是这样，则应使用“暂停”：
> 
> ```
> assetsAudioPlayer.pause();
> ```

Thank you for your answer
It clears the currently playing audio instance when the audio ends automatically

**Comment by ZhangZhiH** [comment]
> “完成”是指您停止了吗？
> 
> 如果是这样，则应使用“暂停”：
> 
> ```
> assetsAudioPlayer.pause();
> ```
Thank you for your answer
It clears the currently playing audio instance when the audio ends automatically
I didn't use pause
In an Android environment
Call open code
`await _assetsAudioPlayer.open(
                                    Playlist(audios: [data], startIndex: 0),
                                    autoStart: true,
                                    showNotification: true,
                                    playInBackground: PlayInBackground.enabled,
                                    audioFocusStrategy:
                                        AudioFocusStrategy.request(
                                            resumeAfterInterruption: true,
                                            resumeOthersPlayersAfterDone: true),
                                    headPhoneStrategy:
                                        HeadPhoneStrategy.pauseOnUnplug,
                                    notificationSettings: NotificationSettings(
                                        seekBarEnabled: false,
                                        stopEnabled: false,
                                        customStopAction: (player) {
                                          player.stop();
                                        }),
                                  );`

![image](https://user-images.githubusercontent.com/14193471/106347314-7b997c80-62f8-11eb-9ca9-ee1640607e84.png)

![image](https://user-images.githubusercontent.com/14193471/106347265-28bfc500-62f8-11eb-99c7-17863cf4c4e6.png)

**Comment by ZhangZhiH** [comment]
> With "Finished" you meant stopped?
> 
> If so, you should use Pause:
> 
> ```
> assetsAudioPlayer.pause();
> ```

Thank you for your answer
When an audio playback ends, it clears the currently playing audio instance , Cannot listen for the currently playing audio
I didn't use pause
In an Android environment
Call the open method and listen for the audio in the current playback, which causes the audio in the current playback to be NULL when the playback is completed
await _assetsAudioPlayer.open();

image

image

**Comment by kalismeras61** [comment]
Can you try like this ? 
Text(current?.current?.audio?.audio?.path)  please add question mark.

**Comment by ZhangZhiH** [comment]
> @ZhangZhiH Can you try like this ?
> Text(current?.current?.audio?.audio?.path ?? '') please add question mark.

It can only be judged that he is empty
This is not what I wanted
IOS environment after the completion of the playback can still listen to the audio
I want him to be able to listen to the current audio even after he's finished playing it
