### ISSUE TITLE
Swipe to dismiss notification  

### ISSUE THREAD

**Issue by Mayb3Nots** [florent37/Flutter-AssetsAudioPlayer#447]
By doing some research I am slowly realizing that this might be a bug cause if this feature is already implemented then I couldn't swipe to dismiss even when a player is paused

**Comment by Mayb3Nots** [comment]
#85

**Comment by thecodersatish** [comment]
me too couldn't swipe notification on pause

**Comment by kalismeras61** [comment]
@Mayb3Nots can you add  below field on your open method and try again.

  playInBackground: PlayInBackground.enabled,

**Comment by Mayb3Nots** [comment]
> @Mayb3Nots can you add below field on your open method and try again.
> 
> playInBackground: PlayInBackground.enabled,

tried and still doesn't work.

**Comment by Mayb3Nots** [comment]
Also I feel like i should open a new issue but my notification recently went missing with it's time stamps and seek bar button
![Screenshot_20210131-193002](https://user-images.githubusercontent.com/68549184/106382481-e03d0000-63fa-11eb-9b4e-ab28e8015e16.jpg)

**Comment by kalismeras61** [comment]
@Mayb3Nots  can you use latest commit ?

**Comment by Mayb3Nots** [comment]
> @Mayb3Nots can you use latest commit ?

Still not resolved ;(

**Comment by kalismeras61** [comment]
In case, i can see seekbar. Can be device issue ? or please do flutter clean.

![notification](https://user-images.githubusercontent.com/246747/106389126-e29b5c00-63f2-11eb-90de-abfcd14b94d6.jpeg)

**Comment by Mayb3Nots** [comment]
> In case, i can see seekbar. Can be device issue ? or please do flutter clean.
> 
> ![notification](https://user-images.githubusercontent.com/246747/106389126-e29b5c00-63f2-11eb-90de-abfcd14b94d6.jpeg)

Did you use a custom notification icon? I tried to remove it and it worked. It seems like the issue is with the icon.

**Comment by kalismeras61** [comment]
No, i am not using custom icon. They are default icons.

**Comment by Mayb3Nots** [comment]
> No, i am not using custom icon. They are default icons.

could you try uploading a custom notification icon and see if the seek bar is missing? 
also can you swipe your notification? if so may I see some of your code?

**Comment by kalismeras61** [comment]
> > No, i am not using custom icon. They are default icons.
> 
> could you try uploading a custom notification icon and see if the seek bar is missing?
> also can you swipe your notification? if so may I see some of your code?

I just use  example. Can you try with example app ?

**Comment by Mayb3Nots** [comment]
> > > No, i am not using custom icon. They are default icons.
> > 
> > 
> > could you try uploading a custom notification icon and see if the seek bar is missing?
> > also can you swipe your notification? if so may I see some of your code?
> 
> I just use example. Can you try with example app ?

I checked and it seems like it is working for the example app since its also using custom icon... now I'm confused.
also i checked and the notification cant be swiped for the example app even when paused.

**Comment by kalismeras61** [comment]
> > > > No, i am not using custom icon. They are default icons.
> > > 
> > > 
> > > could you try uploading a custom notification icon and see if the seek bar is missing?
> > > also can you swipe your notification? if so may I see some of your code?
> > 
> > 
> > I just use example. Can you try with example app ?
> 
> I checked and it seems like it is working for the example app since its also using custom icon... now I'm confused.
> also i checked and the notification cant be swiped for the example app even when paused.

Yeah, i think you have to check your usage.

**Comment by Mayb3Nots** [comment]
> > > > > No, i am not using custom icon. They are default icons.
> > > > 
> > > > 
> > > > could you try uploading a custom notification icon and see if the seek bar is missing?
> > > > also can you swipe your notification? if so may I see some of your code?
> > > 
> > > 
> > > I just use example. Can you try with example app ?
> > 
> > 
> > I checked and it seems like it is working for the example app since its also using custom icon... now I'm confused.
> > also i checked and the notification cant be swiped for the example app even when paused.
> 
> Yeah, i think you have to check your usage.

but how about the ability to swipe the notification? It seems like I'm not the only one experiencing the same issue. although @florent37 mentioned here https://github.com/florent37/Flutter-AssetsAudioPlayer.git.

**Comment by Mayb3Nots** [comment]
@kalismeras61 i just found out the issue with the custom notification icon. It must be a vector asset format .XML. it cannot be a svg format. this should be documented.

**Comment by kalismeras61** [comment]
@Mayb3Nots ok got it. We can add this on readme file. If you found the problem and if it is working for you . Can you close this ?

**Comment by Mayb3Nots** [comment]
@kalismeras61 the notification still cant be swiped so no I can't close it. I only fixed the notification custom icon issue.

**Comment by Mayb3Nots** [comment]
I have found the issue, I think its related to #204

**Comment by Mayb3Nots** [comment]
The solution to bug is here #460.
Waiting for PR merge.
