### ISSUE TITLE
Next and Previous audios takes time to play

### ISSUE THREAD

**Issue by ManojDvs** [florent37/Flutter-AssetsAudioPlayer#449]
I am using the latest version of the plugin and when i call next or previous methods , it is taking long time to start next and previous audios .

**Comment by kalismeras61** [comment]
I depends on your network speed and also file size..

**Comment by ZhangZhiH** [comment]
I also have this problem that the Android environment is much faster than the iOS environment with the same file size on the network

**Comment by ZhangZhiH** [comment]
> 这取决于您的网络速度以及文件大小。
I have the same problem
Same file size and same network speed
The Android environment is much faster than the iOS environment

> It depends on your network speed and also file size..

I have the same problem
Same file size and same network speed
The Android environment is much faster than the iOS environment

**Comment by ZhangZhiH** [comment]
> It depends on your network speed and also file size..

I have the same problem
Same file size and same network speed
The Android environment is much faster than the iOS environment

**Comment by kalismeras61** [comment]
> > It depends on your network speed and also file size..
> 
> I have the same problem
> Same file size and same network speed
> The Android environment is much faster than the iOS environment

Which version are you using ?

**Comment by ZhangZhiH** [comment]
> > > 这取决于您的网络速度以及文件大小。
> > 
> > 
> > 我有相同的问题
> > 相同的文件大小和相同的网络速度
> > Android环境比iOS环境快得多
> 
> 您正在使用哪个版本？



> > > It depends on your network speed and also file size..
> > 
> > 
> > I have the same problem
> > Same file size and same network speed
> > The Android environment is much faster than the iOS environment
> 
> Which version are you using ?

Hello, the version number I used is 2.0.13+1

**Comment by ZhangZhiH** [comment]
> > > It depends on your network speed and also file size..
> > 
> > 
> > I have the same problem
> > Same file size and same network speed
> > The Android environment is much faster than the iOS environment
> 
> Which version are you using ?

Hello, the version number I used is 2.0.13+1

**Comment by Mayb3Nots** [comment]
hi @kalismeras61 can you look at this issue for me? https://github.com/florent37/Flutter-AssetsAudioPlayer/issues/447

**Comment by kalismeras61** [comment]
@ZhangZhiH  i merged some PR's but for some reason, it is not in pub.dev. Can you import project like below and let me know.

  assets_audio_player:
    git:
      url: https://github.com/iAmPlus/asset-audio-player.git
      ref: ac9f356b9be5eeb6972947224f2e9245ba40e3bf

**Comment by kalismeras61** [comment]
@Mayb3Nots  can you try also samething.

**Comment by Mayb3Nots** [comment]
@kalismeras61 when u used it in my pubspec it gave server unavailable errors

**Comment by kalismeras61** [comment]
> @kalismeras61 when I used it in my pubspec it gave server unavailable errors and this
> `stdout: stderr: fatal: ambiguous argument 'ac9f356': unknown revision or path not in the working tree.`
> I think you meant to use the main branch URL? even after that I get a version incompatibility with the web version
> `Because every version of assets_audio_player from git depends on assets_audio_player_web ^2.0.13+2 which doesn't match any versions, assets_audio_player from git is forbidden.`

The last commit used is id. Github is shortened automatically, you have to use it all. 

`ac9f356b9be5eeb6972947224f2e9245ba40e3bf`

**Comment by kalismeras61** [comment]
Sorry, it was my mistake, please try below. 

```
assets_audio_player:
git:
url: https://github.com/florent37/Flutter-AssetsAudioPlayer.git
ref: 5eb1cc3d9dace229c0510c327ed01db2c0619672
```

**Comment by Mayb3Nots** [comment]
@kalismeras61 Stil doesnt work
`Because every version of assets_audio_player from git depends on assets_audio_player_web ^2.0.13+2 which doesn't match any versions, assets_audio_player from git is forbidden.`

**Comment by kalismeras61** [comment]
I did, and changed ref. Please be fore commit id is  "5eb1cc3d9dace229c0510c327ed01db2c0619672"

**Comment by kalismeras61** [comment]
when try to add new version. Please remove puspec.lock file and try flutter clean and run flutter pub get.

**Comment by Mayb3Nots** [comment]
Still no hope after doing the above..

**Comment by kalismeras61** [comment]
> Still no hope after doing the above..
> ![image](https://user-images.githubusercontent.com/68549184/106364175-0cf40780-6368-11eb-8786-e1eb37f7e25f.png)

Okay found the problem. 
Please use this commit `6aee5ada6d751aa1edc5073515daea29bb1f47d4`  this should be work

**Comment by Mayb3Nots** [comment]
> > Still no hope after doing the above..
> > ![image](https://user-images.githubusercontent.com/68549184/106364175-0cf40780-6368-11eb-8786-e1eb37f7e25f.png)
> 
> Okay found the problem.
> Please use this commit `6aee5ada6d751aa1edc5073515daea29bb1f47d4` this should be work

This times it says 
`Because every version of assets_audio_player from git depends on assets_audio_player_web ^2.0.13+3 which doesn't match any versions, assets_audio_player from git is forbidden.
So, because fressic depends on assets_audio_player from git, version solving failed.`

**Comment by kalismeras61** [comment]
Are you using web ? if not please fork this repository and un comment assets_audio_player_web from pubspec.yaml in your repository. and use you repository link and commit.

**Comment by Mayb3Nots** [comment]
@kalismeras61 not using web and i forked it and removed comment still doesn't work. And also I think the author has to publish for it to update in pub.dev

**Comment by kalismeras61** [comment]
> @kalismeras61 not using web and i forked it and removed comment still doesn't work. And also I think the author has to publish for it to update in pub.dev

Yeah he should  do it. But he is not avaliable.  Sorry time is so late for me i think found the problem now :)))

can you try with this commit ?  `8ec5fef024fa56049f93db41e5db31ebc4a39ab5`

**Comment by Mayb3Nots** [comment]
@kalismeras61 just tested the latest version and the notification still cant be swiped when the music player is paused. :( Still wanna thank your time for trying to help the community

**Comment by kalismeras61** [comment]
> @kalismeras61 just tested the latest version and the notification still cant be swiped when the music player is paused. :( Still wanna thank your time for trying to help the community

In my case it is swiple, can you share your code ? how you are opening player ? ( open method)

**Comment by Mayb3Nots** [comment]
> > @kalismeras61 just tested the latest version and the notification still cant be swiped when the music player is paused. :( Still wanna thank your time for trying to help the community
> 
> In my case it is swiple, can you share your code ? how you are opening player ? ( open method)

this is my code
` Future<bool> playCurrentSong() async {
    bool result;
    print(audio.toString());

    try {
      await player
          .open(audio.value,
              showNotification: true,
              headPhoneStrategy: HeadPhoneStrategy.pauseOnUnplugPlayOnPlug)
          .then((value) => result = true);
      miniPlayer.setShowMiniPlayer;
    } catch (t) {
      result = false;
      print(t);
    }
    return result;
  }`

**Comment by ZhangZhiH** [comment]
> @ZhangZhiH 我合并了一些PR，但是由于某种原因，它不在pub.dev中。您可以像下面那样在您的项目中导入插件并让我知道。
> 
> asset_audio_player：
> git：
> 网址：[https](https://github.com/florent37/Flutter-AssetsAudioPlayer.git)
> : [//github.com/florent37/Flutter-AssetsAudioPlayer.git](https://github.com/florent37/Flutter-AssetsAudioPlayer/commit/ac9f356b9be5eeb6972947224f2e9245ba40e3bf)参考：[ac9f356](https://github.com/florent37/Flutter-AssetsAudioPlayer/commit/ac9f356b9be5eeb6972947224f2e9245ba40e3bf)



> @ZhangZhiH i merged some PR's but for some reason, it is not in pub.dev. Can you import plugin in your project like below and let me know.
> 
> assets_audio_player:
> git:
> url: https://github.com/florent37/Flutter-AssetsAudioPlayer.git
> ref: [ac9f356](https://github.com/florent37/Flutter-AssetsAudioPlayer/commit/ac9f356b9be5eeb6972947224f2e9245ba40e3bf)

Thank you very much for your help in your busy schedule
This has solved my problem
There is currently no lag on iOS
This is my solution
assets_audio_player:
git:
url: https://github.com/florent37/Flutter-AssetsAudioPlayer.git
ref: 8ec5fef024fa56049f93db41e5db31ebc4a39ab5

**Comment by ZhangZhiH** [comment]
> @ZhangZhiH i merged some PR's but for some reason, it is not in pub.dev. Can you import plugin in your project like below and let me know.
> 
> assets_audio_player:
> git:
> url: https://github.com/florent37/Flutter-AssetsAudioPlayer.git
> ref: [ac9f356](https://github.com/florent37/Flutter-AssetsAudioPlayer/commit/ac9f356b9be5eeb6972947224f2e9245ba40e3bf)

@kalismeras61 @ManojDvs
Thank you very much for your help in your busy schedule
This has solved my problem
There is currently no lag on iOS
This is my solution
`  
assets_audio_player: 

    git:

     url: https://github.com/florent37/Flutter-AssetsAudioPlayer.git

     ref: 8ec5fef024fa56049f93db41e5db31ebc4a39ab5

`
But I have another problem here
#446 
How to keep the state of the last music because when a finished music instance is automatically emptied This only happens in the Android environment

**Comment by kalismeras61** [comment]
@ManojDvs, Please use plugin like below.

assets_audio_player:
git:
 url: https://github.com/florent37/Flutter-AssetsAudioPlayer.git
 ref: 8ec5fef024fa56049f93db41e5db31ebc4a39ab5
