### ISSUE TITLE
Finished implementation missing

### ISSUE THREAD

**Issue by netojose** [florent37/Flutter-AssetsAudioPlayer#45]
The `finished` method not exists.

<img width="874" alt="Screenshot 2020-04-12 at 08 51 13" src="https://user-images.githubusercontent.com/134008/79062451-dcd55e00-7c9a-11ea-95ce-c1697d3180bb.png">

**Comment by florent37** [comment]
finished does not exists anymore, now you have 



playlistAudioFinished <---  Called when the current playlist song has finished

playlistFinished <--- Called when the complete playlist has finished to play

if you have only one audio, use playlistAudioFinished

**Comment by florent37** [comment]
I updated the README

**Comment by BringTheChill** [comment]
@florent37 it's not working on iOS
