### ISSUE TITLE
Unable to start receiver androidx.media.session.MediaButtonReceiver: java.lang.IllegalStateException: Could not find any Service that handles android.intent.action.MEDIA_BUTTON or implements a media browser service.

### ISSUE THREAD

**Issue by dong199101** [florent37/Flutter-AssetsAudioPlayer#450]
Fatal Exception: java.lang.RuntimeException
Unable to start receiver androidx.media.session.MediaButtonReceiver: java.lang.IllegalStateException: Could not find any Service that handles android.intent.action.MEDIA_BUTTON or implements a media browser service.
android.app.ActivityThread.handleReceiver
Caused by java.lang.IllegalStateException
Could not find any Service that handles android.intent.action.MEDIA_BUTTON or implements a media browser service.
androidx.media.session.MediaButtonReceiver.onReceive (MediaButtonReceiver.java:131)
android.app.ActivityThread.handleReceiver (ActivityThread.java:3846)
android.app.ActivityThread.access$1500 (ActivityThread.java:224)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1898)
android.os.Handler.dispatchMessage (Handler.java:107)
android.os.Looper.loop (Looper.java:224)
android.app.ActivityThread.main (ActivityThread.java:7562)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:539)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:950)

My android_apk happened crash in google firebase.
But i  am not register this Media_Button receiver in my whole project.
And i found 'android.intent.action.MEDIA_BUTTON' in flutter-'assets_audio_player'.
So i want to know, how i should to resolve this problem?

**Comment by kalismeras61** [comment]
It is already there but there is no new build for pub.dev . You can use last version of this package like below in your pubspec file.

assets_audio_player:
    git:
      url: https://github.com/florent37/Flutter-AssetsAudioPlayer.git
      ref: 7fcc470da3f50d007b93e8d6176545b0e06f070a
