### ISSUE TITLE
Media notification buttons aren't working cause of Workmanager

### ISSUE THREAD

**Issue by ayob2k** [florent37/Flutter-AssetsAudioPlayer#452]
When i used this plugin for the first time everything worked fine.. but after i added a lot of featurs to my app, i found out that Notification buttons aren't working anymore..
So i did my best to fix it, i changed version and everything and same issue remains.. it took me like 3 weeks to find out the problem, and i acctually found out that these Ntf Btns only get disabled when i use **Workmanager** plugin, and especially after i call **registerPeriodicTask**.. i'm using workmanager as shown below, any solution, thanks in adv :)

**Small code to reproduce**

```dart

import 'package:workmanager/workmanager.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  await Workmanager.initialize(callbackDispatcher, isInDebugMode: false);
      await Workmanager.registerPeriodicTask(
      "1",
      "Ntf",
      frequency: Duration(hours: 1),
      tag: "NtfW",
      existingWorkPolicy: ExistingWorkPolicy.append,
    );
  runApp(MyApp());
}


```

**Comment by arif2k17** [comment]
@ayob2k  any update on this bug? i am also facing same issue when is use `android_alarm_manager` plugin.

**Comment by kalismeras61** [comment]
@arif2k17  can you test with latest version ? 2.0.15

**Comment by AbanoubWagih94** [comment]
@florent37 @ayob2k @arif2k17 any update i also facing same issue

**Comment by ayob2k** [comment]
@AbanoubWagih94 @arif2k17  I end up using background fetch as i can remenber, its doing same work as work manager

**Comment by AbanoubWagih94** [comment]
@ayob2k can share code please.
i faced a problem app killed after certain time so i used workmanager to prevent that.
if background_fetch do same please share code if can
