### ISSUE TITLE
Build failed after importing AssetsAudioPlayer in pubspec.yaml

### ISSUE THREAD

**Issue by MuhammadKh** [florent37/Flutter-AssetsAudioPlayer#453]
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-2.0.13+1\android\src\main\kotlin\com\github\florent37\assets_audio_player\Player.kt: (542, 5): 'handleMessage' overrides nothing
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-2.0.13+1\android\src\main\kotlin\com\github\florent37\assets_audio_player\Player.kt: (543, 29): Type mismatch: inferred type is Message? but Message was expected
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-2.0.13+1\android\src\main\kotlin\com\github\florent37\assets_audio_player\notification\NotificationActionReceiver.kt: (12, 85): Type mismatch: inferred type is String? but String was expected
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-2.0.13+1\android\src\main\kotlin\com\github\florent37\assets_audio_player\notification\NotificationActionReceiver.kt: (30, 39): Type mismatch: inferred type is Intent? but Intent was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':assets_audio_player:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 17s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by kalismeras61** [comment]
Can you run flutter clean and try ?

**Comment by kalismeras61** [comment]
@MuhammadKh please do flutter clean and reinstall again. Closing for now.

**Comment by MuhammadKh** [comment]
It doesn't work for me
even I uninstall flutter and android studio then install them again
but still show same error while importing assets audio player in
pubspc.yaml

**Comment by MuhammadKh** [comment]
Thanks for your email
