### ISSUE TITLE
Update to the newest rxdart version (0.25.0)

### ISSUE THREAD

**Issue by robertoltrocha** [florent37/Flutter-AssetsAudioPlayer#456]
Hi,
Please, could you uptade to the newest rxdart?
thanks

```
Because sii depends on assets_audio_player from git which depends on rxdart ^0.24.1, rxdart ^0.24.1 is required.
So, because sii depends on rxdart 0.25.0, version solving failed.
pub get failed (1; So, because sii depends on rxdart 0.25.0, version solving failed.)
```

**Comment by Mayb3Nots** [comment]
created a PR #457

**Comment by kalismeras61** [comment]
Pr merged! Thanks @Mayb3Nots . Please use latest commit.

**Comment by robertoltrocha** [comment]
Hi,

I'm sorry for my ignorance, I'm new to the flutter, do I have to do anything? I still have the reported problem. Do I have to wait for a new publication?

assets_audio_player:
    git:
      url: https://github.com/florent37/Flutter-AssetsAudioPlayer.git
      ref: b49a4360f6a7f182d4a6e23ebcdbf43ad570913b

**Comment by Mayb3Nots** [comment]
> Hi,
> 
> I'm sorry for my ignorance, I'm new to the flutter, do I have to do anything? I still have the reported problem. Do I have to wait for a new publication?
> 
> assets_audio_player:
> git:
> url: https://github.com/florent37/Flutter-AssetsAudioPlayer.git
> ref: [b49a436](https://github.com/florent37/Flutter-AssetsAudioPlayer/commit/b49a4360f6a7f182d4a6e23ebcdbf43ad570913b)

try
assets_audio_player:
 git:
  url: https://github.com/florent37/Flutter-AssetsAudioPlayer.git
  ref: b49a4360f6a7f182d4a6e23ebcdbf43ad570913b

**Comment by robertoltrocha** [comment]
@Mayb3Nots 
The same issue.
 assets_audio_player:
    git:
      url: https://github.com/florent37/Flutter-AssetsAudioPlayer.git
      ref: b49a4360f6a7f182d4a6e23ebcdbf43ad570913b

I applied: 
-  flutter pub cache repair
- flutter clean
- flutter pub get



```
Because sii depends on assets_audio_player from git which depends on rxdart ^0.24.1, rxdart ^0.24.1 is required.
So, because sii depends on rxdart 0.25.0, version solving failed.
pub get failed (1; So, because sii depends on rxdart 0.25.0, version solving failed.)
```

**Comment by kalismeras61** [comment]
@robertoltrocha  Every commit has different feature, new commit id is `43c886159139303924ea7214e04507d594487d57`

You can use like that.

assets_audio_player:
 git:
  url: https://github.com/florent37/Flutter-AssetsAudioPlayer.git
  ref: master

**Comment by robertoltrocha** [comment]
@kalismeras61 
it is working now.
Thank you
