### ISSUE TITLE
Xcode build failed

### ISSUE THREAD

**Issue by erolasan** [florent37/Flutter-AssetsAudioPlayer#46]
I saw that there are already issues about this but i tried 'flutter clean' and i still get:
`/Users/erolasan/flutter/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-1.3.0/ios/Classes/Asset
    sAudioPlayer.swift:5:14: error: invalid redeclaration of 'SwiftAssetsAudioPlayerPlugin'
    public class SwiftAssetsAudioPlayerPlugin: NSObject, FlutterPlugin {     
    /Users/erolasan/flutter/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-1.3.0/ios/Classes/Swift
    AssetsAudioPlayerPlugin.swift:4:14: note: 'SwiftAssetsAudioPlayerPlugin' previously declared here
    public class SwiftAssetsAudioPlayerPlugin: NSObject, FlutterPlugin {`

I tried deleting Pods folder -> pod install -> flutter clean - xcode build and i still get the same error

**Comment by rwebster2012** [comment]
Also getting the same error as erolasan as of this morning

**Comment by MsXam** [comment]
As the error states, there are two re-declarations of the same swift class. You can force the correct class to be used by explicitly specifying a #if compiler directive that looks for a specific swift version and then load that class when the version is met. You would then need to specify a **global platform** version, i.e 11.0

If you dont want to get down this route - if you follow this process below **EXACTLY** your compiler issue will go and you will be able to use this plugin. ** Note ** Until the plugin author resolves the duplicated class - you may have to repeat this process when ever you refresh this PLUGIN in your .pub-cache folder.

![image](https://user-images.githubusercontent.com/18722796/79376389-01a72b00-7f52-11ea-82fc-67d7d782227e.png)

**Comment by florent37** [comment]
hi, i'm trying to resolve it but don't know where to search, in the repo I only have one SwiftAssetsAudioPlayerPlugin.swift file, any idea ?

**Comment by florent37** [comment]
Oh I found it, its in the AssetsAudioPlayer.swift file, I remove it and push a new version !

**Comment by florent37** [comment]
I fixed it, sorry for that, and published a v1.3.1

I created a sample project with the 1.3.0, found the same error as you,
I updated to 1.3.1 -> no error anymore, so it should be fixed !

thanks for the issue, cheers
