### ISSUE TITLE
com.github.florent37.assets_audio_player.playerimplem.PlayerFinder$NoPlayerFoundException

### ISSUE THREAD

**Issue by mfaizk** [florent37/Flutter-AssetsAudioPlayer#462]
**Flutter Version**
Flutter 1.22.6 • channel stable
My version : 
Flutter 1.22.6 • channel stable
**Lib Version**
assets_audio_player: ^2.0.13+1
My version : 
assets_audio_player: ^2.0.13+1
**Platform (Android / iOS / web) + version**
Android 11
Platform : 

**Describe the bug**
assets_audio_player.playerimplem.PlayerFinder$NoPlayerFoundException
I/TetheringManager( 4448): registerTetheringEventCallback:com.anthem.player.anthem_music_player
W/em_music_playe( 4448): Accessing hidden method Landroid/media/AudioTrack;->getLatency()I (greylist, reflection, allowed)
I/ExoPlayerImpl( 4448): Init 642230a [ExoPlayerLib/2.11.4] [generic_x86_arm, sdk_gphone_x86_arm, Google, 30]
I/ExoPlayerImpl( 4448): Release 642230a [ExoPlayerLib/2.11.4] [generic_x86_arm, sdk_gphone_x86_arm, Google, 30] [goog.exo.core]
V/MediaPlayer( 4448): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 4448): cleanDrmObj: mDrmObj=null mDrmSessionId=null      
W/System.err( 4448): com.github.florent37.assets_audio_player.playerimplem.PlayerFinder$NoPlayerFoundException
W/System.err( 4448):    at com.github.florent37.assets_audio_player.playerimplem.PlayerFinder._findWorkingPlayer(PlayerFinder.kt:68)
W/System.err( 4448):    at com.github.florent37.assets_audio_player.playerimplem.PlayerFinder._findWorkingPlayer(PlayerFinder.kt:86)
W/System.err( 4448):    at com.github.florent37.assets_audio_player.playerimplem.PlayerFinder$_findWorkingPlayer$1.invokeSuspend(Unknown Source:12)
W/System.err( 4448):    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
W/System.err( 4448):    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:55)
W/System.err( 4448):    at android.os.Handler.handleCallback(Handler.java:938)
W/System.err( 4448):    at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err( 4448):    at android.os.Looper.loop(Looper.java:223)      
W/System.err( 4448):    at android.app.ActivityThread.main(ActivityThread.java:7656)
W/System.err( 4448):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 4448):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
W/System.err( 4448):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
**Small code to reproduce**
loadSongs() async {
    FlutterAudioQuery query = new FlutterAudioQuery();

    List<SongInfo> songInfo = await query.getSongs();
    List<Audio> audioList = new List<Audio>();

    songInfo.forEach((element) {
      audioList.add(Audio(element.filePath,
          metas: Metas(
            title: element.title.isEmpty ? "Title Not Found" : element.title,
            artist:
                element.artist.isEmpty ? "Artist Not Found" : element.artist,
            album:
                element.album.isEmpty ? "Album Name Not Found" : element.album,
          )));
    });

    try {
      
      await audioAssetplayer.open(
        Playlist(audios: audioList),
        headPhoneStrategy: HeadPhoneStrategy.pauseOnUnplugPlayOnPlug,
        audioFocusStrategy:
            AudioFocusStrategy.request(resumeAfterInterruption: true),
      );
    } on Exception catch (e) {
      print(e);
    }
  }

**Comment by Mayb3Nots** [comment]
Hi how do you resolve this issue? I had this issue also.

**Comment by mfaizk** [comment]
songInfo.forEach((element) {
      this.audioList.add(Audio.file(element.filePath,
          metas: Metas(
            title: element.title.isEmpty ? "Title Not Found" : element.title,
            artist:
                element.artist.isEmpty ? "Artist Not Found" : element.artist,
            album:
                element.album.isEmpty ? "Album Name Not Found" : element.album,
            image: element.album.isEmpty
                ? null
                : MetasImage.file(element.albumArtwork),
          )));
    });



this.audioList.add(Audio.file(element.filePath, 
This Audio.file is main problem i am generating list worng thts why its creating problem

**Comment by Mayb3Nots** [comment]
what do you mean by generating a list wrong? How did you solve it then?

**Comment by mfaizk** [comment]
To open playlist you need to list of songs see my for.each loop function which is generating list of songs and match both you will understand what i am trying to say. One uses audio.file and previous one has only audio .

**Comment by Mayb3Nots** [comment]
> To open playlist you need to list of songs see my for.each loop function which is generating list of songs and match both you will understand what i am trying to say. One uses audio.file and previous one has only audio .

Omg yea that is the same issue with mine! Wow thanks a lot kind sir, you just saved me hours!

**Comment by Mayb3Nots** [comment]
It should also be changed or written in the documentation. I was confused why it doest work even after following documentation.
