### ISSUE TITLE
Multi players not working on new version

### ISSUE THREAD

**Issue by kobeumut** [florent37/Flutter-AssetsAudioPlayer#466]
**Flutter Version**

My version :  1.26.0-12.0.pre

**Lib Version**

My version :  ^2.0.13+7

**Platform (Android / iOS / web) + version**

Platform : IOS / Android

**Describe the bug**

I try below code but it's not working at the same time. Certainly only last audio plays in your new version. I try 2.0.13+7, 2.0.13+6 neither works. And then I tried main_multiples.dar in your example. It's not working too. After then I try old version 2.0.13 in my app also yours', that's working all audio's same time. 

**Small code to reproduce**

```dart
var player = AssetsAudioPlayer.newPlayer();
var player1 = AssetsAudioPlayer.newPlayer();
var player2 = AssetsAudioPlayer.newPlayer();
```

**Comment by kalismeras61** [comment]
@kobeumut  i applied to fix. Can you try with 2.0.13+8 ?

**Comment by kobeumut** [comment]
I tried IOS and Android, it's working now. Thanks.
