### ISSUE TITLE
flutter: log: resource not found | iOS 

### ISSUE THREAD

**Issue by pinkeshdarji** [florent37/Flutter-AssetsAudioPlayer#469]
It works fine in Android but not in iOS.

Library version
assets_audio_player: ^2.0.9+2

Here is the exact error:
**flutter: log: resource not found /assets/audios/song/001 song1.mp3**

[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.7 19H114 darwin-x64, locale en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.43.0)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (2 available)

! Doctor found issues in 2 categories.
---------------------------------------
I am testing on iPhone 12 Max pro **emulator** with iOS  14.3

**Comment by kalismeras61** [comment]
There is a empty space in the song name ? can you remove it and try ? Please let me know if it is work or not.

**Comment by pinkeshAubergine** [comment]
Hey @kalismeras61 Removing space in the song name seems to be working fine.
Thanks for the help.

Just wondering why this difference exists in the Android and iOS platforms

**Comment by kalismeras61** [comment]
@pinkeshAubergine will explain you on teams :)))I left a message.

**Comment by gronka** [comment]
I have this error. There are no spaces in my asset names. I have names such as res_man_eating.mp3

`flutter: log: resource not found assets/sounds/res_man_eating.mp3`
