### ISSUE TITLE
Couldn't get artist cover url.

### ISSUE THREAD

**Issue by yubarajshrestha** [florent37/Flutter-AssetsAudioPlayer#472]
albumArt field is giving null. Tried different approaches but couldn't resolve the issue with cover url. Is there anyway we can convert **Uint8List** to MetasImage? Really needed help in this please.

**Comment by Mayb3Nots** [comment]
To convert `Uint8List `to `MetasImage `you have to create a new `MetasImage `using the constructor` .Asset` or `.File` and attach it to the player.

**Comment by yubarajshrestha** [comment]
> To convert `Uint8List `to `MetasImage `you have to create a new `MetasImage `using the constructor` .Asset` or `.File` and attach it to the player.

A basic example if you have time.

**Comment by Mayb3Nots** [comment]
First, you get the `Uint8List `and store it in a file. 
By using [path_provider](https://pub.dev/packages/path_provider) to get a getTemporaryDirectory then store it.
If you don't know how then refer to this [article ](https://programmingwithswift.com/how-to-save-a-file-locally-with-flutter/).

Then once you store the `Uint8List `into a file you can now get the path of the file and then insert inside the `MetaImage.file() `constructor.

```
AssetsAudioPlayer().open(Audio.network(
          url,
          metas: Metas(
              artist: "Kyle Watson",
              title: "Wurkit (Original Mix)",
              image: MetasImage.file(filePath),
        )
    )
);

```

**Comment by yubarajshrestha** [comment]
> First, you get the `Uint8List `and store it in a file.
> By using [path_provider](https://pub.dev/packages/path_provider) to get a getTemporaryDirectory then store it.
> If you don't know how then refer to this [article ](https://programmingwithswift.com/how-to-save-a-file-locally-with-flutter/).
> 
> Then once you store the `Uint8List `into a file you can now get the path of the file and then insert it inside the `MetaImage.file() `constructor.
> 
> ```
> AssetsAudioPlayer().open(Audio.network(
>           url,
>           metas: Metas(
>               artist: "Kyle Watson",
>               title: "Wurkit (Original Mix)",
>               image: MetasImage.file(filePath),
>         )
>     )
> );
> ```

Thanks.
