### ISSUE TITLE
incompatible with AndroidX

### ISSUE THREAD

**Issue by Mouslim2021** [florent37/Flutter-AssetsAudioPlayer#476]
**Flutter Version**

My version : 

**Lib Version**

My version : 

**Platform (Android / iOS / web) + version**

Platform : 

**Describe the bug**

**Small code to reproduce**

```dart
import 'package:assets_audio_player/assets_audio_player.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State {
  
  final AssetsAudioPlayer _assetsAudioPlayer = AssetsAudioPlayer();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: RaisedButton(
            child: Text("open"),
            onPressed: () {
              //open code here
            }
          ),
        ),
      ),
    );
  }
}
```

**Comment by Mouslim2021** [comment]
When I try to build App apk I got the error that it's not compatible with AndroidX. The screenshot is below.

![2](https://user-images.githubusercontent.com/62414871/109373052-a7326700-78a4-11eb-9e50-ccb148703882.JPG)

**Comment by kalismeras61** [comment]
@Mouslim2021 this is not related to AndroidX will fix it.

**Comment by kalismeras61** [comment]
Pr Merged please use latest version.

**Comment by Mouslim2021** [comment]
Okay....

Le lun. 1 mars 2021 à 15:40, Yasin ilhan ***@***.***> a
écrit :
