### ISSUE TITLE
MetasImage.asset do not work to show notification placeholder with local asset ? 

### ISSUE THREAD

**Issue by mayouf** [florent37/Flutter-AssetsAudioPlayer#477]
**Flutter Version**

My version :  Flutter Channel stable, 1.22.5

**Lib Version**

My version : ^2.0.13+6

**Platform (Android / iOS / web) + version**

Platform : Android 

**Describe the bug**

The notification image do not show up when we use a local file by using these following settings:
```
Audio(
"assets/audios/rock.mp3",
 metas: Metas(
        title: "Rock",
        artist: "Florent Champigny",
        album: "RockAlbum",
        image: MetasImage.asset("assets/images/country.jpg"),
      ),
    )
```

ONLY THE NETWORK works with this:
```
image: MetasImage.network("https://static.radio.fr/images/broadcasts/cb/ef/2075/c300.png"),
```

When the notification placeholder do not show the `MetasImage.asset` that we provide, it automatically show the notification placeholder specified in the AndroidManifest.xml as below:
```
<meta-data
            android:name="assets.audio.player.notification.place.holder"
            android:resource="@drawable/notification_place_holder"/>
```
wich corresponds to this image:
<img src="https://user-images.githubusercontent.com/5865600/109399373-c089f080-7942-11eb-853e-8d0d16ca9872.jpg"  width="200">        <img src="https://user-images.githubusercontent.com/5865600/109399388-de575580-7942-11eb-81da-c5f136b47de6.png"  width="200">

**Small code to reproduce**

:warning: **I used the main_builder.dart file from the example folder in the plugin.**

**Comment by vemla-solutions** [comment]
Same issue here on Flutter (Channel stable, 1.22.6) and assets_audio_player: ^2.0.13+6, but even worse, as neither image from asset and also placeholder in Manifest work.
The notification is still with blank background:
![image](https://user-images.githubusercontent.com/79815144/109507996-a285d280-7a9f-11eb-9ebf-b9a6e3298c5b.png)

@mayouf could you please share how you added resource in drawable and which type you used? Did you use Image Asset in Android studio? As at least this is some workaround, because we just need one background (app relevant) for all sounds.
I tried to add images in both all drawable folders and also mipmap ones, and still the resource is not taken from Manifest:
`<meta-data
                android:name="assets.audio.player.notification.place.holder"
                android:resource="@drawable/pic"/>`

**Comment by mayouf** [comment]
Hi @vemla-solutions 

Here what I did, let me know if this helped :

1. I created a placeholder PNG image of 510x340. You can have transparent background, it will be automatically switched to black. I called this file "notification_place_holder.png".
<img src="https://user-images.githubusercontent.com/5865600/109642509-5d22dd00-7b53-11eb-8a23-6867b8683a88.png" width="300">

2. I inserted this file in the following folder in the project :
 `android/app/src/main/res/drawable/notification_place_holder.png`
<img src="https://user-images.githubusercontent.com/5865600/109640804-382d6a80-7b51-11eb-8c72-b108aabef114.png" width="300">
 
3. in `android/app/src/main/AndroidManifest.xml`, I insert this line at the very end as below:
<img src="https://user-images.githubusercontent.com/5865600/109640717-1c29c900-7b51-11eb-96af-bc7dccad78a4.png"  width="500">

4. Then, in my code, I called the audioplayer like below:

```
  @override
  Widget build(BuildContext context) {
    assetsAudioPlayer.open(
      Audio(
        "write the path to the audio in assets",
        metas: Metas(
          title: "Online",
          image: MetasImage.network("write the image png path of 510x340 size "),
          artist: "Florent Champigny",
        ),
      ),
      showNotification: true,
      autoStart: true,
    );
```

RESULT:

<img src="https://user-images.githubusercontent.com/5865600/109642202-f1d90b00-7b52-11eb-94ee-3290ce56be8b.png" width="300">

**Comment by vemla-solutions** [comment]
@mayouf  thank you for your very detailed response, thanks to this, I could find how to make it work.
The problem on my side was that I put meta-data info inside application / activity element of the Manifest, and there it didn't work, but it worked when I put at the end of the application, like on your screenshot.

My findings, for this to work, you don't need to have 510*340 image, any size works, even square one.
And in the code, you don't need to specify image attribute of Metas at all. If it is not defined, it just takes it from Android manifest settings.

Also with the same fix I could resolve the icon display, as it has to be placed inside application element of the Manufest as well and fixed: https://github.com/florent37/Flutter-AssetsAudioPlayer/issues/479

Thanks again!
PS
But the bug described still holds, as setting the notification image via asset doesn't work (e.g. when you need to change the cover based on sound played). The workaround only fixes when one image needs to be used per application for all sounds.

**Comment by mayouf** [comment]
Hi @vemla-solutions 

### **IMAGE SIZE**
YES you are right. The image is automatically resized with the Glide library (used internally). No need to prepare any image.

### **PLACEHOLDER (image by default)**
YES you are right again, you don't need to specify any image in META. ONLY if you want to keep the same image on notification. This image by default is called the "placeholder". A placeholder is the temporary image, until the real image is ready to be displayed OR if loading of the image fails.

SO if you don't specify any image in meta, it will display automatically the placeholder (which is the image specified in AndroidManifest.xml at the very bottom as you found out (-: ) below:
```
<meta-data
    android:name="assets.audio.player.notification.place.holder"
    android:resource="@drawable/notification_place_holder"/>
```

### **IMAGE VIA ASSET**
That's a pain in ass, it drives me crazy. I give up, I tried to modify this file  `ImageDownloader.kt`. This is where `Glide `is used to call image through `MetasImage.asset` `MetasImage.network `and `MetasImage.file`. I FAILED lool !! 

Im not sure what is the issue, but it seems to be related the **Scoped Storage**, this is a new tool from Andoid Q. It impacts the app all the way as soon as we are leveraging local file access.

I tried tinkering with permissions in AndroidManifest.xml by :

- adding 
`<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>`

- adding 
`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"
        android:maxSdkVersion="28" />`

- adding
```
<application
        android:label="application name here"
        android:requestLegacyExternalStorage="true"
        android:preserveLegacyExternalStorage="true"
```
But the issue is still here in this line 61 from this file `Flutter-AssetsAudioPlayer/android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/ImageDownloader.kt:`

Here `filePath ` is the problem, it throws an exception (No such file or directory)
```
FlutterLoader.getInstance().getLookupKeyForAsset(filePath) 
 ```

I tried to also to remove all the code related to path and deal directly with GLIDE. So I changed the URI passed to Glide:
```
Glide.with(context)
  .asBitmap()
  .timeout(5000)
  .load(uri) // here I tried many way 
  .into(object : CustomTarget<Bitmap>() {
      override fun onLoadFailed(errorDrawable: Drawable?) {
          continuation.resumeWithException(Exception("failed to download $filePath"))
      }
  
      override fun onResourceReady(resource: Bitmap, transition: Transition<in Bitmap>?) {
          continuation.resume(resource)
      }
  
      override fun onLoadCleared(placeholder: Drawable?) {
  
      }
  })
```

I still kept having this error below:

```
[ +127 ms] W/Glide   (21596): Load failed for assets/images/young_girl_listening.png with size [-2147483648x-2147483648]
[        ] W/Glide   (21596): class com.bumptech.glide.load.engine.GlideException: Failed to load resource
[        ] W/Glide   (21596): There were 3 causes:
[        ] W/Glide   (21596): java.io.FileNotFoundException(/assets/images/young_girl_listening.png (No such file or directory))
[        ] W/Glide   (21596): java.io.FileNotFoundException(open failed: ENOENT (No such file or directory))
[        ] W/Glide   (21596): java.io.FileNotFoundException(open failed: ENOENT (No such file or directory))
[        ] W/Glide   (21596):  call GlideException#logRootCauses(String) for more detail
```

So I stopped trying to solve this, Hopefully someone will find out.

**Comment by mayouf** [comment]
Hi @florent37 

Maybe you could use some help with this tutorial about being prepared for Scoped Storage:
[https://www.raywenderlich.com/10217168-preparing-for-scoped-storage](https://www.raywenderlich.com/10217168-preparing-for-scoped-storage)

With Android 11, Some major changes and restrictions are added to enhance user privacy, including this damn **Scoped storage** enforcement. 

The access into external storage directories is limited to an app-specific directory and specific types of media that the app has created.

Have a look on the screenshot. It seems to explain how you can update `Resolver.kt` to make it compatible with ANDROID 11.
I tried by myself, Im not a dev basically, And I did not make it.

![image](https://user-images.githubusercontent.com/5865600/109809977-3e8f1580-7c29-11eb-9a84-c17cd72f6b8d.png)

![image](https://user-images.githubusercontent.com/5865600/109810022-4d75c800-7c29-11eb-91e3-522b5102acc9.png)

**Comment by kalismeras61** [comment]
@mayouf  we have fix for that with this https://github.com/florent37/Flutter-AssetsAudioPlayer/pull/482 PR. I don't have time to check the PR will do it this weekend. If you have time can you check it ?

**Comment by mayouf** [comment]
Hi again @florent37 

I just read something on [https://developer.android.com/training/data-storage](https://developer.android.com/training/data-storage).
<img src="https://user-images.githubusercontent.com/5865600/109810766-3be0f000-7c2a-11eb-8a7a-a5a6b3ac4982.png" width="650">

If I got it right, MEDIA STORE API is required for EXTERNAL_STORAGE.

But for the `MetasImage.asset` and `MetasImage.file`, we need to access internal storage, which requires no permission. 

### My question is : 

**Is it possible that the plugin is wrong about using MEDIASTORE API, instead of FILE API, to access app-specific storage, i.e internal storage ?**

_DISCLAIMER: As I said, im not a dev basically._

Here is also another screenshot about which API to use to access app specific storage:

<img src="https://user-images.githubusercontent.com/5865600/109812189-105f0500-7c2c-11eb-9054-3fbbbe34e1e4.png" width="650">

Merci d'avance @florent37, je laisse en anglais pour les autres devs

**Comment by mayouf** [comment]
> @mayouf we have fix for that with this #482 PR. I don't have time to check the PR will do it this weekend. If you have time can you check it ?

Hi @kalismeras61 

Im ashamed to say it, but Im not a dev basically. I learned very recently. I don't even know what is rhe "PR". I just spent so much time on this issue, I wish I could do it. 
I'll be glad if you can point me to documentation to how we check the "PR" so I can help in future. 

Sorry for not being helpful, maybe soon

**Comment by mayouf** [comment]
Thanks for @kalismeras61 

It works like a charms ! Yo are my hero !

**Comment by kalismeras61** [comment]
Fixed please use latest version. 2.0.15
