### ISSUE TITLE
Notification icon is not customized

### ISSUE THREAD

**Issue by vemla-solutions** [florent37/Flutter-AssetsAudioPlayer#479]
**Flutter Version**

My version :  Channel stable, 1.22.6

**Lib Version**

My version :  assets_audio_player: ^2.0.13+6

**Platform (Android / iOS / web) + version**

Platform :  Android 10.0

**Describe the bug**

The notification icon is not customized.

**Small code to reproduce**

I create a custom notification icon through Image Assets in Android Studio:
![image](https://user-images.githubusercontent.com/79815144/109509324-107ec980-7aa1-11eb-9b54-f988c2565f7d.png)

![image](https://user-images.githubusercontent.com/79815144/109509445-2be9d480-7aa1-11eb-966b-1bb0040f828d.png)

Then in app/src/main/AndroidManifest.xml I add inside **application/activity** element:
`<meta-data
     android:name="assets.audio.player.notification.icon"
     android:resource="@drawable/ic_music_custom"/>
`

But when player is started and notification displayed:
```dart
playerNotification = AssetsAudioPlayer();
      playerNotification.open(
        Audio('assets/sounds/sound.ogg'),
        loopMode: LoopMode.single,
        showNotification: true,
      );
```

Still the standard library notification icon is displayed instead:
![image](https://user-images.githubusercontent.com/79815144/109510115-eda0e500-7aa1-11eb-8c83-5498f5bbb02a.png)

There are no error logs for this.

**Comment by vemla-solutions** [comment]
The solution is to put icon settings inside application element of the Manifest file directly, and then it works. I put it inside application / activity and it didn't work. The issue can be closed, but I suggest to update the documentation to make it more clear.
Thank you!

**Comment by txufiknr** [comment]
> The solution is to put icon settings inside application element of the Manifest file directly, and then it works. I put it inside application / activity and it didn't work. The issue can be closed, but I suggest to update the documentation to make it more clear. Thank you!

Would you give me the code or screenshot for the solution?
