### ISSUE TITLE
Loop Bug

### ISSUE THREAD

**Issue by mmarlonsodre1** [florent37/Flutter-AssetsAudioPlayer#48]
When setting the loop to true.
If I change the volume, it resets on restarting the song

**Comment by florent37** [comment]
are you on android / ios / web ?

**Comment by mmarlonsodre1** [comment]
Android

**Comment by florent37** [comment]
fixed, can you try the `1.3.5`

I tried it on android & ios

**Comment by mmarlonsodre1** [comment]
Error due to web version



Compiler message:
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-1.3.5+1/lib/assets_audio_player_web.dart:2:8: Error: Not found: 'dart:html'
import 'dart:html';
       ^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/import_js_library-1.0.1/lib/import_js_library_web.dart:2:8: Error: Not found: 'dart:html'
import 'dart:html' as html;
       ^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/js-0.6.1+1/lib/js.dart:8:1: Error: Not found: 'dart:js'
export 'dart:js' show allowInterop, allowInteropCaptureThis;
^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/import_js_library-1.0.1/lib/import_js_library_web.dart:10:10: Error: Type 'html.ScriptElement' not found.
  static html.ScriptElement _createScriptTag(String library) {
         ^^^^^^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/import_js_library-1.0.1/lib/import_js_library_web.dart:37:25: Error: Type 'html.Element' not found.
  static bool _isLoaded(html.Element head, String url) {
                        ^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-1.3.5+1/lib/assets_audio_player_web.dart:99:13: Error: The getter 'window' isn't defined for the class '_WebPlayer'.
 - '_WebPlayer' is from 'package:assets_audio_player/assets_audio_player_web.dart' ('/C:/flutter/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-1.3.5+1/lib/assets_audio_player_web.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'window'.
    path = (window.location.href.replaceAll("/#/", "") + "/assets/" + path);
            ^^^^^^

Compiler message:
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-1.3.5+1/lib/assets_audio_player_web.dart:2:8: Error: Not found: 'dart:html'
import 'dart:html';
       ^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/import_js_library-1.0.1/lib/import_js_library_web.dart:2:8: Error: Not found: 'dart:html'
import 'dart:html' as html;
       ^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/js-0.6.1+1/lib/js.dart:8:1: Error: Not found: 'dart:js'
export 'dart:js' show allowInterop, allowInteropCaptureThis;
^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_web_howl-1.0.0/lib/howl.dart:66:9: Error: The method 'allowInterop' isn't defined for the class 'Howl'.
 - 'Howl' is from 'package:flutter_web_howl/howl.dart' ('/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_web_howl-1.0.0/lib/howl.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
        allowInterop(callback),
        ^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/import_js_library-1.0.1/lib/import_js_library_web.dart:10:10: Error: Type 'html.ScriptElement' not found.
  static html.ScriptElement _createScriptTag(String library) {
         ^^^^^^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/import_js_library-1.0.1/lib/import_js_library_web.dart:37:25: Error: Type 'html.Element' not found.
  static bool _isLoaded(html.Element head, String url) {
                        ^^^^^^^^^^^^
/C:/flutter/packages/flutter_web_plugins/lib/src/plugin_registry.dart:29:5: Error: Method not found: 'webOnlySetPluginHandler'.
    ui.webOnlySetPluginHandler(_binaryMessenger.handlePlatformMessage);
    ^^^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/import_js_library-1.0.1/lib/import_js_library_web.dart:11:16: Error: 'ScriptElement' isn't a type.
    final html.ScriptElement script = html.ScriptElement()
               ^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/import_js_library-1.0.1/lib/import_js_library_web.dart:11:39: Error: Method not found: 'ScriptElement'.
    final html.ScriptElement script = html.ScriptElement()
                                      ^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/import_js_library-1.0.1/lib/import_js_library_web.dart:24:18: Error: Method not found: 'querySelector'.
    final head = html.querySelector('head');
                 ^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/import_js_library-1.0.1/lib/import_js_library_web.dart:37:30: Error: 'Element' isn't a type.
  static bool _isLoaded(html.Element head, String url) {
                             ^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/import_js_library-1.0.1/lib/import_js_library_web.dart:42:27: Error: 'ScriptElement' isn't a type.
      if (element is html.ScriptElement) {
                          ^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/import_js_library-1.0.1/lib/import_js_library_web.dart:52:18: Error: Method not found: 'querySelector'.
    final head = html.querySelector('head');
                 ^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-1.3.5+1/lib/assets_audio_player_web.dart:99:13: Error: The getter 'window' isn't defined for the class '_WebPlayer'.
 - '_WebPlayer' is from 'package:assets_audio_player/assets_audio_player_web.dart' ('/C:/flutter/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-1.3.5+1/lib/assets_audio_player_web.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'window'.
    path = (window.location.href.replaceAll("/#/", "") + "/assets/" + path);
            ^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_web_howl-1.0.0/lib/howl.dart:66:9: Error: The method 'allowInterop' isn't defined for the class 'Howl'.
 - 'Howl' is from 'package:flutter_web_howl/howl.dart' ('/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_web_howl-1.0.0/lib/howl.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
        allowInterop(callback),
        ^^^^^^^^^^^^
/C:/flutter/packages/flutter_web_plugins/lib/src/plugin_registry.dart:29:5: Error: Method not found: 'webOnlySetPluginHandler'.
    ui.webOnlySetPluginHandler(_binaryMessenger.handlePlatformMessage);
    ^^^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/import_js_library-1.0.1/lib/import_js_library_web.dart:11:16: Error: 'ScriptElement' isn't a type.
    final html.ScriptElement script = html.ScriptElement()
               ^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/import_js_library-1.0.1/lib/import_js_library_web.dart:11:39: Error: Method not found: 'ScriptElement'.
    final html.ScriptElement script = html.ScriptElement()
                                      ^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/import_js_library-1.0.1/lib/import_js_library_web.dart:24:18: Error: Method not found: 'querySelector'.
    final head = html.querySelector('head');
                 ^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/import_js_library-1.0.1/lib/import_js_library_web.dart:37:30: Error: 'Element' isn't a type.
  static bool _isLoaded(html.Element head, String url) {
                             ^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/import_js_library-1.0.1/lib/import_js_library_web.dart:42:27: Error: 'ScriptElement' isn't a type.
      if (element is html.ScriptElement) {
                          ^^^^^^^^^^^^^
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/import_js_library-1.0.1/lib/import_js_library_web.dart:52:18: Error: Method not found: 'querySelector'.
    final head = html.querySelector('head');
                 ^^^^^^^^^^^^^
U
nhandled exception:
FileSystemException(u
ri=org-dartlang-untranslatable-uri:dart%3Ahtml; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system
.dart:33:7)
#1      asFileUri (package:vm/kernel_front_end.dart:567:37)
#2      writeDepfile (package:vm/kernel_front_end.dart:760:21)
<asynchr
onous suspension>
#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:536:15)
<asynchronous 
suspension>
#4      _FlutterFrontendCompiler.compile (package:flutter_frontend_server/server.dart:40:22)
#5      starter (package:f
lutter_frontend_server/server.dart:178:27)
#6      main (file:///C:/b/s/w/ir/cache/builder/src/flutter/flutter_frontend_ser
ver/bin/starter.dart:8:30)
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

**Comment by florent37** [comment]
I tried ton import the `assets_audio_player: 1.3.5+1` in a  new empty project, and compile it to android, adding just a play for one asset, and I don't have the issue.

can you please try to `flutter clean` and try again ?

and if it not work, can you send me the output of your `flutter doctor` please ?

**Comment by florent37** [comment]
I think it's related to https://github.com/flutter/flutter/issues/54588

**Comment by florent37** [comment]
I think temporary I will extract the web implementation into a separate pubspec package like 'ssets_audio_player_web'

**Comment by florent37** [comment]
As mentioned in the new README (just uploaded), I just extracted the web support to a new package  `assets_audio_player_web` https://pub.dev/packages/assets_audio_player_web

```yaml
dependencies:
  assets_audio_player: ^1.3.6
```

And if you wan [web support, enable web](https://flutter.dev/web) then add
```yaml
dependencies:
  assets_audio_player_web: ^1.3.6
```

I tested it locally but I have the web option enabled, can you please try the `  assets_audio_player: ^1.3.6` only ? without adding `assets_audio_player_web` and tell me if it works !

thanks for the issue :)

**Comment by mmarlonsodre1** [comment]
Thank you.
Now the loop is working correctly, but now I can't change the volume anymore before the song starts playing.
I'm only able to use setVolume () after the song is already playing, but before that I was able to do that.
Would you like to put the volume parameter in open ()  or have the option to update the defaultVolume?

**Comment by florent37** [comment]
yes I do that now ;)

**Comment by florent37** [comment]
done ! can you try the `1.3.6+1`, you can now use open(path, volume: 0.2)

**Comment by florent37** [comment]
https://github.com/florent37/Flutter-AssetsAudioPlayer/commit/9b8ba0a7ac085d3729849fd2a81569b1db3003d5 

if you want to see the commit

**Comment by mmarlonsodre1** [comment]
Thank you.
It's working

**Comment by florent37** [comment]
;)
