### ISSUE TITLE
Android Api Level 30

### ISSUE THREAD

**Issue by offline-first** [florent37/Flutter-AssetsAudioPlayer#481]
Is Android Api level 30 already in development? I have updated the plugin to compileSdkVersion 30 and fixed some issues with asset loading. Everything works except for the media controls in the notification. If there is interest I can make a commit

**Comment by kalismeras61** [comment]
i have plan for that but of course PRs are welcomed.

**Comment by offline-first** [comment]
The PR is here, thank you [offline-first:android_api_30](https://github.com/florent37/Flutter-AssetsAudioPlayer/pull/482)

**Comment by kalismeras61** [comment]
Pr merged. Thanks @offline-first .
