### ISSUE TITLE
Notification buttons aren't working 

### ISSUE THREAD

**Issue by arif2k17** [florent37/Flutter-AssetsAudioPlayer#483]
When i used this plugin for the first time everything worked fine. But after i added `android_alarm_manger` plugin, notification action buttons are not working.

If i remove `android_alarm_manger` plugin it works again as expected.
### Small code to reproduce
```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await AndroidAlarmManager.initialize();
  runApp(MyApp());
}
```

**Comment by offline-first** [comment]
I have found the bug inside `AssetsAudioPlayerPlugin.kt`.
````
override fun onAttachedToEngine(@NonNull flutterPluginBinding: FlutterPlugin.FlutterPluginBinding) {
        if(instance != null)return // bug fix
        instance = this
        notificationChannel = MethodChannel(flutterPluginBinding.binaryMessenger, "assets_audio_player_notification")
        assetsAudioPlayer = AssetsAudioPlayer(
                flutterAssets = flutterPluginBinding.flutterAssets,
                context = flutterPluginBinding.applicationContext,
                messenger = flutterPluginBinding.binaryMessenger
        )
        assetsAudioPlayer!!.register();
    }
````

**Comment by arif2k17** [comment]
@offline-first great to hear that. Can you please tell me how i can fix this in my project? Is there a way?

**Comment by offline-first** [comment]
@arif2k17 clone the repo and change the part in the code is the only way to fix this bug. Sorry I'm not the author of this package

**Comment by arif2k17** [comment]
@offline-first I see. It's okay i understand. Please help me with one more thing, If i clone the repo and make the change then how can i import it in my project?

Thanks.

**Comment by kalismeras61** [comment]
Fix applied. Please use latest version.
