### ISSUE TITLE
Couldn't open url from firestorage 

### ISSUE THREAD

**Issue by farahfarah1** [florent37/Flutter-AssetsAudioPlayer#485]
Couldn't open https://firebasestorage.googleapis.com/v0/b/homeland-b25a0.appspot.com/o/chats%2FyGviUvt71kTOWap5wokvx8vVppH3EpRczlIBQeb7gMKqRq2MgBksWrf2%2Frecords%2Fef702320-7d88-11eb-8644-299789426b25?alt=media&token=ef4a5bd7-398f-4927-ab6a-8632ff968576: java.io.FileNotFoundException: No content provider: https://firebasestorage.googleapis.com/v0/b/homeland-b25a0.appspot.com/o/chats%2FyGviUvt71kTOWap5wokvx8vVppH3EpRczlIBQeb7gMKqRq2MgBksWrf2%2Frecords%2Fef702320-7d88-11eb-8644-299789426b25?alt=media&token=ef4a5bd7-398f-4927-ab6a-8632ff968576
I/MediaPlayer(26348): setDataSource(https://firebasestorage.googleapis.com/v0/b/homeland-b25a0.appspot.com/o/chats%2FyGviUvt71kTOWap5wokvx8vVppH3EpRczlIBQeb7gMKqRq2MgBksWrf2%2Frecords%2Fef702320-7d88-11eb-8644-299789426b25?alt=media&token=ef4a5bd7-398f-4927-ab6a-8632ff968576)

**Comment by kalismeras61** [comment]
It is working well. Please check with example app using the link.
