### ISSUE TITLE
iOS Issues related to import_js_library

### ISSUE THREAD

**Issue by dkobia** [florent37/Flutter-AssetsAudioPlayer#49]
I can't run this on iOS because the cocoapods installer runs into an issue:

```
[!] No podspec found for `import_js_library` in `.symlinks/plugins/import_js_library/ios`
```

**Comment by florent37** [comment]
if's a web library, it would not try to import it in ios, I'm on it, try temporary to use 1.3.1 !

**Comment by dkobia** [comment]
@florent37 I am on 1.3.1

The problem is that `import_js_library=../.pub-cache/hosted/pub.dartlang.org/import_js_library-0.0.2+1/` is automatically added to .**flutter-plugins**, by Flutter which CocoaPods uses in the Podfile:

```
plugin_pods = parse_KV_file('../.flutter-plugins')
plugin_pods.each do |name, path|
  symlink = File.join('.symlinks', 'plugins', name)
  File.symlink(path, symlink)
  pod name, :path => File.join(symlink, 'ios')
end
```

**Comment by florent37** [comment]
ok, maybe I can add an eempty podfile to import_js_library

**Comment by florent37** [comment]
yes ! like this https://github.com/flutter/plugins/blob/master/packages/url_launcher/url_launcher_web/ios/url_launcher_web.podspec

**Comment by florent37** [comment]
I just fixed it, can you try the 1.3.3 please ? @dkobia

**Comment by florent37** [comment]
I added no-op files for android & ios, as other flutter web packages...

**Comment by florent37** [comment]
just tried on a sample empty app, on 1.3.2 it failes on pods, on 1.3.3 it works (as screenshot)

<img width="1000" alt="Capture d’écran 2020-04-17 à 20 09 34" src="https://user-images.githubusercontent.com/5754972/79600413-6b0c7280-80e7-11ea-9b9d-c29832562685.png">

I close it, but you can for sure re-open it if you have the issue on 1.3.3 👍

**Comment by dkobia** [comment]
Excellent @florent37 and thanks for your work!

**Comment by florent37** [comment]
;)
