### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by syleishere** [florent37/Flutter-AssetsAudioPlayer#491]
import 'package:flutter_audio_desktop/flutter_audio_desktop.dart'; // for windows

can you integrate this one?

**Comment by DomingoMG** [comment]
**There is no need to create another publication when one already exists.**

Here you have a reference:
https://github.com/florent37/Flutter-AssetsAudioPlayer/issues/386

**Comment by kalismeras61** [comment]
Duplicate #386
