### ISSUE TITLE
Breaking dependancies

### ISSUE THREAD

**Issue by syleishere** [florent37/Flutter-AssetsAudioPlayer#492]
Because assets_audio_player >=2.0.14 depends on path_provider ^1.6.27 and musicplayer depends on path_provider ^2.0.1, assets_audio_player >=2.0.14 is forbidden.
So, because musicplayer depends on assets_audio_player ^2.0.14, version solving failed.
pub get failed (1; So, because musicplayer depends on assets_audio_player ^2.0.14, version solving failed.)

Because assets_audio_player >=2.0.14 depends on http ^0.12.2 and musicplayer depends on http ^0.13.0, assets_audio_player >=2.0.14 is forbidden.
So, because musicplayer depends on assets_audio_player ^2.0.14, version solving failed.
pub get failed (1; So, because musicplayer depends on assets_audio_player ^2.0.14, version solving failed.)

**Comment by syleishere** [comment]
Because no versions of assets_audio_player match >2.0.14 <3.0.0 and assets_audio_player 2.0.14 depends on path_provider ^1.6.27, assets_audio_player ^2.0.14 requires path_provider ^1.6.27.
And because no versions of path_provider match >1.6.27 <2.0.0 and path_provider 1.6.27 depends on path_provider_platform_interface ^1.0.1, assets_audio_player ^2.0.14 requires path_provider_platform_interface ^1.0.1.
And because path_provider_platform_interface <2.0.0-nullsafety depends on plugin_platform_interface ^1.0.1 and permission_handler_platform_interface >=3.0.0 depends on plugin_platform_interface ^2.0.0, assets_audio_player ^2.0.14 is incompatible with permission_handler_platform_interface >=3.0.0.
Because permission_handler >=6.0.0 <6.1.0 depends on permission_handler_platform_interface ^3.0.0+1 and permission_handler >=6.1.0 depends on permission_handler_platform_interface ^3.1.0, permission_handler >=6.0.0 requires permission_handler_platform_interface ^3.0.0+1.
Thus, assets_audio_player ^2.0.14 is incompatible with permission_handler >=6.0.0.
So, because musicplayer depends on both permission_handler ^6.0.1+1 and assets_audio_player ^2.0.14, version solving failed.
pub get failed (1; So, because musicplayer depends on both permission_handler ^6.0.1+1 and assets_audio_player ^2.0.14, version solving failed.)
Process finished with exit code 1

**Comment by kalismeras61** [comment]
It is not supported Flutter 2.0. Still in progress please wait . PR: closeing for now.

P.S . if you want you can override depencies
