### ISSUE TITLE
MetasImage.asset( ) not working for notification

### ISSUE THREAD

**Issue by specOper99** [florent37/Flutter-AssetsAudioPlayer#494]
**Flutter Version**

My version : Flutter 1.25.0-8.3.pre • channel beta

**Lib Version**

My version : ^2.0.14

**Platform (Android / iOS / web) + version**

Platform : Android Q (10)

**Describe the bug**

When loading the Image form network it works like charm, BUT the asset Image shows nothing at the notification with the following error at the console

java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.embedding.engine.loader.FlutterApplicationInfo.flutterAssetsDir' on a null object reference

W/System.err(15875): 	at io.flutter.embedding.engine.loader.FlutterLoader.fullAssetPathFrom(FlutterLoader.java:391)
W/System.err(15875): 	at io.flutter.embedding.engine.loader.FlutterLoader.getLookupKeyForAsset(FlutterLoader.java:372)
W/System.err(15875): 	at com.github.florent37.assets_audio_player.notification.ImageDownloader$getBitmap$2.invokeSuspend(ImageDownloader.kt:61)

Note:
(The audio works fine only the problem is with the asset image)

**Small code to reproduce**

await player.open(
        Audio.liveStream(
          selectedStream,
          metas: Metas(
              title: localization['home']['liveStream'][locale],
              image: MetasImage.asset('assets/images/alghadSmall.png')
              ),
        ),
        showNotification: true,
        notificationSettings: NotificationSettings(
            nextEnabled: false,
            prevEnabled: false,
            seekBarEnabled: false,
            playPauseEnabled: false,
          ),
        )

**Comment by kalismeras61** [comment]
We have Pr for that. Will merge this weekend.

**Comment by specOper99** [comment]
All right, I will wait for it
Thanks ❤️
