### ISSUE TITLE
click a button quickly with next()

### ISSUE THREAD

**Issue by franvara** [florent37/Flutter-AssetsAudioPlayer#514]
**Flutter Version**

My version : Channel stable, 2.0.4

**Lib Version**

My version : assets_audio_player: ^3.0.3+2

**Platform (Android / iOS / web) + version**

Platform : Android 11 API 30

**Describe the bug**

 In a playlist when I click a button many times and quickly with next() or previous() method, a lot of songs sound at the same time. After that, I have to kill the app to stop the music.

**Small code to reproduce**

class _TrackDetailScreenState extends State<TrackDetailScreen> {
  final AssetsAudioPlayer audioPlayer =
      AssetsAudioPlayer.withId("DjFrankKruxMusic");

.......

audioPlayer.open(
        Playlist(audios: [
          Audio.network('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-13.mp3',
              metas: Metas(
                  title: 'All That',
                  artist: 'Benjamin Tissot',
                  image: MetasImage.asset('assets/allthat.jpg'))),
          Audio.network('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3',
              metas: Metas(
                  title: 'Love',
                  artist: 'Benjamin Tissot',
                  image: MetasImage.asset('assets/love.jpg'))),
          Audio.network('https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3',
              metas: Metas(
                  title: 'The Jazz Piano',
                  artist: 'Benjamin Tissot',
                  image: MetasImage.asset('assets/thejazzpiano.jpg'))),
        ]),
        autoStart: false,
        loopMode: LoopMode.playlist);

......

Widget buttons(RealtimePlayingInfos realtimePlayingInfos) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        IconButton(
          icon: Icon(Icons.skip_previous_rounded),
          onPressed: () => audioPlayer.previous(),
          iconSize: 40,
          color: Colors.white,
          splashColor: Colors.transparent,
          highlightColor: Colors.transparent,
        ),
        Container(
          decoration: BoxDecoration(
              color: Colors.white, borderRadius: BorderRadius.circular(50.0)),
          child: IconButton(
            icon: Icon(realtimePlayingInfos.isPlaying
                ? Icons.pause_rounded
                : Icons.play_arrow_rounded),
            iconSize: 40,
            color: Colors.black,
            onPressed: () => audioPlayer.playOrPause(),
          ),
        ),
        IconButton(
          icon: Icon(Icons.skip_next_rounded),
          onPressed: () => audioPlayer.next(),
          iconSize: 40,
          color: Colors.white,
          splashColor: Colors.transparent,
          highlightColor: Colors.transparent,
        ),
      ],
    );
  }

**Comment by Mayb3Nots** [comment]
Same issue. @kalismeras61 do you know where is the issue?

**Comment by Mayb3Nots** [comment]
Hey @franvara I found out the issue. You have to call await and make sure it is completed before you call the function `next() `again.

**Comment by kalismeras61** [comment]
@Mayb3Nots we are using cancelable future so you have to use await as you mention.

**Comment by Mayb3Nots** [comment]
> @Mayb3Nots we are using cancelable future so you have to use await as you mention.

What do you mean cancleable future?

**Comment by franvara** [comment]
With only "await" don't work to my app. I did the following method to disable the button.

  Future<bool> skipNext() async {
    if (enabled) {
      enabled = false;
      await audioPlayer.pause();
      await audioPlayer.next();
      enabled = true;
      return true;
    } else
      return false;
  }

With this method it works correctly.

I also overwrote the notification buttons with notificationSettings:

audioPlayer.open(
      Playlist(
        audios: setPlaylist(widget.trackDetailArguments.tracks,
            widget.trackDetailArguments.position),
      ),
      showNotification: true,
      headPhoneStrategy: HeadPhoneStrategy.pauseOnUnplugPlayOnPlug,
      audioFocusStrategy:
          AudioFocusStrategy.request(resumeAfterInterruption: true),
      autoStart: false,
      loopMode: LoopMode.playlist,
      notificationSettings: NotificationSettings(
        stopEnabled: false, //disable the stop button
        //and have a custom next action (will disable the default action)
        customNextAction: (player) {
          skipNext();
        },
        customPrevAction: (player) {
          skipPrevious();
        },
      ),
    );

**Comment by Mayb3Nots** [comment]
Yes this is what i mean by await, you have to make sure its finish before calling another next. If this has sovled your issue please close it thanks!
