### ISSUE TITLE
Play error in Stateless

### ISSUE THREAD

**Issue by shun007** [florent37/Flutter-AssetsAudioPlayer#515]
**Flutter Version**

My version : Flutter 2.0.1 • channel stable

**Lib Version**

My version : assets_audio_player: ^3.0.3+2

**Platform (Android / iOS / web) + version**

Platform : Android 9

**Describe the bug**

It's normal to use it in StatefulWidget,
There's an error in StatelessWidget,
I want to use GetX package. is there a way to solve this problem?

W/System.err(12230): com.github.florent37.assets_audio_player.playerimplem.PlayerFinder$NoPlayerFoundException

**Small code to reproduce**

```dart
import 'package:assets_audio_player/assets_audio_player.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
// This link may be out of date. I can use it when I test it
AssetsAudioPlayer()..open(Audio("https://sharefs.yun.kugou.com/202104090754/6c5ce68ce5577ed936b46881d670eb27/G060/M02/03/00/fA0DAFcfRyqAFqVVADzuCsUW34U840.mp3"));
    return Scaffold(
        appBar: AppBar(
          title: Text('Flutter Demo'),
        ),
        body: Text("123"));
  }
}
```

**Comment by Mayb3Nots** [comment]
The issue here is you have to use `Audio.network()`. Its a common mistake.

**Comment by shun007** [comment]
> The issue here is you have to use `Audio.network()`. Its a common mistake.

Successful! Thank you, I am too careless
