### ISSUE TITLE
audio file is stopping

### ISSUE THREAD

**Issue by dmrcierhn** [florent37/Flutter-AssetsAudioPlayer#517]
I want to use this great plugin along with the video_player plugin but i didn't succeed. The video starts to display but the audio file i integrated with this package stops playing. How can i fix  this ? thank you!

**Comment by kalismeras61** [comment]
Can yoy share some code?

**Comment by nohli** [comment]
Did you try this?

`videoPlayerOptions: VideoPlayerOptions(mixWithOthers: true)`

> Set this to true to mix the video players audio with other audio sources. The default value is false

**Comment by kalismeras61** [comment]
@dmrcierhn if you fixed your issue can you close this ?

**Comment by dmrcierhn** [comment]
sure, thank you for help
