### ISSUE TITLE
[question] Does not jump to next Audio in Playlist after completion 

### ISSUE THREAD

**Issue by alexmercerind** [florent37/Flutter-AssetsAudioPlayer#519]
THIS DIDN'T HAPPEN BEFORE UPDATING LIBRARY TO NULL SAFETY. I DIDN'T CHANGE ANY OF MY CODE & THIS STARTED HAPPENING.

**Flutter Version**

Latest

My version : 

Latest

Platform : 

Android

**Describe the bug**

The audio player does not jump to next audio in the playlist, regardless of the fact that I've defined `LoopMode.playlist`.

More information: Manually calling `next` makes audio player jump to next audio in the playlist. The only fault is that it does not happen after completion of playback (like it was in earlier version). 

**Small code to reproduce**

This is a simple `play` method that I'm using to play a a list of `Track` (a simple data class).

```dart
abstract class Playback {

  static Future<void> play({required int index, required List<Track> tracks}) async {
    List<Track> _tracks = tracks;
    if (_tracks.length > 20) _tracks = tracks.sublist(index, index + 20);
    List<Audio> audios = <Audio>[];
    _tracks.forEach((Track track) {
      audios.add(
        new Audio.file(
          track.filePath!,
          metas: new Metas(
            id: track.trackId,
            image: new MetasImage.file(
              track.albumArt.path,
            ),
            title: track.trackName!,
            album: track.albumName!,
            artist: track.trackArtistNames!.join(', '),
            extra: track.toMap(),
          )
        ),
      );
    });
    audioPlayer.open(
      new Playlist(
        audios: audios,
        startIndex: index,
      ),
      loopMode: LoopMode.playlist,
      playInBackground: PlayInBackground.enabled,
      headPhoneStrategy: HeadPhoneStrategy.pauseOnUnplug,
      showNotification: true,
      notificationSettings: new NotificationSettings(
        playPauseEnabled: true,
        nextEnabled: true,
        prevEnabled: true,
        seekBarEnabled: true,
        stopEnabled: false,   
      ),
    );
  }
}
```

**Comment by alexmercerind** [comment]
@kalismeras61, could you please take a look at this? 🙏

**Comment by ash2osh** [comment]
+1 @florent37 please 🙏

**Comment by jxzy999** [comment]
the same issue

**Comment by Mayb3Nots** [comment]
@nohli any chances you can take a look into this? Since you did most of the migration.

**Comment by nohli** [comment]
@Mayb3Nots sure, probably tomorrow.
Are there any other new bugs (since null safety) that you know of?

**Comment by Mayb3Nots** [comment]
> @Mayb3Nots sure, probably tomorrow.
> Are there any other new bugs (since null safety) that you know of?

Nope, and thanks for looking into it. Just FYI the bug only happens when null saftey is on. So even with lastest version, if your enviroment sdk is less than 2.12.0 it works fine without able to reproduce the bug. But if you enabke null safter (sdk >= 2.12.0) it will have this bug.

**Comment by nohli** [comment]
Interesting.
Good to know, thanks for investigating :)

**Comment by nohli** [comment]
@Mayb3Nots I can't reproduce the issue.

Could anyone share some fully working example code to reproduce the issue?
(without the audio files)

Also @alexmercerind please share one `track.filePath`
On a sidenote - you have a few unnecessary force unwraps.
Would this code work for you?

```
    _tracks.forEach((Track track) {
      if (track.filePath != null) {
        audios.add(
          Audio.file(
            track.filePath,
            metas: Metas(
              id: track.trackId,
              image: MetasImage.file(
                track.albumArt.path,
              ),
              title: track.trackName,
              album: track.albumName,
              artist: track.trackArtistNames?.join(', '),
              extra: track.toMap(),
            ),
          ),
        );
      }
    });
```

**Comment by Mayb3Nots** [comment]
> @Mayb3Nots I can't reproduce the issue.
> 
> Could anyone share some fully working example code to reproduce the issue?
> (without the audio files)
> 
> Also @alexmercerind please share one `track.filePath`
> On a sidenote - you have a few unnecessary force unwraps.
> Would this code work for you?
> 
> ```
>     _tracks.forEach((Track track) {
>       if (track.filePath != null) {
>         audios.add(
>           Audio.file(
>             track.filePath,
>             metas: Metas(
>               id: track.trackId,
>               image: MetasImage.file(
>                 track.albumArt.path,
>               ),
>               title: track.trackName,
>               album: track.albumName,
>               artist: track.trackArtistNames?.join(', '),
>               extra: track.toMap(),
>             ),
>           ),
>         );
>       }
>     });
> ```

Thanks for looking into it. Here is a badly made example you can use to test it out just copy and paste it. Make sure to use latest version of the package and null safety is enabled. 

```
import 'package:assets_audio_player/assets_audio_player.dart';
import 'package:flutter/material.dart';

main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final player = AssetsAudioPlayer();
  late Future future;
  @override
  void initState() {
    player.shuffle = true;
    future = player.open(
        Playlist(
          audios: [
            Audio.network(
                'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
                metas: Metas(title: '1')),
            Audio.network(
                'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
                metas: Metas(title: '2')),
            Audio.network(
                'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
                metas: Metas(title: '3')),
            Audio.network(
                'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
                metas: Metas(title: '4')),
            Audio.network(
                'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3',
                metas: Metas(title: '5')),
            Audio.network(
                'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3',
                metas: Metas(title: '6'))
          ],
        ),
        showNotification: true);
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: FutureBuilder(
          future: future,
          builder: (context, snapshot) {
            if (snapshot.connectionState == ConnectionState.done)
              return Center(
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    StreamBuilder<Playing?>(
                      stream: player.current,
                      builder: (BuildContext context, snapshot) {
                        final data = snapshot.data;
                        return Column(
                          children: [
                            StreamBuilder<Duration>(
                                stream: player.currentPosition,
                                builder: (context, snapshot) {
                                  return Slider(
                                    onChanged: (double value) {
                                      player.seek(
                                          Duration(seconds: value.toInt()));
                                    },
                                    value: snapshot.data!.inSeconds.toDouble(),
                                    min: 0.0,
                                    max: data!.audio.duration.inSeconds
                                        .toDouble(),
                                  );
                                }),
                            Text(data!.audio.audio.metas.title!),
                          ],
                        );
                      },
                    ),
                    StreamBuilder<bool>(
                      stream: player.isShuffling,
                      builder: (context, snapshot) {
                        return ElevatedButton(
                            onPressed: () {
                              player.toggleShuffle();
                            },
                            child: Text('shuffle :${snapshot.data}'));
                      },
                    ),
                    ElevatedButton(
                        onPressed: () {
                          player.next();
                        },
                        child: Text('next')),
                    ElevatedButton(
                        onPressed: () {
                          player.playOrPause();
                        },
                        child: Text('toggle play pause'))
                  ],
                ),
              );
            return Center(
              child: CircularProgressIndicator(),
            );
          },
        ),
      ),
    );
  }
}
```

**Comment by nohli** [comment]
Thanks!

It only happens on Android (iOS is working), correct?

**Comment by Mayb3Nots** [comment]
> Thanks!
> 
> It only happens on Android (iOS is working), correct?

Not sure but all my test are conducted on Android . Need others to confirm this. If its the case what could be the cause? The migration didn't change any native code right?

**Comment by nohli** [comment]
So far no success...

@Mayb3Nots your code has helped, thanks! I used it with a few changes:

<details>
  <summary>Sample Code</summary>

```
import 'package:assets_audio_player/assets_audio_player.dart';
import 'package:flutter/material.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(MyApp());
}

Future<void> _openPlayer(AssetsAudioPlayer player) async {
  await player.open(
    Playlist(
      audios: [
        Audio.network(
          'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
          metas: Metas(title: '1'),
        ),
        Audio.network(
          'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
          metas: Metas(title: '2'),
        ),
        Audio.network(
          'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
          metas: Metas(title: '3'),
        ),
      ],
    ),
    loopMode: LoopMode.playlist,
  );
}

class MyApp extends StatelessWidget {
  final _player = AssetsAudioPlayer();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark(),
      home: Scaffold(
        body: FutureBuilder(
          future: _openPlayer(_player),
          builder: (context, snapshot) {
            if (snapshot.connectionState == ConnectionState.done) {
              return Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  StreamBuilder<Playing?>(
                    // without null safety use <Playing>
                    stream: _player.current,
                    builder: (BuildContext context, snapshot) {
                      final duration = snapshot.data?.audio.duration.inSeconds;
                      if (duration != null) {
                        return Column(
                          children: [
                            StreamBuilder<Duration>(
                              stream: _player.currentPosition,
                              builder: (context, snapshot) {
                                final position = snapshot.data?.inSeconds;
                                if (position != null) {
                                  return Column(
                                    children: [
                                      Text(snapshot.data.toString()),
                                      Slider(
                                        onChanged: (double value) {
                                          _player.seek(
                                            Duration(seconds: value.toInt()),
                                          );
                                        },
                                        value: position.toDouble(),
                                        min: 0,
                                        max: duration.toDouble(),
                                      ),
                                    ],
                                  );
                                }
                                return const SizedBox();
                              },
                            ),
                          ],
                        );
                      }
                      return const SizedBox();
                    },
                  ),
                  StreamBuilder<bool>(
                    stream: _player.isShuffling,
                    builder: (context, snapshot) {
                      return ElevatedButton(
                        onPressed: () => _player.toggleShuffle(),
                        child: Text('shuffle: ${snapshot.data}'),
                      );
                    },
                  ),
                  ElevatedButton(
                    onPressed: () => _player.next(),
                    child: Text('next'),
                  ),
                  ElevatedButton(
                    onPressed: () => _player.playOrPause(),
                    child: Text('toggle play pause'),
                  )
                ],
              );
            }
            return Center(child: CircularProgressIndicator());
          },
        ),
      ),
    );
  }
}
```
</details>

Maybe the output is interesting:
(enabled sound null safety stops after line 1, disabled* works with some warnings)
\* i.e. by running with `--no-sound-null-safety` or setting `sdk: '>=2.11.0 <3.0.0`

<details>
  <summary>Log</summary>

```
D/AudioTrack(12963): stop(185): called with 472320 frames delivered
I/ExoPlayerImpl(12963): Release 401ca3a [ExoPlayerLib/2.13.2] [emulator64_arm64, sdk_gphone64_arm64, Google, 31] [goog.exo.core]
I/CCodecConfig(12963): query failed after returning 7 values (BAD_INDEX)
W/Codec2Client(12963): query -- param skipped: index = 1342179345.
W/Codec2Client(12963): query -- param skipped: index = 2415921170.
4 times: D/CCodecBufferChannel(12963): [c2.android.mp3.decoder#839] MediaCodec discarded an unknown buffer
I/hw-BpHwBinder(12963): onLastStrongRef automatically unlinking death recipients
I/ExoPlayerImpl(12963): Init 5d8e519 [ExoPlayerLib/2.13.2] [emulator64_arm64, sdk_gphone64_arm64, Google, 31]
D/CCodec  (12963): allocate(c2.android.mp3.decoder)
I/CCodec  (12963): setting up 'default' as default (vendor) store
I/CCodec  (12963): Created component [c2.android.mp3.decoder]
D/CCodecConfig(12963): read media type: audio/mpeg
D/ReflectedParamUpdater(12963): extent() != 1 for single value type: algo.buffers.max-count.values
D/ReflectedParamUpdater(12963): extent() != 1 for single value type: output.subscribed-indices.values
D/ReflectedParamUpdater(12963): extent() != 1 for single value type: input.buffers.allocator-ids.values
D/ReflectedParamUpdater(12963): extent() != 1 for single value type: output.buffers.allocator-ids.values
D/ReflectedParamUpdater(12963): extent() != 1 for single value type: algo.buffers.allocator-ids.values
D/ReflectedParamUpdater(12963): extent() != 1 for single value type: output.buffers.pool-ids.values
D/ReflectedParamUpdater(12963): extent() != 1 for single value type: algo.buffers.pool-ids.values
I/CCodecConfig(12963): query failed after returning 7 values (BAD_INDEX)
D/CCodecConfig(12963): c2 config diff is Dict {
D/CCodecConfig(12963):   c2::u32 coded.bitrate.value = 64000
D/CCodecConfig(12963):   c2::u32 input.buffers.max-size.value = 8192
D/CCodecConfig(12963):   c2::u32 input.delay.value = 0
D/CCodecConfig(12963):   string input.media-type.value = "audio/mpeg"
D/CCodecConfig(12963):   string output.media-type.value = "audio/raw"
D/CCodecConfig(12963):   c2::u32 raw.channel-count.value = 2
D/CCodecConfig(12963):   c2::u32 raw.sample-rate.value = 44100
D/CCodecConfig(12963): }
D/CCodec  (12963): [c2.android.mp3.decoder] buffers are bound to CCodec for this session
D/CCodecConfig(12963): no c2 equivalents for flags
D/CCodecConfig(12963): config failed => CORRUPTED
W/Codec2Client(12963): query -- param skipped: index = 1107298332.
D/CCodec  (12963): client requested max input size 4096, which is smaller than what component recommended (8192); overriding with component recommendation.
W/CCodec  (12963): This behavior is subject to change. It is recommended that app developers double check whether the requested max input size is in reasonable range.
D/CCodec  (12963): setup formats input: AMessage(what = 0x00000000) = {
D/CCodec  (12963):   int32_t channel-count = 2
D/CCodec  (12963):   int32_t max-input-size = 8192
D/CCodec  (12963):   string mime = "audio/mpeg"
D/CCodec  (12963):   int32_t sample-rate = 44100
D/CCodec  (12963): } and output: AMessage(what = 0x00000000) = {
D/CCodec  (12963):   int32_t channel-count = 2
D/CCodec  (12963):   string mime = "audio/raw"
D/CCodec  (12963):   int32_t sample-rate = 44100
D/CCodec  (12963): }
W/Codec2Client(12963): query -- param skipped: index = 1342179345.
W/Codec2Client(12963): query -- param skipped: index = 2415921170.
2 times: E/FMQ     (12963): grantorIdx must be less than 3
D/CCodecBufferChannel(12963): [c2.android.mp3.decoder#603] Created input block pool with allocatorID 16 => poolID 33 - OK (0)
D/BufferPoolAccessor2.0(12963): bufferpool2 0xb400006fdba837c8 : 0(0 size) total buffers - 0(0 size) used buffers - 0/5 (recycle/alloc) - 7/1800 (fetch/transfer)
D/BufferPoolAccessor2.0(12963): Destruction - bufferpool2 0xb400006fdba837c8 cached: 0/0M, 0/0% in use; allocs: 5, 0% recycled; transfers: 1800, 100% unfetched
I/CCodecBufferChannel(12963): [c2.android.mp3.decoder#603] Created output block pool with allocatorID 16 => poolID 109 - OK
D/CCodecBufferChannel(12963): [c2.android.mp3.decoder#603] Configured output block pool ids 109 => OK
2 times: E/FMQ     (12963): grantorIdx must be less than 3
D/AudioTrack(12963): getTimestamp_l(186): device stall time corrected using current time 16823321081021
```

</details>

@kalismeras61 maybe you have an idea?

Issue summary: Playlists stop playing after one song. Only on Android. If run without sound null safety, it works.

How to reproduce: Play, seek close to end, wait.
Enabled sound null safety: It stops.
Disabled sound null safety (but same code): It plays the next audio.

FYI This displays changes from two weeks before null safety migration to now: https://github.com/florent37/Flutter-AssetsAudioPlayer/compare/0ff631...102f1e

**Comment by Mayb3Nots** [comment]
> So far no success...
> 
> @Mayb3Nots your code has helped, thanks! I used it with a few changes:
> 
> Sample Code
> Maybe the output is interesting:
> (enabled sound null safety stops after line 1, disabled* works with some warnings)
> * i.e. by running with `--no-sound-null-safety` or setting `sdk: '>=2.11.0 <3.0.0`
> 
> Log
> @kalismeras61 maybe you have an idea?
> 
> Issue summary: Playlists stop playing after one song. Only on Android. If run without sound null safety, it works.
> 
> How to reproduce: Play, seek close to end, wait.
> Enabled sound null safety: It stops.
> Disabled sound null safety (but same code): It plays the next audio.
> 
> FYI This displays changes from two weeks before null safety migration to now: [0ff631...102f1e](https://github.com/florent37/Flutter-AssetsAudioPlayer/compare/0ff631...102f1e)

This is indeed a mystery. Since it only happens on android can we conclude that it nothing to do with the code written in dart and null safety? Since IOS will also be the effect if that's the case. Because if that's the case I have seen some changes to the native code but unfortunately I don't understand the changes.

**Comment by jxzy999** [comment]
In my case , I found _recieveChannel in file assets_audio_player.dart report METHOD_FINISHED with arguments null on Android, and  deal function _onFinished  parameters declare not null.

**Comment by nohli** [comment]
@jxzy999 can you please explain what you mean exactly?

**Comment by alexmercerind** [comment]
@jxzy999 thanks for looking at it.
Could you make a pull request from your fork?

I recall it is one of the common encountered problems I also had during migration. Because errors are also not thrown at some places & no-one handles those either.

**Comment by Mayb3Nots** [comment]
> In my case , I found _recieveChannel in file assets_audio_player.dart report METHOD_FINISHED with arguments null on Android, and deal function _onFinished parameters declare not null.
> @nohli

`isFinished` is not even used or mentioned in the function. How does it affect the outcome and why have it there in the first place?
https://github.com/florent37/Flutter-AssetsAudioPlayer/blob/102f1e8515e78a700745f04840da14d23d279b85/lib/src/assets_audio_player.dart#L898-L906

**Comment by nohli** [comment]
> > In my case , I found _recieveChannel in file assets_audio_player.dart report METHOD_FINISHED with arguments null on Android, and deal function _onFinished parameters declare not null.
> > @nohli
> 
> `isFinished` is not even used or mentioned in the function. How does it affect the outcome and why have it there in the first place?
> https://github.com/florent37/Flutter-AssetsAudioPlayer/blob/102f1e8515e78a700745f04840da14d23d279b85/lib/src/assets_audio_player.dart#L898-L906

It has been there before the null safety migration and apparently didn't produce errors. Glad that you found it! 💪🏾
Probably better to remove it.

https://github.com/florent37/Flutter-AssetsAudioPlayer/blob/2e95c69f0f96955f9dfbb95f51eb4e97febb4d4c/lib/src/assets_audio_player.dart#L875-L883

**Comment by Mayb3Nots** [comment]
> > > In my case , I found _recieveChannel in file assets_audio_player.dart report METHOD_FINISHED with arguments null on Android, and deal function _onFinished parameters declare not null.
> > > @nohli
> > 
> > 
> > `isFinished` is not even used or mentioned in the function. How does it affect the outcome and why have it there in the first place?
> > https://github.com/florent37/Flutter-AssetsAudioPlayer/blob/102f1e8515e78a700745f04840da14d23d279b85/lib/src/assets_audio_player.dart#L898-L906
> 
> It has been there before the null safety migration and apparently didn't produce errors. Glad that you found it! 💪🏾
> Probably better to remove it.
> 
> https://github.com/florent37/Flutter-AssetsAudioPlayer/blob/2e95c69f0f96955f9dfbb95f51eb4e97febb4d4c/lib/src/assets_audio_player.dart#L875-L883

I agree better to remove it completely. I think what happened is sometimes the value returned from the method channel was null therefore when the function was run it threw an exception but somehow it didn't show? I am currently testing to see it fixes the issue.

**Comment by vocsykenil** [comment]
AssetsAudioPlayer  ?_assetsAudioPlayer;

_assetsAudioPlayer!.builderRealtimePlayingInfos(builder: (context, RealtimePlayingInfos? infos) {
                            if (_assetsAudioPlayer?.playlist!.audios.last.metas.id == _assetsAudioPlayer?.current.value!.audio.audio.metas.id &&
                                infos!.currentPosition.inSeconds == infos.duration.inSeconds - 1) {
                              _assetsAudioPlayer?.stop();
                              Get.back();
                              return const SizedBox.shrink();
                            } else {
                              if (infos!.duration > const Duration(seconds: 0)) {
                                return PositionSeekWidget(
                                    currentPosition: infos.currentPosition,
                                    duration: infos.duration,
                                    seekTo: (to) {
                                      if (_assetsAudioPlayer?.playlist!.audios.last.metas.id == _assetsAudioPlayer?.current.value!.audio.audio.metas.id) {
                                        if (to.inSeconds <= infos.duration.inSeconds - 2) {
                                          _assetsAudioPlayer?.seek(to);
                                        } else {
                                          _assetsAudioPlayer?.seek(Duration(seconds: infos.duration.inSeconds - 2));
                                        }
                                      } else {
                                        _assetsAudioPlayer?.seek(to);
                                      }
                                    });
                              } else {
                                return PositionSeekWidget(
                                  currentPosition: const Duration(minutes: 0, seconds: 0),
                                  duration: const Duration(minutes: 0, seconds: 0),
                                  seekTo: (to) {
                                    _assetsAudioPlayer?.seek(to);
                                  },
                                );
                              }
                            }
                          }),



/// class of slider 
 import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:meditation/views/utils/textwidget.dart';
import '../../constant/constant.dart';

class PositionSeekWidget extends StatefulWidget {
  final Duration currentPosition;
  final Duration duration;
  final Function(Duration) seekTo;

  const PositionSeekWidget({required this.currentPosition, required this.duration, required this.seekTo});

  @override
  _PositionSeekWidgetState createState() => _PositionSeekWidgetState();
}

class _PositionSeekWidgetState extends State<PositionSeekWidget> {
  late Duration _visibleValue;
  bool listenOnlyUserInteraction = false;

  double get percent => widget.duration.inMilliseconds == 0 ? 0 : _visibleValue.inMilliseconds / widget.duration.inMilliseconds;

  @override
  void initState() {
    super.initState();
    _visibleValue = widget.currentPosition;
  }

  @override
  void didUpdateWidget(PositionSeekWidget oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (!listenOnlyUserInteraction) {
      _visibleValue = widget.currentPosition;
    }
  }

  @override
  Widget build(BuildContext context) {
    Duration d = widget.duration - widget.currentPosition;
    String m = d.toString().substring(2, 4);
    String s = d.toString().substring(5, 7);
    return Padding(
      padding: const EdgeInsets.all(8.0),
      child: Column(
        children: <Widget>[
          Slider(
            activeColor: Constant.whiteColor,
            thumbColor: Constant.whiteColor,
            inactiveColor: Constant.alertDialogColor,
            label: widget.duration.toString(),
            min: 0,
            max: widget.duration.inMilliseconds.toDouble(),
            value: percent * widget.duration.inMilliseconds.toDouble(),
            onChangeEnd: (newValue) {
              setState(() {
                listenOnlyUserInteraction = false;
                widget.seekTo(_visibleValue);
              });
            },
            onChangeStart: (_) {
              setState(() {
                listenOnlyUserInteraction = true;
              });
            },
            onChanged: (newValue) {
              setState(() {
                final to = Duration(milliseconds: newValue.floor());
                _visibleValue = to;
              });
            },
          ),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: <Widget>[
              SizedBox(
                width: 40,
                child: Styles.regular(durationToString(widget.currentPosition), c: Constant.whiteColor, fs: 10.sp),
              ),
              SizedBox(
                width: 40,
                child: Styles.regular(durationToString(widget.duration), c: Constant.whiteColor, fs: 10.sp),
              ),
            ],
          ),
        ],
      ),
    );
  }
}

String durationToString(Duration duration) {
  String twoDigits(int n) {
    if (n >= 10) return '$n';
    return '0$n';
  }

  final twoDigitHours = twoDigits(duration.inHours.remainder(Duration.hoursPerDay));
  final twoDigitMinutes = twoDigits(duration.inMinutes.remainder(Duration.minutesPerHour));
  final twoDigitSeconds = twoDigits(duration.inSeconds.remainder(Duration.secondsPerMinute));
  return twoDigitHours == "00" ? '$twoDigitMinutes:$twoDigitSeconds' : '$twoDigitHours:$twoDigitMinutes:$twoDigitSeconds';
}

**Comment by vocsykenil** [comment]
AssetsAudioPlayer? _assetsAudioPlayer;


_assetsAudioPlayer!.builderRealtimePlayingInfos(builder: (context, RealtimePlayingInfos? infos) {
                            if (_assetsAudioPlayer?.playlist!.audios.last.metas.id == _assetsAudioPlayer?.current.value!.audio.audio.metas.id &&
                                infos!.currentPosition.inSeconds == infos.duration.inSeconds - 1) {
                              _assetsAudioPlayer?.stop();
                              Get.back();
                              return const SizedBox.shrink();
                            } else {
                              if (infos!.duration > const Duration(seconds: 0)) {
                                return PositionSeekWidget(
                                    currentPosition: infos.currentPosition,
                                    duration: infos.duration,
                                    seekTo: (to) {
                                      if (_assetsAudioPlayer?.playlist!.audios.last.metas.id == _assetsAudioPlayer?.current.value!.audio.audio.metas.id) {
                                        if (to.inSeconds <= infos.duration.inSeconds - 2) {
                                          _assetsAudioPlayer?.seek(to);
                                        } else {
                                          _assetsAudioPlayer?.seek(Duration(seconds: infos.duration.inSeconds - 2));
                                        }
                                      } else {
                                        _assetsAudioPlayer?.seek(to);
                                      }
                                    });
                              } else {
                                return PositionSeekWidget(
                                  currentPosition: const Duration(minutes: 0, seconds: 0),
                                  duration: const Duration(minutes: 0, seconds: 0),
                                  seekTo: (to) {
                                    _assetsAudioPlayer?.seek(to);
                                  },
                                );
                              }
                            }
                          }),

/// slider class

import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

class PositionSeekWidget extends StatefulWidget {
  final Duration currentPosition;
  final Duration duration;
  final Function(Duration) seekTo;

  const PositionSeekWidget({required this.currentPosition, required this.duration, required this.seekTo});

  @override
  _PositionSeekWidgetState createState() => _PositionSeekWidgetState();
}

class _PositionSeekWidgetState extends State<PositionSeekWidget> {
  late Duration _visibleValue;
  bool listenOnlyUserInteraction = false;

  double get percent => widget.duration.inMilliseconds == 0 ? 0 : _visibleValue.inMilliseconds / widget.duration.inMilliseconds;

  @override
  void initState() {
    super.initState();
    _visibleValue = widget.currentPosition;
  }

  @override
  void didUpdateWidget(PositionSeekWidget oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (!listenOnlyUserInteraction) {
      _visibleValue = widget.currentPosition;
    }
  }

  @override
  Widget build(BuildContext context) {
    Duration d = widget.duration - widget.currentPosition;
    String m = d.toString().substring(2, 4);
    String s = d.toString().substring(5, 7);
    return Padding(
      padding: const EdgeInsets.all(8.0),
      child: Column(
        children: <Widget>[
          Slider(
            activeColor: Constant.whiteColor,
            thumbColor: Constant.whiteColor,
            inactiveColor: Constant.alertDialogColor,
            label: widget.duration.toString(),
            min: 0,
            max: widget.duration.inMilliseconds.toDouble(),
            value: percent * widget.duration.inMilliseconds.toDouble(),
            onChangeEnd: (newValue) {
              setState(() {
                listenOnlyUserInteraction = false;
                widget.seekTo(_visibleValue);
              });
            },
            onChangeStart: (_) {
              setState(() {
                listenOnlyUserInteraction = true;
              });
            },
            onChanged: (newValue) {
              setState(() {
                final to = Duration(milliseconds: newValue.floor());
                _visibleValue = to;
              });
            },
          ),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: <Widget>[
              SizedBox(
                width: 40,
                child: Text(durationToString(widget.currentPosition))
/
              ),
              SizedBox(
                width: 40,
                child: Text(durationToString(widget.duration))
              ),
            ],
          ),
        ],
      ),
    );
  }
}

String durationToString(Duration duration) {
  String twoDigits(int n) {
    if (n >= 10) return '$n';
    return '0$n';
  }

  final twoDigitHours = twoDigits(duration.inHours.remainder(Duration.hoursPerDay));
  final twoDigitMinutes = twoDigits(duration.inMinutes.remainder(Duration.minutesPerHour));
  final twoDigitSeconds = twoDigits(duration.inSeconds.remainder(Duration.secondsPerMinute));
  return twoDigitHours == "00" ? '$twoDigitMinutes:$twoDigitSeconds' : '$twoDigitHours:$twoDigitMinutes:$twoDigitSeconds';
}

**Comment by vocsykenil** [comment]
```
AssetsAudioPlayer? _assetsAudioPlayer;

_assetsAudioPlayer!.builderRealtimePlayingInfos(builder: (context, RealtimePlayingInfos? infos) {
if (_assetsAudioPlayer?.playlist!.audios.last.metas.id == _assetsAudioPlayer?.current.value!.audio.audio.metas.id &&
infos!.currentPosition.inSeconds == infos.duration.inSeconds - 1) {
_assetsAudioPlayer?.stop();
Get.back();
return const SizedBox.shrink();
} else {
if (infos!.duration > const Duration(seconds: 0)) {
return PositionSeekWidget(
currentPosition: infos.currentPosition,
duration: infos.duration,
seekTo: (to) {
if (_assetsAudioPlayer?.playlist!.audios.last.metas.id == _assetsAudioPlayer?.current.value!.audio.audio.metas.id) {
if (to.inSeconds <= infos.duration.inSeconds - 2) {
_assetsAudioPlayer?.seek(to);
} else {
_assetsAudioPlayer?.seek(Duration(seconds: infos.duration.inSeconds - 2));
}
} else {
_assetsAudioPlayer?.seek(to);
}
});
} else {
return PositionSeekWidget(
currentPosition: const Duration(minutes: 0, seconds: 0),
duration: const Duration(minutes: 0, seconds: 0),
seekTo: (to) {
_assetsAudioPlayer?.seek(to);
},
);
}
}
}),

/// slider class

import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

class PositionSeekWidget extends StatefulWidget {
final Duration currentPosition;
final Duration duration;
final Function(Duration) seekTo;

const PositionSeekWidget({required this.currentPosition, required this.duration, required this.seekTo});

@OverRide
_PositionSeekWidgetState createState() => _PositionSeekWidgetState();
}

class _PositionSeekWidgetState extends State {
late Duration _visibleValue;
bool listenOnlyUserInteraction = false;

double get percent => widget.duration.inMilliseconds == 0 ? 0 : _visibleValue.inMilliseconds / widget.duration.inMilliseconds;

@OverRide
void initState() {
super.initState();
_visibleValue = widget.currentPosition;
}

@OverRide
void didUpdateWidget(PositionSeekWidget oldWidget) {
super.didUpdateWidget(oldWidget);
if (!listenOnlyUserInteraction) {
_visibleValue = widget.currentPosition;
}
}

@OverRide
Widget build(BuildContext context) {
Duration d = widget.duration - widget.currentPosition;
String m = d.toString().substring(2, 4);
String s = d.toString().substring(5, 7);
return Padding(
padding: const EdgeInsets.all(8.0),
child: Column(
children: [
Slider(
activeColor: Constant.whiteColor,
thumbColor: Constant.whiteColor,
inactiveColor: Constant.alertDialogColor,
label: widget.duration.toString(),
min: 0,
max: widget.duration.inMilliseconds.toDouble(),
value: percent * widget.duration.inMilliseconds.toDouble(),
onChangeEnd: (newValue) {
setState(() {
listenOnlyUserInteraction = false;
widget.seekTo(visibleValue);
});
},
onChangeStart: () {
setState(() {
listenOnlyUserInteraction = true;
});
},
onChanged: (newValue) {
setState(() {
final to = Duration(milliseconds: newValue.floor());
_visibleValue = to;
});
},
),
Row(
mainAxisAlignment: MainAxisAlignment.spaceBetween,
children: [
SizedBox(
width: 40,
child: Text(durationToString(widget.currentPosition))
/
),
SizedBox(
width: 40,
child: Text(durationToString(widget.duration))
),
],
),
],
),
);
}
}

String durationToString(Duration duration) {
String twoDigits(int n) {
if (n >= 10) return '$n';
return '0$n';
}

final twoDigitHours = twoDigits(duration.inHours.remainder(Duration.hoursPerDay));
final twoDigitMinutes = twoDigits(duration.inMinutes.remainder(Duration.minutesPerHour));
final twoDigitSeconds = twoDigits(duration.inSeconds.remainder(Duration.secondsPerMinute));
return twoDigitHours == "00" ? '$twoDigitMinutes:$twoDigitSeconds' : '$twoDigitHours:$twoDigitMinutes:$twoDigitSeconds';
}
```
