### ISSUE TITLE
type 'Null' is not a subtype of type 'String' 

### ISSUE THREAD

**Issue by zxl777** [florent37/Flutter-AssetsAudioPlayer#526]
![image](https://user-images.githubusercontent.com/816448/116063312-69d93280-a6b7-11eb-8a21-e0885ed7ed6d.png)

**Comment by zxl777** [comment]
Fixed it by
```
  void _handleOnError(Map args) async {
    final String errorType = args['type'];
    if (args['message'] == null) args['message'] = '';
    final String errorMessage = args['message'];
```

**Comment by Mayb3Nots** [comment]
or this is less verbose.
```
 void _handleOnError(Map args) async {
    final String errorType = args['type'] ?? '';
    final String errorMessage = args['message'] ?? '';
    final error = AssetsAudioPlayerError(
      errorType: parseAssetsAudioPlayerErrorType(errorType),
      message: errorMessage,
    );
```

**Comment by Mayb3Nots** [comment]
could you do a pull request on this? Might be good to fix it to prevent future errors.

**Comment by RR-Reddy** [comment]
@Mayb3Nots  facing same issue 

***Error log***
![Screenshot 2021-05-03 at 8 43 22 AM](https://user-images.githubusercontent.com/32235964/116838367-bd81d980-abeb-11eb-995b-4c5fb38257df.png)

Can you guys please fix this issue ASAP and release it to pub.dev

@zxl777

**Comment by RR-Reddy** [comment]
@Mayb3Nots  here is pull request #535

**Comment by kalismeras61** [comment]
Fixed latest version.
