### ISSUE TITLE
Respect Silence

### ISSUE THREAD

**Issue by MobileMon** [florent37/Flutter-AssetsAudioPlayer#54]
Is there anyway to respect silence of the mute switch?

I like this library better than other audioplayers but its missing that key feature

**Comment by florent37** [comment]
you want a mute switch ? 

If it's what you want, you can set the volume of the song at 0 

```dart
assetsAudioPlayer.open(yourAudio, volume: 0); //at open

assetsAudioPlayer.setVolume(0); //when playing
```

**Comment by florent37** [comment]
It it's not your what you want, can you add a sample of your need ?

**Comment by florent37** [comment]
Oh you mean that https://stackoverflow.com/questions/2048427/how-can-i-detect-whether-the-android-phone-in-silent-mode-programmatically

**Comment by florent37** [comment]
You have now a new parameter on `open` named `respectSilentMode`

```
_assetsAudioPlayer.open(myAudio.audio, autoStart: false, respectSilentMode: true);
```

on android, it force the volume at 0, you cannot have set a different volume if the switch is still off (will try later to re-enable it when the switch changes)

on ios : it follow this rule 

```
AVAudioSessionCategorySoloAmbient: Your audio is silenced by screen locking and by the Silent switch

AVAudioSessionCategoryPlayBack: Your Audio continues with the Silent switch set to silent or when the screen locks
```

**Comment by florent37** [comment]
now on android you can change the switch, and it "mute" / "demute" dynamically with no required prog action

**Comment by florent37** [comment]
it's pushed in `1.3.9+1` can you try it ? if it's ok, push a 1.4.0 👍

**Comment by florent37** [comment]
```_player.open(PLAYABLE, respectSilentMode: true);```

**Comment by MobileMon** [comment]
On iOS its working as expected

Haven't tested Android and probably won't any time soon

**Comment by florent37** [comment]
;) I tested on my Android phone and on iOS simulator. Thanks for your issues ! Don't hesitate to send others :)

**Comment by ollydixon** [comment]
I don't see these options on ```audioplayers: ^1.0.0-rc.4```

We're using ^1.0.0-rc.4 because the previous version is broken on some Android devices.

**Comment by ollydixon** [comment]
@kalismeras61 ah yes sorry.
