### ISSUE TITLE
Has anyone successfully tried to dynamically fetch multiple audio data from firestore?

### ISSUE THREAD

**Issue by ogbodotg** [florent37/Flutter-AssetsAudioPlayer#542]
Hi, 

I have been trying to dynamically populate the audios list with data from firestore without success. 

I have 3 songs in the db collection, but i was only able to get 1 of them into the audios list. 

I don't want to add the song urls statically as shown in the example. Can anyone please help?

i am getting frustrated after so many attempts and failures. I have tried everything i could think of.

**Comment by Mayb3Nots** [comment]
Can you provide some sample code? Have you tried `Playlist`

**Comment by yubarajshrestha** [comment]
@ogbodotg 

Steps to your solution:
1. Fetch list of songs first
2. Create playlist with the list of songs.
3. Open player with the playlist.

```dart
List<String> songs = []; // list of your firebase song urls
Playlist playlist = songs.map((song) => Audio.network(song, metas: {}));
AssetsAudioPlayer().open(playlist, showNotification: true, autoStart: true);
```
Above code snippet is from my working application.

**Comment by ogbodotg** [comment]
Thank you very much for your help @yubarajshrestha

**Comment by Mayb3Nots** [comment]
@ogbodotg Please close this if your issue is resolved
