### ISSUE TITLE
[Q] How to know and execute some method when audio is finished playing?

### ISSUE THREAD

**Issue by UsamaKarim** [florent37/Flutter-AssetsAudioPlayer#545]
Hi, I am trying to implement a very basic audio playing experience but I need some kind of help. The question is how could I know that `audio file` is finished playing? 

I tried with `player.isPlaying` and I am not able to get the `player.isPlaying.value` as mentioned in docs.
I also tried with 
`assetsAudioPlayer.playlistAudioFinished.listen((Playing playing){})`
&
`assetsAudioPlayer.playlistFinished.listen((finished){})`

**Comment by Mayb3Nots** [comment]
Hi I have tested on the lastest version that `playlistAudioFinished` is working. Maybe you can provide some sample code for us to help you.

**Comment by UsamaKarim** [comment]
> Hi I have tested on the lastest version that `playlistAudioFinished` is working. Maybe you can provide some sample code for us to help you.

Thanks for the reply. I found it that it's working. 
Can you please help me with my code? I want to update the widget after the audio playing is finished, I find out that `playlistAudioFinished` return stream, Since I never worked with stream before, So, I don't know what to do. Here is my code if you can do any help

Widget I want to rebuild, Since I want to animated the button

```dart
 Consumer<AudioPickerProvider>(
              builder: (_, provider, __) => Visibility(
                visible: !provider.isRecording && !provider.noAudio,
                child: _CustomButton(
                  child: Center(
                    child: AnimatedIcon(
                      icon: AnimatedIcons.play_pause,
                      progress: _controller,
                      color: Colors.green,
                    ),
                  ),
                  onTap: () async {
                    if (provider.isPlaying) {
                      await provider.stop();
                      _controller.reverse();
                    } else {
                      await provider.play();
                      _controller.forward();
                    }
                  },
                ),
              ),
            ),

```
Here is my method, `play()` method executed instantly as I get the animation pressing the button (I am using Provider package)

```dart

  Future<void> play() async {
    _player = AssetsAudioPlayer();
    if (_audio == null) return;
    await _player.open(Audio.file(_audio.path));
    _player.play();
    _isPlaying = true;
    _player.playlistAudioFinished.listen((event) async {
      print('executed');
      await stop();
    });
    // notifyListeners();
  }

  Future<void> stop() async {
    _player.stop();
    _isPlaying = false;
    // notifyListeners();
  }
```

**Comment by Mayb3Nots** [comment]
You would wanna use a `StreamBuilder` widget for your case, or you can use a listen to a stream and use the controller to animate. I suggest you search online on how to use it. Below is the 2nd example where you subscribe to a stream and listen to events and according to the events (Play/Pause) you wanna update your animation controller accordingly.

```
  late AnimationController _animationController;
  late StreamSubscription stream;

  @override
  void initState() {
    stream = player.isPlaying.listen((event) {
      if (event && mounted) {
        _animationController.reverse();
      } else if (mounted) {
        _animationController.forward();
      }
    });
    _animationController =
        AnimationController(vsync: this, duration: Duration(milliseconds: 450));

    super.initState();
  }
 @override
  void dispose() {
    _animationController.dispose();
    stream.cancel();
    super.dispose();
  }

 ElevatedButton(
                        onPressed: () => player.playOrPause()!
                            ? _animationController.forward()
                            : _animationController.reverse(),
                        child: AnimatedIcon(
                            size: getPWidth(30),
                            icon: AnimatedIcons.pause_play,
                            color: Colors.black,
                            progress: _animationController),
                        style: ElevatedButton.styleFrom(
                          primary: Colors.white,
                          padding: EdgeInsets.all(16),
                          minimumSize: Size(getPWidth(50), getPWidth(50)),
                          shape: CircleBorder(),
                          elevation: 0.0,
                        ),
                      ),
```

Also a few thing to note in your code:

1. You don't have to create your own `_isPlaying` property because the player already has one as a stream.
2. try not to create a new player instance every time you play something.
3. You don't have to manually call play after you open. By default, it auto-plays the song.
4. And also when the audio is finished playing the play stops by it self. So no need to call `stop()`
