### ISSUE TITLE
App sounds stops when opening another music app like spotify

### ISSUE THREAD

**Issue by Daventer** [florent37/Flutter-AssetsAudioPlayer#546]
Hi, I am trying to implement a very basic timer with a metronomic sounds. I got it working, but the audio stops when opening music from another app.

So my question is, is it possible to make it work simultaneously with audio from other applications?

**Comment by kalismeras61** [comment]
Which os are you trying ? Did you tried AudioFocusStragety none ?

**Comment by Daventer** [comment]
Ooh damnn, AudioFocusStrategy none worked! Should have read the documentation better.... Thnx man!
