### ISSUE TITLE
Screen shaking or being dark

### ISSUE THREAD

**Issue by muratmjdci** [florent37/Flutter-AssetsAudioPlayer#547]
**Flutter Version**
My version : 2.0

**Lib Version**
My version : 3.0.3+3

**Platform (Android / iOS / web) + version**
Platform : Android

**Describe the bug**
when taking app to background several times, screen is being dark or screen is shaking

video1: https://go.4vio.com/4861bn0
video2: https://go.4vio.com/4df1bn3

**Comment by kalismeras61** [comment]
This issue not related to this plugin. Please check your codebase.
