### ISSUE TITLE
Is there a way to open the player while app is in background?

### ISSUE THREAD

**Issue by aadesh1993** [florent37/Flutter-AssetsAudioPlayer#548]
So essentially what i am trying to do is play an audio when a user enters a geo fence region. The problem is the player never opens while my app is in background(not killed). 

When i reopen the app the audio is played as expected. Is there a way to play the audio while the app is still in background?

**Comment by Mayb3Nots** [comment]
If the app is in the background and you are listening to a geofence region, I don't see how you couldn't open a player when entering a certian region.

**Comment by aadesh1993** [comment]
Figured it out. The ui was the problem. Player does run in background.
