### ISSUE TITLE
Stop on back button press

### ISSUE THREAD

**Issue by ScottishRoss** [florent37/Flutter-AssetsAudioPlayer#550]
I have tried wrapping the AudioPlayer widget in an OnWillPop() to try and call the stop function, but it doesn't seem to work. What is the best way to implement stopping, or pausing, an audio file on the back button press, and even better if you go back into the file it remembers where you were?

**Comment by kalismeras61** [comment]
Use statefull widget and add pause method inside dispose function.
 
 @override
  void dispose() {
    super.dispose();
  }

**Comment by ScottishRoss** [comment]
After figuring out dispose(), that seems to work. Thanks!
