### ISSUE TITLE
how to use uint8list image on notification

### ISSUE THREAD

**Issue by adem74** [florent37/Flutter-AssetsAudioPlayer#570]
how to use uint8list image on notification

**Comment by Mayb3Nots** [comment]
You can save the data in a file and then use `MetasImage.file`

**Comment by adem74** [comment]
> 
> 
> You can save the data in a file and then use `MetasImage.file`

I take uint8list directly from mp3 files. If i create a image file for every mp3 files. I thought it might take a long time for hundreds mp3.

**Comment by Mayb3Nots** [comment]
It doesnt take any time create file, if creating many blocks your main thread try using an isolate.

**Comment by adem74** [comment]
> It doesnt take any time create file, if creating many blocks your main thread try using an isolate.

it worked thank you so much for your advice :)
