### ISSUE TITLE
audio not playing in android

### ISSUE THREAD

**Issue by muskanstegowl** [florent37/Flutter-AssetsAudioPlayer#575]
**Flutter Version**

My version : 

**Lib Version**

My version : 

**Platform (Android / iOS / web) + version**

Platform : 

**Describe the bug**

I/ExoPlayerImpl( 4939): Init e3eaaf9 [ExoPlayerLib/2.13.2] [raphaelin, Redmi K20 Pro, Xiaomi, 29]
D/AudioManager( 4939): getStreamVolume isRestricted mode = 0
E/ExoPlayerImplInternal( 4939): Playback error
E/ExoPlayerImplInternal( 4939):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal( 4939):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:579)
E/ExoPlayerImplInternal( 4939):       at android.os.Handler.dispatchMessage(Handler.java:103)
E/ExoPlayerImplInternal( 4939):       at android.os.Looper.loop(Looper.java:224)
E/ExoPlayerImplInternal( 4939):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal( 4939):   Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$CleartextNotPermittedException: Cleartext HTTP traffic not permitted. See https://exoplayer.dev/issues/cleartext-not-permitted
E/ExoPlayerImplInternal( 4939):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:354)
E/ExoPlayerImplInternal( 4939):       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
E/ExoPlayerImplInternal( 4939):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1015)
E/ExoPlayerImplInternal( 4939):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)
E/ExoPlayerImplInternal( 4939):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal( 4939):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal( 4939):       at java.lang.Thread.run(Thread.java:919)
E/ExoPlayerImplInternal( 4939):   Caused by: java.io.IOException: Cleartext HTTP traffic to 54.164.120.46 not permitted
E/ExoPlayerImplInternal( 4939):       at com.android.okhttp.HttpHandler$CleartextURLFilter.checkURLPermitted(HttpHandler.java:124)
E/ExoPlayerImplInternal( 4939):       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:462)
E/ExoPlayerImplInternal( 4939):       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
E/ExoPlayerImplInternal( 4939):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:641)
E/ExoPlayerImplInternal( 4939):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:543)
E/ExoPlayerImplInternal( 4939):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:349)
E/ExoPlayerImplInternal( 4939):       ... 6 more
I/ExoPlayerImpl( 4939): Release e3eaaf9 [ExoPlayerLib/2.13.2] [raphaelin, Redmi K20 Pro, Xiaomi, 29] [goog.exo.core]
V/MediaPlayer( 4939): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 4939): cleanDrmObj: mDrmObj=null mDrmSessionId=null
W/MediaPlayer( 4939): Couldn't open http://54.164.120.46/...
W/MediaPlayer( 4939): java.io.FileNotFoundException: No content provider: http://54.164.120.46/djbigty/storage/uploads/RBRAW1_1609200925.mp3
W/MediaPlayer( 4939): 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1688)
W/MediaPlayer( 4939): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1518)
W/MediaPlayer( 4939): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1435)
W/MediaPlayer( 4939): 	at android.media.MediaPlayer.attemptDataSource(MediaPlayer.java:1159)
W/MediaPlayer( 4939): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1117)
W/MediaPlayer( 4939): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1155)
W/MediaPlayer( 4939): 	at com.github.florent37.assets_audio_player.playerimplem.PlayerImplemMediaPlayer$open$2.invokeSuspend(PlayerImplemMediaPlayer.kt:127)
W/MediaPlayer( 4939): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
W/MediaPlayer( 4939): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
W/MediaPlayer( 4939): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
W/MediaPlayer( 4939): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
W/MediaPlayer( 4939): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
W/MediaPlayer( 4939): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
V/MediaHTTPService( 4939): MediaHTTPService(android.media.MediaHTTPService@b552e6d): Cookies: null
V/MediaHTTPService( 4939): makeHTTPConnection: CookieHandler (java.net.CookieManager@5df7343) exists.
V/MediaHTTPService( 4939): makeHTTPConnection(android.media.MediaHTTPService@b552e6d): cookieHandler: java.net.CookieManager@5df7343 Cookies: null
E/MediaPlayerNative( 4939): error (1, -2147483648)
V/MediaPlayer( 4939): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 4939): cleanDrmObj: mDrmObj=null mDrmSessionId=null
W/System.err( 4939): com.github.florent37.assets_audio_player.playerimplem.PlayerFinder$NoPlayerFoundException
W/System.err( 4939): 	at com.github.florent37.assets_audio_player.playerimplem.PlayerFinder._findWorkingPlayer(PlayerFinder.kt:69)
W/System.err( 4939): 	at com.github.florent37.assets_audio_player.playerimplem.PlayerFinder._findWorkingPlayer(PlayerFinder.kt:87)
W/System.err( 4939): 	at com.github.florent37.assets_audio_player.playerimplem.PlayerFinder$_findWorkingPlayer$1.invokeSuspend(Unknown Source:12)
W/System.err( 4939): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
W/System.err( 4939): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
W/System.err( 4939): 	at android.os.Handler.handleCallback(Handler.java:914)
W/System.err( 4939): 	at android.os.Handler.dispatchMessage(Handler.java:100)
W/System.err( 4939): 	at android.os.Looper.loop(Looper.java:224)
W/System.err( 4939): 	at android.app.ActivityThread.main(ActivityThread.java:7560)
W/System.err( 4939): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 4939): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
W/System.err( 4939): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
I/flutter ( 4939): PlatformException(OPEN, null, null, null)
E/flutter ( 4939): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Exception: unble to play audio beacuse or Exception PlatformException(OPEN, null, null, null)
E/flutter ( 4939): #0      _MusicScreenState.openPlayer (package:stress_ball_merchandise/MusicScreen.dart:57:7)
E/flutter ( 4939): <asynchronous suspension>
E/flutter ( 4939): 
E/MediaPlayerNative( 4939): error (1, -2147483648)
V/MediaPlayer( 4939): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 4939): cleanDrmObj: mDrmObj=null mDrmSessionId=null
W/System.err( 4939): com.github.florent37.assets_audio_player.playerimplem.PlayerFinder$NoPlayerFoundException
W/System.err( 4939): 	at com.github.florent37.assets_audio_player.playerimplem.PlayerFinder._findWorkingPlayer(PlayerFinder.kt:69)
W/System.err( 4939): 	at com.github.florent37.assets_audio_player.playerimplem.PlayerFinder._findWorkingPlayer(PlayerFinder.kt:87)
W/System.err( 4939): 	at com.github.florent37.assets_audio_player.playerimplem.PlayerFinder$_findWorkingPlayer$1.invokeSuspend(Unknown Source:12)
W/System.err( 4939): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
W/System.err( 4939): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
W/System.err( 4939): 	at android.os.Handler.handleCallback(Handler.java:914)
W/System.err( 4939): 	at android.os.Handler.dispatchMessage(Handler.java:100)
W/System.err( 4939): 	at android.os.Looper.loop(Looper.java:224)
W/System.err( 4939): 	at android.app.ActivityThread.main(ActivityThread.java:7560)
W/System.err( 4939): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 4939): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
W/System.err( 4939): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
I/flutter ( 4939): PlatformException(OPEN, null, null, null)
E/flutter ( 4939): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(OPEN, null, null, null)
E/flutter ( 4939):

**Comment by xmrfast** [comment]
you are using http:// you must use https:// file!
or add this to youe Android Manifest

android:usesCleartextTraffic="true"

**Comment by anasssanba1** [comment]
> you are using http:// you must use https:// file!
> or add this to your Android Manifest
> 
> android:usesCleartextTraffic="true"

what do you mean by  https:// file? adding  android:usesCleartextTraffic="true"

do not work for me
