### ISSUE TITLE
Not working with Flutter version >=2.0.0

### ISSUE THREAD

**Issue by harshkumarkhatri** [florent37/Flutter-AssetsAudioPlayer#578]
**Describe the feature you'd like**
Please make this plugin available for Flutter version >=2.0.0

**Comment by markst** [comment]
@harshkumarkhatri I'm using Flutter `2.2.0` + assets_audio_player `3.0.3+3 and is working fine.

**Comment by harshkumarkhatri** [comment]
@markst There were some other issues that were arising when I was using this plugin in combination with other plugins. It seems to be working for me after some changes in the code.
