### ISSUE TITLE
getting error of same class of exoplayer in android

### ISSUE THREAD

**Issue by radhen-thirstydevs** [florent37/Flutter-AssetsAudioPlayer#583]
**Flutter Version**

My version :  2.2.3

**Lib Version**

My version : 3.0.3+3

**Platform (Android / iOS / web) + version**

Platform : android

**Describe the bug**

I got an error when building the project suddenly got error of same class path

**Small code to reproduce**

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.google.android.exoplayer2.ui.package-info found in modules jetified-exoplayer-common-2.14.1-runtime (com.google.android.exoplayer:exoplayer-common:2.14.1) and jetified-exoplayer-ui-2.13.2-runtime (com.google.android.exoplayer:exoplayer-ui:2.13.2)

     Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 31s

```

**Comment by JMApps** [comment]
I have a similar problem, only this has to do with exoplayer:

**Duplicate class com.google.android.exoplayer2.ui.package-info found in modules jetified-exoplayer-common-2.14.1-runtime (com.google.android.exoplayer: exoplayer-common: 2.14.1) and jetified-exoplayer -ui-2.13.2-runtime (com.google.android.exoplayer: exoplayer-ui: 2.13.2)**

In the root of the libraries, I observe this:

<img width="639" alt="Снимок экрана 2021-07-15 в 12 12 00" src="https://user-images.githubusercontent.com/40570649/125762754-ee6450e3-5daf-4127-a183-e73823e231b5.png">

And even if I remove some libraries, the error still remains.

**Comment by radhen-thirstydevs** [comment]
@JMApps I think this is an one type of bug. I didn't get any solution. I'll inform you when I got the solution

**Comment by JMApps** [comment]
Yes, definitely. Note, everything works well on iOS, the problem is on the android platform. I will also inform you if I can decide about.

**Comment by radhen-thirstydevs** [comment]
oh ! in iOS works fine that's good, @JMApps thank you buddy.

**Comment by JMApps** [comment]
@kalismeras61 Your library calls two different versions of exoplayer, if you specify either the latest version or something specifically, that would be enough for now. We are waiting for your reply.

**Comment by radhen-thirstydevs** [comment]
Hey I got the solution u can use this

**Comment by radhen-thirstydevs** [comment]
Hey I got the solution you can use this

assets_audio_player:
  git:
    url: https://github.com/radhen-thirstydevs/Flutter-AssetsAudioPlayer.git
    ref: master

**Comment by radhen-thirstydevs** [comment]
in pubspect.yaml file
under dependecy

**Comment by kalismeras61** [comment]
Fixed latest version.

**Comment by JMApps** [comment]
> Fixed latest version.

Great, now everything works! Thank you!

**Comment by radhen-thirstydevs** [comment]
> Fixed latest version.

thanks buddy 👍🏻
