### ISSUE TITLE
Web: PlatformException(error, Expected a value of type 'double', but got one of type 'Null', null, null)

### ISSUE THREAD

**Issue by Curvel** [florent37/Flutter-AssetsAudioPlayer#594]
**Flutter Version**

My version :  Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale en-DE)

**Lib Version**

My version : 3.0.3+6

**Platform (Android / iOS / web) + version**

Platform : macOs Chrome Version 92.0.4515.107 (Official Build) (x86_64)

**Describe the bug**

When starting the example app or try to call `.open`, the exception `PlatformException(error, Expected a value of type 'double', but got one of type 'Null', null, null)` is thrown, and the song isn't played.

**Small code to reproduce**
Start the example app in web.

Furthermore, dart analysis shows the following exception
![image](https://user-images.githubusercontent.com/13559511/127373829-3e368bfa-14e2-4654-89fa-980474b5942c.png)

**Comment by kalismeras61** [comment]
Merged will be next build.
