### ISSUE TITLE
Try correcting the name to the name of an existing getter, or defining a getter or field named 'valueOrNull'.       autoStart: isPlaying.valueOrNull ?? false,

### ISSUE THREAD

**Issue by PillarChen** [florent37/Flutter-AssetsAudioPlayer#597]
Flutter2
com.android.tools.build:gradle:4.1.0

assets_audio_player: 3.0.3+4

异常提示:

../../Documents/setup/develop/flutter/.pub-cache/hosted/pub.flutter-io.cn/assets_audio_player-3.0.3+4/lib/src/player_group.dart:135:28: Error: The getter 'valueOrNull' isn't defined for the class 'ValueStream<bool>'.
 - 'ValueStream' is from 'package:rxdart/src/streams/value_stream.dart' ('../../Documents/setup/develop/flutter/.pub-cache/hosted/pub.flutter-io.cn/rxdart-0.24.1/lib/src/streams/value_stream.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'valueOrNull'.
      autoStart: isPlaying.valueOrNull ?? false,

**Comment by kalismeras61** [comment]
You have to run flutter clean and then flutter pub get. If you use rxdart in your project please use rxdart: ^0.27.0

**Comment by lyntree** [comment]
Thank you @kalismeras61  it does work x
