### ISSUE TITLE
Execution failed for task ':assets_audio_player:compileDebugKotlin ON 1.4.0

### ISSUE THREAD

**Issue by kw2019ltd** [florent37/Flutter-AssetsAudioPlayer#60]
Launching lib\main.dart on HD1903 in debug mode...
Running Gradle task 'assembleDebug'...
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.3.8+1\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (14, 14): Conflicting declarations: internal val METHOD_POSITION: String, internal val METHOD_POSITION: String
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.3.8+1\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (15, 14): Conflicting declarations: internal val METHOD_VOLUME: String, internal val METHOD_VOLUME: String
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.3.8+1\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (16, 14): Conflicting declarations: internal val METHOD_FINISHED: String, internal val METHOD_FINISHED: String
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.3.8+1\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (17, 14): Conflicting declarations: internal val METHOD_IS_PLAYING: String, internal val METHOD_IS_PLAYING: String
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.3.8+1\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (18, 14): Conflicting declarations: internal val METHOD_CURRENT: String, internal val METHOD_CURRENT: String
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.3.8+1\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (19, 14): Conflicting declarations: internal val METHOD_NEXT: String, internal val METHOD_NEXT: String
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.3.8+1\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (20, 14): Conflicting declarations: internal val METHOD_PREV: String, internal val METHOD_PREV: String
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.3.8+1\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (22, 7): Redeclaration: Player
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.3.8+1\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (40, 42): Overload resolution ambiguity: 
internal val METHOD_POSITION: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
internal val METHOD_POSITION: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.3.8+1\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (74, 34): Overload resolution ambiguity: 
internal val METHOD_POSITION: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
internal val METHOD_POSITION: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.3.8+1\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (86, 38): Overload resolution ambiguity: 
internal val METHOD_CURRENT: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
internal val METHOD_CURRENT: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.3.8+1\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (101, 34): Overload resolution ambiguity: 
internal val METHOD_POSITION: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
internal val METHOD_POSITION: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.3.8+1\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (111, 34): Overload resolution ambiguity: 
internal val METHOD_FINISHED: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
internal val METHOD_FINISHED: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.3.8+1\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (125, 34): Overload resolution ambiguity: 
internal val METHOD_POSITION: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
internal val METHOD_POSITION: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.3.8+1\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (130, 34): Overload resolution ambiguity: 
internal val METHOD_IS_PLAYING: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
internal val METHOD_IS_PLAYING: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.3.8+1\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (149, 34): Overload resolution ambiguity: 
internal val METHOD_IS_PLAYING: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
internal val METHOD_IS_PLAYING: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.3.8+1\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (157, 34): Overload resolution ambiguity: 
internal val METHOD_IS_PLAYING: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
internal val METHOD_IS_PLAYING: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.3.8+1\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (164, 34): Overload resolution ambiguity: 
internal val METHOD_POSITION: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
internal val METHOD_POSITION: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.3.8+1\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (171, 34): Overload resolution ambiguity: 
internal val METHOD_VOLUME: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
internal val METHOD_VOLUME: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.3.8+1\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (176, 7): Redeclaration: AssetsAudioPlayerPlugin
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.0\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (11, 14): Conflicting declarations: internal val METHOD_POSITION: String, internal val METHOD_POSITION: String
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.0\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (12, 14): Conflicting declarations: internal val METHOD_VOLUME: String, internal val METHOD_VOLUME: String
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.0\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (13, 14): Conflicting declarations: internal val METHOD_FINISHED: String, internal val METHOD_FINISHED: String
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.0\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (14, 14): Conflicting declarations: internal val METHOD_IS_PLAYING: String, internal val METHOD_IS_PLAYING: String
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.0\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (15, 14): Conflicting declarations: internal val METHOD_CURRENT: String, internal val METHOD_CURRENT: String
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.0\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (16, 14): Conflicting declarations: internal val METHOD_NEXT: String, internal val METHOD_NEXT: String
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.0\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (17, 14): Conflicting declarations: internal val METHOD_PREV: String, internal val METHOD_PREV: String
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.0\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (20, 7): Redeclaration: AssetsAudioPlayerPlugin
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.0\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (35, 40): No value passed for parameter 'channel'
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.0\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (37, 17): Unresolved reference: onVolumeChanged
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.0\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (37, 37): Cannot infer a type for this parameter. Please specify it explicitly.
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.0\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (38, 42): Overload resolution ambiguity: 
internal val METHOD_VOLUME: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
internal val METHOD_VOLUME: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.0\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (40, 17): Unresolved reference: onPositionChanged
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.0\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (40, 39): Cannot infer a type for this parameter. Please specify it explicitly.
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.0\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (41, 42): Overload resolution ambiguity: 
internal val METHOD_POSITION: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
internal val METHOD_POSITION: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.0\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (43, 17): Unresolved reference: onReadyToPlay
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.0\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (43, 35): Cannot infer a type for this parameter. Please specify it explicitly.
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.0\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (44, 42): Overload resolution ambiguity: 
internal val METHOD_CURRENT: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
internal val METHOD_CURRENT: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.0\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (44, 58): Type inference failed: Not enough information to infer parameter V in fun <K, V> mapOf(pair: Pair<K, V>): Map<K, V>
Please specify it explicitly.

e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.0\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (48, 17): Unresolved reference: onPlaying
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.0\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (49, 42): Overload resolution ambiguity: 
internal val METHOD_IS_PLAYING: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
internal val METHOD_IS_PLAYING: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.0\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (49, 61): Unresolved reference: it
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.0\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (51, 17): Unresolved reference: onFinished
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.0\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (52, 42): Overload resolution ambiguity: 
internal val METHOD_FINISHED: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
internal val METHOD_FINISHED: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.0\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (177, 29): Type mismatch: inferred type is Boolean but MethodChannel.Result was expected
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.0\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (178, 29): Type mismatch: inferred type is MethodChannel.Result but Context was expected
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.0\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (179, 29): Too many arguments for public final fun open(assetAudioPath: String?, audioType: String, autoStart: Boolean, volume: Double, seek: Int?, result: MethodChannel.Result, context: Context): Unit defined in com.github.florent37.assets_audio_player.Player
e: C:\Tools\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.0\android\src\main\kotlin\com\github\florent37\assets_audio_player\Player.kt: (10, 7): Redeclaration: Player

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':assets_audio_player:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 18s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by florent37** [comment]
just perform a `flutter clean` :)
