### ISSUE TITLE
[WEB] Sound is not playing

### ISSUE THREAD

**Issue by youssef-fk** [florent37/Flutter-AssetsAudioPlayer#610]
**Flutter Version**

My version : 2.2.3

**Lib Version**

My version : assets_audio_player: ^3.0.3+6

**Platform (Android / iOS / web) + version**

Platform : Version 92.0.4515.159 (Official Build) (x86_64)

**Describe the bug**

The plugin works wonderfully on android and iOS. However on my web build it is not playing a sound.

**Small code to reproduce**

```dart
import 'package:assets_audio_player/assets_audio_player.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State {
  
  final AssetsAudioPlayer audioPlayer = AssetsAudioPlayer.newPlayer()
      ..open(
        Audio("assets/sounds/right.mp3"),
        autoStart: false,
      );

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: RaisedButton(
            child: Text("open"),
            onPressed: () {
                audioPlayer.stop();
                audioPlayer.play();
            }
          ),
        ),
      ),
    );
  }
}
```

**Comment by sarpde** [comment]
I'm having the same issue. Works on mobile but I get an error on web. Getting the error below:
PlatformException(error, Expected a value of type 'double', but got one of type 'Null', null, null)

**Comment by Victor-Dev77** [comment]
Same error, do you know if there is an older version that works for the web?

**Comment by jamontes79** [comment]
Any news of this? Thanks in advance

**Comment by kalismeras61** [comment]
Please use next build

**Comment by raahimz** [comment]
**Very simple solution!**
So apparently, web browsers have strict security policies that prevent direct access to the local file system... all you have to do is **replace** `assetsAudioPlayer.open(Audio("assets/audios/bg.mp3")` with `assetsAudioPlayer.open(Audio.network("assets/audios/bg.mp3")`

**Comment by amad-a96** [comment]
i used this package https://pub.dev/packages/audioplayer and worked for web



    import 'dart:typed_data';
    import 'package:audioplayers/audioplayers.dart';
    import 'package:flutter/services.dart';
 code:

          AudioPlayer player = AudioPlayer();
          String audioasset = "assets/sound/bell-dinging-jam-fx-2-2-00-05.mp3";
          ByteData bytes =
              await rootBundle.load(audioasset); //load sound from assets
          Uint8List soundbytes =
              bytes.buffer.asUint8List(bytes.offsetInBytes, bytes.lengthInBytes);
    
          final urlSource = UrlSource(
              Uri.dataFromBytes(soundbytes, mimeType: 'audio/mpeg').toString());
    
          player.play(urlSource);

**Comment by Anna-Myzukina** [comment]
> **Flutter Version**
> 
> My version : 2.2.3
> 
> **Lib Version**
> 
> My version : assets_audio_player: ^3.0.3+6
> 
> **Platform (Android / iOS / web) + version**
> 
> Platform : Version 92.0.4515.159 (Official Build) (x86_64)
> 
> **Describe the bug**
> 
> The plugin works wonderfully on android and iOS. However on my web build it is not playing a sound.
> 
> **Small code to reproduce**
> 
> ```dart
> import 'package:assets_audio_player/assets_audio_player.dart';
> import 'package:flutter/material.dart';
> 
> void main() {
>   runApp(MyApp());
> }
> 
> class MyApp extends StatefulWidget {
>   @override
>   _MyAppState createState() => _MyAppState();
> }
> 
> class _MyAppState extends State {
>   
>   final AssetsAudioPlayer audioPlayer = AssetsAudioPlayer.newPlayer()
>       ..open(
>         Audio("assets/sounds/right.mp3"),
>         autoStart: false,
>       );
> 
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       home: Scaffold(
>         body: Center(
>           child: RaisedButton(
>             child: Text("open"),
>             onPressed: () {
>                 audioPlayer.stop();
>                 audioPlayer.play();
>             }
>           ),
>         ),
>       ),
>     );
>   }
> }
> ```

you need 1) use `Audio.network("assets/...")` instead of `Audio("assets/...")` 2) try `audioPlayer.playOrPause();` instead of using ```
audioPlayer.stop();
 audioPlayer.play();
```

**Comment by ChunhThanhDe** [comment]
I want ask if anyone has actually solved this error ?
