### ISSUE TITLE
[Android] support for managing audio from Notification

### ISSUE THREAD

**Issue by vipulasri** [florent37/Flutter-AssetsAudioPlayer#62]
Is it possible to add support for managing the audios from a single notification? Like we have in android, we can manage our player from notification using controls

**Comment by florent37** [comment]
You mean support it on Android ?

**Comment by florent37** [comment]
It's a hard task to do this on Android, I should rework all the library to make it playable from a background service, display a notification, handle broadcast receivers, it's really a hard task to do.

**Comment by florent37** [comment]
Btw I planned to do that !

**Comment by vipulasri** [comment]
Okay, thanks for the update.

**Comment by vipulasri** [comment]
@florent37 I see you have made some progress on it. Is there a road plan for this feature, I could look into and can contribute to this? 
Do you have any idea, If it will be possible to show a single notification for all the media's playing simultaneously?

**Comment by florent37** [comment]
It's developed :) I have to test it, then rebase it from master and push it. I think i'll be available in next days

**Comment by florent37** [comment]
btw there will be only 1 notif for all the current application, like "play music" by google

sending a new notification will override the existing one

And if I push multiple notifications, the package will have a different behavior than on ios (only 1 notif on ios permitted)

**Comment by vipulasri** [comment]
I agree. But what is your plan to handle the notification when there are audios are playing simultaneously? 
Is it only going to show the notification generated from the last audio played? or the notification being there will be able to stop and play all the audio's at once

**Comment by florent37** [comment]
to handle notification, you have to put an extra argument on open(audio, showNotification: true)

by default it's false

Si it will only display the last audio which has showNotification=true 

if two audios have this optional parameter, when an action happen on an audio (ex: play/pause), it will display this audio meetas (title, image, play/pause, next, prev) buttons in replacement of the preivous, like it happens on ios

**Comment by florent37** [comment]
I merged it ! 

to try it: 

add metas into your audio, ex: 


```
Audio(
      "assets/audios/instrumental.mp3",
      metas: Metas(
        title: "Instrumental",
        artist: "Florent Champigny",
        album: "InstrumentalAlbum",
        image: MetasImage.network("https://i.ytimg.com/vi/zv_0dSfknBc/maxresdefault.jpg"),
      ),
    ),
```

open your song using `showNotification: true,`

```
_assetsAudioPlayer.open(
      audio,
      showNotification: true,
);
```

**Comment by florent37** [comment]
<img width="371" alt="Capture d’écran 2020-05-12 à 22 18 28" src="https://user-images.githubusercontent.com/5754972/81741232-85dfc600-949e-11ea-84ee-e011f9535fb8.png">

**Comment by vipulasri** [comment]
@florent37 great work man! 🎉

**Comment by florent37** [comment]
I push a 1.4.4

**Comment by florent37** [comment]
published, can you try ?

**Comment by vipulasri** [comment]
@florent37 it's working perfectly. Hurray :)

**Comment by florent37** [comment]
:) don't hesitate to send others feedbacks features and issues 🥰
