### ISSUE TITLE
LateInitializationError: Field '_totalDuration@959461076' has not been initialized

### ISSUE THREAD

**Issue by lalLAL95828** [florent37/Flutter-AssetsAudioPlayer#623]
**Flutter Version**

My version : 

**Lib Version**

My version : 

**Platform (Android / iOS / web) + version**

Platform : 

**Describe the bug**

**Small code to reproduce**

```dart
import 'package:assets_audio_player/assets_audio_player.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State {
  
  final AssetsAudioPlayer _assetsAudioPlayer = AssetsAudioPlayer();
  bool _play = false;
  @override
  Widget build(BuildContext context) {
    return AudioWidget.assets(
      path: "assets/musics/xinxiedejiuge.mp3",
      play: _play,
      child: ElevatedButton(
          child: Text(
            _play ? "pause" : "play",
          ),
          onPressed: () {
            setState(() {
              _play = !_play;
            });
          }
      ),
      onReadyToPlay: (duration) {
        //onReadyToPlay
        // print("onReadyToPlay:${duration.toString()}");
      },
      onPositionChanged: (current, duration) {
        //onPositionChanged
        // print("onPositionChanged${current.toString()}-${duration.toString()}");
      },
    );
  }
}
```

//first run error
E/flutter (19175): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: LateInitializationError: Field '_totalDuration@959461076' has not been initialized.
E/flutter (19175): #0      _AudioWidgetState._totalDuration (package:assets_audio_player/src/widget/audio_widget.dart)
E/flutter (19175): #1      _AudioWidgetState._open.<anonymous closure> (package:assets_audio_player/src/widget/audio_widget.dart:146:44)
E/flutter (19175): #2      _rootRunUnary (dart:async/zone.dart:1362:47)
E/flutter (19175): #3      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
E/flutter (19175): #4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
E/flutter (19175): #5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter (19175): #6      _DelayedData.perform (dart:async/stream_impl.dart:591:14)
E/flutter (19175): #7      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
E/flutter (19175): #8      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
E/flutter (19175): #9      _rootRun (dart:async/zone.dart:1346:47)
E/flutter (19175): #10     _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (19175): #11     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
E/flutter (19175): #12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
E/flutter (19175): #13     _rootRun (dart:async/zone.dart:1354:13)
E/flutter (19175): #14     _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (19175): #15     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
E/flutter (19175): #16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
E/flutter (19175): #17     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (19175): #18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)

**Comment by kalismeras61** [comment]
Please use latest version

**Comment by FrankenApps** [comment]
I have the same issue on the latest version (e.g. `assets_audio_player: ^3.0.5`).

**Comment by mohmdezeldeen** [comment]
I have the same issue on the latest version (e.g. assets_audio_player: ^3.0.6).
Please change `late Duration _totalDuration;` to `Duration? _totalDuration;` and handle related code.

**Comment by CK-Kumar** [comment]
Still have the same issue in the latest version ^3.1.1
