### ISSUE TITLE
audio duration not working

### ISSUE THREAD

**Issue by nacertaker** [florent37/Flutter-AssetsAudioPlayer#624]
**Flutter Version**
2.5.1

**Lib Version**
^3.0.3+6

**Platform (Android / iOS / web) + version**
Android

**Describe the bug**

assetsAudioPlayer.builderRealtimePlayingInfos(builder: (context, playerInfo){
            duration = playerInfo.duration;
           print(duration);

duration not true value

**Comment by kalismeras61** [comment]
There is no issue with the duration. Please use latest version
