### ISSUE TITLE
Player crashes when track file in invalid

### ISSUE THREAD

**Issue by MsalekM** [florent37/Flutter-AssetsAudioPlayer#627]
**Flutter Version**
Flutter (Channel stable, 2.5.0, on Ubuntu 20.04.3 LTS 5.11.0-37-generic, locale fr_FR.UTF-8)
**Platform (Android / iOS / web) + version**

Platform : Android
assets_audio_player: ^3.0.3+6
 minSdkVersion 21
 targetSdkVersion 30

**Describe the bug**

Player crashes when track file in invalid instead of giving some message.

```dart

try {
        await _assetsAudioPlayer.open(
          Audio.liveStream(
            item.url,
          ),
          playInBackground: PlayInBackground.enabled,
        );
      } catch (e) {
        await _assetsAudioPlayer.stop();
        return;
      }

```
log

`W/MediaPlayer( 7297): Couldn't open https://test.tt/media.mp3
W/MediaPlayer( 7297): java.io.FileNotFoundException: No content provider: https://test.tt/media.mp3
W/MediaPlayer( 7297):   at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1690)
W/MediaPlayer( 7297):   at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1520)
W/MediaPlayer( 7297):   at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1437)
W/MediaPlayer( 7297):   at android.media.MediaPlayer.attemptDataSource(MediaPlayer.java:1174)
W/MediaPlayer( 7297):   at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1146)
W/MediaPlayer( 7297):   at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1170)
W/MediaPlayer( 7297):   at com.github.florent37.assets_audio_player.playerimplem.PlayerImplemMediaPlayer$open$2.invokeSuspend(PlayerImplemMediaPlayer.kt:129)
W/MediaPlayer( 7297):   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
W/MediaPlayer( 7297):   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
W/MediaPlayer( 7297):   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
W/MediaPlayer( 7297):   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
W/MediaPlayer( 7297):   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
W/MediaPlayer( 7297):   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
I/OppoMediaPlayer( 7297): setDataSource(path, headers) isOppoCreate=false
V/MediaHTTPService( 7297): MediaHTTPService(android.media.MediaHTTPService@ddd12ca): Cookies: null
I/OppoMediaPlayer( 7297): prepare() isOppoCreate=false
V/MediaHTTPService( 7297): makeHTTPConnection: CookieManager created: java.net.CookieManager@516bc3b
V/MediaHTTPService( 7297): makeHTTPConnection(android.media.MediaHTTPService@ddd12ca): cookieHandler: java.net.CookieManager@516bc3b Cookies: null
E/MediaPlayerNative( 7297): error (1, -2147483648)
W/System.err( 7297): java.io.IOException: Prepare failed.: status=0x1
W/System.err( 7297):    at android.media.MediaPlayer._prepare(Native Method)
W/System.err( 7297):    at android.media.MediaPlayer.prepare(MediaPlayer.java:1414)
W/System.err( 7297):    at com.github.florent37.assets_audio_player.playerimplem.PlayerImplemMediaPlayer$open$2.invokeSuspend(PlayerImplemMediaPlayer.kt:185)
W/System.err( 7297):    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
W/System.err( 7297):    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
W/System.err( 7297):    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
W/System.err( 7297):    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
W/System.err( 7297):    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
W/System.err( 7297):    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
I/OppoMediaPlayer( 7297): handleMediaPlayerError() mCurrentState=4
I/OppoMediaPlayer( 7297): handleMediaPlayerError() mNotUsingOppoMedia is true
I/MediaPlayer( 7297): prepare failed ,throw IOException to app
I/OppoMediaPlayer( 7297): release() isOppoCreate =false
D/OppoMediaPlayer( 7297): closeFd()
V/MediaPlayer( 7297): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 7297): cleanDrmObj: mDrmObj=null mDrmSessionId=null
D/MediaPlayer( 7297): _release native called
D/MediaPlayer( 7297): _release native finished
W/System.err( 7297): com.github.florent37.assets_audio_player.playerimplem.PlayerFinder$NoPlayerFoundException
W/System.err( 7297):    at com.github.florent37.assets_audio_player.playerimplem.PlayerFinder._findWorkingPlayer(PlayerFinder.kt:70)
W/System.err( 7297):    at com.github.florent37.assets_audio_player.playerimplem.PlayerFinder._findWorkingPlayer(PlayerFinder.kt:88)
W/System.err( 7297):    at com.github.florent37.assets_audio_player.playerimplem.PlayerFinder$_findWorkingPlayer$1.invokeSuspend(Unknown Source:12)
W/System.err( 7297):    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
W/System.err( 7297):    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
W/System.err( 7297):    at android.os.Handler.handleCallback(Handler.java:883)
W/System.err( 7297):    at android.os.Handler.dispatchMessage(Handler.java:100)
W/System.err( 7297):    at android.os.Looper.loop(Looper.java:237)
W/System.err( 7297):    at android.app.ActivityThread.main(ActivityThread.java:7830)
W/System.err( 7297):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 7297):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
W/System.err( 7297):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1040)
I/flutter ( 7297): PlatformException(OPEN, null, null, null)`

**Comment by kalismeras61** [comment]
Fixed please use latest version
