### ISSUE TITLE
[Android] Pipelines: Minimum supported Gradle version is 4.10.1. Current version is 4.4

### ISSUE THREAD

**Issue by mik91** [florent37/Flutter-AssetsAudioPlayer#63]
When I've tried to launch my application after installing Assets Audio Player I've gotten error
![error](https://user-images.githubusercontent.com/41644495/80923632-d5155080-8d52-11ea-8ac0-857e4282665d.PNG)

Pipelines: Minimum supported Gradle version is 4.10.1. Current version is 4.4 for the android version.
Is it possible to update the Graddle version?

**Comment by florent37** [comment]
in your android/ dir 
modify this file : `android/gradle/wrapper/gradle-wrapper.properties`

you can upgrade the gradle file with 

`distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip`

and the `android/build.gradle`

upgrade your build:gradle 

`classpath 'com.android.tools.build:gradle:3.5.3'`

can you try ?

**Comment by florent37** [comment]
oh it's in the project ! I update it now ! sorry

**Comment by florent37** [comment]
published in `1.4.0+1` can you try ?

**Comment by mik91** [comment]
It's all working now! Thank you
