### ISSUE TITLE
how to get current duration when playing in background?

### ISSUE THREAD

**Issue by nacertaker** [florent37/Flutter-AssetsAudioPlayer#632]
i want to save player current duration before app killed to i can continue  playing next time using app, my problem how to get player current duration when background playing?

**Comment by hustler-manishdayma** [comment]
**assetsAudioPlayer.currentPosition** provides you the current position of the song. 
you can listen it and save the duration in a persistant way like provider data.

on again when you open the app use the stored value as a duration to seek song upto that duration

**Comment by kalismeras61** [comment]
Please look hustler anwer.
