### ISSUE TITLE
New Feature

### ISSUE THREAD

**Issue by ncr9108** [florent37/Flutter-AssetsAudioPlayer#64]
is an option to fast forward and rewind audio?

**Comment by florent37** [comment]
can you explain what you want ? 

you already have seek(duration) to move to a specific point

you want to add .forward(duration) like `.foward(Duration(seconds: 10))` and `. rewind(Duration(seconds: 10))` ?

I can add it if it's your use case 👍

**Comment by florent37** [comment]
you can see the pull request

if it's ok for you I'll publish it
