### ISSUE TITLE
google.bintray bad gateway

### ISSUE THREAD

**Issue by telmedola** [florent37/Flutter-AssetsAudioPlayer#645]
**First of all.  I'm not sure if it's a bug, but as there's no other option to open an issue, I used the same.**

**Flutter Version**

Flutter (Channel stable, 2.8.0, on Mac OS X 10.15.7 19H1519 darwin-x64, locale pt-BR)

**Lib Version**

^3.0.3+6

**Platform (Android / iOS / web) + version**

Platform : compileSdkVersion 29 / Kotlin

**Describe the bug**

i tray to download from maven, but returns http 502 from url https://google.bintray.com/exoplayer/androidx/media2/media2-common/maven-metadata.xml inside your project.
I research and found this message in the site: https://status.bintray.com/
"Thanks for supporting Bintray! This service has now been sunset." in: Dec 1, 15:04 UTC

````
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:processReleaseResources'.
> Could not resolve all task dependencies for configuration ':app:releaseRuntimeClasspath'.
   > Could not resolve androidx.media2:media2-common:[1.1.3].
     Required by:
         project :app > project :audio_session > androidx.media2:media2-session:1.1.3
      > Failed to list versions for androidx.media2:media2-common.
         > Unable to load Maven meta-data from https://google.bintray.com/exoplayer/androidx/media2/media2-common/maven-metadata.xml.
            > Could not get resource 'https://google.bintray.com/exoplayer/androidx/media2/media2-common/maven-metadata.xml'.
               > Could not GET 'https://google.bintray.com/exoplayer/androidx/media2/media2-common/maven-metadata.xml'. Received status code 502 from server: Bad Gateway
````

BUT.. i not used audio_session in my pubspecs.yaml and when comment audio_assets_player, the error not occurs.
I researched other repositories and found that audio_assets_player uses an out-of-date gradle repository called jcenter.

I don't know if using this outdated repository leads to the error. Do you have any prevision for updating the repository?

Very thanks!

**Small code to reproduce**
Not applicable, but I believe the example below is enough

```dart
import 'package:assets_audio_player/assets_audio_player.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State {
  
  final AssetsAudioPlayer _assetsAudioPlayer = AssetsAudioPlayer();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: RaisedButton(
            child: Text("open"),
            onPressed: () {
              //open code here
            }
          ),
        ),
      ),
    );
  }
}
```

**Comment by telmedola** [comment]
Well, i figured out:
1 - open the folder "android" in separated window of android studio.
2 - zzz...zzzz.... maven execution about 20 minutes
3 - upgraded my maven of 3.5.4 to 7.0.4, as sugest ed of android studio. 
4 - zzz...zzzzz... maven execution about 30 minutes.
5 - closed the windows of android project and open my flutter application.
6 - flutter build apk   ..zzz....zzzzz... waiting about 20 minutes
7 - change same dependencies with incompatibilits wiht new gradle.
8 - abracadabra: and everthing worked. 
🤷‍♂️

**Comment by wz19900616** [comment]
I have same problem  . and I solved by doing:
1. disabled  image_picker-0.6.7 build.gradle  maven {“google.bintray”}...  
2. replaced all jcenter() to mavenCentral() in Dart Packages 
3. replaced all jcenter() to mavenCentral() in C:\Users\Qian\flutter\packages\flutter_tools\gradler\esolve_dependencies.gradle and 
 C:\Users\Qian\flutter\packages\flutter_tools\gradler\flutter.gradle
4. removed pubpesc.lock；
5.  run project

**Comment by telmedola** [comment]
Cool. I'll change the jcenter too
thanks

**Comment by kalismeras61** [comment]
Fixed please use latest version
