### ISSUE TITLE
error pub get for assets_audio_player

### ISSUE THREAD

**Issue by reihane1374** [florent37/Flutter-AssetsAudioPlayer#646]
**Flutter Version**

My version : 

**Lib Version**

My version : 

**Platform (Android / iOS / web) + version**

Platform : 

**Describe the bug**

**Small code to reproduce**

```dart
import 'package:assets_audio_player/assets_audio_player.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State {
  
  final AssetsAudioPlayer _assetsAudioPlayer = AssetsAudioPlayer();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: RaisedButton(
            child: Text("open"),
            onPressed: () {
              //open code here
            }
          ),
        ),
      ),
    );
  }
}
```

**Comment by reihane1374** [comment]
Pub failed to delete entry because it was in use by another process.
This may be caused by a virus scanner or having a file
in the directory open in another application.
pub get failed (1; in the directory open in another application.)

**Comment by ibrahim-cse** [comment]
Facing this same problem as you.

**Comment by PedroPinto23** [comment]
Just faced this issue. Worked for me oppening the code editor as administrator, (VS CODE in my case)

**Comment by MaherSaad** [comment]
> Just faced this issue. Worked for me oppening the code editor as administrator, (VS CODE in my case)

yes, i faced same issue and only way worked for me is to run editor as administrator (android studio)

**Comment by kalismeras61** [comment]
Please run as administrator
