### ISSUE TITLE
PlatformException on Web

### ISSUE THREAD

**Issue by ivanjpg** [florent37/Flutter-AssetsAudioPlayer#654]
**Flutter Version**

My version : 2.8.1

**Lib Version**

My version : 3.0.3+9

**Platform (Android / iOS / web) + version**

Platform : Web

**Describe the bug**

```
PlatformException(error, Expected a value of type 'String', but got one of type 'Null', null, null)
Error: PlatformException(error, Expected a value of type 'String', but got one of type 'Null', null, null)
at Object.createErrorWithStack (http://localhost:46093/dart_sdk.js:5076:12)
    at Object._rethrow (http://localhost:46093/dart_sdk.js:40477:16)
    at async._AsyncCallbackEntry.new.callback (http://localhost:46093/dart_sdk.js:40473:13)
    at Object._microtaskLoop (http://localhost:46093/dart_sdk.js:40330:13)
    at _startMicrotaskLoop (http://localhost:46093/dart_sdk.js:40336:13)
    at http://localhost:46093/dart_sdk.js:35811:9
```

The player for web platform does not work. I've searching past issues and found #529, #594, and #610, nevertheless those are for past versions (3.0.3+6, and 3.0.3+2) of the library and the recommendations stated there just does not work (add assets_audio_player_web to dependencies as well as the imports for the class, and use the next build).

**Small code to reproduce**

```
import 'package:assets_audio_player/assets_audio_player.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State {
  
  final AssetsAudioPlayer audioPlayer = AssetsAudioPlayer.newPlayer()
      ..open(
        Audio("assets/01.mp3"),
        autoStart: true,
      );

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: RaisedButton(
            child: Text("Stop"),
            onPressed: () {
                audioPlayer.stop();
            }
          ),
        ),
      ),
    );
  }
}
```

**Comment by Terranic** [comment]
confirmed..... happens using web app with this code:

    assetsAudioPlayer.open(
      Audio("assets/music/$filename"),
      notificationSettings: const NotificationSettings(),
      loopMode: LoopMode.playlist,
      respectSilentMode: true,
    );

**Comment by telostia** [comment]
I was thinking if I made the mistake somewhere but it was the web using flutter 2.81 and environment:
  sdk: ">=2.12.0 <3.0.0".

When testing environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.6 <2.0.0", the player works though...

**Comment by campcoxconsultants** [comment]
I put up a pr for this issue.  There is a place where package is not nullable where every where else it is.

**Comment by kalismeras61** [comment]
It is fixed use latest version.
