### ISSUE TITLE
com.github.florent37.assets_audio_player.playerimplem.PlayerFinder$NoPlayerFoundException

### ISSUE THREAD

**Issue by Upsctimer** [florent37/Flutter-AssetsAudioPlayer#657]
com.github.florent37.assets_audio_player.playerimplem.PlayerFinder$NoPlayerFoundException

issue in latest sdk : >2.12.0<3.0.0

**Comment by kalismeras61** [comment]
We don't have any issue. Please check your, player open method.

**Comment by tyukesz** [comment]
Looks like this issue is still unresolved.

![Screenshot 2023-04-02 at 19 04 58](https://user-images.githubusercontent.com/22120920/229364837-799ba4e3-dce1-4152-8950-a78f4e58f54d.png)
