### ISSUE TITLE
It doesn't work auto play and pause during incoming calls?

### ISSUE THREAD

**Issue by ekremaksoy47** [florent37/Flutter-AssetsAudioPlayer#66]
Hello, I realized that when an audio is playing it doesn't pause the music during incoming phone calls. Can you help me to solve that please? 
Thanks.

**Comment by florent37** [comment]
What platform are you using ? Android or ios ?

**Comment by ekremaksoy47** [comment]
I use Android right now and i tested it on my mi9T which has Android 10 OS in it.

**Comment by florent37** [comment]
ok, I look for solutions

1. listen phone state 
https://stackoverflow.com/questions/11120922/how-to-pause-and-resume-audio-for-phone-calls

it look simple,
but it request a permission

2. play with audioFocus on android, but it seems to be android > 8.0

https://developer.android.com/guide/topics/media-apps/audio-focus

**Comment by florent37** [comment]
the first requests a runtime permission :'(

**Comment by ekremaksoy47** [comment]
Ok, i saw the audioFocus when i searched for solution. 
How can i use the number 2 solution for dart and flutter for your pluging. it must be done  for sure :)

**Comment by florent37** [comment]
I need to update the Android source code to do this, I'm on my phone now, it's 21.43pm, I'll try to do it tomorrow, I will ping you ;)

**Comment by ekremaksoy47** [comment]
Oh thanks a lot then. I am looking forward for your answers :)

**Comment by florent37** [comment]
pushed in 1.4.3 ! can you try ?
