### ISSUE TITLE
Flutter app does not installed in Android 12

### ISSUE THREAD

**Issue by SampathNarayanan** [florent37/Flutter-AssetsAudioPlayer#660]
If I create new flutter app, it does get installed on Android 12 but an existing app does not.

I checked all possibilities and based on the following link,

https://stackoverflow.com/questions/26721951/install-parse-failed-manifest-malformed

I found that , below content from android manifest that is generated in out directory,
-----------------
android:name="com.github.florent37.assets_audio_player.notification.NotificationActionReceiver"
            android:exported="false" />
        <receiver
            android:name="com.github.florent37.assets_audio_player.notification.CustomMediaButtonReceiver"
            android:exported="false" >
            <intent-filter>
                <action android:name="android.intent.action.MEDIA_BUTTON" />
            </intent-filter>
        </receiver>
---------------------------------

The exported needs to have "true" in case of  <receiver> with <intent-filter> but above code shows it is not.

Kindly comment and fix this, I dont find any other library is having this issue in my manifest.

**Comment by SampathNarayanan** [comment]
My apologies, even though i found this discripency, creating fresh app with assets audio player does work in android 12, need to explore more.
Anyhow check this difference as per the link above

**Comment by SampathNarayanan** [comment]
OK, found that if I use  targetSdkVersion as 31, I am able to reproduce the issue with android 12 device.
You can use emulator with pixel deivice using API 31

**Comment by kalismeras61** [comment]
for now please use 30. #664 already fixing that issue but app crash when you click notification panel.
