### ISSUE TITLE
File path for network audios

### ISSUE THREAD

**Issue by mohammadreza0852** [florent37/Flutter-AssetsAudioPlayer#661]
Hi,
first of all thanks for your awesome package. I wanted to draw waveform for audio and I found out that this package doesn't support this feature. Am I right?
So I wanted to implement it myself but I need audio file itself. How can I get audio paths which they are stored when using Audio.network?
Thanks a lot.

**Comment by kalismeras61** [comment]
It depends on how you are using streams but basicly you can get path like below. 

```
 StreamBuilder<Playing?>(
                          stream: _assetsAudioPlayer.current,
                          builder: (context, playing) {
                            if (playing.data != null) {
                                  print(playing.data!.audio.assetAudioPath); 
                          }),
```

**Comment by mohammadreza0852** [comment]
> It depends on how you are using streams but basicly you can get path like below.
> 
> ```
>  StreamBuilder<Playing?>(
>                           stream: _assetsAudioPlayer.current,
>                           builder: (context, playing) {
>                             if (playing.data != null) {
>                                   print(playing.data!.audio.assetAudioPath); 
>                           }),
> ```

Thanks for your help.
Another question, as I said I'm using this library to play musics simultaneously and I need them to be synchronous but when I'm using network audio and network connection is slow, so the audio need to get downloaded, they become asynchronous.
Is there any way to get it work?
