### ISSUE TITLE
 MissingPluginException(No implementation found for method...) for every method

### ISSUE THREAD

**Issue by nutchanon-c** [florent37/Flutter-AssetsAudioPlayer#662]
**Flutter Version**

My version :  2.10.0

**Lib Version**

My version :  assets_audio_player: ^3.0.3+9

**Platform (Android / iOS / web) + version**

Platform : Android 12

**Describe the bug**

Getting this error while trying to run on my Galaxy S10+ with OneUI 4 (Android 12):
Edit: It seems to be throwing this error on EVERY method such as `volume`, `open`, etc.

`[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method playSpeed on channel assets_audio_player)`

Looks like it happens right at `initState()`

Here's my code:
```
  @override
  void initState() {
    AssetsAudioPlayer audioPlayer = AssetsAudioPlayer();

    super.initState();

    audioPlayer.setVolume((1.0).toDouble());

    setupPlaylist();
    audioPlayer.onErrorDo = (handler) {
      handler.player.open(
          handler.playlist!.copyWith(startIndex: handler.playlistIndex),
          seek: handler.currentPosition);
    };

    WidgetsBinding.instance!.addObserver(this);
  }

  void setupPlaylist() async {
    Playlist musicPlaylist = Playlist(
        audios: sList.musicAudioDataList
            .where((element) => element.metas.extra!['category'] == "piano")
            .toList());
    print(
        'PLAYLIST: ${sList.musicAudioDataList.where((element) => element.metas.extra!['category'] == "piano").toList().length}');
    await audioPlayer.open(
      musicPlaylist,
      autoStart: false,
      loopMode: LoopMode.playlist,
      showNotification: true,
      playInBackground: PlayInBackground.enabled,
    );
```

**Comment by nutchanon-c** [comment]
I am now getting the same error with method `volume` as well.

**Comment by jankibhatti** [comment]
same issue

**Comment by kalismeras61** [comment]
I didn't test latest version of flutter. Is starting to happening with latest stable ?

**Comment by jankibhatti** [comment]
yes ,it's happen with latest version

**Comment by kalismeras61** [comment]
I just upgrade flutter version 2.0.10 and i don't see any issue. It works fine. I need more information.

**Comment by nutchanon-c** [comment]
> I just upgrade flutter version 2.0.10 and i don't see any issue. It works fine. I need more information.

What kind of information should I provide? I don't really know what's causing the issue as well. I tried downgrading flutter to 2.8.1 and the issue still persists. It happens only on Android 12 though. Running the exact same thing on Android 11 works completely fine.

**Comment by kalismeras61** [comment]
@nutchanon-c , i don't have Android 12 real device but i just checked with Android 12 emulator. I don't see any issue.

**Comment by kalismeras61** [comment]
Can you open the player like below. 

AssetsAudioPlayer audioPlayer = AssetsAudioPlayer.newPlayer() instead of AssetsAudioPlayer audioPlayer = AssetsAudioPlayer();

**Comment by nutchanon-c** [comment]
I reduced my code to 

```
late AssetsAudioPlayer audioPlayer;
@override
  void initState() {
    super.initState();
    audioPlayer = AssetsAudioPlayer.newPlayer();

    audioPlayer.setVolume(_volume);
    // audioPlayer.play();
    audioPlayer.setPlaySpeed(1);
    // audioPlayer.showNotification;
    // PlayInBackground.enabled;

    setupPlaylist();
    audioPlayer.onErrorDo = (handler) {
      handler.player.open(
          handler.playlist!.copyWith(startIndex: handler.playlistIndex),
          seek: handler.currentPosition);
    };

    WidgetsBinding.instance!.addObserver(this);
  }

  void setupPlaylist() async {
    Playlist musicPlaylist = Playlist(
        audios: sList.musicAudioDataList
            .where((element) => element.metas.extra!['category'] == "piano")
            .toList());
    print(
        'PLAYLIST: ${sList.musicAudioDataList.where((element) => element.metas.extra!['category'] == "piano").toList().length}');
    await audioPlayer.open(
      musicPlaylist,
      autoStart: false,
      loopMode: LoopMode.playlist,
      showNotification: true,
      playInBackground: PlayInBackground.enabled,
    );
}
```

and still getting errors since this
`[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method volume on channel assets_audio_player)`

**Comment by nutchanon-c** [comment]
Addition: I tried creating a very simple app and it throws the same error right at `open`.

**Comment by kalismeras61** [comment]
can you try to example app ? Because i am not able to reproduce this issue with emulator.

**Comment by nutchanon-c** [comment]
@kalismeras61 yeah that's what I did.
```
import 'package:assets_audio_player/assets_audio_player.dart';
import 'package:flutter/material.dart';

class AudioPlayer extends StatefulWidget {
  const AudioPlayer({Key? key}) : super(key: key);

  @override
  _AudioPlayerState createState() => _AudioPlayerState();
}

class _AudioPlayerState extends State<AudioPlayer> {
  final AssetsAudioPlayer _assetsAudioPlayer = AssetsAudioPlayer();

  @override
  void initState() {
    super.initState();
    _assetsAudioPlayer.open(
      Audio.network(
        'https://files.freemusicarchive.org/storage-freemusicarchive-org/music/Music_for_Video/springtide/Sounds_strange_weird_but_unmistakably_romantic_Vol1/springtide_-_03_-_We_Are_Heading_to_the_East.mp3',
        metas: Metas(
          id: 'Online',
          title: 'Online',
          artist: 'Florent Champigny',
          album: 'OnlineAlbum',
          // image: MetasImage.network('https://www.google.com')
          image: const MetasImage.network(
              'https://image.shutterstock.com/image-vector/pop-music-text-art-colorful-600w-515538502.jpg'),
        ),
      ),
      showNotification: true,
      autoStart: true,
      loopMode: LoopMode.single,
      playInBackground: PlayInBackground.enabled,
      volume: 1.0,
    );
  }

  @override
  void dispose() {
    _assetsAudioPlayer.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: const Text('Audio Player'),
        ),
        body: Center(
            child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: <Widget>[
              RaisedButton(
                child: const Text('Play'),
                onPressed: () {
                  _assetsAudioPlayer.play();
                },
              ),
              RaisedButton(
                child: const Text('Pause'),
                onPressed: () {
                  _assetsAudioPlayer.pause();
                },
              ),
              RaisedButton(
                child: const Text('Stop'),
                onPressed: () {
                  _assetsAudioPlayer.stop();
                },
              ),
            ])));
  }
}

```

**Comment by nutchanon-c** [comment]
Update: I updated assets_audio_player to 3.0.4 and the issues still happen on both the new app just for testing and my own app.

**Comment by kalismeras61** [comment]
Sorry, i found Andorid 12 device. Still don't have issue. I think you have problem with your side. Fork with this project and try to run example app. 

try "flutter clean"
try "flutter pub cache repair"

**Comment by kalismeras61** [comment]
Bu the way i am working fix for Android 12 so you will able to use targetSdkVersion 31

**Comment by nutchanon-c** [comment]
Im using targetSdk 31. Will try 30 later tonight. Do I have to set the compilesdk to 30 as well?

**Comment by kalismeras61** [comment]
> Im using targetSdk 31. Will try 30 later tonight. Do I have to set the compilesdk to 30 as well? They're both 31 right now.

No targetSdk is enough.

**Comment by nutchanon-c** [comment]
> > Im using targetSdk 31. Will try 30 later tonight. Do I have to set the compilesdk to 30 as well? They're both 31 right now.
> 
> No targetSdk is enough. 

I tried setting 30 and it's back and working again. Thank you very much.
