### ISSUE TITLE
Plugin throwing MissingPluginException on android 12 devices both real and emulated while the same code runs in other version

### ISSUE THREAD

**Issue by nikz9** [florent37/Flutter-AssetsAudioPlayer#666]
**Flutter Version**

My version : 2.10.0

**Lib Version**

My version : ^3.0.3+1

**Platform (Android / iOS / web) + version**

Platform : Android 12

**Describe the bug**

I am trying to play local file using the app and it works fine but on android 12 emulator and real device both it gives the following error of MissingPlugin even though I have restarted the app even reinstalled whole several times still the issue remains same. In my project the mindsdk is 21 and targetsdk is 32 and I am using kotlin version 1.6.10 and Gradle 7.1.0.

**Small code to reproduce**

final AssetsAudioPlayer player = AssetsAudioPlayer();

void play(String path) {
    player.open(Audio.file(path));
}

onTap: () {
    play('path to file');
}

**Comment by kalismeras61** [comment]
you have to run your app targetSdk 30 or lower. I have created new branch https://github.com/florent37/Flutter-AssetsAudioPlayer/tree/anroid_12-fix you can use that branch also. Will merge branch end of this week.

**Comment by nikz9** [comment]
> you have to run your app targetSdk 30 or lower. I have created new branch https://github.com/florent37/Flutter-AssetsAudioPlayer/tree/anroid_12-fix you can use that branch also. Will merge branch end of this week.

So 31 and 32 will be available after that merge....?

**Comment by kalismeras61** [comment]
Yes.

**Comment by nikz9** [comment]
> Yes.

ok thanks man really appreciated I am making something god wishes it goes well I will definitely not forget people who helped for now I can only say thanks 😅😁.
