### ISSUE TITLE
The App stop work while another app has sound

### ISSUE THREAD

**Issue by ekremaksoy47** [florent37/Flutter-AssetsAudioPlayer#73]
Hello,  we have a problem for the last update. It is working for phone calling but when i open another app like youtube or default music player that start to play any sound my App stop working. (it crushes and doesn't go on until i close and reopen again. ) Can you check it please?

**Comment by ekremaksoy47** [comment]
I tested my app about sound focus with other app.
In some cases it is not working. I want to describe :

# It is working with:
- incoming calls
- incoming messages
- incoming whatsapp calls
- surfing instagram watching short videos there. 

# It is not working with:
-YouTube, vimeo, etc
- Music Players
- Any sound (mp3, mp4, etc, videos) which is playing on Browsers.

**Comment by ekremaksoy47** [comment]
When I pause youtube or default music player your pluging should go on playing. It is not working for me :(

**Comment by florent37** [comment]
I fixed it, when you go to another app (or in notification), the system ping you that you loose the audio focus, but it does not re-ping you when your app is displayed again

my solution, I ask again the focus when I ask to play(). The focus is free so I can play

I push it in a beta for you

**Comment by florent37** [comment]
I publish a `1.4+3+6` can you try ?

**Comment by florent37** [comment]
the possible remaining issue : it cannot resume automatically  the playing audio when the other media player paused

**Comment by ekremaksoy47** [comment]
I tried, this update seems to be working on my device which has Android 10. Thanks:). I will test with another device which has a lower version of Android OS also. And i will give feedback here. 

(Does it also contain player notifications? Because i used to use another plugin for media notification. But your plugin's seems to be working also. So should I use this which comes from your plugin. )

**Comment by florent37** [comment]
Yes I just implemented it in 1.4.4 ! Look at the readme

**Comment by florent37** [comment]
Try to use the notification from my lib and send feedbacks :)

**Comment by ekremaksoy47** [comment]
Yes i tested on my device. The notfication is great :) but there is something. When current song has been finished why i can't replay it by touching notification play button.

**Comment by florent37** [comment]
good to know, I look for it, in fact it's the same for media player, if the sont has finished and you call "play", it does not call it. I should update it to "open the previous playlist(or audio)"

**Comment by florent37** [comment]
you can open a new issue for this if you want :) 
I try to no fix multiple issues on the same page

**Comment by ekremaksoy47** [comment]
Yeah, you are right. When it should act like we are on playlist. Because the next and prev buttons also don't work too :) That is not urgent but i should be :)

**Comment by florent37** [comment]
it's fixed in 1.4.6 :)

**Comment by ekremaksoy47** [comment]
i think changing notificaiton acts effects playing controls acts:( 
 Because when i want to next or prev with playing controls all buttons disapear and  then appear suddenly. It is so bad now :( Before update it was better.

**Comment by florent37** [comment]
Can you record it please (video) ?

**Comment by ekremaksoy47** [comment]
Yes of course. I recorded a video. When i play a song the player controls buttons disappear. 
https://streamable.com/om96rn

**Comment by florent37** [comment]
What stream are you using over the media player buttons ? ''.current'' ?

**Comment by florent37** [comment]
I think it happens because I call stop() which push a null to current

I can, for an ''open'' to avoird pushing this null

**Comment by ekremaksoy47** [comment]
Yes, the stream is "assetAudioPlayer.current" which is like your example. 
This issue happened with 1.4.6 i think. 
It happens because it acts like all songs has been finish and go to stop them i think.

**Comment by florent37** [comment]
I fixed it and pushed it in 1.4.6+1

**Comment by ekremaksoy47** [comment]
I tested it seems working :) Thanks a lot.
