### ISSUE TITLE
Execution failed for task ':assets_audio_player:compileDebugKotlin' 

### ISSUE THREAD

**Issue by ekremaksoy47** [florent37/Flutter-AssetsAudioPlayer#74]
Hello, after i update to version ^1.4.3+3 , i cant 'Run' my code. I paste error messages below:

Launching lib\main.dart on Xiaomi Redmi Note 7 in debug mode...
Running Gradle task 'assembleDebug'...
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.3+2\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (15, 14): Conflicting declarations: internal val METHOD_POSITION: String, internal val METHOD_POSITION: String
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.3+2\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (16, 14): Conflicting declarations: internal val METHOD_VOLUME: String, internal val METHOD_VOLUME: String
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.3+2\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (17, 14): Conflicting declarations: internal val METHOD_FORWARD_REWIND_SPEED: String, internal val METHOD_FORWARD_REWIND_SPEED: String
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.3+2\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (18, 14): Conflicting declarations: internal val METHOD_PLAY_SPEED: String, internal val METHOD_PLAY_SPEED: String
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.3+2\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (19, 14): Conflicting declarations: internal val METHOD_FINISHED: String, internal val METHOD_FINISHED: String
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.3+2\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (20, 14): Conflicting declarations: internal val METHOD_IS_PLAYING: String, internal val METHOD_IS_PLAYING: String
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.3+2\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (21, 14): Conflicting declarations: internal val METHOD_CURRENT: String, internal val METHOD_CURRENT: String
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.3+2\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (22, 14): Conflicting declarations: internal val METHOD_NEXT: String, internal val METHOD_NEXT: String
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.3+2\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (23, 14): Conflicting declarations: internal val METHOD_PREV: String, internal val METHOD_PREV: String
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.3+2\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (25, 7): Redeclaration: AssetsAudioPlayerPlugin
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.3+2\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (42, 7): Redeclaration: AssetsAudioPlayer
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.3+2\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (80, 42): Overload resolution ambiguity: 
internal val METHOD_VOLUME: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
internal val METHOD_VOLUME: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.3+2\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (83, 42): Overload resolution ambiguity: 
internal val METHOD_FORWARD_REWIND_SPEED: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
internal val METHOD_FORWARD_REWIND_SPEED: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.3+2\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (86, 42): Overload resolution ambiguity: 
internal val METHOD_PLAY_SPEED: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
internal val METHOD_PLAY_SPEED: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.3+2\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (89, 42): Overload resolution ambiguity: 
internal val METHOD_POSITION: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
internal val METHOD_POSITION: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.3+2\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (92, 42): Overload resolution ambiguity: 
internal val METHOD_CURRENT: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
internal val METHOD_CURRENT: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.3+2\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (97, 42): Overload resolution ambiguity: 
internal val METHOD_IS_PLAYING: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
internal val METHOD_IS_PLAYING: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.3+2\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (100, 42): Overload resolution ambiguity: 
internal val METHOD_FINISHED: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
internal val METHOD_FINISHED: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.3+2\android\src\main\kotlin\com\github\florent37\assets_audio_player\Player.kt: (25, 7): Redeclaration: Player
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.3+2\android\src\main\kotlin\com\github\florent37\assets_audio_player\Player.kt: (310, 7): Redeclaration: ForwardHandler
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.3+3\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (15, 14): Conflicting declarations: internal val METHOD_POSITION: String, internal val METHOD_POSITION: String
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.3+3\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (16, 14): Conflicting declarations: internal val METHOD_VOLUME: String, internal val METHOD_VOLUME: String
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.3+3\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (17, 14): Conflicting declarations: internal val METHOD_FORWARD_REWIND_SPEED: String, internal val METHOD_FORWARD_REWIND_SPEED: String
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.3+3\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (18, 14): Conflicting declarations: internal val METHOD_PLAY_SPEED: String, internal val METHOD_PLAY_SPEED: String
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.3+3\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (19, 14): Conflicting declarations: internal val METHOD_FINISHED: String, internal val METHOD_FINISHED: String
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.3+3\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (20, 14): Conflicting declarations: internal val METHOD_IS_PLAYING: String, internal val METHOD_IS_PLAYING: String
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.3+3\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (21, 14): Conflicting declarations: internal val METHOD_CURRENT: String, internal val METHOD_CURRENT: String
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.3+3\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (22, 14): Conflicting declarations: internal val METHOD_NEXT: String, internal val METHOD_NEXT: String
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.3+3\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (23, 14): Conflicting declarations: internal val METHOD_PREV: String, internal val METHOD_PREV: String
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.3+3\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (25, 7): Redeclaration: AssetsAudioPlayerPlugin
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.3+3\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (42, 7): Redeclaration: AssetsAudioPlayer
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.3+3\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (80, 42): Overload resolution ambiguity: 
internal val METHOD_VOLUME: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
internal val METHOD_VOLUME: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.3+3\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (83, 42): Overload resolution ambiguity: 
internal val METHOD_FORWARD_REWIND_SPEED: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
internal val METHOD_FORWARD_REWIND_SPEED: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.3+3\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (86, 42): Overload resolution ambiguity: 
internal val METHOD_PLAY_SPEED: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
internal val METHOD_PLAY_SPEED: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.3+3\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (89, 42): Overload resolution ambiguity: 
internal val METHOD_POSITION: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
internal val METHOD_POSITION: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.3+3\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (92, 42): Overload resolution ambiguity: 
internal val METHOD_CURRENT: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
internal val METHOD_CURRENT: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.3+3\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (97, 42): Overload resolution ambiguity: 
internal val METHOD_IS_PLAYING: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
internal val METHOD_IS_PLAYING: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.3+3\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (100, 42): Overload resolution ambiguity: 
internal val METHOD_FINISHED: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
internal val METHOD_FINISHED: String defined in com.github.florent37.assets_audio_player in file AssetsAudioPlayerPlugin.kt
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.3+3\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (264, 29): Type mismatch: inferred type is Double but MethodChannel.Result was expected
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.3+3\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (265, 29): Type mismatch: inferred type is MethodChannel.Result but Context was expected
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.3+3\android\src\main\kotlin\com\github\florent37\assets_audio_player\AssetsAudioPlayerPlugin.kt: (266, 29): Too many arguments for public f�nal fun open(assetAudioPath: String?, audioType: String, autoStart: Boolean, volume: Double, seek: Int?, respectSilentMode: Boolean, result: MethodChannel.Result, context: Context): Unit defined in com.github.florent37.assets_audio_player.Player
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.3+3\android\src\main\kotlin\com\github\florent37\assets_audio_player\Player.kt: (25, 7): Redeclaration: Player
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\assets_audio_player-1.4.3+3\android\src\main\kotlin\com\github\florent37\assets_audio_player\Player.kt: (312, 7): Redeclaration: ForwardHandler

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':assets_audio_player:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BU�LD FAILED in 39s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by florent37** [comment]
Can you perform a ''flutter clean'' then try again ?

**Comment by ekremaksoy47** [comment]
I tried this commend due to similar error of closed issu. But my terminal does not recognise 'flutter' words. I searched for this it seems like it is about Path. I do changes but nothing happend.
So i move my code to a new project. It is working now.

**Comment by ekremaksoy47** [comment]
Thank you for your support 😊

**Comment by florent37** [comment]
It happens frequently while upgrading flutter packages :)
