### ISSUE TITLE
Local files on iOS, yes/no/maybe?

### ISSUE THREAD

**Issue by mohamnag** [florent37/Flutter-AssetsAudioPlayer#75]
It is not clear whether one should expect this plugin to work on iOS when playing local files (for example downloaded to some path) is working. on the description (and also https://pub.dev/packages/assets_audio_player) there is only an apple icon for that row but no mention anywhere. 
would appreciate it if this is made clear as I tried and it does not work (bug file will follow if you want to make it work).

**Comment by florent37** [comment]
On iOS apps are sandboxed, you cannot read mp3 files on sdcard

If you found any documentation how to play mp3 stored in a directory on iOS i'll implement it !

**Comment by florent37** [comment]
https://www.google.com/amp/s/mobikul.com/play-audio-file-save-document-directory-ios-swift/amp/

Maybe that

**Comment by florent37** [comment]
It seems to work like network filed using prefix file:// I'll implement it today !

https://stackoverflow.com/questions/9577471/avplayer-and-local-files

**Comment by mohamnag** [comment]
so multiple things.

first its not about just playing any file from sdcard, its a file dedicated to my app, downloaded to application's support directory (`NSApplicationSupportDirectory`). 

second thing is that, currently I'm downloading audio files using `dio` library, but this means I have to wait until download is finished and then can start playing. If you want to work on storing files on disk (like stream & save mode) I would be very happy but that would not be my prio.

third regarding the prefix `file://`, as soon as implemented, I can test it and give feedback.

**Comment by mohamnag** [comment]
ok, I just added the prefix (`path = Platform.isIOS ? "file://" + path : path`) and can verify that it is working.

**Comment by florent37** [comment]
Using audio.network yes, but I'll make it available directly in the library using audio.file(path)

**Comment by florent37** [comment]
When I'll be on my computer 😅

**Comment by florent37** [comment]
By the way playing a file from NSApplicationSupportDirectory should works fine, it's not outside the sandbox, I keep you updated

**Comment by mohamnag** [comment]
I actually used the `Audio.file(Platform.isIOS ? "file://" + path : path)` to play from `NSApplicationSupportDirectory` as just using path (as is provided by `File().path`) did not work.

**Comment by florent37** [comment]
I implemented it, but I think you have to make sure the path is correct, for this, can you try using directly your File().path, and if it does not work, use `https://pub.dev/packages/path_provider` to give you the correct file path (using . getApplicationSupportDirectory())

**Comment by florent37** [comment]
I merge it soon and will publish it in a beta version

**Comment by florent37** [comment]
I merged it on master, published a tmp version `1.4+3+5`, re-open it until you tell me it's working :)

**Comment by mohamnag** [comment]
got `1.4.3+5`. 

`path = '/var/mobile/Containers/Data/Application/A5E48D3C-011D-4A2C-A32C-275B3BF51F0F/Library/Application Support/file.mp3'` is definitely correct as `File(path).existsSync()` returns true. (it is obtained using `path_provider`).

the `assetsAudioPlayer.open(Audio.file(Platform.isIOS ? "file://" + path : path))` which **was working** before, does not work anymore giving me the error:
```
flutter: log: resource not found file:///var/mobile/Containers/Data/Application/A5E48D3C-011D-4A2C-A32C-275B3BF51F0F/Library/Application Support/file.mp3
```

the `assetsAudioPlayer.open(Audio.file(path))` which I expected would work now, does not work giving me following error:
```
flutter: log: resource not found /var/mobile/Containers/Data/Application/A5E48D3C-011D-4A2C-A32C-275B3BF51F0F/Library/Application Support/file.mp3
```

the `assetsAudioPlayer.open(Audio.network(path))` does nothing (I did not use Xcode but probably crashing some how that flutter can not get its log.

the `assetsAudioPlayer.open(Audio.network(Platform.isIOS ? "file://" + path : path))` which was working before, is still working.

I don't know how to analyse the result, but I would say the change does not work if it was your intention that `Audio.file()` works as is for both iOS and Android.

**Comment by florent37** [comment]
yes I want for Audio.file() to work for both andorid & ios just using a static path like 

```
final path = '/var/mobile/Containers/Data/Application/A5E48D3C-011D-4A2C-A32C-275B3BF51F0F/Library/Application Support/file.mp3'
assetsAudioPlayer.open(Audio.file(path)
```

I try to fix it

**Comment by florent37** [comment]
he assetsAudioPlayer.open(Audio.file(Platform.isIOS ? "file://" + path : path)) was working so I have just to follow the same rule :)

**Comment by florent37** [comment]
I'll have to create a sample with dio & path provider too

**Comment by florent37** [comment]
I just fixed it, I push it and my sample code to let you try

**Comment by florent37** [comment]
you can find my sample code here : https://github.com/florent37/Flutter-AssetsAudioPlayer/blob/master/example/lib/main_local_file.dart

**Comment by florent37** [comment]
I push a tmp version for you, can you try ? it's the `1.4.4+1`

**Comment by mohamnag** [comment]
will try and let you know

**Comment by florent37** [comment]
👍

**Comment by mohamnag** [comment]
fine, I can confirm that `Audio.file(path)` works on both android an ios (hardware devices) the same. thanks for fixing this.

**Comment by florent37** [comment]
you're welcome :) dont hesitate to send other bugfixes and features request !
