### ISSUE TITLE
onAudioFocusChange problem

### ISSUE THREAD

**Issue by kalismeras61** [florent37/Flutter-AssetsAudioPlayer#76]
I am using, your plugin, but i am also using Speech Recognition. When i held down for activating speech recognition, sounds automaticly paused. But i dont want this i just want to set volume low instead of pause. Music in the background should continue, I just need to slowly lower the volume.
 
Is there any way handle this?

**Comment by florent37** [comment]
Yes I need to update the audio focus, there's a configuration for this, I keep you updated

**Comment by florent37** [comment]
I'll add a custom case following 
AudioManager.AUDIOFOCUS_LOSS_TRANSIENT_CAN_DUCK

Which reduces the volume to 0.3 (for exemple) but don't pause

**Comment by florent37** [comment]
I pushed it on 1.4.3+4, but did not tried (I only tried to ask google assistant on my phone, but it does not ask AUDIOFOCUS_LOSS_TRANSIENT_CAN_DUCK), can you try ? and if it not work, send me a sample code ? (using your speech recognition library)
