### ISSUE TITLE
Icons in the buttons are not displayed in the notification widget on ios

### ISSUE THREAD

**Issue by Ellweb3** [florent37/Flutter-AssetsAudioPlayer#764]
**Flutter Version**

My version : 
3.3.10
**Lib Version**

My version : 

**Platform (Android / iOS / web) + version**

Platform : 
IOS 16.2
**Describe the bug**

Icons in the buttons (play, previousTrack, nextTrack) are not displayed in the notification widget on ios in example and in my app. They can be pressed, but only to the touch.

![Here the screenshot](https://user-images.githubusercontent.com/95847507/223187552-d0926ecb-3827-479e-a395-f8e64f52f079.png)
**Small code to reproduce**
```dart
import 'package:assets_audio_player/assets_audio_player.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State {
  
  final AssetsAudioPlayer _assetsAudioPlayer = AssetsAudioPlayer();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: RaisedButton(
            child: Text("open"),
            onPressed: () {
            try {
                          await _assetsAudioPlayer.open(
                            myAudio,
                            autoStart: true,
                            showNotification: true,
                            playInBackground: PlayInBackground.enabled,
                            audioFocusStrategy: AudioFocusStrategy.request(
                                resumeAfterInterruption: true,
                                resumeOthersPlayersAfterDone: true),
                            headPhoneStrategy: HeadPhoneStrategy.pauseOnUnplug
                          );
                        } catch (e) {
                          print(e);
                        }
            }
          ),
        ),
      ),
    );
  }
}
```

**Comment by benjitusk** [comment]
@florent37 This is a huge problem that is a deal breaker for this library. If you can point me in the right direction, I'll be more than happy to fix it.

**Comment by Adrian5er** [comment]
use: `notificationSettings: NotificationSettings(playPauseEnabled: true, prevEnabled: false, nextEnabled: false, stopEnabled: false, seekBarEnabled: false,),`

;)

**Comment by Ellweb3** [comment]
> use: > > `notificationSettings: NotificationSettings(playPauseEnabled: true, prevEnabled: false, nextEnabled: false, stopEnabled: false, seekBarEnabled: false,),`

@Adrian5er thanks for your response, but the thing is that the buttons themselves are in the widget and can be clicked, but the icons of these buttons are not displayed (Maybe they need to be somewhere to determine - I have not found unfortunately where to do it

**Comment by Ellweb3** [comment]
I apologize - the problem was only in the simulator Xcode, on testfligth no such problem
