### ISSUE TITLE
No implementation found for method stop on channel assets_audio_player

### ISSUE THREAD

**Issue by istoriaenglishapp** [florent37/Flutter-AssetsAudioPlayer#773]
**Flutter Version**

My version : 3.7.12

**Lib Version**

My version : 
  assets_audio_player: ^3.0.5

**Platform (Android 10,11,12,13) **

Platform : 

**Describe the bug**

Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: MissingPluginException(No implementation found for method stop on channel assets_audio_player). Error thrown null.
       at MethodChannel._invokeMethod(platform_channel.dart:313)
       at AssetsAudioPlayer._stop(assets_audio_player.dart:1410)

```dart
class SayWordController extends GetxController {
  final assetsAudioPlayer = AssetsAudioPlayer.withId('SayWordAudioPlayer');
  Future<void> stopSay() async {
    await assetsAudioPlayer.stop();
  }
}
```

**Comment by faisalcheq** [comment]
@florent37 Any update for this issue ?

**Comment by kalismeras61** [comment]
please use latest version it is fixed.
