### ISSUE TITLE
http package is old

### ISSUE THREAD

**Issue by anokabb** [florent37/Flutter-AssetsAudioPlayer#776]
Please can you upgrade the HTTP package to the latest version (http ^1.0.0)

**Comment by josseed** [comment]
flutter_facebook_auth depends on facebook_auth_desktop ^1.0.0 which depends on http ^1.0.0 😱

**Comment by wlw81** [comment]
Yes, please upgrade HTTP dep! Thx!

**Comment by kalismeras61** [comment]
fixed use latest build

**Comment by anokabb** [comment]
thanks @kalismeras61
