### ISSUE TITLE
Audio not playing in background in IOS

### ISSUE THREAD

**Issue by ShridharBanavasi1997** [florent37/Flutter-AssetsAudioPlayer#777]
**Flutter Version**

My version : 3.7.12 

**Lib Version**

My version : 3.0.6

**Platform (Android / iOS / web) + version**

Platform :  ios/11

**Describe the bug**

I have implement audio player. It playing audio fine in Android . But in IOS, when app is in background, audio stop playing immediately.

**Comment by kalismeras61** [comment]
Did you read readme file ?

**Comment by ShridharBanavasi1997** [comment]
Ok, it woking in background after adding belo code in info.plist

<key>UIBackgroundModes</key>
<array>
    <string>audio</string>
    <string>fetch</string>
</array>

But in reade , it not mentined clearly because, it says for "enable http calls on macOs"
