### ISSUE TITLE
Cannot create bundle with latest version 

### ISSUE THREAD

**Issue by ikeremozcan** [florent37/Flutter-AssetsAudioPlayer#789]
**Flutter Version**
[✓] Flutter (Channel stable, 3.7.0, on macOS 13.1 22C65 darwin-arm64, locale en-TR)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.81.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

**Lib Version**
My version : `assets_audio_player: ^3.0.8`

Platform : Android

**Description**

After run the command below
`flutter build appbundle --release`

**I got this error**

```
💪 Building with sound null safety 💪

Running Gradle task 'bundleRelease'...                          
e: /Users/user/.pub-cache/hosted/pub.dev/assets_audio_player-3.0.8/android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/NotificationService.kt: (20, 49): Unresolved reference: R
e: /Users/user/.pub-cache/hosted/pub.dev/assets_audio_player-3.0.8/android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/NotificationService.kt: (165, 68): Unresolved reference: R
e: /Users/user/.pub-cache/hosted/pub.dev/assets_audio_player-3.0.8/android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/NotificationService.kt: (169, 80): Unresolved reference: R
e: /Users/user/.pub-cache/hosted/pub.dev/assets_audio_player-3.0.8/android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/NotificationService.kt: (173, 81): Unresolved reference: R
e: /Users/user/.pub-cache/hosted/pub.dev/assets_audio_player-3.0.8/android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/NotificationService.kt: (177, 80): Unresolved reference: R
e: /Users/user/.pub-cache/hosted/pub.dev/assets_audio_player-3.0.8/android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/NotificationService.kt: (181, 80): Unresolved reference: R
e: /Users/user/.pub-cache/hosted/pub.dev/assets_audio_player-3.0.8/android/src/main/kotlin/com/github/florent37/assets_audio_player/notification/NotificationService.kt: (185, 80): Unresolved reference: R

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':assets_audio_player:compileReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 37s
Running Gradle task 'bundleRelease'...                             37.7s
Gradle task bundleRelease failed with exit code 1


```

**Comment by ikeremozcan** [comment]
Please update here when it's deployed. So we mark this as closed

**Comment by kalismeras61** [comment]
> Please update here when it's deployed. So we mark this as closed

Not sure, what do you mean, but If you use it as above, there will be no problem.

**Comment by ikeremozcan** [comment]
I don't prefer to use git reference. Currently I am going with previous version
`assets_audio_player: 3.0.6`
pub reference more convenient. I will close this and check later

**Comment by kalismeras61** [comment]
I am a contributor of the package, so unfortunately it can't be uploaded to the pub due to a problem on the CI side. Since the package has no maintainer, unfortunately we have no other solution.

**Comment by ikeremozcan** [comment]
I see, no worries

**Comment by isosoft-dev** [comment]
Kerem hocam aynı hata bende alıyorum ne yapmalıyım bu durumda lütfen yardımcı olabilir misiniz.

**Comment by ikeremozcan** [comment]
> Kerem hocam aynı hata bende alıyorum ne yapmalıyım bu durumda lütfen yardımcı olabilir misiniz.

pubspec.yaml dan referansı 2 şekilde verebilirsin
1. Yöntem: Bir önceki stabil versiyonu direkt referans verebilirsin.
` assets_audio_player: 3.0.6`
2. Yöntem: Git referansı olarak kullanabilirsin.
  ```
assets_audio_player:
      git:
        url: https://github.com/florent37/Flutter-AssetsAudioPlayer.git
        ref: master
```

**Comment by kalismeras61** [comment]
CI / CD sorunu çözüldü, yeni versiyonu kullanabilirsiniz. 

assets_audio_player: 3.1.0
