### ISSUE TITLE
Notification is not displayed on Android

### ISSUE THREAD

**Issue by akarapetsas** [florent37/Flutter-AssetsAudioPlayer#792]
**Flutter Version**

My version : 
Flutter 3.10.6

**Lib Version**

My version : 
assets_audio_player: ^3.1.0. 

**Platform (Android / iOS / web) + version**

Platform : 
Android

**Describe the bug**

I have update from `assets_audio_player: ^3.0.6` to `assets_audio_player: ^3.1.0`. 
I'm using the code below where I explicitly request to show the notification. However, the notification is not being appeared. It was working on v.3.0.6 . I have seen that a PR was merged to fix the long lasting bug with the notifications on Android (thank you @ShadyBoshra2012 ). I'm wondering if any adjustments needed after the bug fix provided or if the `showNotification: true` should still expected to do the trick. Do you have any inputs on this @kalismeras61 ?

**Small code to reproduce**

```dart
await assetsAudioPlayer.open(
          updatedModel.audio,
          showNotification: true,
          headPhoneStrategy: HeadPhoneStrategy.pauseOnUnplug,
          notificationSettings: NotificationSettings(
              playPauseEnabled: true,
              prevEnabled: false,
              nextEnabled: false,
              seekBarEnabled: true),
        );
```

**Comment by kalismeras61** [comment]
I don't have any issue in example app. Can you run example / main.dart ?

**Comment by akarapetsas** [comment]
I have tried the example app and everything works well there. No issues with the notification. I guess the issue might be related with my set up. I'm closing the bug ticket (FYI @kalismeras61 )
