### ISSUE TITLE
rxdart problem

### ISSUE THREAD

**Issue by zszen** [florent37/Flutter-AssetsAudioPlayer#8]
`Because XXXX  depends on assets_audio_player 1.0.1 which depends on rxdart ^0.20.0, rxdart ^0.20.0 is required.

So, because XXXX depends on rxdart 0.22.0, version solving failed.`

I must downgrade rxdart from 0.22.0 to 0.20.0

**Comment by AirborneEagle** [comment]
This seems like a duplicate of #9

**Comment by florent37** [comment]
fixed
