### ISSUE TITLE
Buttons to rewind and forward 10s of playing music

### ISSUE THREAD

**Issue by BahodurSaidov** [florent37/Flutter-AssetsAudioPlayer#80]
Hi,
The existing example is great for exploring plugin features. Another famous and useful buttons in the example would be rewinding and skipping 10s of the playing music by pressing button.

**Comment by florent37** [comment]
You can implement it without the sample, just create the buttons and call ''seekBy(Duration(seconds:10))''

**Comment by florent37** [comment]
The sample cannot have all features in one screen unfortunately

**Comment by florent37** [comment]
I updated the sample for you :)

**Comment by BahodurSaidov** [comment]
> I updated the sample for you :) 

Thanks, i ll be happy to try it out
