### ISSUE TITLE
Compatability for Android 4.2.2

### ISSUE THREAD

**Issue by BahodurSaidov** [florent37/Flutter-AssetsAudioPlayer#81]
I tested same example app (build with minSdk 16 and compileSdk 28) on android 4.2.2 and it doesn't play even bell button. And the app breaks unexpectedly. But i suspect that this issue is related to flutter tools. Any idea ?

**Comment by BahodurSaidov** [comment]
In ionic v 1 - cordova app, there was a plugin that worked great with older phones even Android 2.x !! May be it might help, here is a link : [https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-media/](Cordova plugin)

**Comment by florent37** [comment]
I tried the app on a 4.2 android, it works fine but I had to launch it using `flutter run --enable-software-rendering`

https://stackoverflow.com/questions/48802841/minimum-android-version-with-flutter

**Comment by florent37** [comment]
btw I don't think It's usefull to support android below 21

before lollipop you target only 5% of users

**Comment by florent37** [comment]
if you found an explicit android exception I can update the project

**Comment by BahodurSaidov** [comment]
> btw I don't think It's usefull to support android below 21
> 
> before lollipop you target only 5% of users

I also agree with that... This was because i found android 4.2.2 device roaming near-by and just tested on it to see results...
But still it should be considered that there are still large quantity of users who are using edicted to their old phones...
