### ISSUE TITLE
The asset audio should accept a package argument

### ISSUE THREAD

**Issue by long1eu** [florent37/Flutter-AssetsAudioPlayer#82]
Right now you assume that all assets are from a Flutter app. However I'm developing a plugin and just specifying the assets path in my package is not enough since it will not be bundle in the save flutter_asset flutter, but in the plugin folder.   

Have a look at how `AssetImage` is implemented to use the package name. You might also see this argument existsing in both java and objc when requiring for the asset key.

**Comment by long1eu** [comment]
![Screenshot 2020-05-15 at 23 42 33](https://user-images.githubusercontent.com/9283414/82094478-d0af4700-9705-11ea-8717-ce9a1518377d.png)

As you can see assets included by other packages are bundled inside the `package/{package_name}`

**Comment by florent37** [comment]
Yes I see, I forgot it thanks I'll implement it !

**Comment by florent37** [comment]
I fixed it in master, some others bugfix will be like this will be added before I publish a new version

**Comment by florent37** [comment]
thanks for you issue btw :)

**Comment by long1eu** [comment]
Absolutely! You're the best.

**Comment by florent37** [comment]
I forgot to add this on iOS 😓

**Comment by florent37** [comment]
Pushed in 1.4.7, can you try ?

**Comment by long1eu** [comment]
works perfect :D

**Comment by long1eu** [comment]
I;m gonna by you a beer

**Comment by florent37** [comment]
Thanks for your issue :) and for the sponsor 🥰
