### ISSUE TITLE
Unable to handle error "ConnectException : Failed to connect" when trying to connect to unreachable url

### ISSUE THREAD

**Issue by manojvsp12** [florent37/Flutter-AssetsAudioPlayer#83]
Thanks for the great plugin. I have looked into lots of audio players in pub.dev but didnt find any plugin with vast features provided in AssetsAudioPlayer and all these features resolves common audio player requirements.

This issue describes an issue i faced when I was using this plugin, which is required to be fixed. It would be a great help if you guys can fix this issue or resolve it by providing a patch to the plugin.

Issue: When I try to play a network url which is unreachable, I am getting logs as below, but I need a way to handle this error or if there is a way to handle errors is already implemented, please let me know.

OS: Android, iOS (will provide logs for ios if required)

Error log:
E/ExoPlayerImplInternal(19364): Source error
E/ExoPlayerImplInternal(19364):   com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect
E/ExoPlayerImplInternal(19364):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:282)
E/ExoPlayerImplInternal(19364):       at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:177)
E/ExoPlayerImplInternal(19364):       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
E/ExoPlayerImplInternal(19364):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:956)
E/ExoPlayerImplInternal(19364):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
E/ExoPlayerImplInternal(19364):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal(19364):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal(19364):       at java.lang.Thread.run(Thread.java:919)
E/ExoPlayerImplInternal(19364):   Caused by: java.net.ConnectException: Failed to connect to /51.15.86.61:80
E/ExoPlayerImplInternal(19364):       at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:147)
E/ExoPlayerImplInternal(19364):       at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
E/ExoPlayerImplInternal(19364):       at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
E/ExoPlayerImplInternal(19364):       at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
E/ExoPlayerImplInternal(19364):       at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
E/ExoPlayerImplInternal(19364):       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
E/ExoPlayerImplInternal(19364):       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
E/ExoPlayerImplInternal(19364):       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
E/ExoPlayerImplInternal(19364):       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
E/ExoPlayerImplInternal(19364):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:550)
E/ExoPlayerImplInternal(19364):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:439)
E/ExoPlayerImplInternal(19364):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:280)
E/ExoPlayerImplInternal(19364):       ... 7 more

**Comment by florent37** [comment]
I just "quick fixed" this issue by throwing the native mediaplayer error to flutter

```dart
try {
     await _player.open(audio);
} catch(t) {
     //the native error message
} 
```

all methods return a future now

**Comment by florent37** [comment]
In a next commit, I think I'll throw custom errors as "Network Exception" to easy catch & adjust the usecases

**Comment by florent37** [comment]
Pushed in 1.4.7, can you try ?
