### ISSUE TITLE
player's notification is not getting updated when trying to play using "playlistPlayAtIndex"

### ISSUE THREAD

**Issue by manojvsp12** [florent37/Flutter-AssetsAudioPlayer#84]
continuing to my previous bug, below is another issue I faced.

Scenario: Currently song is playing and trying to pick track from Playlist and playing using "PlaylistPlayAtIntex(index)"

issue: Notification player is not getting updated with the title, artist, isPlaying etc

**Comment by florent37** [comment]
I fixed it and pushed on master.
I'll wait to fixes some other bugs before sending a new version to pub.dev

I keep you in touch !

**Comment by florent37** [comment]
Pushed in 1.4.7, can you try ?

**Comment by manojvsp12** [comment]
Working as expected now

**Comment by florent37** [comment]
Thanks for the issue 🥰
