### ISSUE TITLE
Android 14 getting crashes

### ISSUE THREAD

**Issue by chouthri007** [florent37/Flutter-AssetsAudioPlayer#840]
**Flutter Version** 

My version :  3.22.0

**Lib Version**

My version :  assets_audio_player: ^3.1.1

**Platform (Android / iOS / web) + version**

Platform : Android 14

**Describe the bug**

App gets crashed when i tap the list to play the audio

when i use target sdk version to 34
when its 33 its working fine, But now its mandatory to use target version as 34 in google play console

**Comment by emanuel-braz** [comment]
same here :(

any solution?

**Comment by chouthri007** [comment]
Yes, the solution is -> update your Flutter SDK version to current ie. 3.22.3 and change android/settings.gradle , android/app/build.gradle and android/app/gradle/wrapper/gradle-wrapper.properties.......
it will work 

reference --> 
https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply
