### ISSUE TITLE
Got error verifyReleaseResources when trying to build release apk

### ISSUE THREAD

**Issue by istiaksaif** [florent37/Flutter-AssetsAudioPlayer#844]
:assets_audio_player_web:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/home/istaiksaif/Documents/Sports76/build/assets_audio_player_web/intermediates/merged_res/release/values/values.xml:194: AAPT: error: resource android:attr/lStar not found.

**Comment by admincode1** [comment]
+ 1

**Comment by ikoshik** [comment]
Flutter (Channel stable, 3.24.0, on macOS 14.6.1 23G93 darwin-x64, locale ru-RU)
Android toolchain - develop for Android devices (Android SDK version 35.0.0-rc3)

Same problem

**Comment by hkidevone** [comment]
I have the same problem. Does anyone have any other solution.

**Comment by Mae623** [comment]
> +1
> 
> [✓] Flutter (Channel stable, 3.24.0, on macOS 14.5 23F79 darwin-x64, locale en-US) • Flutter version 3.24.0 on channel stable • Upstream repository https://github.com/flutter/flutter.git • Framework revision 80c2e84975 (2 weeks ago), 2024-07-30 23:06:49 +0700 • Engine revision b8800d88be • Dart version 3.5.0 • DevTools version 2.37.2
> 
> I had to downgrade to Flutter version 3.22.3 (Stable).

Hello, I'm cross into same situation. May I ask you how to downgrade to Flutter version 3.22.3 (Stable)? I try "flutter downgrade" command, but I just got "There is no previously recorded version for channel "stable".".

**Comment by admincode1** [comment]
> > +1
> > [✓] Flutter (Channel stable, 3.24.0, on macOS 14.5 23F79 darwin-x64, locale en-US) • Flutter version 3.24.0 on channel stable • Upstream repository https://github.com/flutter/flutter.git • Framework revision 80c2e84975 (2 weeks ago), 2024-07-30 23:06:49 +0700 • Engine revision b8800d88be • Dart version 3.5.0 • DevTools version 2.37.2
> > I had to downgrade to Flutter version 3.22.3 (Stable).
> 
> Hello, I'm cross into same situation. May I ask you how to downgrade to Flutter version 3.22.3 (Stable)? I try "flutter downgrade" command, but I just got "There is no previously recorded version for channel "stable".".

Go to:
https://docs.flutter.dev/release/archive
Download version [3.22.3] or use this link: https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_3.22.3-stable.zip
Unzip then replace the Flutter folder.

**Comment by Mae623** [comment]
> > > +1
> > > [✓] Flutter (Channel stable, 3.24.0, on macOS 14.5 23F79 darwin-x64, locale en-US) • Flutter version 3.24.0 on channel stable • Upstream repository https://github.com/flutter/flutter.git • Framework revision 80c2e84975 (2 weeks ago), 2024-07-30 23:06:49 +0700 • Engine revision b8800d88be • Dart version 3.5.0 • DevTools version 2.37.2
> > > I had to downgrade to Flutter version 3.22.3 (Stable).
> > 
> > 
> > Hello, I'm cross into same situation. May I ask you how to downgrade to Flutter version 3.22.3 (Stable)? I try "flutter downgrade" command, but I just got "There is no previously recorded version for channel "stable".".
> 
> Go to: https://docs.flutter.dev/release/archive Download version [3.22.3]. Unzip then replace the Flutter folder.

Succeeded! Thank you very much!

**Comment by admincode1** [comment]
Try this workaround:

Change (at android/build.gradle):

subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

To:

subprojects {
    afterEvaluate { project ->
        if (project.plugins.hasPlugin("com.android.application") ||
                project.plugins.hasPlugin("com.android.library")) {
            project.android {
                compileSdkVersion 34
            }
        }
    }
}
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(':app')
}

**Comment by Mae623** [comment]
> Try this workaround:
> 
> Change (at android/build.gradle):
> 
> ```
> subprojects {
>     project.buildDir = "${rootProject.buildDir}/${project.name}"
> }
> subprojects {
>     project.evaluationDependsOn(':app')
> }
> ```
> 
> To:
> 
> ```
> subprojects {
>     afterEvaluate { project ->
>         if (project.plugins.hasPlugin("com.android.application") ||
>                 project.plugins.hasPlugin("com.android.library")) {
>             project.android {
>                 compileSdkVersion 34
>             }
>         }
>     }
> }
> subprojects {
>     project.buildDir = "${rootProject.buildDir}/${project.name}"
>     project.evaluationDependsOn(':app')
> }
> ```

It works! You are great!

**Comment by saeedahmed725** [comment]
> Try this workaround:
> 
> Change (at android/build.gradle):
> 
> ```
> subprojects {
>     project.buildDir = "${rootProject.buildDir}/${project.name}"
> }
> subprojects {
>     project.evaluationDependsOn(':app')
> }
> ```
> 
> To:
> 
> ```
> subprojects {
>     afterEvaluate { project ->
>         if (project.plugins.hasPlugin("com.android.application") ||
>                 project.plugins.hasPlugin("com.android.library")) {
>             project.android {
>                 compileSdkVersion 34
>             }
>         }
>     }
> }
> subprojects {
>     project.buildDir = "${rootProject.buildDir}/${project.name}"
>     project.evaluationDependsOn(':app')
> }
> ```

It works,Thank you

**Comment by srikanth-vanga-pipra** [comment]
subprojects {
    afterEvaluate { project ->
        if (project.plugins.hasPlugin("com.android.application") ||
                project.plugins.hasPlugin("com.android.library")) {
            project.android {
                compileSdkVersion 34
            }
        }
    }
}
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(':app')
}
this is working thank you.

**Comment by istiaksaif** [comment]
> Try this workaround:
> 
> Change (at android/build.gradle):
> 
> ```
> subprojects {
>     project.buildDir = "${rootProject.buildDir}/${project.name}"
> }
> subprojects {
>     project.evaluationDependsOn(':app')
> }
> ```
> 
> To:
> 
> ```
> subprojects {
>     afterEvaluate { project ->
>         if (project.plugins.hasPlugin("com.android.application") ||
>                 project.plugins.hasPlugin("com.android.library")) {
>             project.android {
>                 compileSdkVersion 34
>             }
>         }
>     }
> }
> subprojects {
>     project.buildDir = "${rootProject.buildDir}/${project.name}"
>     project.evaluationDependsOn(':app')
> }
> ```

**The solution currently works.** flutter version 3.24.3
