### ISSUE TITLE
Swiping the player's notification from notification tray doesn't kill app

### ISSUE THREAD

**Issue by manojvsp12** [florent37/Flutter-AssetsAudioPlayer#85]
continuing to my previous bugs, below is another issue I faced.

issue: Audio is playing and trying to kill by swiping the notification in the android notifications but app is still playing and app is not getting killed.

**Comment by florent37** [comment]
I think I'll implement the same behavior than google play music : 
if (playing) cancel = false (cannot swipe)
else {
    //can swipe
    stopForegreound()  <-- if on background, can be killed by os, else, if visible, just hide the notification
}

**Comment by florent37** [comment]
It's already what's implemented

**Comment by florent37** [comment]
You have to ''pause'' the music then you can swipe the notification

If the app is focused : does not kill
If it's in background, Android can kill it whenever he has to

**Comment by florent37** [comment]
If it's not paused, you cannot swipe the notification

**Comment by florent37** [comment]
Reopen it if it does not answer your issue ☝️

**Comment by Mayb3Nots** [comment]
notification doesn't close when swiped
