### ISSUE TITLE
AAPT: error: resource android:attr/lStar not found.

### ISSUE THREAD

**Issue by vinaykharayat** [florent37/Flutter-AssetsAudioPlayer#852]
**Flutter Version**

My version :  3.24.3

**Lib Version**

My version :  ^3.1.1

**Platform (Android / iOS / web) + version**

Platform : Android

**Describe the bug**

When building apk **_Build>Flutter>Build APK_**
I am getting an error

```
Execution failed for task ':assets_audio_player_web:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:D:\StudioProjects\MyProject\build\assets_audio_player_web\intermediates\merged_res\release\values\values.xml:194: AAPT: error: resource android:attr/lStar not found.
```

**Comment by wangya123456789** [comment]
[Try this method](https://github.com/florent37/Flutter-AssetsAudioPlayer/issues/844#issuecomment-2308573574)

**Comment by vinaykharayat** [comment]
> [Try this method](https://github.com/florent37/Flutter-AssetsAudioPlayer/issues/844#issuecomment-2308573574)

Thanks, fixed. After this I had to run 
`flutter pub cache clean`
and
`flutter clean`
