### ISSUE TITLE
Player wont dismiss from the Notifications Center

### ISSUE THREAD

**Issue by hannyce** [florent37/Flutter-AssetsAudioPlayer#859]
**Flutter Version**

My version : 3.27.0

**Lib Version**

My version : 3.1.1

**Platform (Android / iOS / web) + version**

Platform : Android 13

**Describe the bug**

I'm trying to remove the player from the notifications center.
By setting the metas variable to null the data (author, title, album, picture...) is correctly cleared but the player stays.

**Small code to reproduce**

```dart
import 'package:assets_audio_player/assets_audio_player.dart';
import 'package:flutter/material.dart';

class Player {
 final _player = AssetsAudioPlayer.withId("my_player");
 _removeNotifications() async {
    await _player.updateCurrentAudioNotification(metas: null);
  }
}
```

**Comment by eweren** [comment]
Did you try `player.showNotification = false` ?

**Comment by hannyce** [comment]
> Did you try `player.showNotification = false` ?

perfect, it worked, thanks 👍
