### ISSUE TITLE
Request to provide support for livestream

### ISSUE THREAD

**Issue by manojvsp12** [florent37/Flutter-AssetsAudioPlayer#86]
I am trying to stream a livestream audio. Everything works perfect but when I pause for sometime and play, audio feed is not live instead it is playing from buffer. Please provide support for livestreaming.

**Comment by florent37** [comment]
do you know how this feature works in ExoPlayer (android) & AVPlayer (ios) ? 

I only implemented files, but livestream is different (eg: no duration)

**Comment by florent37** [comment]
for flutter side I think I could add a `Audio.stream(url)`, but for android side I don't know what to add 

for me I prefer to keep `Audio.network(url)` for determinism files (with a duration, etc.) and a new audio type for streams

**Comment by florent37** [comment]
also can you provide me a sample mp3 stream url to test it please ? :)

**Comment by manojvsp12** [comment]
I am new to android and iOS app development. I have no idea how this feature works. but I have seen few plugins provide streaming (search for radio in pub.dev).

streaming url : http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio1_mf_p

**Comment by florent37** [comment]
I think I found, for stream uri, pause make no ''real'' sense, each pause should ''stop'' and play should reopen the media

https://codelabs.developers.google.com/codelabs/exoplayer-intro/#2

**Comment by florent37** [comment]
Found it too

https://www.it-swarm.dev/fr/android/exo-player-dash-exemple-de-streaming/1051583783/amp/

**Comment by florent37** [comment]
I tried on android and it seems to work without changing anything, did you tried on ios ?

**Comment by florent37** [comment]
I pushed it in `1.4.7+1` can you try ?

**Comment by florent37** [comment]
`open(Audio.liveStream(url))`

each pause then play goes to current stream audio and not from buffer

you also have a "buffering" listener

look at the https://github.com/florent37/Flutter-AssetsAudioPlayer/blob/master/example/lib/main_livestream.dart

**Comment by manojvsp12** [comment]
great!!! working as expected

**Comment by florent37** [comment]
Thanks for your issue ! 
Don't hesitate to sent more feedbacks
