### ISSUE TITLE
Audio not work on Android Lolipop 5.1.1 with message QCMediaPlayer mediaplayer NOT present

### ISSUE THREAD

**Issue by ghonijee** [florent37/Flutter-AssetsAudioPlayer#87]
Hello, i'm using this package to play local asset mp3 files. but on android device with version 5.1.1 audio not working and show this messages. 

E/MediaPlayer-JNI(12394): QCMediaPlayer mediaplayer NOT present
E/MediaPlayer(12394): Should have subtitle controller already set
E/MediaPlayer(12394): Should have subtitle controller already set
E/MediaPlayer-JNI(12394): QCMediaPlayer mediaplayer NOT present
E/MediaPlayer(12394): Should have subtitle controller already set
E/MediaPlayer(12394): Should have subtitle controller already set

How to handle that problem? 
Thanks

**Comment by florent37** [comment]
Hi, what version of the library are you using ?

**Comment by florent37** [comment]
It seems to be a ''native mediaplayer'' issue, but I moved to exoplayer Somme days ago, can you try with an updated version of the lib ?

**Comment by florent37** [comment]
can you try the `^1.4.7+2` ?

**Comment by florent37** [comment]
I set it at closes, it it now works, don"t hesitate to re-open it !

**Comment by ghonijee** [comment]
i'm using version 
 assets_audio_player: ^1.4.0+1

okey. i will try with new version.
