### ISSUE TITLE
Notification player background image is not displayed

### ISSUE THREAD

**Issue by manojvsp12** [florent37/Flutter-AssetsAudioPlayer#88]
In 1.4.7, getting FileNotFound exception when loading image from asset.

MetaImage.asset('assets/image.jpg') throws FileNotFound from Notification.

**Comment by manojvsp12** [comment]
Solved this issue by reverting code in ImageDownloader.kt as below.

                        Glide.with(context)
                                .asBitmap()
                                .timeout(5000)
                                .load(Uri.parse("file:///android_asset/flutter_assets/$filePath"))

**Comment by florent37** [comment]
I updated it while added package to images, I think it broke, I'll fix it

**Comment by florent37** [comment]
I fixed it by prexifing with the `android_asset/` you used, I pushe it in a beta version

**Comment by florent37** [comment]
it's in the `1.4.7+2`

**Comment by florent37** [comment]
I close it for now, you can reopen it if it not work
