### ISSUE TITLE
Compatibily with rxdart

### ISSUE THREAD

**Issue by fvisticot** [florent37/Flutter-AssetsAudioPlayer#9]
Does not work with current version of rxdart (0.22)
Can you please update the plugin ?

Because bloc 0.13.0 depends on rxdart ^0.22.0 and no versions of bloc match >0.13.0 <0.14.0, bloc ^0.13.0 requires rxdart ^0.22.0.
And because every version of assets_audio_player depends on rxdart ^0.20.0, assets_audio_player is incompatible with bloc ^0.13.0.
And because flutter_bloc 0.13.0 depends on bloc ^0.13.0 and no versions of flutter_bloc match >0.13.0 <0.14.0, assets_audio_player is incompatible with flutter_bloc ^0.13.0.
So, because tibe depends on both flutter_bloc ^0.13.0 and assets_audio_player ^1.0.1, version solving failed.

**Comment by benoitverstraete** [comment]
Hi,

I have the same error message with the "bloc" and "flutter_bloc" package. Could you please update it in your package ?

Thanks a lot !

**Comment by jcgentr** [comment]
Try this workaround:
dependency_overrides:
  rxdart: ^0.22.0

**Comment by ChristianKleineidam** [comment]
dependency_overrides doesn't seem to be enough. It throws errors such as:
```
/C:/Progs/flutter/.pub-cache/hosted/pub.dartlang.org/assets_audio_player-1.0.1/lib/assets_audio_player.dart:29:29: Error: No named parameter with the name 'seedValue'.
      BehaviorSubject<bool>(seedValue: false);
```
It seems that [seedValue](https://pub.dev/documentation/rxdart/latest/rx/BehaviorSubject-class.html) used to be a named parameter but now isn't anymore and one of the default parameters for BehaviorSubject.seeded. 

I added a pull request to make the necessary changes.

**Comment by AirborneEagle** [comment]
I also cannot use this plugin for the same reason.   any update on the PR?

**Comment by sgehrman** [comment]
same issue:

Running "flutter pub get" in therapist_training...              
Because every version of assets_audio_player depends on rxdart ^0.20.0 and therapist_training depends on rxdart ^0.23.1, assets_audio_player is forbidden.

**Comment by florent37** [comment]
try with the 1.0.2 it's been fixed :)
