### ISSUE TITLE
iOS Notification player is not visible in Playlist mode.

### ISSUE THREAD

**Issue by manojvsp12** [florent37/Flutter-AssetsAudioPlayer#90]
iOS notification player is not displayed when Playing songs in Playlist. It is visible when opened as current.

tested in iOS 9.3.5

**Comment by florent37** [comment]
what's your AssetsAudioPlayer version ?

**Comment by manojvsp12** [comment]
AssetsAudioPlayer: 1.4.7

**Comment by florent37** [comment]
ok I try to reproduce and tell you :)

**Comment by florent37** [comment]
![ezgif com-video-to-gif (22)](https://user-images.githubusercontent.com/5754972/82152523-1b45d600-9862-11ea-8868-4f132a5e8ff5.gif)

**Comment by florent37** [comment]
I did not reproduced, the simulator is on ios 10

**Comment by florent37** [comment]
can you send me the code you're using to open the playlist, and if it's possible, a short video ?

**Comment by manojvsp12** [comment]
can you check on lockscreen? I am using using ipad with iOS 9.3.5.

**Comment by florent37** [comment]
I don't have any iPhone I just tried on simulator and this notification is only visible on ios 10 & on notification center

**Comment by florent37** [comment]
I implemented this https://medium.com/@varundudeja/showing-media-player-system-controls-on-notification-screen-in-ios-swift-4e27fbf73575

**Comment by florent37** [comment]
If you have a real device I would like some help :)

**Comment by florent37** [comment]
Maybe this can fix https://stackoverflow.com/questions/52451454/ios-12-lock-screen-controls-for-music-app

**Comment by florent37** [comment]
just set it as "help wanted" as I don't test it

**Comment by florent37** [comment]
I think I fixed it ! doing what's in https://stackoverflow.com/questions/52451454/ios-12-lock-screen-controls-for-music-app

**Comment by florent37** [comment]
I push it in a new version for you

**Comment by florent37** [comment]
<img width="398" alt="Capture d’écran 2020-05-18 à 16 42 49" src="https://user-images.githubusercontent.com/5754972/82226517-e2bc0000-9926-11ea-9371-86bee3633a4f.png">

look at the lockscreen of my simulator (ios 10)
