### ISSUE TITLE
I Can't Play Local Files

### ISSUE THREAD

**Issue by ekremaksoy47** [florent37/Flutter-AssetsAudioPlayer#93]
My app can play files from assets but when i want to play files from local i cant.
In the explanation u say this :  Audio.file(FILE_URI), 
If my files in the  path like this how can i play: 'sdcard/Android/data/com.ekrem.example/files/Download/maher1.mp3'
 what will be my FILE_URI exactly and can i use short path something like "../files/Download"?

For Example:
final audios = <MyAudio>[
    MyAudio(
        name: "Mine Sound",
        audio: Audio.file("../files/Download/maher1.mp3",
          metas: Metas(

**Comment by florent37** [comment]
You have to use the library path_provider to obtain your download directory and the complete uri of this file

You cannot use a short path I think

**Comment by florent37** [comment]
Look at this sample : https://github.com/florent37/Flutter-AssetsAudioPlayer/blob/master/example/lib/main_local_file.dart

It downloads a fine in a download directory then play t

**Comment by florent37** [comment]
can you try using https://pub.dev/packages/path_provider ? 

sample code from main_local_file.dart 

```
return RaisedButton.icon(
        onPressed: () async {
          final tempDir = await getTemporaryDirectory();
          final downloadPath = tempDir.path + "/downloaded.mp3";
          print('full path $downloadPath');

          await downloadFileTo(
              dio: dio,
              url: mp3Url,
              savePath: downloadPath,
              progressFunction: (received, total) {
                if (total != -1) {
                  setState(() {
                    downloadingProgress = (received / total * 100).toStringAsFixed(0) + "%";
                  });
                }
              });
          setState(() {
            this.downloadingProgress = null;
            this.downloadedFilePath = downloadPath;
          });
        },
```

**Comment by florent37** [comment]
I set it at closes, it it now works, don"t hesitate to re-open it !
